### PR TITLE
Update to Android Components 69.0.20201203140753 [Fixes breaking API change]

### PR DESCRIPTION
**Pull request by pocmo**

### CODE REVIEW

**Review by Amejia481 — APPROVED** [review]

**Comment by pocmo** [comment]
>      FATAL EXCEPTION: main
Process: org.mozilla.fenix.debug, PID: 13544
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.work.testing.TestScheduler.setAllConstraintsMet(java.util.UUID)' on a null object reference
	at androidx.work.testing.TestWorkManagerImpl.setAllConstraintsMet(TestWorkManagerImpl.java:94)
	at mozilla.telemetry.glean.utils.WorkManagerUtilsKt$testFlushWorkManagerJob$1$1.invokeSuspend(WorkManagerUtils.kt:35)
	at mozilla.telemetry.glean.utils.WorkManagerUtilsKt$testFlushWorkManagerJob$1$1.invoke(Unknown Source:10)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:120)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:37)
	at mozilla.telemetry.glean.utils.WorkManagerUtilsKt$testFlushWorkManagerJob$1.invokeSuspend(WorkManagerUtils.kt:28)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at mozilla.telemetry.glean.utils.WorkManagerUtilsKt.testFlushWorkManagerJob(WorkManagerUtils.kt:27)
	at mozilla.telemetry.glean.utils.WorkManagerUtilsKt.testFlushWorkManagerJob$default(WorkManagerUtils.kt:26)
	at mozilla.telemetry.glean.scheduler.PingUploadWorker$Companion.enqueueWorker$glean_release(PingUploadWorker.kt:72)
	at mozilla.telemetry.glean.GleanInternalAPI.submitPingByNameSync$glean_release(Glean.kt:648)
	at mozilla.telemetry.glean.GleanInternalAPI$submitPingByName$1.invokeSuspend(Glean.kt:611)
	at mozilla.telemetry.glean.GleanInternalAPI$submitPingByName$1.invoke(Unknown Source:10)
	at mozilla.telemetry.glean.Dispatchers$WaitableCoroutineScope$executeTask$1.invokeSuspend(Dispatchers.kt:190)

**Comment by pocmo** [comment]
In AC we updated the work library from `2.2.0` to `2.4.0`. Is that causing it? We didn't run into any issues on the AC-side of things.

**Comment by pocmo** [comment]
Failed test: `validateBaselinePing`

I'll try locally.

**Comment by pocmo** [comment]
It passed locally for me. Let's try once more.

**Comment by csadilek** [comment]
`validateBaselinePing` failed a second time. :(

**Comment by csadilek** [comment]
We have another upgrade for the tab counter and its breaking changes so closing and combining in a new PR.

**Comment by csadilek** [comment]
Follow-up PR is: https://github.com/mozilla-mobile/fenix/pull/16605

**Pull request closed without merging**
