### PR TITLE
Bump a-s dependency to 0.48.2 

### PR DESCRIPTION
**Pull request by vladikoff**
Changelog: https://github.com/mozilla/application-services/releases/tag/v0.48.2

Ref: https://github.com/mozilla-mobile/android-components/pull/5558

@grigoryk @ekager r?

### CODE REVIEW

**Comment by grigoryk** [comment]
This was locally tested and seems to fix our problems (see https://github.com/mozilla-mobile/android-components/pull/5558)

**Comment by grigoryk** [comment]
mozilla-mobile/android-components#5558 landed, so this must now also land before snapshot is updated.

**Comment by grigoryk** [comment]
New snapshot is ready. Let's see if TC will pass now!

**Comment by vladikoff** [comment]
Thank you all!

**Pull request merged**
