### PR TITLE
Feature: Added quick actions for nav bar in home.

### PR DESCRIPTION
**Pull request by DrCesar**
Added the display of quick actions when long pressing the navbar in
home. The quick actions added are "Paste" and "Paste & Go".

### Pull Request checklist

- [ ] **Screenshots**: Screenshots of quick actions with the navbar set to bottom and top.
Screenshot_20200401-000948
nav-bar-bottom

### CODE REVIEW

**Comment by liuche** [comment]
@AmyYLee I don't think this is attached to an existing issue. Is this something that UX wants to do? It's an unsolicited feature afaict, but let us know.

**Comment by yoasif** [comment]
@liuche I have actually missed  this feature - without it, I have to wait until a prolonged process while the address bar animates into place (goes from bottom of screen to top), and then the keyboard opens.

It also adds consistency vs. the open tab address bar context menu and makes it feel like an input field instead of a fancy styled button.

**Comment by AmyYLee** [comment]
Reaching out to @brampitoyo since he's working on search bar - Can you review this and see if this is something that works for you?

**Comment by brampitoyo** [comment]
@liuche @AmyYLee Yes. Having “Paste” and “Paste & Go” here makes sense to me.

**Comment by liuche** [comment]
Hey @DrCesar! Thanks for the PR. Now that we have UX sign-off, could you rebase so we can review and then run CI on it?

**Comment by DrCesar** [comment]
Ok. Yeah, im going to rebase and run CI on ti.

**Comment by liuche** [comment]
It looks like we have an issue related to this, can you link this in your commit messages too? https://github.com/mozilla-mobile/fenix/issues/6846

**Comment by ekager** [comment]
Reopened as https://github.com/mozilla-mobile/fenix/pull/11035

**Pull request closed without merging**
