### PR TITLE
For #22995: Address crash when switching languages.

### PR DESCRIPTION
**Pull request by Amejia481**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by Amejia481** [comment]
@Mugurell  to keep consistency I think it's better to just follow the same pattern as we are doing on the rest of the app.

**Comment by Mugurell** [comment]
> @Mugurell to keep consistency I think it's better to just follow the same pattern as we are doing on the rest of the app.

`onResume` seems misused for this kind of things even according to [it's documentation](https://developer.android.com/guide/components/activities/activity-lifecycle#onresume).
If we are updating the toolbar title after it is shown this will cause a bit of a jank.
Having this in `onStart` would be marginally better - less jank
and doing this in `onCreateView` (while making sure that the parent activity has finished it's `onCreate` - so there is a toolbar we can work with) and being able to set it up so that it will be displayed as expected from the first time the screen is shown would be perfect.

That being said, this solves the crash. r+.

**Review by Mugurell — APPROVED** [review]

**Comment by Amejia481** [comment]
> > @Mugurell to keep consistency I think it's better to just follow the same pattern as we are doing on the rest of the app.
> 
> `onResume` seems misused for this kind of things even according to [it's documentation](https://developer.android.com/guide/components/activities/activity-lifecycle#onresume). If we are updating the toolbar title after it is shown this will cause a bit of a jank. Having this in `onStart` would be marginally better - less jank and doing this in `onCreateView` (while making sure that the parent activity has finished it's `onCreate` - so there is a toolbar we can work with) and being able to set it up so that it will be displayed as expected from the first time the screen is shown and not updating it again when the app gains focus - because the title should not have changed anyways (thinking about the scenario of switching between apps) would be perfect.
> 
> That being said, this solves the crash. r+.

Thanks for taking a look. Testing locally, I couldn't see any significant impact. For the moment, I will address the issue until we take a more general solution for all the instances.

**Comment by gabrielluong** [comment]
@Mugurell @Amejia481 Let's file a follow up to refactor how and where we call `showToolbar`.

**Comment by Amejia481** [comment]
> @Mugurell @Amejia481 Let's file a follow up to refactor how and where we call `showToolbar`. I would do it myself, but it was on unclear if we prefer to do this in `onStart` vs `onCreateView`.

@gabrielluong I filed https://github.com/mozilla-mobile/fenix/issues/23059 for exploring both options and use which one best fits our needs.

**Pull request merged**
