### PR TITLE
Fix #8469 - Properly align radio buttons in two-pane onboarding layouts.

### LINKED ISSUE #8469: [Bug][RTL] Radio buttons for the Theme selection on the welcome screen are overlapping the images
Originally filed in [bug 1616101](https://bugzilla.mozilla.org/show_bug.cgi?id=1608218):
תמונה

The radio buttons should be placed in the punch holes.

### PR DESCRIPTION
**Pull request by Mugurell**
### Pull Request checklist

- [x] **Tests**: This PR does not include tests as it only adds minor cosmetic changes
- [x] **Screenshots**: This PR includes screenshots for the before and after changes
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md)

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

ProperlyAlignedRadioButtonsWithOnboardingImages

### CODE REVIEW

**Comment by ekager** [comment]
Hey @Mugurell ! This looks great, did you try using `android:autoMirrored="true"` for these resources to be flipped as well? I think it makes more sense for RTL to have the radio button and cutout be on the right edge for RTL, but if it's not working, then this is definitely an improvement

**Comment by Mugurell** [comment]
@ekager `autoMirrored` doesn't work but we can mirror the view the old fashioned way - just rotate it 180 degrees.
There are some inaccuracies in the images now (most visible being the virtual navigation back button) for which I think we'd need a new ticket for UX to provide updated resources to use in RTL though.

**Comment by ekager** [comment]
@Mugurell could we do something like this? I think creating an `ic_onboarding_dark_theme` and `ic_onboarding_light_theme` that just wraps the pngs in a bitmap with automirroring true could work and be a bit simpler? Let me know! 
https://stackoverflow.com/a/44637677

**Comment by Mugurell** [comment]
Thanks! Indeed this works great!

**Pull request merged**
