### PR TITLE
Let bors wait on complete-task which errors out whenever all task have run

### PR DESCRIPTION
**Pull request by JohanLorenzo**
---

Ports https://github.com/mozilla-mobile/android-components/pull/4745 to Fenix.

changes on push:
```json
[
    "add", 
    "", 
    [
        [
            "complete-push", 
            {
                "attributes": {
                    "always_target": false, 
                    "code-review": true, 
                    "kind": "complete", 
                    "run_on_projects": [
                        "all"
                    ], 
                    "run_on_tasks_for": [
                        "github-push"
                    ]
                }, 
                "dependencies": {
                    "docker-image": "build-docker-image-base"
                }, 
                "kind": "complete", 
                "label": "complete-push", 
                "optimization": null, 
                "soft_dependencies": [
                    "test-ui", 
                    "lint-ktlint", 
                    "lint-detekt", 
                    "build-debug", 
                    "lint-lint", 
                    "test-debug", 
                    "lint-compare-locales"
                ], 
                "task": {
                    "created": {
                        "relative-datestamp": "0 seconds"
                    }, 
                    "deadline": {
                        "relative-datestamp": "1 day"
                    }, 
                    "expires": {
                        "relative-datestamp": "1 year"
                    }, 
                    "extra": {
                        "index": {
                            "rank": 0
                        }, 
                        "parent": ""
                    }, 
                    "metadata": {
                        "description": "Push Summary Task", 
                        "name": "complete-push", 
                        "owner": "sdblatz@gmail.com", 
                        "source": "https://github.com/mozilla-mobile/fenix/blob/841b06b02fc3a887fcea2a8b42dfbb9142f0bc52/taskcluster/ci/complete"
                    }, 
                    "payload": {
                        "command": [
                            "/usr/local/bin/run-task", 
                            "--mobile-checkout=/builds/worker/checkouts/src/", 
                            "--fetch-hgfingerprint", 
                            "--", 
                            "bash", 
                            "-cx", 
                            {
                                "task-reference": "/builds/worker/checkouts/src/taskcluster/scripts/are_dependencies_completed.py <test-ui> <lint-ktlint> <lint-detekt> <build-debug> <lint-lint> <test-debug> <lint-compare-locales>"
                            }
                        ], 
                        "env": {
                            "HG_STORE_PATH": "/builds/worker/checkouts/hg-store", 
                            "MOBILE_BASE_REPOSITORY": "https://github.com/mozilla-mobile/fenix", 
                            "MOBILE_HEAD_REF": "refs/heads/master", 
                            "MOBILE_HEAD_REPOSITORY": "https://github.com/mozilla-mobile/fenix", 
                            "MOBILE_HEAD_REV": "841b06b02fc3a887fcea2a8b42dfbb9142f0bc52", 
                            "MOBILE_REPOSITORY_TYPE": "git", 
                            "MOZ_AUTOMATION": "1", 
                            "MOZ_SCM_LEVEL": "3", 
                            "REPOSITORIES": "{\"mobile\": \"Fenix\"}", 
                            "SCCACHE_DISABLE": "1", 
                            "TASKCLUSTER_VOLUMES": "/builds/worker/.cache;/builds/worker/checkouts", 
                            "VCS_PATH": "/builds/worker/checkouts/src"
                        }, 
                        "features": {
                            "taskclusterProxy": true
                        }, 
                        "image": {
                            "path": "public/image.tar.zst", 
                            "taskId": {
                                "task-reference": "<docker-image>"
                            }, 
                            "type": "task-image"
                        }, 
                        "maxRunTime": 600, 
                        "onExitStatus": {
                            "purgeCaches": [
                                72
                            ], 
                            "retry": [
                                72
                            ]
                        }
                    }, 
                    "priority": "highest", 
                    "provisionerId": "aws-provisioner-v1", 
                    "requires": "all-resolved", 
                    "routes": [
                        "checks"
                    ], 
                    "scopes": [], 
                    "tags": {
                        "createdForUser": "sdblatz@gmail.com", 
                        "kind": "complete", 
                        "label": "complete-push", 
                        "os": "linux", 
                        "worker-implementation": "docker-worker"
                    }, 
                    "workerType": "mobile-3-b-fenix"
                }
            }
        ]
    ]
]

```

changes on pull-request:
```json
[
    "add", 
    "", 
    [
        [
            "complete-pr", 
            {
                "attributes": {
                    "always_target": false, 
                    "code-review": true, 
                    "kind": "complete", 
                    "run_on_projects": [
                        "all"
                    ], 
                    "run_on_tasks_for": [
                        "github-pull-request"
                    ]
                }, 
                "dependencies": {
                    "docker-image": "build-docker-image-base"
                }, 
                "kind": "complete", 
                "label": "complete-pr", 
                "optimization": null, 
                "soft_dependencies": [
                    "test-ui", 
                    "lint-ktlint", 
                    "lint-detekt", 
                    "build-debug", 
                    "lint-lint", 
                    "test-debug", 
                    "lint-compare-locales"
                ], 
                "task": {
                    "created": {
                        "relative-datestamp": "0 seconds"
                    }, 
                    "deadline": {
                        "relative-datestamp": "1 day"
                    }, 
                    "expires": {
                        "relative-datestamp": "28 days"
                    }, 
                    "extra": {
                        "index": {
                            "rank": 0
                        }, 
                        "parent": ""
                    }, 
                    "metadata": {
                        "description": "PR Summary Task", 
                        "name": "complete-pr", 
                        "owner": "Pike@users.noreply.github.com", 
                        "source": "https://github.com/Pike/fenix/blob/3e6c558e8e74e04ebf60f853687c8b644c6c16da/taskcluster/ci/complete"
                    }, 
                    "payload": {
                        "command": [
                            "/usr/local/bin/run-task", 
                            "--mobile-checkout=/builds/worker/checkouts/src/", 
                            "--fetch-hgfingerprint", 
                            "--", 
                            "bash", 
                            "-cx", 
                            {
                                "task-reference": "/builds/worker/checkouts/src/taskcluster/scripts/are_dependencies_completed.py <test-ui> <lint-ktlint> <lint-detekt> <build-debug> <lint-lint> <test-debug> <lint-compare-locales>"
                            }
                        ], 
                        "env": {
                            "HG_STORE_PATH": "/builds/worker/checkouts/hg-store", 
                            "MOBILE_BASE_REPOSITORY": "https://github.com/mozilla-mobile/fenix", 
                            "MOBILE_HEAD_REF": "import-l10n", 
                            "MOBILE_HEAD_REPOSITORY": "https://github.com/Pike/fenix", 
                            "MOBILE_HEAD_REV": "3e6c558e8e74e04ebf60f853687c8b644c6c16da", 
                            "MOBILE_REPOSITORY_TYPE": "git", 
                            "MOZ_AUTOMATION": "1", 
                            "MOZ_SCM_LEVEL": "1", 
                            "REPOSITORIES": "{\"mobile\": \"Fenix\"}", 
                            "SCCACHE_DISABLE": "1", 
                            "TASKCLUSTER_VOLUMES": "/builds/worker/.cache;/builds/worker/checkouts", 
                            "VCS_PATH": "/builds/worker/checkouts/src"
                        }, 
                        "features": {
                            "taskclusterProxy": true
                        }, 
                        "image": {
                            "path": "public/image.tar.zst", 
                            "taskId": {
                                "task-reference": "<docker-image>"
                            }, 
                            "type": "task-image"
                        }, 
                        "maxRunTime": 600, 
                        "onExitStatus": {
                            "purgeCaches": [
                                72
                            ], 
                            "retry": [
                                72
                            ]
                        }
                    }, 
                    "priority": "highest", 
                    "provisionerId": "aws-provisioner-v1", 
                    "requires": "all-resolved", 
                    "routes": [
                        "checks"
                    ], 
                    "scopes": [], 
                    "tags": {
                        "createdForUser": "Pike@users.noreply.github.com", 
                        "kind": "complete", 
                        "label": "complete-pr", 
                        "os": "linux", 
                        "worker-implementation": "docker-worker"
                    }, 
                    "workerType": "mobile-1-b-fenix"
                }
            }
        ]
    ]
]
[
    "remove", 
    "", 
    [
        [
            "pr-complete", 
            {
                "attributes": {
                    "always_target": false, 
                    "kind": "pr", 
                    "run_on_projects": [
                        "all"
                    ], 
                    "run_on_tasks_for": [
                        "github-pull-request"
                    ]
                }, 
                "dependencies": {}, 
                "kind": "pr", 
                "label": "pr-complete", 
                "optimization": null, 
                "soft_dependencies": [
                    "test-ui", 
                    "lint-ktlint", 
                    "lint-detekt", 
                    "build-debug", 
                    "lint-lint", 
                    "test-debug", 
                    "lint-compare-locales"
                ], 
                "task": {
                    "created": {
                        "relative-datestamp": "0 seconds"
                    }, 
                    "deadline": {
                        "relative-datestamp": "1 day"
                    }, 
                    "expires": {
                        "relative-datestamp": "28 days"
                    }, 
                    "extra": {
                        "index": {
                            "rank": 0
                        }, 
                        "parent": ""
                    }, 
                    "metadata": {
                        "description": "PR Summary Task", 
                        "name": "pr-complete", 
                        "owner": "Pike@users.noreply.github.com", 
                        "source": "https://github.com/Pike/fenix/blob/3e6c558e8e74e04ebf60f853687c8b644c6c16da/taskcluster/ci/pr"
                    }, 
                    "payload": {}, 
                    "priority": "highest", 
                    "provisionerId": "built-in", 
                    "routes": [
                        "checks"
                    ], 
                    "scopes": [], 
                    "tags": {
                        "createdForUser": "Pike@users.noreply.github.com", 
                        "kind": "pr", 
                        "label": "pr-complete", 
                        "worker-implementation": "succeed"
                    }, 
                    "workerType": "succeed"
                }
            }
        ]
    ]
]
```

Other graphs haven't changed. 

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by JohanLorenzo** [comment]
bors try

**Comment by JohanLorenzo** [comment]
I guess bors timed out because the new config hasn't made master, yet. I'll give it a try.

bors r=mitchhentges,pocmo

**Comment by JohanLorenzo** [comment]
bors r=mitchhentges,pocmo

**Comment by JohanLorenzo** [comment]
Crap, that failure is https://bugzilla.mozilla.org/show_bug.cgi?id=1587765, again.

**Comment by JohanLorenzo** [comment]
bors r=mitchhentges,pocmo

**Comment by JohanLorenzo** [comment]
bors r=mitchhentges,pocmo

**Comment by JohanLorenzo** [comment]
Ah, these changes rename `pr-complete` into `complete-pr`. Can we change the github PR settings to match the new name @pocmo ?

**Comment by pocmo** [comment]
> Ah, these changes rename pr-complete into complete-pr. Can we change the github PR settings to match the new name @pocmo ?

We need to do that in bors.toml:
https://github.com/mozilla-mobile/fenix/blob/master/bors.toml#L1-L9

It currently lists the individual tasks since back then we didn't have a "everything complete" task (and this is a way smaller list than in AC). That said, for bors we'd need a "push" complete task since it doesn't look at the PR itself. Do we have that?

**Comment by JohanLorenzo** [comment]
Thanks for the quick reply @pocmo !

This PR does change these lines https://github.com/mozilla-mobile/fenix/pull/6117/files#diff-2f8c9db9253b64f9a332c09f492cd54eR2. 

It seems bors does look at the PR itself per https://app.bors.tech/repositories/21013/log#batch-36738: 
```
10/23/2019, 10:15:00 AM | Crash | batch | {{:badmatch,   {:error, :push, 422,    "{\"message\":\"Required status check \\\"pr-complete\\\" is expected.\",\"documentation_url\":\"https://help.github.com/articles/about-protected-branches\"}"}},  [    {BorsNG.Worker.Batcher, :complete_batch, 3,     [file: 'lib/worker/batcher.ex', line: 475]},    {BorsNG.Worker.Batcher, :maybe_complete_batch, 1,     [file: 'lib/worker/batcher.ex', line: 456]},    {BorsNG.Worker.Batcher, :poll_, 1,     [file: 'lib/worker/batcher.ex', line: 204]},    {BorsNG.Worker.Batcher, :handle_info, 2,     [file: 'lib/worker/batcher.ex', line: 186]},    {:gen_server, :try_dispatch, 4,     [file: 'gen_server.erl', line: 637]},    {:gen_server, :handle_msg, 6,     [file: 'gen_server.erl', line: 711]},    {:proc_lib, :init_p_do_apply, 3,     [file: 'proc_lib.erl', line: 249]}  ]}
```

What do you think?

**Comment by pocmo** [comment]
I think that shows bors looking at the push (to the staging branch) where this check does not exist? 🤔

**Comment by JohanLorenzo** [comment]
If that's the case, I'm confused. How does bors know about `pr-complete`? Have we told bors about it?

**Comment by pocmo** [comment]
I think that"s the response from the Github API. The Fenix just team just made this a required check for pushing/merging to master and well, bors' commits on the staging branch does not have that check.
The Fenix team just yesterday send out a mail that they disabled the bors check because they had some issues - and I assume that's why they are enforcing this check in the branch protection again.
We either need to disable it again or maybe have a check that is named the same for PRs and pushes.

**Comment by JohanLorenzo** [comment]
Okay, thank you very much for the context. I'll wait to hear what people think in https://github.com/mozilla-mobile/fenix/issues/6139, then ask to deactivate this check, if it's a viable solution.

**Comment by gabrielluong** [comment]
Closing this since we removed bors in https://github.com/mozilla-mobile/fenix/issues/6139

**Pull request closed without merging**
