### PR TITLE
For #14557 - Toggles seach engine selection when tapping the search engine icon

### PR DESCRIPTION
**Pull request by boek**
### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by Mugurell — APPROVED** [review]
LGTM

**Comment by Mugurell** [comment]
The `verifySearchEngineCanBeChangedTemporarilyUsingShortcuts` UI test seems to be failing probably because now tapping the search engine icon toggles showing the search engines list.

**Comment by boek** [comment]
going to wait for the a-c pr to land and use a proper API

**Comment by ekager** [comment]
@boek which AC PR is that and can we link it here if it's still waiting so someone else can pick it up when it's ready? :)

**Comment by eliserichards** [comment]
Closing this for now. Will follow up with @pocmo on changes now that his search refactors are landed

**Pull request closed without merging**
