### PR TITLE
No issue: Make sure we are cleaning up test coroutines

### PR DESCRIPTION
**Pull request by ekager**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by ekager** [comment]
Yes! This was a test, but seems better

**Comment by ekager** [comment]
Speculative fix for some of test timeout errors, seems to have passed quickly, hopefully not a fluke! In either case, none of this will hurt to add.

**Review by gabrielluong — APPROVED** [review]
Wild idea - I am wondering if it makes sense to file an "help wanted" issue for the purpose of writing a linter to make sure all test coroutine scope and test dispatcher clear their coroutines. 

I also wanted to leave behind some context for whoever might randomly tumble into this issue and wonder what this is fixing. I think this is an attempt to resolve https://github.com/mozilla-mobile/fenix/issues/16262 and https://github.com/mozilla-mobile/fenix/issues/16237 by eliminating coroutine leaks in our tests.

Some articles I found:
https://proandroiddev.com/eliminating-coroutine-leaks-in-tests-3af825e7cde2
https://medium.com/swlh/kotlin-coroutines-in-android-unit-test-28ff280fc0d5

@ekager I am hoping I captured the intentions of the changes 🙏

**Comment by ekager** [comment]
Yes that sounds good! I would have linked the issues but I honestly didn't know if this was even the right tree to bark up 😆 

Let's land this and I'll file a followup for possibly adding a linter

**Pull request merged**
