### PR TITLE
For #27245: hold to open tab history item in duplicated tab 

### LINKED ISSUE #27245: Hold to open tab history item in duplicated tab
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
A missing feature in Fenix that is present in desktop Firefox is the ability to open a tab history item in a new tab while preserving the tab history (i.e., duplicating the tab and navigating to the tab history URL).

This is accomplished on desktop by middle-clicking the tab history item, so on mobile the natural action is a hold event ("long click") on the tab history item.

### How do you know that this problem exists today? Why is this important?
This functionality is missing entirely in Fenix. Workflows that "branch" into new tabs frequently would be improved by having the tab history stack along with each tab, as described in #9956. This generalizes that issue by allowing the duplicated tab to start in a different history index than the current tab.

### Who will benefit from it?
As described in #9956 and above, various workflows would benefit from this, and this is a feature that is present in desktop Firefox that users may expect in the mobile version.

I've already implemented this and will link the PR shortly.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21707)

### PR DESCRIPTION
**Pull request by fice-t**
This offers feature parity with Desktop.

[Device-2022-10-02-114950-reencoded.webm](https://user-images.githubusercontent.com/13156601/193468913-8d668937-d3fe-4200-9c5a-6d4804c0d7e3.webm)

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #27245

### CODE REVIEW

**Review by jonalmeida — APPROVED** [review]
Thanks for contribution! I didn't know desktop had that feature. 😄 

Engineering-wise this looks good (just needs a unit test to be fixed).

Leaving the UX label on for final sign-off.

**Comment by fice-t** [comment]
Thanks for the review! I rebased and added a couple docstrings for `detekt`'s sake.

About the failed unit test: I ran it locally and it passed both before and after the rebase, so I don't know what went wrong there. I also didn't meaningfully touch that specific test 🤷. Let's see how it fairs after the rebase.

**Comment by fice-t** [comment]
The test passes on my machine using: 
`./gradlew clean testdebugunittest --tests org.mozilla.fenix.tabhistory.TabHistoryControllerTest`

Are there major differences with the CI that would affect this? Could you try the above on your machine to see if it's a CI issue?

**Comment by jonalmeida** [comment]
> The test passes on my machine using: `./gradlew clean testdebugunittest --tests org.mozilla.fenix.tabhistory.TabHistoryControllerTest`
> 
> Are there major differences with the CI that would affect this? Could you try the above on your machine to see if it's a CI issue?

It passes for me too locally and there are no differences between CI and local - when CI fails but local doesn't, it's usually indicative that there is an intermittent failure happening because of a race. A quick peruse makes me think that the test hasn't changed, but the _setup_ has.

The _setup_ now includes the line `tabsUseCases.addTab("mozilla.org")` which dispatches a new tab creation on the _store's thread_ so that can mean the test may run before the setup is complete.

We could add a `store.waitUntilIdle()` call at the end of the `setup` method so ensure the store is ready before the test starts.

**Comment by fice-t** [comment]
> We could add a store.waitUntilIdle() call at the end of the setup method so ensure the store is ready before the test starts.

Alright, I pushed a new commit that adds this and punts the tab creation to the only test that uses it.

**Comment by gabrielluong** [comment]
Hey there, thank you for the contribution! We have migrated the original issue over to Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1815636. When this PR is ready to land, could we please update your commit message and PR title to reference the new Bugzilla issue using the following format: "Bug xxxxxx - \<short description\>". Thanks!

**Comment by csadilek** [comment]
Hey @fice-t, Thank you so much for your contribution. We will be moving this repository to [firefox-android](https://github.com/mozilla-mobile/firefox-android) in the coming days, and won't be able review or land this PR until after  the migration.

Sorry for the delay getting feedback. For this PR, it may be best to continue discussing on the [ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1807067), since this needs Product and UX input before landing.

For more information, please see https://github.com/mozilla-mobile/fenix/issues/26855.

**Pull request closed without merging**
