### PR TITLE
For #6704: Enable FxA state encryption for all channels 

### PR DESCRIPTION
**Pull request by ValentinTimisica**
### Pull Request checklist

- [x] **Tests**: This PR does not include thorough tests.
- [x] **Screenshots**: This PR does not include screenshots or GIFs.
- [x] **Accessibility**: The code in this PR does not include any user facing features.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by liuche** [comment]
@grigoryk ^ so we can get this into 3.3 and we have a chance to see this in the wild before Beta Migration.

**Comment by ekager** [comment]
@grigoryk so can we land this and I'll monitor Sentry for the next few days for any weirdness?

**Comment by grigoryk** [comment]
To complete the loop: we've talked about this on Slack; there are a number of low-volume, device-specific issues associated with keystore access, but we think they will be mostly addressed by https://github.com/mozilla-mobile/android-components/pull/5796

The only remaining bit of due diligence that I think we should do is to make sure that our worst-case scenario is graceful. Loosing data may be inevitable due to the nature of these issues, but at least let's make sure we won't crash in case of keystore-related exceptions, and submit them to Sentry as `info` level exceptions instead to keep track of their volume.

Depending on what key material was affected, a corrupt keystore may mean either:
- loosing our FxA state - in which case, we need to make sure that account manager is transferred into a "Logged out" state
- loosing access to data in the login storage, in which case we need to make sure that logins-related functionality continues to function (can create new logins, autofill, etc).

**Comment by ekager** [comment]
Closing this because we've decided to wait a bit longer to enable for all channels see #8324

**Comment by ekager** [comment]
Ugh meant to close the PR not the issue, sorry

**Pull request closed without merging**
