### PR TITLE
Add EngineViewBottomBehavior to fragment_browser.

### PR DESCRIPTION
**Pull request by psymoon**
Do not merge until https://github.com/mozilla-mobile/android-components/pull/4712

### CODE REVIEW

**Comment by csadilek** [comment]
We should wait until https://bugzilla.mozilla.org/show_bug.cgi?id=1590582 is resolved and lands in beta before landing this.

**Comment by boek** [comment]
@csadilek @psymoon is this ready? :)

**Comment by csadilek** [comment]
@boek we need to make sure we're using the latest GV beta that contains this fix: https://bugzilla.mozilla.org/show_bug.cgi?id=1590582

@psymoon So, I think we should upgrade to the latest GV beta and make sure this works (open sozone.de and check that we can interact with / confirm that cookie banner)

**Comment by csadilek** [comment]
Just tagging @abodea who wants to verify this fix once it lands.

**Comment by psymoon** [comment]
Verified working on latest gecko beta 71. We can land this!

**Comment by jonalmeida** [comment]
There are still some GV issues with setVerticalClipping that we're seeing. Hold off from merging this for a bit.

cc: @csadilek

**Comment by jonalmeida** [comment]
I reopened [bug 1516048](https://bugzilla.mozilla.org/show_bug.cgi?id=1516048#c22) for this.

**Comment by sblatz** [comment]
It looks like that bugzilla ticket doesn't have any movement on it. Is this something we need to get on GV's radar? @jonalmeida

**Comment by boek** [comment]
Closing this for now, feel free re-open when it's ready 👍

**Pull request closed without merging**
