### PR TITLE
String Uplifts for Firefox 85

### PR DESCRIPTION
**Pull request by st3fan**
This PR contains string uplifts that are made according to the instructions in the [Release Checklist](https://github.com/mozilla-mobile/fenix/blob/master/.github/ISSUE_TEMPLATE/release_checklist.md)

That translated to the following commands:

```
git clone git@github.com:mozilla-mobile/fenix.git
cd fenix/
git checkout releases_v85.0.0
git checkout -b st3fan/strings-uplift-v85
./l10n-uplift.py st3fan/strings-uplift-v85 --uplift --verbose
git push --set-upstream origin st3fan/strings-uplift-v85
```

The result of the `l10n-uplift.py` tool was:

```
stefan@Discovery ~/M/fenix (st3fan/strings-uplift-v85)> ./l10n-uplift.py st3fan/strings-uplift-v85 --uplift --verbose

Processing l10n commits for 'st3fan/strings-uplift-v85'...
Since 'st3fan/strings-uplift-v85' split off 'master', there were 13 commit(s) from release+l10n-automation-bot@mozilla.com.

Hashes of those commits on 'master' are: ['7bf0f7595c7d91c531530da8236f1061e9479dd3', '5445e61b6aa3d03bbea390200e5536f493a7e38b', '57d453dc7fe3f3d52b9196162b4a8e38b0b88442', '96b63485cc7d761247c8a319b62d16d29e6b6a0c', '33272d5447491f92249da61f13f3c3543ccc36f1', '16ab8bf1abf651e1410705f3b4236667aa386957', '96be55067dd0e1894d7d634567a9e8a3f2164c41', 'f8f677ce7f5200025cbf3efd6a7383e789f0a993', 'bad65b501782dd1945e03cf42bfadd3c28a2408b', '9c776f1d7fe9d6091e1e8b03e6d509dc5a88214d', 'f95547c27103f778bf578dade8c9a7e8b81d43bb', '9966a85bd5b83d51d2fc6d27b41590fdae057b9f', '1fbf227a61c5776c420591b6ce23faa76bd93cac']

Of those, 0 commit(s) already uplifted.
Hashes of commits already uplifted to 'st3fan/strings-uplift-v85': []

Need to uplift 13 commit(s).
Hashes of commits to uplift from 'master' to 'st3fan/strings-uplift-v85': ['7bf0f7595c7d91c531530da8236f1061e9479dd3', '5445e61b6aa3d03bbea390200e5536f493a7e38b', '57d453dc7fe3f3d52b9196162b4a8e38b0b88442', '96b63485cc7d761247c8a319b62d16d29e6b6a0c', '33272d5447491f92249da61f13f3c3543ccc36f1', '16ab8bf1abf651e1410705f3b4236667aa386957', '96be55067dd0e1894d7d634567a9e8a3f2164c41', 'f8f677ce7f5200025cbf3efd6a7383e789f0a993', 'bad65b501782dd1945e03cf42bfadd3c28a2408b', '9c776f1d7fe9d6091e1e8b03e6d509dc5a88214d', 'f95547c27103f778bf578dade8c9a7e8b81d43bb', '9966a85bd5b83d51d2fc6d27b41590fdae057b9f', '1fbf227a61c5776c420591b6ce23faa76bd93cac']

Uplifting (for real)...
Cherry picking 7bf0f7595c7d91c531530da8236f1061e9479dd3 from 'master' to 'st3fan/strings-uplift-v85'
Cherry picking 5445e61b6aa3d03bbea390200e5536f493a7e38b from 'master' to 'st3fan/strings-uplift-v85'
Cherry picking 57d453dc7fe3f3d52b9196162b4a8e38b0b88442 from 'master' to 'st3fan/strings-uplift-v85'
Cherry picking 96b63485cc7d761247c8a319b62d16d29e6b6a0c from 'master' to 'st3fan/strings-uplift-v85'
Cherry picking 33272d5447491f92249da61f13f3c3543ccc36f1 from 'master' to 'st3fan/strings-uplift-v85'
Cherry picking 16ab8bf1abf651e1410705f3b4236667aa386957 from 'master' to 'st3fan/strings-uplift-v85'
Cherry picking 96be55067dd0e1894d7d634567a9e8a3f2164c41 from 'master' to 'st3fan/strings-uplift-v85'
Cherry picking f8f677ce7f5200025cbf3efd6a7383e789f0a993 from 'master' to 'st3fan/strings-uplift-v85'
Cherry picking bad65b501782dd1945e03cf42bfadd3c28a2408b from 'master' to 'st3fan/strings-uplift-v85'
Cherry picking 9c776f1d7fe9d6091e1e8b03e6d509dc5a88214d from 'master' to 'st3fan/strings-uplift-v85'
Cherry picking f95547c27103f778bf578dade8c9a7e8b81d43bb from 'master' to 'st3fan/strings-uplift-v85'
Cherry picking 9966a85bd5b83d51d2fc6d27b41590fdae057b9f from 'master' to 'st3fan/strings-uplift-v85'
Cherry picking 1fbf227a61c5776c420591b6ce23faa76bd93cac from 'master' to 'st3fan/strings-uplift-v85'
Uplifted 13 commits from 'master' to 'st3fan/strings-uplift-v85'
```

I think this looks good, but I'd like to ask @Delphine and @Mugurell for feedback here.

### CODE REVIEW

**Comment by ekager** [comment]
AFAIK this looks good - the main thing we have to be careful of with uplifts is if strings were deleted after this branch was cut and the l10n imports remove those (but they are still being used in this branch)

**Comment by st3fan** [comment]
> AFAIK this looks good - the main thing we have to be careful of with uplifts is if strings were deleted after this branch was cut and the l10n imports remove those (but they are still being used in this branch)

There are definitely some deletions and renames. For example in `values-ar/srings.xml` I see:

 - `download_empty_message` renamed to `download_empty_message1`
 - `download_delete_item` renamed to `download_delete_item1`

In `values-be/strings.xml` there is:

 - removal of `browser_menu_new_tab`

@ekager Do changes like that need to be audited? I'm sorry I am not sure if this is normal or not.

**Comment by st3fan** [comment]
This looks inconsistent: `download_empty_message_1` vs `download_empty_message1` what I see in other files:

https://github.com/mozilla-mobile/fenix/pull/17371/files?diff=unified&w=1#diff-3e6579cdc4ce8f9c726197e42a2c426c9010e9c9fcfee7fc5aa09041ff9bdc52L728

**Comment by ekager** [comment]
I just checked the base `res/strings.xml` file on releases_v85.0.0 and it contains `download_empty_message_1` and `download_delete_item_1` and doesn't contain `browser_menu_new_tab`. So those seem fine. I would usually just run a sanity check by checking the base file on the branch, and if anything looks confusing/questionable, we could also smoke test it with those languages.

Too late for this now, but the safer thing we should probably start doing is not actually deleting strings when we change them/stop using them, and instead move them to a `deprecated in X release` section to be deleted after the release.

**Comment by st3fan** [comment]
Looks like `oc` removed `download_empty_message` but did not bring back `download_empty_message_1`.

**Comment by st3fan** [comment]
If that missing string in `oc` is fine for now, let's land this so that the next Beta (Monday?) is up to date with all the work our localizers have put in.

**Review by ekager — APPROVED** [review]

**Pull request merged**
