### PR TITLE
For #10069: added AppLaunchTime.kt to handle logic of startup time for cold, warm, and hot startup types. 

### PR DESCRIPTION
**Pull request by mcomella**
@MarcLeclair This was written by sraturi and reviewed (by me) in https://github.com/mozilla-mobile/fenix/pull/14375 – can I get a rubberstamp and perhaps a review on the few commits I added?

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by MarcLeclair — APPROVED** [review]
Looks good to me @mcomella. I can see the ping locally would you want me to check if we see it on the Debug ping viewer?

**Comment by mcomella** [comment]
> Looks good to me @mcomella. I can see the ping locally would you want me to check if we see it on the Debug ping viewer?

It's up to your judgment if you think it's necessary. I usually test with the debug ping viewer than looking locally.

**Review by liuche — APPROVED** [review]
# Data Review Form (to be filled by Data Stewards)

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way? 

Yes, in metrics.md

2) Is there a control mechanism that allows the user to turn the data collection on and off? (Note, for data collection not needed for security purposes, Mozilla provides such a control mechanism) Provide details as to the control mechanism available.

Yes, in telemetry settings in Fenix

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

Has expiry, updating an existing probe

4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Type 1

5) Is the data collection request for default-on or default-off?

Default on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?

No, perf startup data

7) Is the data collection covered by the existing Firefox privacy notice?

yes

8) Does there need to be a check-in in the future to determine whether to renew the data? 
No, will expire


9) Does the data collection use a third-party collection tool? **If yes, escalate to legal.**

No

**Comment by liuche** [comment]
Next time, adding the `needs:data-review` label will make it easier to see.

**Pull request merged**
