### PR TITLE
For #22308: Changed constraint of tab tray overflow to fix rotation

### PR DESCRIPTION
**Pull request by pedroldk**
This PR closes https://github.com/mozilla-mobile/fenix/issues/22308

Video of the rotation working and the tab tray menu rotating correctly:
https://user-images.githubusercontent.com/480413/154987994-a06c9363-dc26-49d3-99f2-ef0112b38f0d.mp4

### Pull Request checklist

- [ x  ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ x ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ x ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by jonalmeida — APPROVED** [review]
Looks good, thanks!

Let's land this after the beta cut that is happening early next week so this can bake.

**Comment by pedroldk** [comment]
@gabrielluong @jonalmeida , anything else that I should pursue for this one to move forward?

**Comment by gabrielluong** [comment]
@pedroldk Thanks for patch and apologizes for taking so long to close on this. I will be landing this in https://github.com/mozilla-mobile/fenix/pull/24547 so I will close this PR.

**Comment by pedroldk** [comment]
@gabrielluong No problem at all! Glad I could contribute 😉

**Pull request closed without merging**
