### PR TITLE
For #22569: Remove allopen plugin and Mockable annotations

### PR DESCRIPTION
**Pull request by grigoryk**
This removes an `allopen` compiler plugin that was invalidating builds in certain scenarios (due to how it was configured, see details in the issue), all of the @Mockable annotations we had in the codebase, and the pair of `TestComponents` + `TestCore` base classes that provided tests with "magical mocking".

Now there's no magic, all mocking is localized to the tests and very explicit, no sneaky compiler plugin and faster builds!

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by grigoryk** [comment]
Now that I'm back, aiming to finish this up soon.

**Comment by grigoryk** [comment]
Was this _very_ tedious to do? Yes! But, do all the tests pass now and are the builds faster? Also yes!

**Comment by grigoryk** [comment]
The only class I marked as `open` was `StrictModeManager`, due to existence of a `TestStrictModeManager`.

**Review by pocmo — APPROVED** [review]
🎉 Awesome! Thank you :)

**Pull request merged**
