### PR TITLE
For #5073: View Site Cert

### PR DESCRIPTION
**Pull request by kglazko**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by kglazko** [comment]
@liuche Done!

**Comment by kglazko** [comment]
Screen Shot 2020-01-31 at 8 10 28 AM
Screen Shot 2020-01-31 at 8 10 55 AM
Screen Shot 2020-01-31 at 8 11 11 AM

**Comment by liuche** [comment]
let's also mention @AmyYLee to take a look!

**Comment by AmyYLee** [comment]
> Screen Shot 2020-01-31 at 8 10 28 AM
> 
> Screen Shot 2020-01-31 at 8 10 55 AM
> 
> Screen Shot 2020-01-31 at 8 11 11 AM

Hi, 

@kglazko  Can you please reference this mock for text formatting and layout? Thanks

https://share.goabstract.com/47608c70-5fc1-4a89-a6b3-14708787e729?mode=design&sha=ac8ee374fd619fa7e74860da1790de764881c052

**Comment by kglazko** [comment]
Absolutely! Will be a quick fix, I’ll push an updated version by the end of
the day.

**Comment by kglazko** [comment]
@AmyYLee The WiFi isn’t good enough here to use GH on a computer, I will be able to push my work tomorrow when I have access to a different connection. Is it ok if I have a different PR for changing the lock icon since it doesn’t directly fall into the scope of this PR (aka only adding the cert name and verified by)? It will help keep things organized.

**Comment by kglazko** [comment]
Screen Shot 2020-02-06 at 3 28 55 PM
Screen Shot 2020-02-06 at 3 29 22 PM

**Pull request merged**
