### PR TITLE
For #2483 #2629: Close tab with no history on back press and return to parent if available

### PR DESCRIPTION
**Pull request by mawen7**
---
Depends on
https://github.com/mozilla-mobile/android-components/pull/4400 (merged)
and
https://github.com/mozilla-mobile/android-components/pull/4798 (merged)

Known issue:

- [x] <del>Closing the second last tab doesn't update the session in engine view. Related https://github.com/mozilla-mobile/android-components/issues/3720</del>

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### CODE REVIEW

**Comment by NotWoods** [comment]
Labelling "do not land" until the corresponding Android Components PR is merged

**Comment by ekager** [comment]
Looks like mozilla-mobile/android-components#4400 has landed? Do we need to also wait for mozilla-mobile/android-components#3720 before landing this?

**Comment by mawen7** [comment]
From my point of view it can land in nightly but not in release/production.
I'll ask it I can open a PR in ac with the suggestat ed solution in https://github.com/mozilla-mobile/android-components/issues/3720.

**Comment by mawen7** [comment]
PR is now ready to land/review since it includes a workaround for https://github.com/mozilla-mobile/android-components/issues/3720

**Comment by ekager** [comment]
@pocmo what do you think about this workaround?

**Comment by ekager** [comment]
@pocmo what do you think about this workaround?

**Comment by liuche** [comment]
We'll wait on a change in AC before landing this - @csadilek can you link to the AC issue you want to fix before this lands?

**Comment by csadilek** [comment]
>@csadilek can you link to the AC issue you want to fix before this lands?

@liuche bug is already linked in description. we'll discuss today.

**Comment by csadilek** [comment]
@mawen7 we have fixed mozilla-mobile/android-components#3720 which will go out with the next A-C 18.0.0-SNAPSHOTs. This should make the patch here easier to implement.

**Comment by mawen7** [comment]
Thanks @csadilek, I think there is one last [issue](https://github.com/mozilla-mobile/android-components/pull/4798) to go.

**Comment by csadilek** [comment]
@mawen7 ok, thanks! Fix landed. :)

**Comment by ekager** [comment]
Removing the "do not land" label since it looks like all dependencies have been merged!

**Comment by mawen7** [comment]
Big thanks to everyone involved for getting this ready and finally merged :)

**Pull request merged**
