### PR TITLE
For #26454 - Update AndroidX Navigation to latest stable version 2.5.1

### LINKED ISSUE #26454: Update AndroidX Navigation to latest stable version 2.5.1
Looking to update AndroidX Navigation to the latest stable version 2.5.1 https://developer.android.com/jetpack/androidx/releases/navigation and add in the navigation-compose dependency in a followup for MR onboarding usage. For now, I want to see if we can update AndroidX Navigation without any issues.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21281)

### PR DESCRIPTION
**Pull request by gabrielluong**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [ ] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #26454

### CODE REVIEW

**Review by MozillaNoah — APPROVED** [review]

**Comment by Amejia481** [comment]
@gabrielluong how we manually checked this is not introducing any regressions? The PR looks a bit big.

**Comment by gabrielluong** [comment]
> @gabrielluong how we manually checked this is not introducing any regressions? The PR looks a bit big.

I am not intending to land this at all. I am just trying to get the build to pass and then re-think about how we should proceed.

**Comment by Amejia481** [comment]
👍🏽

**Comment by gabrielluong** [comment]
Closing this in favor of https://github.com/mozilla-mobile/fenix/pull/25991

**Pull request closed without merging**
