### PR TITLE
For #768 - Add PWA install option to menu

### PR DESCRIPTION
**Pull request by NotWoods**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

pwa-install-ui

### CODE REVIEW

**Comment by NotWoods** [comment]
@apbitner Can we use a shorter string than "Install on Home screen"? It's too long for the menu and gets truncated.

**Comment by apbitner** [comment]
@mheubusch to allow a user to install a PWA we've added "Install on Home screen" to the menu, however, it's getting truncated. Thoughts re: shortening it to just "Install"? I think we should use that verb to be consistent with other browsers.

**Comment by andreasbovens** [comment]
Shortening it to "Install" sounds good to me.

**Comment by andreasbovens** [comment]
Alternatively, "Install web app".

**Comment by mheubusch** [comment]
@NotWoods ```Install``` is good. Thank you!

**Pull request merged**
