### PR TITLE
Closes #19490 : Add event ping telemetry for the Baidu top site click

### LINKED ISSUE #19490: [Telemetry]Fenix Baidu Search tile in MozillaOnline Builds
## Description & Product Manager / Data Scientist User Story
Just like what have done in global builds about Google #17418 , we also want to add telemetry to the existing Baidu search tile in MozillaOnline builds.
## What questions will you answer with this data?
Count of users conducting searches from the Baidu Search tile.
## Acceptance Criteria
- [ ] ENG files a [DS JIRA](https://jira.mozilla.com/projects/DO/issues/DO-228?filter=allopenissues) request outlining their methodology.
- [ ] DS sign off on instrumentation methodology addressing product questions.
- [ ] Event pings can be queried via re:dash
- [ ] Event pings can be queried via amplitude
- [ ] We are sending telemetry events for the actions listed in the requirements
- [ ] We have documented the telemetry
- [ ] We have asked a data steward to [review](https://github.com/mozilla/data-review/blob/master/request.md) the telemetry

### PR DESCRIPTION
**Pull request by rxumoz**
Add event ping for Baidu topsite click

### CODE REVIEW

**Comment by jonalmeida** [comment]
I believe this would need a request for data collection here.

**Comment by rxumoz** [comment]
> I believe this would need a request for data collection here.

Thanks! Could you please tell me what exactly should I do (except the label of _needs:data review_)?

**Comment by rxumoz** [comment]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) What questions will you answer with this data?
 * How often users click the top site of Baidu (default top site of  MozillaOnline builds).

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:

* Since Baidu is one of the main business partner of MozillaOnline builds, we need this to provide information essential for advancing business objectives.

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?
 * N/A, similar event about google has already merged into code base.

4) Can current instrumentation answer these questions?
 * Currently there are no events to track this.

5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.   
 * All data is Category 2.

6) Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
 * This collection is documented in the Glean Dictionary at https://dictionary.telemetry.mozilla.org/

7) How long will this data be collected?  Choose one of the following:
* 2022-02-01 (same as **open_google_search_attribution**)

8) What populations will you measure?

* All release, beta, and nightly users with telemetry enabled. Assuming mainly in China since the top site of Baidu is default in MozillaOnline builds which mainly used in China.

9) If this data collection is default on, what is the opt-out mechanism for users?
 * Default Glean SDK opt-out mechanism.

10) Please provide a general description of how you will analyze this data.
 * Glean / Amplitude

11) Where do you intend to share the results of your analysis?
 * Only on Glean, Amplitude and with mobile teams & Beijing office colleagues.

12) Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection? If so:

* N/A.

**Comment by eliserichards** [comment]
@travis79 Are you available for a data review on this? 🙏

**Comment by travis79** [comment]
> # Request for data collection review form
> 
> **All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**
> 
>     1. What questions will you answer with this data?
> 
> 
>     * How often users click the top site of Baidu (default top site of  MozillaOnline builds).
> 
> 
>     1. Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:
> 
> 
>     * Since Baidu is one of the main business partner of MozillaOnline builds, we need this to provide information essential for advancing business objectives.
> 
> 
>     1. What alternative methods did you consider to answer these questions? Why were they not sufficient?
> 
> 
>     * N/A, similar event about google has already merged into code base.
> 
> 
>     1. Can current instrumentation answer these questions?
> 
> 
>     * Currently there are no events to track this.
> 
> 
>     1. List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Data_Collection) found on the Mozilla wiki.
> 
> 
>     * All data is Category 2.
> 
> 
>     1. Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
> 
> 
>     * This collection is documented in the Glean Dictionary at [dictionary.telemetry.mozilla.org](https://dictionary.telemetry.mozilla.org/)
> 
> 
>     1. How long will this data be collected?  Choose one of the following:
> 
> 
>     * 2022-02-01 (same as **open_google_search_attribution**)
> 
> 
>     1. What populations will you measure?
> 
> 
>     * All release, beta, and nightly users with telemetry enabled. Assuming mainly in China since the top site of Baidu is default in MozillaOnline builds which mainly used in China.
> 
> 
>     1. If this data collection is default on, what is the opt-out mechanism for users?
> 
> 
>     * Default Glean SDK opt-out mechanism.
> 
> 
>     1. Please provide a general description of how you will analyze this data.
> 
> 
>     * Glean / Amplitude
> 
> 
>     1. Where do you intend to share the results of your analysis?
> 
> 
>     * Only on Glean, Amplitude and with mobile teams & Beijing office colleagues.
> 
> 
>     1. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection? If so:
> 
> 
>     * N/A.

# Data Review

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way? 

Yes, through the metrics.yaml file and through the Glean Dictionary.

2) Is there a control mechanism that allows the user to turn the data collection on and off? (Note, for data collection not needed for security purposes, Mozilla provides such a control mechanism) Provide details as to the control mechanism available.

Yes, through the "Send Usage Data" preference in the app settings.

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

N/A, collection set to end 2022-02-01.

4) Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Category 2, Interaction data

5) Is the data collection request for default-on or default-off?

Default-on

6) Does the instrumentation include the addition of **any *new* identifiers**?

No

7) Is the data collection covered by the existing Firefox privacy notice? 

Yes

8) Does the data collection use a third-party collection tool? 

No

## Result

data-review+

**Review by rocketsroger — APPROVED** [review]

**Pull request merged**
