### PR TITLE
Fixes #18581 Fixed ETP Standard option is truncated

### LINKED ISSUE #18581: [Bug][L10n] The ETP Standard (default) option is truncated
## Steps to reproduce
1. Launch Fenix and set the language to Russian or Espanol;
2. Go to Settings -> ETP;
3. Observe the Standard (default) option;
### Expected behavior
The ETP Standard (default) option is visible.
### Actual behavior
The ETP Standard (default) option is truncated.
rsz_screenshot_20210322-152049
rsz_screenshot_20210322-152025

### Device information

* Device vendor / model and Android version: Pixel 2 (Android 9);
* Firefox for Android version: Nightly 3/22, Beta 87.0.0-beta.6 and Release 87.0.0-rc.1 from 3/17

### PR DESCRIPTION
**Pull request by bharat0to**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by topotropic** [comment]
Just to clarify, this PR is going to allow the ETP setting ("Standard (default)") float over 2 lines so that it's readable in spanish and russian, correct? Thanks!

**Comment by Amejia481** [comment]
> ETP

The PR is going to allow the high of the **"Standard (default)"** to wrap, in case the text is too long and it doesn't fit horizontally, it will adapt vertically.

**Comment by Amejia481** [comment]
Thanks for the PR @bharat0to, I updated the PR with some minor changes

**Comment by Amejia481** [comment]
This a Spanish version with a exaggerated long text
image

**Review by Amejia481 — APPROVED** [review]

**Pull request merged**
