### PR TITLE
Use Android Components 24.0.1 with Fenix 3.0.2

### PR DESCRIPTION
**Pull request by pocmo**
Updating the release branch for Fenix 3.0.2 to use Android Components 24.0.1.

### CODE REVIEW

**Comment by mcarare** [comment]
This change https://github.com/mcarare/fenix/commit/c96af458f48e3d431aa96610c4ba7afffd59dc5b should be included in this release to fix the lint issue.

**Comment by pocmo** [comment]
@mcarare Thank you. Added this patch on top.

**Comment by pocmo** [comment]
Looks like some UI test failure happened. Investigating now..

**Comment by pocmo** [comment]
It is only `testDownloadNotification` failing and only on one device. So I think we are still fine here.

**Comment by liuche** [comment]
I'll kick off a new release.

**Pull request merged**
