### PR TITLE
Publish gradle reports as artifacts

### PR DESCRIPTION
**Pull request by mitchhentges**
---
As requested [here](https://mozilla.slack.com/archives/CG2FGG1ST/p1573841677196700).
[This](https://firefox-ci-tc.services.mozilla.com/tasks/Vnnh3-3BSyqUzAzikn1C7Q) is what a task with the associated reports would look like (click the artifacts dropdown).

@JohanLorenzo I'm not sure if there's a better approach here - I think that the reports should be accessible, but it's really difficult choosing the right report in taskcluster when there's hundreds in this list, as shown in that last link^. We can do a zip-and-artifact technique, but I'm not sure if that's a good call. What do you think?

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by mitchhentges** [comment]
As recommended by Severin, I've restricted report artifacts to `reports/tests`. Here's [an example task](https://firefox-ci-tc.services.mozilla.com/tasks/AFsIvcJJReGz17mrLFvkyQ)

**Comment by mitchhentges** [comment]
@Baron-Severin let me know if there's a way that we can cut down the artifact list further. Otherwise, feel free to merge whenever you're ready :+1:

**Comment by Baron-Severin** [comment]
> @Baron-Severin let me know if there's a way that we can cut down the artifact list further. Otherwise, feel free to merge whenever you're ready 👍

@mitchhentges hmm, in [this task](https://firefox-ci-tc.services.mozilla.com/tasks/GtpPfNJIQdi5M7dtD-VGVA/runs/0) the only output we really want to see is `public/reports/testGeckoNightlyDebugUnitTest/index.html`.  It depends on everything else, though.  We could massively clean up the list by hiding anything in the `public/reports/testGeckoNightlyDebugUnitTest/classes/` folder, but only if it was still available to other files.

**Comment by mitchhentges** [comment]
@Baron-Severin 
I wanted to apply this more generally to apply to all `gradle` tasks, but:
* The test report directory changes based on the build flavor (e.g.: `testGeckoNightlyDebugUnitTest`)
* The Taskcluster artifact system doesn't allow for more selective paths, like `app/build/reports/tests/*/index.html` (or `app/build/reports/tests` + `!app/build/reports/tests/*/classes`). I can only request a specific file or directory with an absolute, no-wildcard path.

So, rather than getting too clever with this, I've **just** updated the `test-debug` task to add its test report to the list of artifacts. If we want the `index.html` report for other tasks, we'll have to manually add the artifact on a task-by-task basis

**Comment by Baron-Severin** [comment]
> So, rather than getting too clever with this, I've **just** updated the `test-debug` task to add its test report to the list of artifacts. If we want the `index.html` report for other tasks, we'll have to manually add the artifact on a task-by-task basis

That sounds like a good first step to me; we can always iterate as needed.  I'm good to merge whenever you are.

**Comment by mitchhentges** [comment]
I don't have permissions to merge, but I'm happy with landing this :+1:

**Pull request merged**
