### PR TITLE
Configure either geckoview beta or nightly at compile-time

### PR DESCRIPTION
**Pull request by mitchhentges**
Replaces #4325.
At compile time, you can choose either the `geckoNightly` or `geckoBeta` flavor.
Also updates automation to coalesce more work into less tasks by taking advantage of the APK splitting work that Sebastian did in the original PR.

[Staging nightly release](https://tools.taskcluster.net/groups/JKHgNcGZSSi7RNZKAJ48vg).

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by mitchhentges** [comment]
The [staging nightly release](https://tools.taskcluster.net/groups/JKHgNcGZSSi7RNZKAJ48vg) graph was successful (the pushapk failures are expected).

**Comment by mitchhentges** [comment]
> I think eventually we should look into building all variants for the "push" task

@pocmo when we investigate this further, what is the benefit of building additional variants on push tasks?

**Comment by pocmo** [comment]
> @pocmo when we investigate this further, what is the benefit of building additional variants on push tasks?

Less surprises. There are subtle differences in the builds and I'd prefer us to know that we are breaking the Nightly build at the time we consider merging a PR. :)

In the case of `bors`: It first merges all commits that should land to a staging branch (on top of the master state) which will trigger the push tasks. If those tasks pass then master will be fast forwarded to this state. If we build all variants then this should help us guarantee that all those variants can always be build from master (assuming reproducible builds!).

**Comment by mitchhentges** [comment]
Should we wait until we run into a case where a successful `debug` build gets landed, but a `nightly`/etc fails? Or has that happened already?

I'm lightly pushing back because building release builds have some additional constraints (such as requiring a parameterized version name), but if we perform release builds in a non-release workflow, then these constrains have to be relaxed. Not the end of the world, but perhaps not ideal.

**Comment by pocmo** [comment]
> Should we wait until we run into a case where a successful `debug` build gets landed, but a `nightly`/etc fails? Or has that happened already?

I think that has happened already. I recently fixed test errors that only happened in/with Nightly builds.

Since we have build type based feature flags and also possibly different source sets this is not impossible to happen.

> I'm lightly pushing back because building release builds have some additional constraints (such as requiring a parameterized version name), but if we perform release builds in a non-release workflow, then these constrains have to be relaxed. Not the end of the world, but perhaps not ideal.

Okay, I understand that the constraints make it harder. I still think the early feedback (right in the context of a PR) helps a lot though.

A bit off-topic though: I feel like the parameterized inputs are great for automation but have always been a bit wonky locally with gradle sync and building a different variant locally.

**Pull request merged**
