### PR TITLE
For #21309: add profiler marker for onGlobalLayout

### PR DESCRIPTION
**Pull request by mcomella**
Profile with new markers: https://share.firefox.dev/3ziGmUp

You need to run `fixed = 0; for (thr of profile.threads) { for (data of thr.markers.data) { if (data && data.type === "JavaWithDetails") { data.details = data.name; fixed +=1; } } }; fixed` to get the "text" field in the markers.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by MarcLeclair** [comment]
@mcomella  PR looks good, running `fixed = 0; for (thr of profile.threads) { for (data of thr.markers.data) { if (data && data.type === "JavaWithDetails") { data.details = data.name; fixed +=1; } } }; fixed` just returns "22" in this case. Is that the total # of markers?

**Review by MarcLeclair — APPROVED** [review]
Looks  good to me

**Comment by mcomella** [comment]
> just returns "22" in this case. Is that the total # of markers?

Yes, that's the return value. However, it also mutates the state such that the "text" items also appear on the marker hover dropdowns.

**Comment by mcomella** [comment]
Test failure is unrelated: 
```
WHEN anchorWithAction is called THEN correct text will be set

java.lang.InstantiationError: kotlin.jvm.functions.Function0
	at jdk.internal.reflect.GeneratedSerializationConstructorAccessor216.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
```

**Comment by mcomella** [comment]
Rerunning tests

**Comment by mcomella** [comment]
> Test failure is unrelated:

I filed https://github.com/mozilla-mobile/fenix/issues/21335

**Pull request merged**
