### PR TITLE
Closes #9495: Dismiss the ShareFragment in onPause()

### LINKED ISSUE #9495: [Bug] Crash on Sharing using uninstalled app
## Steps to reproduce
Open the Share Link menu from the three dot menu.
Press home button and Uninstall one of the apps shown within the menu
Return to fenix and as the app is still shown within the share sheet, click on that app.

### Expected behavior
The app should vanish from share sheet upon unsinstalling
### Actual behavior
Crash
### Device information

* Android device: Asus Zenfone
* Fenix version: Fenix Nightly

### PR DESCRIPTION
**Pull request by Mugurell**
Doing this will ensure no corruption of the initial share to apps list while the user went away.

### Pull Request checklist

- [x] **Tests**: No tests. Small change.
- [x] **Screenshots**: No screenshots. Simple flow.
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md).

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by Mugurell** [comment]
Again, congrats @abhay379201 for your first patch!
I opened a new PR just to have the obligatory tests running.
Be assured you are still the author and this patch will count against your profile.

**Comment by Mugurell** [comment]
ui-test-x86-debug seems to be failing because of `verifyReaderViewAppearanceColorSchemeChange`.
This test should not depend on this patch and locally it runs fine.
I'm thinking it's an intermittent failure which will have to be disabled..
Let's do one more try.

**Comment by abhay379201** [comment]
@Mugurell Thanks for your support

**Comment by Mugurell** [comment]
Rebased the patch after `ReaderViewTest` was disabled.
Hope all checks will now be green.

**Pull request merged**
