### PR TITLE
Changes nightly version to follow the format "Nightly 190627 16:19"

### PR DESCRIPTION
**Pull request by mitchhentges**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

I added the phrase "Nightly" to the string, so the timestamp has more context.

### CODE REVIEW

**Comment by mitchhentges** [comment]
Fixes #3315

**Comment by mitchhentges** [comment]
I'm going to hold off on merging until @colintheshots is :+1:, since its his team that has to see these nighly version names all day :smile:

**Comment by jonalmeida** [comment]
Bikeshedding: hyphens or slash between date values? 🙃

**Comment by mitchhentges** [comment]
I'm indifferent once you guys find the scheme that works best for y'all :)

**Pull request merged**
