### PR TITLE
Consume Nimbus FML plugin

### PR DESCRIPTION
**Pull request by grigoryk**
Requires A-C release with https://github.com/mozilla-mobile/android-components/pull/11420 in it.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by grigoryk** [comment]
Once this is actually working, an auto-generated `.experimenter.json` needs to be committed as part of this PR as well.

**Comment by grigoryk** [comment]
cc @jhugman

**Comment by grigoryk** [comment]
`tooling-nimbus-gradle` component is now available! https://nightly.maven.mozilla.org/?prefix=maven2/org/mozilla/components/tooling-nimbus-gradle/ - its first A-C release is `97.0.20211221022315`.

**Comment by grigoryk** [comment]
Failed in CI:
```
> Task :app:assembleNimbusTools
Checking fml binaries in /home/runner/work/fenix/fenix/app/build/bin/nimbus/nimbus-fml
Downloading archive to /home/runner/work/fenix/fenix/app/build/bin/nimbus/nimbus-fml.zip
Unzipping binary, looking for unknown-unknown-linux-musl/nimbus-fml
```

-> `unknown-unknown-linux-musl` isn't an architecture that's shipping in [`nimbus-fml.zip`](https://github.com/mozilla/application-services/releases/tag/v87.2.0). In that archive, we have `x86_64-unknown-linux-musl` which _should_ work on CI - we may need to adjust architecture detection code in the plugin though to match this...

**Comment by grigoryk** [comment]
Before landing this, verify that builds work on:
- [ ] CI
- [ ] Windows
- [ ] OSX (x86)
- [ ] OSX (M1)
- [ ] Linux (x86)

**Comment by tarikeshaq** [comment]
Hey @grigoryk! James is out until the new year but I'm online until Thursday if there is anything you need a hand with on the nimbus/fml side 😄  although I admit I know very little about gradle/groovy plugins 😅

**Comment by grigoryk** [comment]
> Hey @grigoryk! James is out until the new year but I'm online until Thursday if there is anything you need a hand with on the nimbus/fml side 😄 although I admit I know very little about gradle/groovy plugins 😅

Thanks, @tarikeshaq ! This can wait until January once we're all back :)

Basically, we need to adjust the plugin in A-C (https://github.com/mozilla-mobile/android-components/pull/11420) to use the right version of nimbus-fml binary depending on our runtime environment. And I think we'll also need to adjust a bit what goes into the `nimbus-fml.zip` during the A-S release process to ensure we have all the binaries we need for the various consumers (see the checklist above).

**Comment by grigoryk** [comment]
Also, this isn't something we can actually _consume_ in Fenix since the generated FxNimbus.kt file will rely on stuff that's only available in A-S 87.2.0, and we're not taking that in A-C until January (see https://github.com/mozilla-mobile/android-components/pull/11433).

**Pull request closed without merging**
