### PR TITLE
Fixes #4840 - Adds dark search widget based on system theme

### LINKED ISSUE #4840: Search widget is not dark in dark mode
How to reproduce:
- Set Fenix to dark mode.
- Add the Fenix search widget to the home screen

Actual result: a search bar with a white background is added to the home screen 

Expected result: a search bar with a dark background should be added (to be consistent with the dark home screen)

### PR DESCRIPTION
**Pull request by shahsurajk**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

## Screenshots: 
* System theme dark, fenix theme light
image

* System theme light, fenix theme light
image

### CODE REVIEW

**Comment by shahsurajk** [comment]
Auto changing the widget theme based on configuration changes (system wide theme change) is not done. Have little clue on how it would be done. 

Checked the `CONFIGURATION_CHANGED` broadcast receiver, based on the dark theme docs found here, but not sure how it would be done. 

ref: https://developer.android.com/guide/topics/ui/look-and-feel/darktheme#configuration_changes

**Comment by ekager** [comment]
@sblatz could you take a look at this and decide if this is too risky to land before release?

**Comment by liuche** [comment]
hey @sblatz, could you take a look at this PR? we're past code freeze now, so this should be less risky to land.

**Comment by Mugurell** [comment]
This looks like a great addition to the app!
I can help reviewing.

**Comment by Mugurell** [comment]
@shahsurajk Thank you for working on this and sorry for not reviewing sooner.
Since there are some changes needed and also 2 PRs open for the same ticket I just want to make sure you are still interested into updating this.
The changes I'm thinking of would simply involve using the `night` qualifier for the new dark themes layouts and so avoid modifying the widget provider with if/else and then focusing on the best approach for automatic refresh when the system theme changes.

**Comment by shahsurajk** [comment]
I would be interested in doing the same. :)

**Comment by Mugurell** [comment]
Awesome, thank you @shahsurajk !

Well, as I've said I think we'd really benefit from just having the new resources in a new `layout-night` resource directory.
Also in https://github.com/mozilla-mobile/fenix/pull/11575 I saw many more files touched, do we have all the needed resources here?

Regarding actually changing the layout, we refresh the widget at each 60 minutes.
For theme changes in-between this interval we should be able to use something like
>         sendBroadcast(Intent(this, SearchWidgetProvider::class.java).apply {
>             action = AppWidgetManager.ACTION_APPWIDGET_UPDATE
>             putExtra(
>                 AppWidgetManager.EXTRA_APPWIDGET_IDS,
>                 AppWidgetManager.getInstance(applicationContext).getAppWidgetIds(
>                     ComponentName(applicationContext, SearchWidgetProvider::class.java)
>                 )
>             )
>         })

from [application's onConfigurationChanged()](https://github.com/mozilla-mobile/fenix/blob/c9f8986d2b9d0452fd654ba9abbf1979fdee3403/app/src/main/java/org/mozilla/fenix/FenixApplication.kt#L424) after we verify that the uiMode has changed.
^^ This guarantees that while the process is alive we'll be able to update the layout. If the app is not running, I think there is very little we can do, especially with Oreo's background limitations, will checkup with Bram.

**Comment by Mugurell** [comment]
To not have duplicated code and also simplify things maybe that `sendBroadcast...` block of code could be put in a method inside `SearchWidgetProvider`'s companion object?

**Comment by shahsurajk** [comment]
@Mugurell there will still be changes to the SearchWidgetProvider as we resolve the attributes not via night mode directly, but using 
`ThemeManager.resolveAttribute`. Thus we'll have to have changes in the SearchWidgetProvider class.

**Comment by Mugurell** [comment]
> To not have duplicated code and also simplify things maybe that `sendBroadcast...` block of code could be put in a method inside `SearchWidgetProvider`'s companion object?

Regarding this...
Based on https://github.com/mozilla-mobile/fenix/issues/4840#issuecomment-527452868 we don't need to update the widget when the user set's a different theme inside the app.
We should always follow the system theme.

So we probably need to broadcast to update the widget only in the `onConfigurationChanged` callback in `FenixApplication`.
Then, with the resources having the same name but in a different by qualifier resource directory the widget should automagically update to the needed ui.

**Comment by shahsurajk** [comment]
@Mugurell the widget updates even if you resize it or at multiple other instances. Thus, it will re-draw itself at multiple points and thus pick up the night resources  if the app is in night mode and not the system. 

if you wish it to only follow system's behaviour them i think we'll have to do it programmatically, the way we've done in this PR.

**Comment by shahsurajk** [comment]
@Mugurell, could you give me an update on the problem i  mentioned, which is that if we chose doing it via `uiMode`, it will even refresh for app theme changes.

**Comment by Mugurell** [comment]
> @Mugurell the widget updates even if you resize it or at multiple other instances. Thus, it will re-draw itself at multiple points and thus pick up the night resources if the app is in night mode and not the system.
> 
> if you wish it to only follow system's behaviour them i think we'll have to do it programmatically, the way we've done in this PR.

I tested on a Pixel3 with Android 10 and on a Samsung S7 with Android 8 and saw that using qualified resources do get us the intended result: widget following the system theme, not the app theme.
(On the Samsung I did not find the Battery Saver system setting to test the dark layout but the widget was always using the light theme, even when the app was set to use the dark theme).

Have you seen a different behavior on other devices?

**Comment by shahsurajk** [comment]
@Mugurell  my bad, it works. was looking at the wrong place since the start :)

**Comment by shahsurajk** [comment]
Closes in favor of #13975

**Pull request closed without merging**
