### PR TITLE
For #12811: Add preference for show full url

### PR DESCRIPTION
**Pull request by hakkikaancaliskan**
I just wanted to end ongoing full url discussion.
I think this pr deserves some ux feedback.
If you don't want, feel free to close pr.

I'm not a native speaker so strings come from my limited English :)

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by filips123** [comment]
Can you make that user can decide to just strip http/https but not www?

**Comment by hakkikaancaliskan** [comment]
> Can you make that user can decide to just strip http/https but not www? I think this would be useful because in general all _web_sites will use web protocols like http/https. But there is no guarantee that websites will or will not use www, and content displayed with www and without it might be different.

UX team could decide about this. I don't think we should seperate this too.

**Comment by hakkikaancaliskan** [comment]
@AmyYLee ping

**Comment by ekager** [comment]
While I appreciate the PR and interest, I have to close it. 

We are overloaded with issues and have a massive list of priorities that might not match with what you think is most important. Even if you think it's just a small decision, it might require feedback from multiple teams and sign off from owners. Almost nothing is a trivial yes/no decision. Additionally, we don't accept unsolicited PRs that don't have an accompanying issue with a UX or product decision made. 

Lastly, please don't tag specific team members in issues and PRs. It won't get things looked at faster.

If and when a decision is made to change this, and it matches what you've come up with, you can reopen this.

**Pull request closed without merging**
