### PR TITLE
For #18175: Total protection settings option

### LINKED ISSUE #18175: Total cookie protection
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Recently Mozilla has added total cookie protection in v86 however it seems this is not yet added or implemented in Firefox Android. Please add the same

### How do you know that this problem exists today? Why is this important?
Total cookie protection missing 

### Who will benefit from it?
All users

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-9819)

### PR DESCRIPTION
**Pull request by Mugurell**
This should implement the UX from https://www.figma.com/file/OUOpOzgd4EOdgwJZvBGQ9j/TCP?node-id=286%3A13848

It continues the work from https://github.com/mozilla-mobile/fenix/pull/22766 in which I couldn't push again.
Please check the discussions there and https://mozilla-hub.atlassian.net/browse/FNXV2-21268 for more context.

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not. 
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made available on Jira.
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #18175

### CODE REVIEW

**Comment by Mugurell** [comment]
DATA REVIEW REQUEST
1. What questions will you answer with this data?

How many people currently have each cookie option selected under custom ETP.

2. Why does Mozilla need to answer these questions? Are there benefits for users?
   Do we need this information to address product or business requirements?

To better understand the usefulness of new features.

3. What alternative methods did you consider to answer these questions?
   Why were they not sufficient?

There are no other.

4. Can current instrumentation answer these questions?

No.

5. List all proposed measurements and indicate the category of data collection for each
   measurement, using the Firefox data collection categories found on the Mozilla wiki.

Measurement Name | Measurement Description | Data Collection Category | Tracking Bug
---------------- | ----------------------- | ------------------------ | ------------
`preferences.enhanced_tracking_protection` | Existing telemetry probe is updated to now also record the cookies option set in custom ETP  | Category 2 - interaction | https://github.com/mozilla-mobile/fenix/issues/18175

6. Please provide a link to the documentation for this data collection which
   describes the ultimate data set in a public, complete, and accurate way.

This collection is Glean so is documented [in the Glean Dictionary](https://dictionary.telemetry.mozilla.org).

7. How long will this data be collected?

Up until version '119', with the option to renew at that point.

8. What populations will you measure?

All channels, countries, and locales. No filters.

9. If this data collection is default on, what is the opt-out mechanism for users?

Default Glean SDK opt-out mechanism.

10. Please provide a general description of how you will analyze this data.

Glean and Amplitude. 

11. Where do you intend to share the results of your analysis?

Only on Glean, Amplitude, and with mobile teams. 

12. Is there a third-party tool (i.e. not Glean or Telemetry) that you are proposing to use for this data collection?

No.

**Comment by Mugurell** [comment]
> In general it looks good, I'm doing some manual tests to verify.
> 
> Something that I don't see it's the UI behind a feature flag **"these changes are behind the TCP flag (not the TCP onboarding one, but the TCP feature flag itself)"** , I this the tickets refers to this flag
> 
> https://github.com/mozilla-mobile/fenix/blob/cffce104cfcffe2d02fba389ccc4f785be9ac396/app/src/main/java/org/mozilla/fenix/utils/Settings.kt#L576

Thank you!
If using that flag the setting would be available sooner than the general rollout and I'm not sure this is the intention.
Asked about it here - https://mozilla-hub.atlassian.net/browse/FNXV2-21268?focusedCommentId=579762

**Comment by Amejia481** [comment]
Perfect, let's clarify :) 
I tested and was working as expected!

**Review by Amejia481 — APPROVED** [review]

**Comment by rocketsroger** [comment]
> DATA REVIEW REQUEST
> 
>     1. What questions will you answer with this data?
> 
> 
> How many people currently have each cookie option selected under custom ETP.
> 
>     2. Why does Mozilla need to answer these questions? Are there benefits for users?
>        Do we need this information to address product or business requirements?
> 
> 
> To better understand the usefulness of new features.
> 
>     3. What alternative methods did you consider to answer these questions?
>        Why were they not sufficient?
> 
> 
> There are no other.
> 
>     4. Can current instrumentation answer these questions?
> 
> 
> No.
> 
>     5. List all proposed measurements and indicate the category of data collection for each
>        measurement, using the Firefox data collection categories found on the Mozilla wiki.
> 
> 
> Measurement Name 	Measurement Description 	Data Collection Category 	Tracking Bug
> `preferences.enhanced_tracking_protection` 	Existing telemetry probe is updated to now also record the cookies option set in custom ETP 	Category 2 - interaction 	#18175
> 
>     6. Please provide a link to the documentation for this data collection which
>        describes the ultimate data set in a public, complete, and accurate way.
> 
> 
> This collection is Glean so is documented [in the Glean Dictionary](https://dictionary.telemetry.mozilla.org).
> 
>     7. How long will this data be collected?
> 
> 
> Up until version '119', with the option to renew at that point.
> 
>     8. What populations will you measure?
> 
> 
> All channels, countries, and locales. No filters.
> 
>     9. If this data collection is default on, what is the opt-out mechanism for users?
> 
> 
> Default Glean SDK opt-out mechanism.
> 
>     10. Please provide a general description of how you will analyze this data.
> 
> 
> Glean and Amplitude. 
> 
>     11. Where do you intend to share the results of your analysis?
> 
> 
> Only on Glean, Amplitude, and with mobile teams. 
> 
>     12. Is there a third-party tool (i.e. not Glean or Telemetry) that you are proposing to use for this data collection?
> 
> 
> No.

# Data Review

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way? 

Yes, through the metrics.yaml file and the [Glean Dictionary](https://dictionary.telemetry.mozilla.org/apps/fenix )

2) Is there a control mechanism that allows the user to turn the data collection on and off? 

Yes, through the "Send Usage Data" preference in the application settings

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

N/A, collection set to end or be renewed by version 119

4) Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Category 2, Interaction data

5) Is the data collection request for default-on or default-off?

default-on

6) Does the instrumentation include the addition of **any *new* identifiers**?

No

7) Is the data collection covered by the existing Firefox privacy notice? 

Yes

8) Does the data collection use a third-party collection tool? 

No

## Result

data-review+

**Review by Amejia481 — APPROVED** [review]
Great job!!

I tested locally it works as expected, the only addition, I think as part of this path we should revert https://github.com/mozilla-mobile/fenix/commit/8c752c3be1a0853368fb98faca69767a0dc331b1, as a part of the change we were  enabling TCP by force whenever `settings().enabledTotalCookieProtection` was ON, If we don't revert, users won't be able to selected the value from the UI. @jonalmeida  and I, we are working to introduce a new set of nimbus features for all MR functionality, on it you will a setting to know when you can toggle this UI.

**Comment by Mugurell** [comment]
> Great job!!
> 
> I tested locally it works as expected, the only addition, I think as part of this path we should revert [8c752c3](https://github.com/mozilla-mobile/fenix/commit/8c752c3be1a0853368fb98faca69767a0dc331b1), as a part of the change we were enabling TCP by force whenever `settings().enabledTotalCookieProtection` was ON, If we don't revert, users won't be able to selected the value from the UI. @jonalmeida and I, we are working to introduce a new set of nimbus features for all MR functionality, on it you will a setting to know when you can toggle this UI.

Thank you!
Agree on that, will wait to have the final configuration for the TCP experiment and replace [8c752c3](https://github.com/mozilla-mobile/fenix/commit/8c752c3be1a0853368fb98faca69767a0dc331b1) with the new experiment before landing.

**Comment by Mugurell** [comment]
Will add a new data review request based on the discussions from https://mozilla-hub.atlassian.net/browse/RS-455

**Comment by Mugurell** [comment]
DATA REVIEW REQUEST based on 
1. What questions will you answer with this data?

How many people currently have each cookie option selected under custom ETP.

2. Why does Mozilla need to answer these questions? Are there benefits for users?
   Do we need this information to address product or business requirements?

To better understand the usefulness of new features.

3. What alternative methods did you consider to answer these questions?
   Why were they not sufficient?

There are no other.

4. Can current instrumentation answer these questions?

No.

5. List all proposed measurements and indicate the category of data collection for each
   measurement, using the Firefox data collection categories found on the Mozilla wiki.

Measurement Name | Measurement Description | Data Collection Category | Tracking Bug
---------------- | ----------------------- | ------------------------ | ------------
`preferences.etp_custom_cookies_selection` | The option user has selected in the "Custom" mode of the Enhanced Tracking Protection settings.  | Category 2 - interaction | https://github.com/mozilla-mobile/fenix/issues/18175

6. Please provide a link to the documentation for this data collection which
   describes the ultimate data set in a public, complete, and accurate way.

This collection is Glean so is documented [in the Glean Dictionary](https://dictionary.telemetry.mozilla.org).

7. How long will this data be collected?

Up until version '119', with the option to renew at that point.

8. What populations will you measure?

All channels, countries, and locales. No filters.

9. If this data collection is default on, what is the opt-out mechanism for users?

Default Glean SDK opt-out mechanism.

10. Please provide a general description of how you will analyze this data.

Glean and Amplitude. 

11. Where do you intend to share the results of your analysis?

Only on Glean, Amplitude, and with mobile teams. 

12. Is there a third-party tool (i.e. not Glean or Telemetry) that you are proposing to use for this data collection?

No.

**Comment by rocketsroger** [comment]
> DATA REVIEW REQUEST based on
> 
>     1. What questions will you answer with this data?
> 
> 
> How many people currently have each cookie option selected under custom ETP.
> 
>     2. Why does Mozilla need to answer these questions? Are there benefits for users?
>        Do we need this information to address product or business requirements?
> 
> 
> To better understand the usefulness of new features.
> 
>     3. What alternative methods did you consider to answer these questions?
>        Why were they not sufficient?
> 
> 
> There are no other.
> 
>     4. Can current instrumentation answer these questions?
> 
> 
> No.
> 
>     5. List all proposed measurements and indicate the category of data collection for each
>        measurement, using the Firefox data collection categories found on the Mozilla wiki.
> 
> 
> Measurement Name 	Measurement Description 	Data Collection Category 	Tracking Bug
> `preferences.etp_custom_cookies_selection` 	The option user has selected in the "Custom" mode of the Enhanced Tracking Protection settings. 	Category 2 - interaction 	#18175
> 
>     6. Please provide a link to the documentation for this data collection which
>        describes the ultimate data set in a public, complete, and accurate way.
> 
> 
> This collection is Glean so is documented [in the Glean Dictionary](https://dictionary.telemetry.mozilla.org).
> 
>     7. How long will this data be collected?
> 
> 
> Up until version '119', with the option to renew at that point.
> 
>     8. What populations will you measure?
> 
> 
> All channels, countries, and locales. No filters.
> 
>     9. If this data collection is default on, what is the opt-out mechanism for users?
> 
> 
> Default Glean SDK opt-out mechanism.
> 
>     10. Please provide a general description of how you will analyze this data.
> 
> 
> Glean and Amplitude. 
> 
>     11. Where do you intend to share the results of your analysis?
> 
> 
> Only on Glean, Amplitude, and with mobile teams. 
> 
>     12. Is there a third-party tool (i.e. not Glean or Telemetry) that you are proposing to use for this data collection?
> 
> 
> No.

# Data Review

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way? 

Yes, through the metrics.yaml file and the [Glean Dictionary](https://dictionary.telemetry.mozilla.org/apps/fenix )

2) Is there a control mechanism that allows the user to turn the data collection on and off? 

Yes, through the "Send Usage Data" preference in the application settings

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

N/A, collection set to end or be renewed by version 119

4) Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Category 2, Interaction data

5) Is the data collection request for default-on or default-off?

default-on

6) Does the instrumentation include the addition of **any *new* identifiers**?

No

7) Is the data collection covered by the existing Firefox privacy notice? 

Yes

8) Does the data collection use a third-party collection tool? 

No

## Result

data-review+

**Pull request merged**
