### PR TITLE
Added UI tests for the Privacy Settings!

### PR DESCRIPTION
**Pull request by KMaragh**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by AaronMT** [comment]
@KMaragh Remember, prior to committing and pushing, on your local files, you should run ktlint and detkt straight from Gradle. I just run it from the Android Studio, Gradle sidebar

**Comment by KMaragh** [comment]
Currently waiting to add idling resources or another idling method to stop the flaky issues.

**Comment by liuche** [comment]
Hey @AaronMT and @KMaragh, is this still an active PR? We're going through and closing PRs that don't have activity, but if this is still ongoing, please re-base and repush, thanks!

**Comment by KMaragh** [comment]
@liuche I will reopen if needed. Thanks!

**Pull request closed without merging**
