### PR TITLE
Bug 1789398 - ensure task["metadata"]["owner"] is not empty on github…

### PR DESCRIPTION
**Pull request by jcristau**
…-push decision tasks

Treeherder requires this in its ingestion pipeline, so if the pusher doesn't have an email then use their name instead.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [ ] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation

Used by GitHub Actions.

### CODE REVIEW

**Comment by jcristau** [comment]
As far as I can tell this should be fine wrt chain-of-trust, because COT will just use whatever ends up in `task["metadata"]["owner"]` as `event["pusher"]["email"]`, so it'll round-trip OK.

**Review by JohanLorenzo — CHANGES_REQUESTED** [review]
I'm sorry, I haven't looked into the error but taskcluster-github doesn't seem happy with the content of the new `$if` statement[1]: 

```

Uh oh! Looks like an error! Details

SyntaxError at template.tasks[0].ownerEmail: Unexpected input for '${event.pusher.email}' at '${event.pusher.email}'
```

It prevents the decision task to be kicked off on push. Let's test this out on the staging repo with and without mergify to see how it behaves. 

[1] https://github.com/mozilla-releng/staging-fenix/commit/5303fd1e2d72cc854a34791083c516c87f92c00c

**Comment by jcristau** [comment]
Should be fixed now, https://github.com/mozilla-releng/staging-fenix/commit/6f2009673a7b8766dde5d91f107e28a15814d81d

**Comment by jcristau** [comment]
Tested in staging-focus-android, https://firefox-ci-tc.services.mozilla.com/tasks/W9t-XN5pQreYOsf-qRgVoQ is from mergify merging a PR and has owner `mergify[bot]@users.noreply.github.com`

**Review by gbrownmozilla — APPROVED** [review]

**Review by JohanLorenzo — APPROVED** [review]
Clearing "changes requested". The new tests also look good to me 👍

**Pull request merged**
