### PR TITLE
Fixes #4997: Changed navigation to ShareFragment 

### LINKED ISSUE #4997: [Bug]Share button from the 3dot button overlay doesn't work in custom tabs
## Notes
Set Fenix as your default browser

## Steps to reproduce
1. Open Gmail
2. Open a link to a website
3. After the custom tab is loaded tap on the upper right 3dot button
4. Tap on the "Share" button from the overlay

### Expected behavior
Sharing options should pop up and you should be able share the custom tab 

### Actual behavior
Nothing happens

### Device information

* Android device: Google Pixel 3a (Android 9)
* Fenix version: Build #12400613 from 28/8

### Notes
► Video

### PR DESCRIPTION
**Pull request by mcarare**
Added global navigation action to share fragment in navigation graph
Changed share button action to use global navigation to ShareFragment

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by ekager** [comment]
Thanks, looks good! You'll need to update the test `handleToolbarSharePress()` as well

**Comment by mcarare** [comment]
I will do that, also. Thanks! 
Also, related to this: On the custom tab we have a share button defined in a-c. 
It has an action different than the one in the menu, as it does not use the custom Fenix share fragment, but the default layout. Maybe we should consider a change to that button, to keep consistency between behaviours? Or completely remove it?

**Comment by ekager** [comment]
Yep! There's a bug for that and I think it requires future AC work https://github.com/mozilla-mobile/fenix/issues/2933

**Comment by mcarare** [comment]
No worries! Thank you again!

**Pull request merged**
