### PR TITLE
Update Android Components version

### PR DESCRIPTION
**Pull request by MickeyMoz**

### CODE REVIEW

**Comment by jonalmeida** [comment]
The toolchain task is failing because of breaking APIs:

```
[task 2020-06-12T20:48:06.540Z] > Task :app:compileGeckoBetaDebugKotlin FAILED
[task 2020-06-12T20:48:06.540Z] e: /builds/worker/checkouts/src/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt: (386, 17): Type mismatch: inferred type is SessionManager but BrowserStore was expected
[task 2020-06-12T20:48:06.540Z] e: /builds/worker/checkouts/src/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt: (390, 17): Too many arguments for public constructor PictureInPictureFeature(store: BrowserStore, activity: Activity, crashReporting: CrashReporting? = ..., tabId: String? = ...) defined in mozilla.components.feature.session.PictureInPictureFeature
[task 2020-06-12T20:48:06.540Z] e: /builds/worker/checkouts/src/app/src/main/java/org/mozilla/fenix/components/TabCollectionStorage.kt: (74, 16): Type mismatch: inferred type is Flow<List<TabCollection>> but LiveData<List<TabCollection>> was expected
[task 2020-06-12T20:48:06.540Z] e: /builds/worker/checkouts/src/app/src/main/java/org/mozilla/fenix/components/TopSiteStorage.kt: (44, 16): Type mismatch: inferred type is Flow<List<TopSite>> but LiveData<List<TopSite>> was expected
[task 2020-06-12T20:48:06.540Z] e: /builds/worker/checkouts/src/app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserFragment.kt: (102, 25): Type mismatch: inferred type is SessionManager but BrowserStore was expected
[task 2020-06-12T20:48:06.540Z] e: /builds/worker/checkouts/src/app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserFragment.kt: (103, 25): Type mismatch: inferred type is BrowserToolbar! but CustomTabsServiceStore was expected
[task 2020-06-12T20:48:06.540Z] e: /builds/worker/checkouts/src/app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserFragment.kt: (105, 25): Type mismatch: inferred type is List<Uri> but WebAppManifest? was expected
[task 2020-06-12T20:48:06.540Z] e: /builds/worker/checkouts/src/app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserFragment.kt: (161, 32): Unresolved reference: onTrustedScopesChange
[task 2020-06-12T20:48:06.940Z] 
```

@NotWoods I think you worked on this. Do you have a PR to fix these?

**Comment by NotWoods** [comment]
https://github.com/mozilla-mobile/fenix/pull/11481 for Flow changes

**Comment by NotWoods** [comment]
https://github.com/mozilla-mobile/fenix/pull/11539 contains everything

**Comment by jonalmeida** [comment]
Closing in place of https://github.com/mozilla-mobile/fenix/pull/11539.

**Pull request closed without merging**
