### PR TITLE
Fix disabled toggleSearchSuggestions UI test

### PR DESCRIPTION
**Pull request by AndiAJ**
For [#479](https://github.com/mozilla-mobile/mobile-test-eng/issues/479)
✔️ Successfully ran 50x on Firebase

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by AaronMT — CHANGES_REQUESTED** [review]
See comment below. Can you also run this one a number of times after the change?

**Comment by AndiAJ** [comment]
> See comment below. Can you also run this one a number of times after the change?

Hi @AaronMT moved the function to [TestHelper.kt](https://github.com/mozilla-mobile/fenix/blob/main/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt)

Successfully re-ran both `toggleSearchSuggestions` and `shortcutButtonTest` for 50x 

<h1 style="box-sizing: border-box; font-size: 2em; margin: 24px 0px 16px; font-weight: 600; line-height: 1.25; padding-bottom: 0.3em; border-bottom: 1px solid var(--color-border-muted); color: rgb(201, 209, 217); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Results</h1>

matrix | result | logs | details
-- | -- | -- | --
matrix-1dhte7f0xk2i6 | success | logs | 2 test cases passed
matrix-okkxu1rrs7ufa | success | logs | 2 test cases passed
matrix-pyxyg4hylacya | success | logs | 2 test cases passed
matrix-hfv1o02pbuu7a | success | logs | 2 test cases passed
matrix-5sx4sob6b6r3a | success | logs | 2 test cases passed
matrix-27flxdesiibd1 | success | logs | 2 test cases passed
matrix-2ebbs03sq6dsh | success | logs | 2 test cases passed
matrix-1c5h1s67405v3 | success | logs | 2 test cases passed
matrix-3igwc0mp5u8we | success | logs | 2 test cases passed
matrix-2zuwsik1hpifc | success | logs | 2 test cases passed
matrix-sxb664ibfvdsa | success | logs | 2 test cases passed
matrix-1r6dxtvnnn3oa | success | logs | 2 test cases passed
matrix-1tlf2tt8qo77f | success | logs | 2 test cases passed
matrix-3ktpcto1v8a95 | success | logs | 2 test cases passed
matrix-1zdcw54sqo5ls | success | logs | 2 test cases passed
matrix-37s4n7slgkzn9 | success | logs | 2 test cases passed
matrix-wq2fzjdcxfhqa | success | logs | 2 test cases passed
matrix-1bokwhpezzav9 | success | logs | 2 test cases passed
matrix-3ut2vn455pl78 | success | logs | 2 test cases passed
matrix-31pexuu3f419g | success | logs | 2 test cases passed
matrix-3g1bb2zmqdg7i | success | logs | 2 test cases passed
matrix-1rk2do1uieto4 | success | logs | 2 test cases passed
matrix-8e54kqkx9hrna | success | logs | 2 test cases passed
matrix-13ma1e2fklzwr | success | logs | 2 test cases passed
matrix-2umqslxyp66jr | success | logs | 2 test cases passed
matrix-296wfgogkpine | success | logs | 2 test cases passed
matrix-1r1t2iwe05ehx | success | logs | 2 test cases passed
matrix-ub3xyp4s1swha | success | logs | 2 test cases passed
matrix-3ft3mp2uo6u8x | success | logs | 2 test cases passed
matrix-1qzzgco9a2o5g | success | logs | 2 test cases passed
matrix-f4n6el8s5kmia | success | logs | 2 test cases passed
matrix-adkgvdyw2tfoa | success | logs | 2 test cases passed
matrix-3k36jt6y66z74 | success | logs | 2 test cases passed
matrix-1dbocd9wa9i3r | success | logs | 2 test cases passed
matrix-3cxirdp5l4gra | success | logs | 2 test cases passed
matrix-2o4jgy1qeh9x0 | success | logs | 2 test cases passed
matrix-2qbxgtusq2qj5 | success | logs | 2 test cases passed
matrix-3148yilhszlia | success | logs | 2 test cases passed
matrix-3gu8g571dvdy4 | success | logs | 2 test cases passed
matrix-12d34oen0ueyd | success | logs | 2 test cases passed
matrix-27y0h6elv7ik9 | success | logs | 2 test cases passed
matrix-1wmey8edao1rz | success | logs | 2 test cases passed
matrix-l6fhjmbwegxpa | success | logs | 2 test cases passed
matrix-olej5qjb0asca | success | logs | 2 test cases passed
matrix-3d97ecla0ysiv | success | logs | 2 test cases passed
matrix-2rf9datg4uw69 | success | logs | 2 test cases passed
matrix-1mltemqfgjr4l | success | logs | 2 test cases passed
matrix-3v9trhzclcvyq | success | logs | 2 test cases passed
matrix-6g09kukc8a3la | success | logs | 2 test cases passed
matrix-md06anei29jva | success | logs | 2 test cases passed

**Review by AaronMT — APPROVED** [review]
Looks OK to me. Let's try it.

**Comment by AaronMT** [comment]
@AndiAJ Oh this needs a rebase due to your other commit. Feel free to land after.

**Pull request merged**
