### PR TITLE
GeckoProvider: Remove useContentProcessHint() and add useMultiprocess()..

### PR DESCRIPTION
**Pull request by pocmo**
Breaking API change in GeckoView Nightly:
https://mozilla.github.io/geckoview/javadoc/mozilla-central/org/mozilla/geckoview/doc-files/CHANGELOG

### CODE REVIEW

**Comment by pocmo** [comment]
I can't reproduce those test failures locally. 🤔

**Comment by mcarare** [comment]
> I can't reproduce those test failures locally. 🤔

I think it might be used only on performance testing, not in unit tests.

**Comment by pocmo** [comment]
> I think it might be used only on performance testing, not in unit tests.

I'm not sure I understand what you mean?

Looking at the taskcluster logs I see some test failures:

https://firefox-ci-tc.services.mozilla.com/tasks/dMV8H-v8Qqe7oHiN80VrcA/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FdMV8H-v8Qqe7oHiN80VrcA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

I can't reproduce them locally - even when running the same command as taskcluster.

**Comment by mcarare** [comment]
@pocmo  Sorry, I thought you meant the changes in this PR, not the tests. I also have some PR's with something failing, that I cannot reproduce locally. Maybe is a dependencies caching issue?

**Comment by pocmo** [comment]
Rerunning once with `useMultiprocess(false)` - although I do not expect this to change anything.

**Comment by ekager** [comment]
We're seeing these (new) test failures on other PRs too so it's not about `useMultiprocess(true/false)` :/

**Comment by ekager** [comment]
Opened https://github.com/mozilla-mobile/fenix/issues/8470 for the test failures

**Comment by ekager** [comment]
According to GV engineers on Slack we shouldn't need to set `useMultiprocess`. I pulled removing `useContentProcessHint` into fixing the unit tests in #8471

**Comment by ekager** [comment]
Closing because #8471 should resolve

**Pull request closed without merging**
