### PR TITLE
Closes A-C #3695 - add UI to open current page in external app

### PR DESCRIPTION
**Pull request by jhugman**
Closes [ac#3695][1].

[1]: https://github.com/mozilla-mobile/android-components/issues/3695

### Pull Request checklist

- [X] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by jhugman** [comment]
### Design

without app icon

### Implementation

image

**Comment by colintheshots** [comment]
Did design sign off on this? They're also trying to add yet another button to the QAB to Collect tabs in collections.

**Comment by jhugman** [comment]
> Did design sign off on this?

@shorlander did the design.

> Strict mode violations.

Yes, this is the subject of [ac#3748][1]. I very much agree that this should be fixed, but I don't think it should be block this from landing.

[1]: https://github.com/mozilla-mobile/android-components/issues/3748

**Comment by colintheshots** [comment]
> > Strict mode violations.
> 
> Yes, this is the subject of [ac#3748](https://github.com/mozilla-mobile/android-components/issues/3748). I very much agree that this should be fixed, but I don't think it should be block this from landing.

Sounds good. I agree that we shouldn't block landing this. I want this to be on the short-range radar.

**Comment by jhugman** [comment]
@boek Added #4123 and tracking [ac#3748][1] as followups.

Please land when ready.

[1]: https://github.com/mozilla-mobile/android-components/issues/3748

**Pull request merged**
