### PR TITLE
Switch to `full` megazord, remove direct A-S dependency.

### PR DESCRIPTION
**Pull request by grigoryk**
Testing things out in CI...

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by grigoryk** [comment]
As far as I can tell, we never actually exercise the a-s libraries in Fenix tests currently. In a different branch I've started work on adding end-to-end tests, but currently that's blocked on trying to figure out to load native libraries in tests (somehow, fenix's setup is different than what we have in A-C, not yet clear to me in what way).

But! Locally, this branch behaves correctly - `app:dependencies` correctly reports A-S version that's expected - and it comes directly from whatever version of A-C we're building. E.g. locally I can bump my A-C's `dependencies`, and change is picked up correctly by a fenix build without any necessary changes. All Fenix tests also seem to pass for me locally - unit tests, anyway.

So let's see how this does on CI. If we get a green build, let's land this.

**Comment by grigoryk** [comment]
This also switches Fenix to use the `full` megazord, which is essentially what `fenix` megazord is at this point. A-S team wants to remove the `fenix` megazord, so this will help. e.g. https://github.com/mozilla/application-services/pull/2565 is blocked on this work.

So far, this is looking good. I'm going to see if we can remove appservices module substitutions, and inspect local builds coming out of this simplified setup.

**Comment by grigoryk** [comment]
Removing module substitutions didn't seem to affect the final artifact in any meaningful way. `app:dependencies` are the same, inspecting APKs i see the same compiled `libs`, builds work correctly on both the emulator (x86) and my Pixel 3 (arm).

**Comment by ekager** [comment]
Should we also remove the inaccurate comments with `setupMegazord` about the Fenix specific megazord so no one gets confused like me about what's happening?

**Comment by grigoryk** [comment]
> Should we also remove the inaccurate comments with `setupMegazord` about the Fenix specific megazord so no one gets confused like me about what's happening?

Just did :)

**Comment by grigoryk** [comment]
ui test failure in CI seems irrelevant to these changes:
```
org.mozilla.geckoview.GeckoResult$UncaughtException: java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()

     FATAL EXCEPTION: main
Process: org.mozilla.fenix.debug, PID: 7787
org.mozilla.geckoview.GeckoResult$UncaughtException: java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()
	at org.mozilla.geckoview.GeckoResult.dispatchLocked(GeckoResult.java:639)
	at org.mozilla.geckoview.GeckoResult.completeExceptionally(GeckoResult.java:782)
	at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$2$GeckoResult(GeckoResult.java:465)
	at org.mozilla.geckoview.-$$Lambda$GeckoResult$gwCgOUK_EYQn2g6GolfZvo6A_WE.run(lambda)
	at org.mozilla.geckoview.GeckoResult.lambda$dispatchLocked$3(GeckoResult.java:653)
	at org.mozilla.geckoview.-$$Lambda$GeckoResult$PehjG2jgyDa_p37vZrKrSi2I94s.run(lambda)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()
	at androidx.fragment.app.Fragment.getViewLifecycleOwner(Fragment.java:328)
	at org.mozilla.fenix.browser.BaseBrowserFragment$adjustBackgroundAndNavigate$$inlined$let$lambda$1.invoke(BaseBrowserFragment.kt:478)
	at org.mozilla.fenix.browser.BaseBrowserFragment$adjustBackgroundAndNavigate$$inlined$let$lambda$1.invoke(BaseBrowserFragment.kt:98)
	at mozilla.components.browser.engine.gecko.GeckoEngineView$captureThumbnail$1.onValue(GeckoEngineView.kt:171)
	at mozilla.components.browser.engine.gecko.GeckoEngineView$captureThumbnail$1.onValue(GeckoEngineView.kt:25)
	at org.mozilla.geckoview.GeckoResult.lambda$thenInternal$2$GeckoResult(GeckoResult.java:451)
	... 10 more

```

**Comment by grigoryk** [comment]
Second failure had the same stacktrace.

**Pull request merged**
