### PR TITLE
For #19567 - Change saved logins fragments to SecureFragment

### PR DESCRIPTION
**Pull request by Alexandru2909**
Changed SavedLoginsFragment and LoginDetailFragment to extend SecureFragment, instead of manually setting flags.

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by mcarare — APPROVED** [review]
LGTM!

**Comment by gabrielluong** [comment]
> LGTM!

I think we need to manually open a new PR so CI will fully run.

**Comment by mcarare** [comment]
@gabrielluong This seems like a regression in the contributor workflow. Previously we were able to merge the original PR after another PR for running CI was opened.

**Comment by gabrielluong** [comment]
> @gabrielluong This seems like a regression in the contributor workflow. Previously we were able to merge the original PR after another PR for running CI was opened.

I believe that is still true. I opened the CI PR in https://github.com/mozilla-mobile/fenix/pull/23085.

**Comment by gabrielluong** [comment]
This looks like it is holding up the mergify queue.

**Pull request merged**
