### PR TITLE
For #27346 - Disable swiping to switch tabs when fullscreen

### LINKED ISSUE #27346: [Bug]: Toolbar swiping activates even in fullscreen videos when toolbar is not shown
### Steps to reproduce

1. Go to **Settings -> Customize** and set **Scroll to hide toolbar** to **disabled** and **Swipe toolbar sideways to switch tabs** to **enabled** (the bug occurs only in this combination of settings)
2. Open **several tabs** (any websites)
3. Open websites with video, e.g. https://www.youtube.com (happens on other sites as well)
4. Rotate your phone to a **landscape** mode (this is an important step)
5. Play some video and switch it into **fullscreen**
6. See that the bottom toolbar is not shown during fullscreen video playback (which is correct).
7. Try to **swipe on the bottom edge** of the screen left and right, as if the toolbar was there. See that you actually **can swipe** there and switch to a different tab.
8. Back in the fullscreen video, try to use the progress bar slider to **move in the video forward and backward**. Depending on the how close is the slider to the bottom edge of the screen (depending on the website and perhaps your phone dimensions), sometimes it can get extremely tricky to move in the video instead of activating swiping on the invisible toolbar.
9. Repeat the whole process, but this time with **Scroll to hide toolbar** set to **enabled**. The problem doesn't appear. It only appears if the combination of both settings mentioned in step 1 is set as described.

### Expected behaviour

Toolbar swiping shouldn't work when the toolbar is not displayed (e.g. in a fullscreen video).

### Actual behaviour

Toolbar swiping works in a fullscreen video in the described situation, which makes seeking in video very hard.

### Device name

Samsung Galaxy A33

### Android version

Android 12

### Firefox release type

Firefox

### Firefox version

105.2.0

### Device logs

_No response_

### Additional information

See a screencast of the problem below. In the second half of the video, you can see how difficult it is for me to seek to a different part of the video. My touches are interpreted as tab swiping.

https://user-images.githubusercontent.com/755451/194754619-fafd13e2-b958-44d5-b276-0f3d9b89bbd1.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21767)

### PR DESCRIPTION
**Pull request by Mugurell**
https://user-images.githubusercontent.com/11428869/195129687-bc7ec7a9-4535-468d-b485-ba8cf84e5e87.mp4

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #27346

### CODE REVIEW

**Comment by gabrielluong** [comment]
@Mugurell Can you check in with Product and UX to inform them of the issue and the fix that you have proposed here? Just want make sure all of this is expected by all parties before proceeding.

**Comment by fice-t** [comment]
@Mugurell I noticed that I am still able to activate this gesture with the default setup (bottom toolbar + dynamic toolbar) when the toolbar is hidden, which seems like a bug.

Would it make sense to instead check whether or not the toolbar is visible rather than disabling the gesture in fullscreen mode? That should take care of both issues if it's feasible.

**Comment by Mugurell** [comment]
> @Mugurell I noticed that I am still able to activate this gesture (outside of fullscreen mode) with the default setup (bottom toolbar + dynamic toolbar) when the toolbar is hidden, which seems like a bug.

This shouldn't happen. Can you post in the ticket some steps to reproduce / a video?

**Comment by fice-t** [comment]
I believe this should also fix #13845.

**Review by MozillaNoah — COMMENTED** [review]
This looks good to me. I wasn't able to reproduce this locally with the proposed fix. Per the above comment from @gabrielluong, I'll formally approve this behavior if it has been verified by product/UX.

**Review by gabrielluong — APPROVED** [review]
We did raise this with @kbrosnan and got the okay.

Screen Shot 2022-11-16 at 8 11 44 PM

**Pull request merged**
