### PR TITLE
For #8797: Do not allow nested scrolling on top sites.

### PR DESCRIPTION
**Pull request by mcomella**
@boek Can you merge this PR and, when you do, update the bug status as needed?

Note: my solution for this does not address https://github.com/mozilla-mobile/fenix/issues/8561

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by boek** [comment]
@mcomella good catch!

**Comment by mcomella** [comment]
Looks like UI tests failed due to a timeout?

> [task 2020-02-26T23:41:37.273Z] Error: Matrix not finished: matrix-2pxph6a3sv6ac ERROR   

@boek Is there anything for me to do here or can we land?

**Comment by mcomella** [comment]
Retriggering...

**Comment by boek** [comment]
🤞

**Pull request merged**
