### PR TITLE
For #17966: Crash if entering PIP on Samsung devices with Talkback on

### PR DESCRIPTION
**Pull request by yichiehc**
Fixes issue #17966
Added a condition to check and avoid entering PiP if Talkback is turned on on a Samsung device.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by Mugurell** [comment]
Thank you @yichiehc for taking a stab at this!
Looks like there is indeed a crash in ActivityManager but the exception is caught and there is already code preventing it from crashing the app.
Closing this PR as there is no further action necessary.

**Comment by yichiehc** [comment]
Hi @Mugurell,

I have a question not related to this specific pull request...
How can I get rid of all those irrelevant commits when opening a pull request? Please see the screenshot below.

What I usually do on Git:
git checkout -b mybranch
[make changes]
git add .
git commit -m "..."
git pull upstream master
git checkout master
git pull upstream master
git push origin master
git checkout mybranch
git push origin mybranch
[open a PR]

Thanks a lot!

**Comment by Mugurell** [comment]
I think this happens because of that first `git pull upstream master` done in your feature branch which will try to merge the new changes into your branch. 
You could do `git pull upstream master --rebase` or even set have set `git config --global pull.rebase true` so that all future pulls will rebase the current CLs by default.
Otherwise, it's great that you want to keep your patch synced with the latest master before and after finishing your work! 👍

**Comment by yichiehc** [comment]
> I think this happens because of that first `git pull upstream master` done in your feature branch which will try to merge the new changes into your branch.
> You could do `git pull upstream master --rebase` or even set have set `git config --global pull.rebase true` so that all future pulls will rebase the current CLs by default.
> Otherwise, it's great that you want to keep your patch synced with the latest master before and after finishing your work! 👍

Thank you so much @Mugurell! I tried `git pull upstream master --rebase`, along with some other commands, and it works!

**Pull request closed without merging**
