### PR TITLE
WIP re-enable ContextMenusTest.kt

### PR DESCRIPTION
**Pull request by AaronMT**
We'll see which fails still on this PR and work from there.

### CODE REVIEW

**Comment by AaronMT** [comment]
So yet another race. I've simulated and reproduced the intermittent failures happening here happening with 
`setBodyDelay(3, TimeUnit.SECONDS)` on MockResponse probably waiting for the images.

We need to use something like https://github.com/JakeWharton/okhttp-idling-resource (although no AndroidX support https://github.com/JakeWharton/okhttp-idling-resource/issues/19)

**Comment by AaronMT** [comment]
Been using this PR as a playground for implementing sessionloadedidlingresource. However I think I'm actually hitting what FirefoxLite it hitting: https://github.com/mozilla-tw/FirefoxLite/issues/3110

We're currently using 3.11.0 

@cnevinc did upgrading MockWebServer fix this for you? Is sessionloadedidlingresource working out for you?

**Comment by ekager** [comment]
Looks like this is still waiting on #9238

**Comment by AaronMT** [comment]
Going to re-open different PR.

**Pull request closed without merging**
