### PR TITLE
No issue: Upgrades to AC 1.0.0.

### PR DESCRIPTION
**Pull request by sblatz**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by colintheshots** [comment]
Taskcluster seems to be getting a 404 error obtaining the ARM32 GeckoView *.pom file. Why is it looking at Google for this dependency? Huh?

https://dl.google.com/dl/android/maven2/org/mozilla/geckoview/geckoview-beta-x86_64/68.0.20190612114833/geckoview-beta-x86_64-68.0.20190612114833.pom

**Comment by pocmo** [comment]
This looks like an intermittent connection issue on taskcluster.

**Comment by pocmo** [comment]
While we update AC we could (and most of the time should) also update the Gecko version to match the one of the release:
https://github.com/mozilla-mobile/android-components/blob/v1.0.0/buildSrc/src/main/java/Gecko.kt#L14

**Comment by pocmo** [comment]
Oh, changing the title does not re-run the task here?

**Pull request merged**
