### PR TITLE
For #10285: Improve a11y for links in app.

### PR DESCRIPTION
**Pull request by mcarare**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by sblatz** [comment]
@MReschenberg please take a look and make sure this is a reasonable thing to announce with Screen Reader :)

**Comment by MReschenberg** [comment]
Solution looks good to me, checking with eitan to make sure this is a reasonable string.

**Comment by mcarare** [comment]
@eeejay I have previously investigated the possibility of implementing something similar to the code you've linked. Unfortunately, we cannot implement the `roleDescription` in the same manner, because AccessibilityNodeInfo for Views does not have the same info as in your example. (`getExtra` return an empty Bundle, we do not have access to GeckoBundle). So, I can only add the "Link" as a `roleDescription` in the extra bundle for AccessibilityNodeInfo (already implemented the change), but it still has do be localized.

As to the action description, I felt that " double tap to activate" is not relevant info for a link, as it is the same announcement for any other view that has a click listener (buttons, images, etc). That is why I implemented the "to follow link" part.
Also, I have removed the long click announcement, as there is in fact no action for long click.

**Comment by eeejay** [comment]
> @eeejay I have previously investigated the possibility of implementing something similar to the code you've linked. Unfortunately, we cannot implement the `roleDescription` in the same manner, because AccessibilityNodeInfo for Views does not have the same info as in your example. (`getExtra` returns an empty Bundle, we do not have access to GeckoBundle). So, I can only add the "Link" as a `roleDescription` in the extra bundle for AccessibilityNodeInfo (already implemented the change), but it still has to be localized.

The GeckoBundle type you see there is unrelated. It is just how we pass things via JNI from native gecko. The string value of key `AccessibilityNodeInfo.roleDescription` needs to simply be a lowercase `link`. You might be right about the localization. But either way, that is less to translate and less to customize. The click action can be left alone.

**Comment by ekager** [comment]
@sblatz looks like this has been updated - could you rereview?

**Comment by sblatz** [comment]
@mcarare are there more places we can apply this while doing this update? :)

**Comment by mcarare** [comment]
@sblatz Yes, there are more "learn more" links in the app. I did not work on changing them also until I had the go ahead with this solution.

**Comment by sblatz** [comment]
This looks good to me. @MReschenberg or @eeejay can you confirm from the accessibility side?

**Comment by liuche** [comment]
@mcarare looks like this has approval from both a11y and a reviewer, so feel free to rebase and then land it!

**Comment by mcarare** [comment]
Re-running for unrelated test-debug failure: 

`[task 2020-06-26T05:29:37.446Z]   TEST: GIVEN collection WHEN renameCollection is called THEN collection should be renamed

[task 2020-06-26T05:29:37.546Z]   FAILURE
[task 2020-06-26T05:29:37.547Z] 

[task 2020-06-26T05:29:37.548Z] java.lang.AssertionError: Verification failed: call 2 of 3: TabCollectionStorage(tabCollectionStorage#180).renameCollection(eq(TabCollection(#182)), eq(name))) was not called`

**Pull request merged**
