### PR TITLE
Unit tests: Bump max heap size to 3072m.

### PR DESCRIPTION
**Pull request by pocmo**
~~Just a PR to test various things and whether they fix the test hangs we are seeing...~~

Bumping the max heap size seems to avoid the test hangs we have been seeing in automation.

### CODE REVIEW

**Comment by pocmo** [comment]
Test Run 1: https://firefox-ci-tc.services.mozilla.com/tasks/d9kAssOiSeqE3rQYA1Dyow

**Comment by pocmo** [comment]
Test run 2:
https://github.com/mozilla-mobile/fenix/pull/19313

**Comment by st3fan** [comment]
It is green! I'll kick it again.

**Comment by st3fan** [comment]
Let's do this one more time ...

**Comment by pocmo** [comment]
Still green. Looks like it's indeed the same problem as before... and now with more tests we leak more memory. I'll try to tweak the numbers a bit in this PR. I would like to keep `forkEvery` high (if possible) to not slow down test runs.

In the original issue Mike traced this back to a potential problem/leak in Roboletric. So additionally I'll take a look at updating the dependency and see if that improves things too.

**Comment by pocmo** [comment]
Upgrading Robolectric is a rabbit hole with a bunch of test failures. Back to this workaround. I'll try this again with 3GB for tests and leaving `forkEvery` untouched.

**Comment by pocmo** [comment]
* Run 1: https://firefox-ci-tc.services.mozilla.com/tasks/groups/Z0jzrgYqROeJp2PoQbuRew
* Run 2: https://firefox-ci-tc.services.mozilla.com/tasks/groups/MS3VtzzYS723LZnuHm5n7A
* Run 3: https://firefox-ci-tc.services.mozilla.com/tasks/groups/bPWpPElGTlOtsd8_MDUedg
* Run 4: https://firefox-ci-tc.services.mozilla.com/tasks/groups/B1-kL8wbR3CuX30d_lhzCg
* Run 5: https://firefox-ci-tc.services.mozilla.com/tasks/groups/GQpgBjVjQpe5wo0EuaAd1A

**Comment by pocmo** [comment]
There are no hangs in those runs, I think we should land this.

**Review by st3fan — APPROVED** [review]
Ship it

**Comment by st3fan** [comment]
Lets uplift this to the Beta branch too .. cc @rvandermeulen

**Comment by rvandermeulen** [comment]
Would be great if we could uplift to both the v88 and v89 branches.

**Comment by pocmo** [comment]
> Would be great if we could uplift to both the v88 and v89 branches.

I'll put up PRs.

**Pull request merged**
