### PR TITLE
For #16396: Fix text contrast ratio on "recently closed tabs"

### PR DESCRIPTION
**Pull request by fevziomurtekin**
Hi! I fixed the specified error. 

Screenshot: 
Screen Shot 2021-01-23 at 19 54 37

### CODE REVIEW

**Review by topotropic — APPROVED** [review]
LGTM, thanks!

**Comment by fevziomurtekin** [comment]
I accidentally deleted this branch when I was trying to clear the branches in the project. Sorry.

**Comment by eliserichards** [comment]
Re-opening this so our CI can run :)

**Review by eliserichards — APPROVED** [review]
Looks good! Thanks for tackling this issue @fevziomurtekin! Once the CI runs and the build is green we can get this merged 🚀

**Comment by fevziomurtekin** [comment]
You're welcome, it was a pride for me. I'm so excited to be able to contribute a little to Mozilla! 😊 🚀

**Comment by eliserichards** [comment]
Hey @fevziomurtekin , just wanted to keep you in the loop about what's going on - we found some flaky tests that need to be fixed before this gets landed (nothing to do with your PR, don't worry). I'm sorry this is taking so long! I hope you are ok with waiting a bit longer 😅

**Comment by fevziomurtekin** [comment]
Hi @eliserichards, It's not problem for me. I wait 😄 By the way, thank you very much for letting me know.

**Pull request merged**
