### PR TITLE
Closes #5876: Removed @ObsoleteCoroutinesApi in tests

### LINKED ISSUE #5876: Remove @ObsoleteCoroutinesApi in tests
We have various roboletric tests that use `TestApplication`. [`TestApplication` used to have a `@ObsoleteCoroutinesApi` annotation](https://github.com/mozilla-mobile/fenix/pull/5810), resulting in all roboletric also needing the annotation. We can now remove it where unnecessary.

Note: Android Studio will complain if it is necessary and you remove the annotation, so it's easy to check 😄

### PR DESCRIPTION
**Pull request by shldhll**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by sblatz** [comment]
bors r=sblatz

**Comment by sblatz** [comment]
@shldhll looks like when compiling test-debug we run into these errors:

> Task :app:compileGeckoNightlyDebugUnitTestKotlin FAILED
[task 2019-10-10T00:35:31.744Z] e: /builds/worker/checkouts/src/app/src/test/java/org/mozilla/fenix/share/ShareControllerTest.kt: (47, 18): Unresolved reference: ObsoleteCoroutinesApi
[task 2019-10-10T00:35:31.744Z] e: /builds/worker/checkouts/src/app/src/test/java/org/mozilla/fenix/share/ShareControllerTest.kt: (47, 18): An annotation argument must be a compile-time constant
[task 2019-10-10T00:35:31.744Z] e: /builds/worker/checkouts/src/app/src/test/java/org/mozilla/fenix/share/listadapters/AccountDevicesShareAdapterTest.kt: (26, 18): Unresolved reference: ObsoleteCoroutinesApi
[task 2019-10-10T00:35:31.744Z] e: /builds/worker/checkouts/src/app/src/test/java/org/mozilla/fenix/share/listadapters/AccountDevicesShareAdapterTest.kt: (26, 18): An annotation argument must be a compile-time constant
[task 2019-10-10T00:35:31.744Z] e: /builds/worker/checkouts/src/app/src/test/java/org/mozilla/fenix/share/listadapters/AppShareAdapterTest.kt: (26, 18): Unresolved reference: ObsoleteCoroutinesApi
[task 2019-10-10T00:35:31.745Z] e: /builds/worker/checkouts/src/app/src/test/java/org/mozilla/fenix/share/listadapters/AppShareAdapterTest.kt: (26, 18): An annotation argument must be a compile-time constant

**Comment by shldhll** [comment]
@sblatz It should be fine now. Also, shouldn't pre-push hook run these tests locally too?

**Comment by sblatz** [comment]
@shldhll 
new errors found:
> e: warnings found and -Werror specified
[task 2019-10-10T14:03:24.572Z] w: /builds/worker/checkouts/src/app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt: (57, 39): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ObsoleteCoroutinesApi' or '@UseExperimental(kotlinx.coroutines.ObsoleteCoroutinesApi::class)'
[task 2019-10-10T14:03:24.572Z] w: /builds/worker/checkouts/src/app/src/test/java/org/mozilla/fenix/settings/deletebrowsingdata/DefaultDeleteBrowsingDataControllerTest.kt: (35, 39): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ObsoleteCoroutinesApi' or '@UseExperimental(kotlinx.coroutines.ObsoleteCoroutinesApi::class)'
[task 2019-10-10T14:03:24.572Z] w: /builds/worker/checkouts/src/app/src/test/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteAndQuitTest.kt: (41, 39): This declaration is experimental and its usage should be marked with '@kotlinx.coroutines.ObsoleteCoroutinesApi' or '@UseExperimental(kotlinx.coroutines.ObsoleteCoroutinesApi::class)'

In regards to the pre-push hook, you can find it here: https://github.com/mozilla-mobile/fenix/wiki/Recommended-pre-push-hook

`app:testGeckoBetaDebug` is the line that runs these tests locally.

**Comment by shldhll** [comment]
@sblatz I don't know why my pre-push was different from the link you shared but its all working now. BUILD SUCCESSFUL with the new pre-push.

**Comment by shldhll** [comment]
@sblatz Is there anything I need to do on my end?

**Comment by sblatz** [comment]
bors retry

**Comment by sblatz** [comment]
@shldhll I don't believe so. I think bors just failed to merge. I'm trying to re-run it now 😄

**Pull request merged**
