### PR TITLE
For #22516 - Fixed alignment of "Show all" buttons on the homescreen

### PR DESCRIPTION
**Pull request by MozillaNoah**
#22516 

This was mainly an issue of trying to align two pieces of text that have different font weight and size. I ultimately decided to turn the "Show All" elements into TextViews to remove any baked-in padding from the Button object, since this was the only possible solution to closely align the bottom line of two differently-styled TextViews (at least in XML). The side effect of this was the tappable area of the "Show all" buttons did decrease slightly, so this should only be a short term solution until these sections are rewritten into Compose. 

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

Screenshot_1638380951

### CODE REVIEW

**Comment by MozillaNoah** [comment]
CC: @topotropic

**Review by gabrielluong — APPROVED** [review]

**Comment by gabrielluong** [comment]
You might want to consider a rebase approach for your workflow, and amending/squashing commits (looking at the content description commit). I am mostly looking at the `Merge branch 'main' into homepage-section-header-polish` commits and wondering what happens if we didn't squash the PRs when we land. 

Also, we probably should update the title of the PR since squash landing takes the title of the PR inside of using the commit messages. Probably another reason to amend/squash commits is so we don't end up with messy commit description which would include that content description fix.

**Comment by gabrielluong** [comment]
> You might want to consider a rebase approach for your workflow, and amending/squashing commits (looking at the content description commit). I am mostly looking at the `Merge branch 'main' into homepage-section-header-polish` commits and wondering what happens if we didn't squash the PRs when we land. I imagine we don't want "Merge" commits landing in the tree.
> 
> Also, we probably should update the title of the PR to include the issue number and align it with your commit message since squash landing takes the title of the PR inside of using the commit messages. Probably another reason to amend/squash commits is so we don't end up with messy commit description which would include that content description fix.

Just adding a do-not-land until my last comment was seen.

**Comment by MozillaNoah** [comment]
> > You might want to consider a rebase approach for your workflow, and amending/squashing commits (looking at the content description commit). I am mostly looking at the `Merge branch 'main' into homepage-section-header-polish` commits and wondering what happens if we didn't squash the PRs when we land. I imagine we don't want "Merge" commits landing in the tree.
> > Also, we probably should update the title of the PR to include the issue number and align it with your commit message since squash landing takes the title of the PR inside of using the commit messages. Probably another reason to amend/squash commits is so we don't end up with messy commit description which would include that content description fix.
> 
> Just adding a do-not-land until my last comment was seen. Oh, we also don't necessarily have to add "Feature" labels in the PRs since that is more for the Issues.

Oh gotcha, that's good to know

**Comment by MozillaNoah** [comment]
> You might want to consider a rebase approach for your workflow, and amending/squashing commits (looking at the content description commit). I am mostly looking at the `Merge branch 'main' into homepage-section-header-polish` commits and wondering what happens if we didn't squash the PRs when we land. I imagine we don't want "Merge" commits landing in the tree.
> 
> Also, we probably should update the title of the PR to include the issue number and align it with your commit message since squash landing takes the title of the PR inside of using the commit messages. Probably another reason to amend/squash commits is so we don't end up with messy commit description which would include that content description fix.

Yeah, totally. This makes sense. I admittedly use the Github desktop client to manage everything since my terminal skills are very very rusty, so I'll poke around that first and reach out for a git refresher.

**Comment by MozillaNoah** [comment]
As an update, I looked into the commit history, and it looks like the squash does in fact omit the "merge from main" commits. Either way, I'll try to keep my commit feeds a bit tidier in the future.
Screen Shot 2021-12-01 at 2 05 10 PM

**Comment by gabrielluong** [comment]
> As an update, I looked into the commit history, and it looks like the landing squash does in fact omit the "merge from main" commits. Either way, I'll try to keep my commit feeds a bit tidier in the future. Screen Shot 2021-12-01 at 2 05 10 PM

Cool, I am removing the do-not-land since I think it's good enough that we have a reference to the issue number in our title now, which will be used when we do a squash land through mergify. I think you can see in the screenshot that the PR title (which does not reference the issue number) was used by mergify when you landed the MR2 telemetry.

I will point that the squashed commits do end up listed in the commit description, which can end up being quite messy if w e were looking at the git blame through Android Studio and the dialog takes up the whole window. So, it does pay off to amend or squash your commits manually before hand. Alternatively, I will also advocate for landing smaller commits with a good reasonable commit message that focuses on a particular change (such as renaming, refactor, formatting). Sometimes, you see a PR with a lot of refactoring, renaming plus the actual feature implementation, which makes it harder to review altogether because the changes does add up. It's also not as nice squashed together if we chose to do a squash landing since you will sometimes find yourself looking at older commits to see how a thing was implement and seeing all the refactoring vs seeing how the thing was actually implemented adds to the noise. All in all, I am basically trying to say that having many small commits that are not squashed is a good practise, but that requires some planning as you code and commit changes.

**Comment by topotropic** [comment]
Looking good! Thanks!

**Pull request merged**
