### PR TITLE
Update A-S to 0.30.

### PR DESCRIPTION
**Pull request by st3fan**
This patch updates A-S to 0.30. It is a draft until we get a sign off from @eoger

### CODE REVIEW

**Comment by jonalmeida** [comment]
Also depends on https://github.com/mozilla-mobile/android-components/pull/3196 merging first.

**Comment by jonalmeida** [comment]
Looks like CI is pulling in old resources here; build caches need to be refreshed.

**Comment by grigoryk** [comment]
@st3fan the version of a-s specified in Fenix is only used for `-forUnitTests` variants of the libraries; we only have it for the sake of tests. The actual "version bump" happens in a-c.

**Comment by vladikoff** [comment]
Thanks @pocmo !

**Comment by st3fan** [comment]
Apologies, I landed the A-C one yesterday assuming this was one was green and ready to merge too.

**Pull request merged**
