### PR TITLE
For #4333: Open the keyboard when a search engine is selected

### PR DESCRIPTION
**Pull request by miDeb**
### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by gabrielluong** [comment]
bors try

**Comment by gabrielluong** [comment]
@eliserichards if the code looks good to you, we should also get @brampitoyo to do a ux review

**Comment by gabrielluong** [comment]
@miDeb it could be helpful for @brampitoyo if you can post a screenshot or gif of the changes. Thanks!

**Comment by brampitoyo** [comment]
@gabrielluong Thanks for pinging me!

@miDeb as soon as you post a GIF and add me as a reviewer to this issue, I’d be able to ask more questions or approve the design.

Alternatively, I’m also open to testing on a TestFlight build (only if it’s not too tricky – GIF may be easier).

**Comment by miDeb** [comment]
Here's a screen recording: https://streamable.com/u4lhrz. Note that you have to scroll down on the list of search engines to make the keyboard hide in the first place (which doesn't make sense in this case, but usually the list is longer).

**Comment by miDeb** [comment]
@brampitoyo fwiw, you commented here https://github.com/mozilla-mobile/fenix/issues/4333#issuecomment-691847620 that this should be ok

**Comment by brampitoyo** [comment]
@miDeb Yep. I did write on https://github.com/mozilla-mobile/fenix/issues/4333#issuecomment-691847620 that the behaviours are ok. The GIF is useful so that we – mostly I – don’t miss any other edge case. Thanks!

**Review by brampitoyo — APPROVED** [review]
r+

**Review by eliserichards — APPROVED** [review]
Sorry for the delay reviewing this! It's looking good to me. I just updated the branch and fixed one conflict, so once the CI finishes running we can get this merged! 🚀

**Pull request merged**
