### PR TITLE
closes #7207 : changed darktheme accent color to AB71FF

### LINKED ISSUE #7207: [Settings] About Firefox - Link colour is wrong in dark theme
1. Set Fenix to Dark theme (Settings -> Theme)
2. Go to Settings -> About Firefox

Expected:
Links are visible and passes contrast test - Text link colour should be Violet 40 #AB71FF

Actual: 
Links are too dark to see and fail contrast test

Screenshot_20191216-113940

### PR DESCRIPTION
**Pull request by KaairaGupta**
darklink
made the required changes and ran all tests

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by KaairaGupta** [comment]
updated `accent_bright_private_theme` to #ADADFF which passes the tests. @sblatz please review
private

**Comment by sblatz** [comment]
@AmyYLee Can you please verify you want this color to also be used for the shortcuts button? These are currently the same highlight and when we change the about page, it changes the shortcuts buttons: 

image

**Comment by tvenissat** [comment]
@sblatz please see my comment [here](https://github.com/mozilla-mobile/fenix/issues/7207#issuecomment-572257800). Changing these values affects much more than what the issue was opened for and breaks a couple of things. Also, @KaairaGupta was not assigned the issue this pull request is for.

**Comment by AmyYLee** [comment]
> @AmyYLee Can you please verify you want this color to also be used for the shortcuts button? These are currently the same highlight and when we change the about page, it changes the shortcuts buttons:
> 
> image

Hi, 

No we don't want this to change the button colour here. There's not enough contrast between the text and the button background. I think moving forward a text link (no button) should be assigned a colour value that is separate from button colours.

**Comment by brampitoyo** [comment]
Hi @sblatz, according to @AmyYLee on https://github.com/mozilla-mobile/fenix/issues/7313#issuecomment-569958225, the foundation colour for Private Theme is `ink-90` `#1D1133`:

Screen Shot 2019-12-31 at 11 53 10 AM

Assuming the page foundation colour has been darkened as above, the accent colour `violet-40` `#AB71FF` will pass AA:

Screenshot_2020-02-05 WebAIM Contrast Checker

And if we want to pass AAA, we can use a lighter shade: `violet-30` `#C689FF`

Screenshot_2020-02-05 WebAIM Contrast Checker

**Comment by darkwing** [comment]
Superceded by https://github.com/mozilla-mobile/fenix/pull/8237

**Pull request closed without merging**
