### PR TITLE
For #6521 - Remove auto sigin onboarding card

### PR DESCRIPTION
**Pull request by Mugurell**
With the Fennec -> Fenix migration complete there is no other Mozilla
application that would serve as a custom account provider hence the automatic
signin would not be possible.
Make this more obvious by commenting out the code that would trigger an
onboarding banner for it but keep the code in the app for when #15694 would add
to Fenix the ability to serve as a custom account provider.

### Pull Request checklist

- [x] **Tests**: No tests. Small change.
- [x] **Screenshots**: No UI difference versus recent builds.
- [x] **Accessibility**: The code in this PR does not include any a11y user facing features.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by codrut-topliceanu — APPROVED** [review]
LGTM! 👍

**Comment by Mugurell** [comment]
`[taskcluster:error] Error: Error calling 'stopped' for artifactHandler : Error: Encountered error when uploading artifact(s)`
Restarting CI tasks

**Comment by Mugurell** [comment]
[taskcluster:error] Task timeout 
Restarting CI tasks

**Comment by Mugurell** [comment]
[taskcluster:error] Task timeout
Restarting CI tasks

**Pull request merged**
