### PR TITLE
For #13922: Add indicator to synced tabs suggestions in awesomebar

### PR DESCRIPTION
**Pull request by hakkikaancaliskan**
Depends on: ~~#11258~~, ~~https://github.com/mozilla-mobile/android-components/pull/8157~~

image
### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by jonalmeida** [comment]
@hakkikaancaliskan will you be updating this PR, based on the AC changes? 🙂

**Comment by hakkikaancaliskan** [comment]
> 
> 
> @hakkikaancaliskan will you be updating this PR, based on the AC changes? 🙂

yep i'll but this pr based on #11258. So first it needs to be merged.

**Comment by jonalmeida** [comment]
@hakkikaancaliskan you might have to fix the conflict in your PR one more time now that we've landed your other PR.

**Comment by hakkikaancaliskan** [comment]
@jonalmeida done :)

**Review by ekager — APPROVED** [review]

**Comment by jonalmeida** [comment]
@hakkikaancaliskan you might have to do that again. It looks like your changes in Android Components hadn't made it to the nightly release, so the CI build failed to find the references.

Thanks for approving Emily!

**Comment by hakkikaancaliskan** [comment]
rebased 👍

**Pull request merged**
