### PR TITLE
For #24075: Add download PDF metrics.

### PR DESCRIPTION
**Pull request by mcarare**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by mcarare** [comment]
# Request for data collection review form

**All questions are mandatory. You must receive a review from a data steward peer on your responses to these questions before shipping new data collection.**

_1) What questions will you answer with this data?_
This will help analyse the need for additional support for PDF files.

_2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?_
This is needed to analyze feature usage and possible feature improvements.

_3) What alternative methods did you consider to answer these questions? Why were they not sufficient?_
This is the only way.

_4) Can current instrumentation answer these questions?_
No. We need a new specific event for a specific app feature.

_5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Firefox/Data_Collection) found on the Mozilla wiki._

_**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**_

<table>
  <tr>
    <td>Measurement Description</td>
    <td>Data Collection Category</td>
    <td>Tracking Bug #</td>
  </tr>

  <tr>
    <td> A PDF file has been downloaded</td>
    <td>Category 2</td>
    <td>https://github.com/mozilla-mobile/fenix/issues/24075 </td>
    </tr>

  <tr>
    <td> Dialog Open button has been clicked for a downloaded PDF file. </td>
    <td>Category 2</td>
    <td>https://github.com/mozilla-mobile/fenix/issues/24075 </td>
    </tr>

</table>

_6) How long will this data be collected?  Choose one of the following:_
Up until version 107, with the option to renew at that point. 

_7) What populations will you measure?_
All release channels and locales.

_8) If this data collection is default on, what is the opt-out mechanism for users?_
 Default Glean SDK opt-out mechanism. : Users can opt out of data collection by disabling "Usage and technical data" from Settings -> Data collection.

_9) Please provide a general description of how you will analyze this data._
 Glean 

_10) Where do you intend to share the results of your analysis?_
Only on Glean, mobile teams, and BD have internal access.

_12) Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?_
No.

**Review by Amejia481 — APPROVED** [review]
LGTM!
@rocketsroger now sure if you would like to take a quick look!

**Comment by rocketsroger** [comment]
> # Request for data collection review form
> 
> **All questions are mandatory. You must receive a review from a data steward peer on your responses to these questions before shipping new data collection.**
> 
> _1) What questions will you answer with this data?_ This will help analyse the need for additional support for PDF files.
> 
> _2) Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?_ This is needed to analyze feature usage and possible feature improvements.
> 
> _3) What alternative methods did you consider to answer these questions? Why were they not sufficient?_ This is the only way.
> 
> _4) Can current instrumentation answer these questions?_ No. We need a new specific event for a specific app feature.
> 
> _5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Firefox/Data_Collection) found on the Mozilla wiki._
> 
> _**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**_
> Measurement Description 	Data Collection Category 	Tracking Bug #
> A PDF file has been downloaded 	Category 2 	https://github.com/[/issues/24075](https://github.com/mozilla-mobile/fenix/issues/24075)
> Dialog Open button has been clicked for a downloaded PDF file. 	Category 2 	https://github.com/[/issues/24075](https://github.com/mozilla-mobile/fenix/issues/24075)
> 
> _6) How long will this data be collected? Choose one of the following:_ Up until version 107, with the option to renew at that point. 
> 
> _7) What populations will you measure?_ All release channels and locales.
> 
> _8) If this data collection is default on, what is the opt-out mechanism for users?_ Default Glean SDK opt-out mechanism. : Users can opt out of data collection by disabling "Usage and technical data" from Settings -> Data collection.
> 
> _9) Please provide a general description of how you will analyze this data._ Glean
> 
> _10) Where do you intend to share the results of your analysis?_ Only on Glean, mobile teams, and BD have internal access.
> 
> _12) Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?_ No.

# Data Review

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way? 

Yes, through the metrics.yaml file and the [Glean Dictionary](https://dictionary.telemetry.mozilla.org/apps/fenix )

2) Is there a control mechanism that allows the user to turn the data collection on and off? 

Yes, through the "Send Usage Data" preference in the application settings

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

N/A, collection set to end or be renewed by version 107

4) Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Category 2, Interaction data

5) Is the data collection request for default-on or default-off?

default-on

6) Does the instrumentation include the addition of **any *new* identifiers**?

No

7) Is the data collection covered by the existing Firefox privacy notice? 

Yes

8) Does the data collection use a third-party collection tool? 

No

## Result

data-review+

**Review by rocketsroger — COMMENTED** [review]
One question I have is are we expecting this to be removed in about 6 months?  If not and we expect that this will be extended, I would go for version 112-114 (for a year)  This saves us from having to renew it so soon.

**Comment by mcarare** [comment]
@rocketsroger The expiry date mentioned in Jira is 6 months.

**Comment by rocketsroger** [comment]
> @rocketsroger The expiry date mentioned in Jira is 6 months.

Missed that.  Thanks.  🚢

**Pull request merged**
