### PR TITLE
For #13030 - Use material design animation values for swipe to switch…

### PR DESCRIPTION
**Pull request by person808**
… tabs.

Hopefully this feels a little more natural compared to the physics-based animations (with values I made up).
Values taken from https://material.io/design/motion/speed.html

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by person808** [comment]
@brampitoyo @Mugurell https://streamable.com/mu9a6g

Scenarios shown are:
1. Overscroll and release when there's no tab to swipe to.
2. Fling to next tab.
3. Slow scroll and release to switch to next tab.
4. Slow scroll and fling in opposite direction to stay on the same tab.

**Comment by person808** [comment]
As for values, I'm using 250ms when we animate to a new tab and 200ms when staying on the same tab (a "canceled" gesture). These are the values recommended for medium sized animations. I chose medium because thats what Discord uses for their gestures which do similar things (they animate the whole screen to show a new panel).

**Comment by brampitoyo** [comment]
@Mugurell Thanks for tagging me. I agree @person808, this looks and feels good!

I have one question around point 4:

> 4. Slow scroll and fling in opposite direction to stay on the same tab.

Compare these two animations:

- 0:18-0:20 – fling back from tab 2 (right) to tab 1 (left)
- 0:23-0:25 - fling back from tab 1 to tab 2

The first animation seems to be faster and ‘snappier’ than the second. Is this because of how you release the hold gesture?

Paging @topotropic just as an FYI.

**Comment by person808** [comment]
> The first animation seems to be faster and ‘snappier’ than the second. Is this because of how you release the hold gesture?

I think it is because of where I release the hold gesture. Since the animation uses a fixed duration now, the first animation is faster because it has to animate a farther distance in the same amount of time. Maybe if we animate without switching tabs it might make sense to use an even shorter animation duration (like 150ms?). I did notice in my testing that flinging to "cancel" the gesture was the weirdest feeling one because you are likely to lift your finger closer to the edge we are animating towards, resulting in a shorter distance to animate.

**Comment by brampitoyo** [comment]
@person808 wrote:

> Since the animation uses a fixed duration now, the first animation is faster because it has to animate a farther distance in the same amount of time.

Understood. Thanks heaps for the explanation! This makes sense to me.

> Maybe if we animate without switching tabs it might make sense to use an even shorter animation duration (like 150ms?).

Yes. Flinging is generally done in one go. People tend to swipe fast, not slowly or studiously. So if this fling is cancelled (ie. animating without switching tabs), we might want to shorten the duration.

if a 150ms value is easy enough to change, would you be willing to give it a quick test and report back as to how it feels?

**Comment by person808** [comment]
@brampitoyo I tried out a couple of values. Both are an improvement in my opinion.

150ms - https://streamable.com/y1oooy

100ms - https://streamable.com/1xprl0

**Comment by brampitoyo** [comment]
@person808 I thought that the 100ms value felt snappier – but it was also very snappy, at times it felt jarring.

What do you think about using the 150ms value as a compromise?

Great work on this. Whatever your decision end up being, it gets an r+ from me. Thanks heaps!

**Comment by person808** [comment]
Update with 150ms value for flinging to cancel gesture.

**Pull request merged**
