### PR TITLE
For #1998 - Removes stable flag in entering fullscreen navigation

### PR DESCRIPTION
**Pull request by ekager**
### Pull Request checklist

- [X] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by jonalmeida** [comment]
Can we add these changes to a-c instead/as well? 🙂

**Comment by ekager** [comment]
I was going to but then I tested it in Sample Browser and it broke the toolbar there :/ and I didn't take the time to figure out why

**Comment by ekager** [comment]
I'm also not positive that this will fix the problem in #1998 because I don't have a physical button device to test on, but lets test it and if it does, I will follow up in AC

**Comment by ekager** [comment]
@jonalmeida it seems it did fix the users issue, so I will follow up with an AC change next week.

**Pull request merged**
