### PR TITLE
Bug 1681991 - Do not run ui-tests against debug builds on release branches

### PR DESCRIPTION
**Pull request by JohanLorenzo**

### CODE REVIEW

**Comment by rocketsroger** [comment]
Looks like tests was stuck

**Comment by JohanLorenzo** [comment]
This was tested with `try_task_config.json`

 ```

{
    "parameters": {
        "optimize_target_tasks": true,
        "head_ref": "releases_v85.0.0",
        "tasks_for": "github-push"
    },
    "version": 2
}
```

didn't generate a master-only task called `ui-test-x86-debug`: https://firefox-ci-tc.services.mozilla.com/tasks/groups/eWR65ZbwQb6DYCJ-EnJsZg

```
{
    "parameters": {
        "optimize_target_tasks": true,
        "head_ref": "master",
        "tasks_for": "github-push"
    },
    "version": 2
}
```

did, though: https://firefox-ci-tc.services.mozilla.com/tasks/groups/Olxsbpe2S_OjUHGGTk1bsw.

The build tasks are red because they try to fetch a non-existing revision off these forced branches. It's an expected behavior.

**Comment by isabelrios** [comment]
> didn't generate a master-only task called ui-test-x86-debug: https://firefox-ci-tc.services.mozilla.com/tasks/groups/eWR65ZbwQb6DYCJ-EnJsZg

@JohanLorenzo just to double check, and the ui-test-x86-beta will not appear until we land my PR with the changes in [here](https://github.com/mozilla-mobile/fenix/pull/16786/files#diff-295d2d74a1f1b6f29648f61ada339694108a54debf06e6e406b746697dd0ae6bR67)

**Comment by JohanLorenzo** [comment]
That's right! I can help you test #16786 to make sure `ui-test-x86-beta` gets included.

**Review by isabelrios — APPROVED** [review]
LGTM! as long as all the tasks finish ✅

**Comment by isabelrios** [comment]
> That's right! I can help you test #16786 to make sure `ui-test-x86-beta` gets included.

That would be great! Thanks for these changes to make that possible!

**Pull request merged**
