### PR TITLE
For #2271 - Fix hairline color on dark theme and private mode

### PR DESCRIPTION
**Pull request by darkwing**
@AmyYLee 

Screenshot_20200227-232848
Screenshot_20200227-232819

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by boek** [comment]
Waiting on @AmyYLee to sign off

**Comment by darkwing** [comment]
@AmyYLee Screenshot with updated hairline:

Screenshot_20200302-110420

**Comment by AmyYLee** [comment]
@darkwing Hi, I've posted the hex for the hairline colours without opacity. Also the background colours for the search bar without opacity.

Screen Shot 2020-03-02 at 3 30 07 PM

**Comment by darkwing** [comment]
OK, updated screenshots with new colors:

Screenshot_20200302-144525
Screenshot_20200302-144342
Screenshot_20200302-144122

**Comment by darkwing** [comment]
Another update with new background colors:

Screenshot_20200302-152551
Screenshot_20200302-152518
Screenshot_20200302-152432

**Comment by AmyYLee** [comment]
@darkwing The above screenshots look good. Thanks!

**Pull request merged**
