### PR TITLE
Update Android Components version

### PR DESCRIPTION
**Pull request by MickeyMoz**

### CODE REVIEW

**Comment by liuche** [comment]
```
 /builds/worker/checkouts/src/app/src/main/java/org/mozilla/fenix/utils/Settings.kt: (755, 16): None of the following functions can be called with the arguments supplied: 
[task 2020-10-08T15:52:51.641Z] internal constructor SitePermissionsRules(camera: SitePermissionsRules.Action, location: SitePermissionsRules.Action, notification: SitePermissionsRules.Action, microphone: SitePermissionsRules.Action, autoplayAudible: SitePermissionsRules.Action, autoplayInaudible: SitePermissionsRules.Action, persistentStorage: SitePermissionsRules.Action) defined in mozilla.components.feature.sitepermissions.SitePermissionsRules
[task 2020-10-08T15:52:51.641Z] public constructor SitePermissionsRules(camera: SitePermissionsRules.Action, location: SitePermissionsRules.Action, notification: SitePermissionsRules.Action, microphone: SitePermissionsRules.Action, autoplayAudible: SitePermissionsRules.AutoplayAction, autoplayInaudible: SitePermissionsRules.AutoplayAction, persistentStorage: SitePermissionsRules.Action) defined in mozilla.components.feature.sitepermissions.SitePermissionsRules
[task 2020-10-08T15:52:51.641Z] 
[task 2020-10-08T15:52:51.641Z] > Task :app:compileBetaKotlin FAILED
[task 2020-10-08T15:52:51.841Z] 
[task 2020-10-08T15:52:51.841Z] FAILURE: Build failed with an exception.
[task 2020-10-08T15:52:51.841Z] 
```

**Comment by jonalmeida** [comment]
Requires https://github.com/mozilla-mobile/fenix/pull/15704 to be cherry-picked.

**Comment by jonalmeida** [comment]
Toolchain task seems to have failed at an intermittent exception when getting dependencies (network?).
```
[task 2020-10-08T17:42:24.780Z] > Task :app:build_condas
[task 2020-10-08T17:42:24.780Z] > Task :app:build_conda_envs SKIPPED
[task 2020-10-08T17:42:24.780Z] > Task :app:build_pythons SKIPPED
[task 2020-10-08T17:42:24.780Z] > Task :app:build_pythons_from_zip SKIPPED
[task 2020-10-08T17:42:24.780Z] > Task :app:build_virtual_envs SKIPPED
[task 2020-10-08T17:42:24.780Z] > Task :app:build_envs
[task 2020-10-08T17:42:27.380Z] > Task :app:getDependencies
[task 2020-10-08T17:42:27.380Z] 
[task 2020-10-08T17:42:27.380Z] FAILURE: Build failed with an exception.
[task 2020-10-08T17:42:27.380Z] 
```

**Comment by jonalmeida** [comment]
The real failure was a linting issue above and I missed it:

```
[task 2020-10-08T17:58:52.250Z] > Task :ktlint FAILED
[task 2020-10-08T17:58:52.250Z] /builds/worker/checkouts/src/app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsDetailsExceptionsFragment.kt:24:1: Wildcard import (cannot be auto-corrected)
[task 2020-10-08T17:58:53.750Z] 
```

**Review by Amejia481 — APPROVED** [review]

**Comment by jonalmeida** [comment]
Fixed a test build failure, but I didn't add a new test for it right now to get the build to pass cc: @Amejia481 :

```
[task 2020-10-08T18:51:32.957Z] > Task :app:compileDebugUnitTestKotlin FAILED
[task 2020-10-08T18:51:32.957Z] e: /builds/worker/checkouts/src/app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt: (28, 38): None of the following functions can be called with the arguments supplied: 
[task 2020-10-08T18:51:32.957Z] internal constructor SitePermissionsRules(camera: SitePermissionsRules.Action, location: SitePermissionsRules.Action, notification: SitePermissionsRules.Action, microphone: SitePermissionsRules.Action, autoplayAudible: SitePermissionsRules.Action, autoplayInaudible: SitePermissionsRules.Action, persistentStorage: SitePermissionsRules.Action) defined in mozilla.components.feature.sitepermissions.SitePermissionsRules
[task 2020-10-08T18:51:32.957Z] public constructor SitePermissionsRules(camera: SitePermissionsRules.Action, location: SitePermissionsRules.Action, notification: SitePermissionsRules.Action, microphone: SitePermissionsRules.Action, autoplayAudible: SitePermissionsRules.AutoplayAction, autoplayInaudible: SitePermissionsRules.AutoplayAction, persistentStorage: SitePermissionsRules.Action) defined in mozilla.components.feature.sitepermissions.SitePermissionsRules
[task 2020-10-08T18:51:33.057Z] 
```

**Comment by Amejia481** [comment]
> Fixed a test build failure, but I didn't add a new test for it right now to get the build to pass cc: @Amejia481 :
> 
> ```
> [task 2020-10-08T18:51:32.957Z] > Task :app:compileDebugUnitTestKotlin FAILED
> [task 2020-10-08T18:51:32.957Z] e: /builds/worker/checkouts/src/app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt: (28, 38): None of the following functions can be called with the arguments supplied: 
> [task 2020-10-08T18:51:32.957Z] internal constructor SitePermissionsRules(camera: SitePermissionsRules.Action, location: SitePermissionsRules.Action, notification: SitePermissionsRules.Action, microphone: SitePermissionsRules.Action, autoplayAudible: SitePermissionsRules.Action, autoplayInaudible: SitePermissionsRules.Action, persistentStorage: SitePermissionsRules.Action) defined in mozilla.components.feature.sitepermissions.SitePermissionsRules
> [task 2020-10-08T18:51:32.957Z] public constructor SitePermissionsRules(camera: SitePermissionsRules.Action, location: SitePermissionsRules.Action, notification: SitePermissionsRules.Action, microphone: SitePermissionsRules.Action, autoplayAudible: SitePermissionsRules.AutoplayAction, autoplayInaudible: SitePermissionsRules.AutoplayAction, persistentStorage: SitePermissionsRules.Action) defined in mozilla.components.feature.sitepermissions.SitePermissionsRules
> [task 2020-10-08T18:51:33.057Z] 
> ```

Thanks!

**Comment by Amejia481** [comment]
I'm taking care of the failing tests
image

**Comment by Amejia481** [comment]
🤞

**Comment by Amejia481** [comment]
UI tests 🤦

**Comment by Amejia481** [comment]
🎲

**Comment by liuche** [comment]
@Amejia481 I can also keep an eye on this - I'll merge it if it goes green, or if not, you can fix things tomorrow. No need to hang around!

**Comment by Amejia481** [comment]
Thanks @liuche :)
Hope this time passes ✅ 🤞

**Comment by jonalmeida** [comment]
🎉 🎉 🎉

**Pull request merged**
