### PR TITLE
For #23426:Changed expiring perf probes to never expire

### PR DESCRIPTION
**Pull request by MarcLeclair**
1. **Provide a link to the initial Data Collection Review Request for this collection:** 

[start_reason_activity_error](https://github.com/mozilla-mobile/fenix/pull/18632#issue-600193452)
[start_reason_process_error](https://github.com/mozilla-mobile/fenix/pull/20623#issue-701630599) 
[application_on_create](https://github.com/mozilla-mobile/fenix/pull/17973#issue-572183889)
[cold_main_app_to_first_frame ](https://github.com/mozilla-mobile/fenix/pull/18632#issue-600193452)
[cold_unknwn_app_to_first_frame](https://github.com/mozilla-mobile/fenix/pull/18632#issue-600193452)
[cold_view_app_to_first_frame](https://github.com/mozilla-mobile/fenix/pull/18632#issue-600193452)
[app_bytes](https://github.com/mozilla-mobile/fenix/pull/12876#issuecomment-666770732)
[cache_bytes](https://github.com/mozilla-mobile/fenix/pull/12876#issuecomment-666770732)
[data_dir_bytes](https://github.com/mozilla-mobile/fenix/pull/12876#issuecomment-666770732)
[query_stats_duration](https://github.com/mozilla-mobile/fenix/pull/12876#issuecomment-666770732)

2. **When will this collection now expire?**  

Never

3. **Why was the initial period of collection insufficient?** 

Since we're trying to continuously improve and track performance of fenix, having an expiry date for these probes doesn't make much sense. 

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by rocketsroger** [comment]
> 1. **Provide a link to the initial Data Collection Review Request for this collection:**
> 
> 
> [start_reason_activity_error](https://github.com/mozilla-mobile/fenix/pull/18632#issue-600193452) [start_reason_process_error](https://github.com/mozilla-mobile/fenix/pull/20623#issue-701630599) [application_on_create](https://github.com/mozilla-mobile/fenix/pull/17973#issue-572183889) [cold_main_app_to_first_frame ](https://github.com/mozilla-mobile/fenix/pull/18632#issue-600193452) [cold_unknwn_app_to_first_frame](https://github.com/mozilla-mobile/fenix/pull/18632#issue-600193452) [cold_view_app_to_first_frame](https://github.com/mozilla-mobile/fenix/pull/18632#issue-600193452) [app_bytes](https://github.com/mozilla-mobile/fenix/pull/12876#issuecomment-666770732) [cache_bytes](https://github.com/mozilla-mobile/fenix/pull/12876#issuecomment-666770732) [data_dir_bytes](https://github.com/mozilla-mobile/fenix/pull/12876#issuecomment-666770732) [query_stats_duration](https://github.com/mozilla-mobile/fenix/pull/12876#issuecomment-666770732)
> 
>     2. **When will this collection now expire?**
> 
> 
> Never
> 
>     3. **Why was the initial period of collection insufficient?**
> 
> 
> Since we're trying to continuously improve and track performance of fenix, having an expiry date for these probes doesn't make much sense.

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

**Review by rocketsroger — APPROVED** [review]
Looks good!

**Comment by eliserichards** [comment]
We'll backport this to v96 and v97 once it's merged 👍

**Comment by eliserichards** [comment]
@Mergifyio backport releases_v97.0.0

**Comment by eliserichards** [comment]
Uplift for 97: https://github.com/mozilla-mobile/fenix/pull/23515

**Pull request merged**
