### PR TITLE
Update Android Components version

### PR DESCRIPTION
**Pull request by MickeyMoz**
⚠️ Let's not land this, as we are checking for a possible issue introduced on this  AC version, see https://github.com/mozilla-mobile/fenix/pull/20427#discussion_r672639752 for more details.

### CODE REVIEW

**Comment by eliserichards** [comment]
This is failing one of the UI tests: `closePrivateTabsNotificationTest`. I confirmed it is failing locally. I'll open a new PR with this update and let the testing team know about the failure

**Comment by jonalmeida** [comment]
There are now build errors from API changes that need to be addressed:
```
[task 2021-07-20T16:06:15.370Z] > Task :app:compileDebugUnitTestKotlin
[task 2021-07-20T16:06:15.370Z] WARNING: [Processor] Library '/builds/worker/fetches/android-gradle-dependencies/central/org/robolectric/shadows-framework/4.3.1/shadows-framework-4.3.1.jar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
[task 2021-07-20T16:06:15.370Z]  Example of androidX reference: 'androidx/test/runner/lifecycle/Stage'
[task 2021-07-20T16:06:15.370Z]  Example of support library reference: 'android/support/annotation/NonNull'
[task 2021-07-20T16:06:43.470Z] e: /builds/worker/checkouts/src/app/src/test/java/org/mozilla/fenix/tabstray/CloseOnLastTabBindingTest.kt: (109, 45): Classifier 'RemoveAllTabsAction' does not have a companion object, and thus must be initialized here
[task 2021-07-20T16:06:43.470Z] e: /builds/worker/checkouts/src/app/src/test/java/org/mozilla/fenix/telemetry/TelemetryMiddlewareTest.kt: (138, 38): Classifier 'RemoveAllTabsAction' does not have a companion object, and thus must be initialized here
```

**Comment by pocmo** [comment]
@jonalmeida I can look at the API changes (from my A-C commit)... but what is this other thing about?

**Comment by pocmo** [comment]
Unused strings have been removed in A-C. But some of them seem to be used in Fenix. Re-adding them to A-C here:
https://github.com/mozilla-mobile/android-components/pull/10648

**Comment by Amejia481** [comment]
The breaking changes are addressed here https://github.com/mozilla-mobile/fenix/pull/20399, I already updated the AC version there.

**Comment by Amejia481** [comment]
> Unused strings have been removed in A-C. But some of them seem to be used in Fenix. Re-adding them to A-C here:
> [mozilla-mobile/android-components#10648](https://github.com/mozilla-mobile/android-components/pull/10648)

I will wait for the new AC version that contains the new strings for updating #20399 with it.

**Pull request closed without merging**
