### PR TITLE
Issue #16780: Enable Firefox to handle intent category CATEGORY_APP_BROWSER 

### LINKED ISSUE #16780: [Bug] Firefox doesn't response from intent category CATEGORY_APP_BROWSER
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
In certain situations, developers need to send an intent to be opened in browsers only instead of using `ACTION_VIEW`. This is done by using `CATEGORY_APP_BROWSER` [(API Doc)](https://developer.android.com/reference/android/content/Intent#CATEGORY_APP_BROWSER) with `makeMainSelectorActivity ` [(API Doc)](https://developer.android.com/reference/android/content/Intent#makeMainSelectorActivity(java.lang.String,%20java.lang.String)) 

**Currently, Chrome, Opera, Edge, and Brave handle this category.**

This can be reproduced using the code blow:
``` kotlin
fun startBrowserIntent(uri: Uri) {
        val intent = Intent.makeMainSelectorActivity(Intent.ACTION_MAIN, Intent.CATEGORY_APP_BROWSER)
        intent.data = uri

        startActivity(intent)
}
```
### Expected behavior
After sending the intent, we should expect firefox to be in the list of Browser that handles `CATEGORY_APP_BROWSER`, but it does not. 
test
test

### Actual behavior
Screen Shot 2020-11-30 at 1 54 40 AM
### Device information

* Android device: Pixel 2 XL
* Fenix version: Firefox version 83.1.0

### PR DESCRIPTION
**Pull request by ilPikachu**
### Context:
In certain situations, developers need to force their intent to be opened in the browsers, instead of using `ACTION_VIEW`. This is done by using `CATEGORY_APP_BROWSER` with `makeMainSelectorActivity`.

**Currently, Chrome, Opera, Edge, and Brave handle this category.**

This can be reproduced using the code blow:
```kotlin
fun startBrowserIntent(uri: Uri) {
        val intent = Intent.makeMainSelectorActivity(Intent.ACTION_MAIN, Intent.CATEGORY_APP_BROWSER)
        intent.data = uri

        startActivity(intent)
}
```
More details and screenshots:  #16780

### PR Explanation:
Add AppBrowserIntentProcessor to handle category APP_BROWSER in the HomeActivity. Supports normal and private tabs.

AppBrowserIntentProcessor coverts the intent action to `ACTION_VIEW` then utlizes `TabIntentProcessor` for processing.

`CloneFilter` was used when converting to ViewIntent because we don't want to change the original intent as it will be used for analytics tracking.

Although do we want to track this type of intent to be ` Event.AppReceivedIntent.Source.LINK`? I see we're only tracking `Intent.ACTION_VIEW` as `Link`.

Closes #16780

### Testing:
1. Sent an intent from an external app using the code above or use the adb.
2. Verify firefox preview is on the list of browsers.
3. Open the link verify is loading properly. 
4. Toggle `Open links in a private tab` ON in the `Private browsing` settings. Retry from step 1 to step 3, verify the link is opened in private mode.

### Screenshots and gifs:
test
normal tab:
test
private tab:
test

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests.
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made and an explanation of what it does.
- [x] **Accessibility**: The code in this PR does not include any user facing features. 

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by pocmo** [comment]
Looks like there's some overlap with PR #16356. CC @jonalmeida

**Comment by ilPikachu** [comment]
Any updates on reviewing this PR?

**Comment by ilPikachu** [comment]
Verified and fixed in: https://github.com/mozilla-mobile/fenix/issues/16780#issuecomment-793470498

**Comment by Mugurell** [comment]
Meant to say, thank you @ilPikachu for wanting to help with this!
I'm sorry I haven't seen this and worked in parallel based on another ticket.

**Pull request closed without merging**
