### PR TITLE
For #3262 - Enable pull down to refresh in Nightly.

### PR DESCRIPTION
**Pull request by Mugurell**
### Pull Request checklist

- [x] **Tests**: Changes a feature flag. No tests.
- [x] **Screenshots**: This PR includes a video of the result.
- [x] **Accessibility**: The code in this PR enables the pull down to refresh functionality which follows [accessibility best practices].

Video showcasing the result - https://drive.google.com/file/d/1USVgp8IirznWWJoYPi6XPETdROYYxzTQ/view

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by Mugurell** [comment]
This should be merged after https://github.com/mozilla-mobile/android-components/pull/6411 is merged.

**Comment by liuche** [comment]
@Mugurell looks like we have the new AC version, and everything is green - so is this ready to land? 🙌

**Comment by Mugurell** [comment]
Yup, let's do this!

**Comment by sflorean** [comment]
#3262 was closed and verified. Marking this also.

**Pull request merged**
