### PR TITLE
For #12544 - Prevent search engines mixup

### PR DESCRIPTION
**Pull request by Mugurell**
Stricter synchronization by always using the same "loadedSearchEngines"
variable.
With "loadedSearchEngines" calling "refreshAsync()" we also get the fallback
engines to contain reddit and youtube (which are programatically added) and
also now we properly remember and display the engines added by user.

### Pull Request checklist

- [x] **Tests**: No new tests. Small changes. The existing tests should confirm the code works good.
- [x] **Screenshots**: This PR includes screenshots or GIFs.
- [x] **Accessibility**: The code in this PR does not include any user facing features.

Here is a small gif of fenix debug but with working MLS that shows everything working nicely including `reddit` and `youtube` from the first run and that custom search engines are properly handled.
FenixSearchEnginesAllGood

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by Mugurell** [comment]
@liuche Oana helped me test various scenarios and saw that this patch should resolve the issues with custom default engines / other default engines for specific regions.
But just to be sure, I'd say after review we should verify this in Nightly and only after that uplift in Beta.

**Comment by st3fan** [comment]
Marked this as a release blocker that needs an uplift

**Comment by st3fan** [comment]
Adding a few more reviewers to get this one going.

**Comment by sv-ohorvath** [comment]
Left a comment on the issue, this is now fixed on the latest Nightly 7/17. Thank you!

**Pull request merged**
