### PR TITLE
Fixup breaking changes from AppServices upgrade to 93.0.1

### PR DESCRIPTION
**Pull request by jhugman**
Fixes changes caused by https://github.com/mozilla-mobile/android-components/pull/11972

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by bendk** [comment]
I'm seeing this error when trying to build:
```
e: /home/bdk/fenix/app/build/generated/source/nimbus/debug/kotlin/org/mozilla/fenix/nimbus/FxNimbus.kt: (126, 46): Property delegate must have a 'getValue(DefaultBrowserMessage, KProperty<*>)' method. None of the following functions is suitable: 
public inline operator fun <T> Lazy<{Comparable<{MessageSurfaceId & String}>? & java.io.Serializable?}?>.getValue(thisRef: Any?, property: KProperty<*>): {Comparable<{MessageSurfaceId & String}>? & java.io.Serializable?}? defined in kotlin
```

Any ideas how to fix it?

**Comment by jhugman** [comment]
I think you need to land pr#[11972](https://github.com/mozilla-mobile/android-components/pull/11972) and [pr#11799](https://github.com/mozilla-mobile/android-components/pull/11799). then wait overnight for an ac release
that will break the build for fenix, and then you land [fenix#24669](https://github.com/mozilla-mobile/fenix/pull/24669#issuecomment-1098329063) to fix that.

/cc @Amejia481 would you mind helping navigate this upgrade/update cycle?

**Comment by Amejia481** [comment]
> upgrade

We have around 2 week for the next beta cut, it will be on May 3rd, I think we have time to figure out any issue earlier.

**Comment by gabrielluong** [comment]
Closing this since the change was done in https://github.com/mozilla-mobile/fenix/pull/24904.

**Pull request closed without merging**
