### PR TITLE
For #25183 - Update the Sentry base URL

### LINKED ISSUE #25183: [Bug]: Update the Sentry base URL to use the new instance
We're still using the old Sentry base URL for the crash reporter UI [here](https://github.com/mozilla-mobile/fenix/blob/72b9e7e1747b547640f55646bb0582fe00a4e8f3/app/src/main/java/org/mozilla/fenix/components/Analytics.kt#L149=). 

So when a user clicks on the Sentry link in the crash reporter UI, it will try to load the crash ID at the wrong cloud instance.

Old: `https://sentry.prod.mozaws.net/operations/{project_name}`
**New**: `https://sentry.io/organizations/mozilla/issues/?project={project_id}`

Before, we appended the project name to the end of the base URL:
- Release: `/fenix-fennec`
- Beta: `/fenix-fennec-beta`
- Nightly: `fenix`

Now (**new**), each project now has an integer instead of a project string:
- Release: `6375561`
- Beta: `6295551`
- Nightly: `6295546`

An example constructed URL for beta would be: `https://sentry.io/organizations/mozilla/issues/?project=6295551&query=a27d4fc0a8ba4c229a6136e3982a9e7c`

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20426)

### PR DESCRIPTION
**Pull request by cschanaj**
Update the Sentry base URL to use the new instance, closes #25183

Screenshots, Accessibility: n.a., no user visible change.

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by jonalmeida — CHANGES_REQUESTED** [review]
Thanks for the change @cschanaj !

You're right that the change is not easy to test for contributors and that was my fault for suggesting it.

However, I did the testing with your patch and a crash URL ended up looking like this: `https://sentry.io/organizations/mozilla/issues/?project=6295546/?query=ba8cdf78130f46f991865cc4f9391dca`

So what we would need is to change the `/?` before the `query` param to be an `&`. You can do this with a patch to change this line here in the Android Components repository: https://github.com/mozilla-mobile/android-components/blob/main/components/lib/crash-sentry/src/main/java/mozilla/components/lib/crash/sentry/SentryService.kt#L56=

I'm happy to re-test the patch for you, but (optionally) if you'd like to test it out yourself and you can follow these steps to fake a sentry instance:
1. Add a file called `.sentry_token` containing any text. This is meant to be the API key, but you can just add `https://1234@1234.ingest.sentry.io/1234`.
2. Build a release variant of the app, like Nightly. You can follow [these instructions](https://github.com/mozilla-mobile/fenix/pull/25323/) to sign the app easily.
3. Somewhere in the app, add a `throw Exception("This is a test")`.
4. Run the app and when it crashes, click the notification to submit the report.
5. Run the app again with the previous line removed and type in the url bar: `about:crashes`.

You should see your crash report at the top with the link in `New Sentry Instance` that will have the link.

Let me know if you have any questions. You can also join our channel on Matrix too if you'd like more real-time support. :)

**Comment by cschanaj** [comment]
@jonalmeida thanks for the instructions. it seems that a patch is already submitted to https://github.com/mozilla-mobile/android-components/pull/12284 by @maxslimb. Would you mind to test & merge the patches if you have the time, please?

**Review by jonalmeida — APPROVED** [review]
This works for me in my testing with the [AC patch](https://github.com/mozilla-mobile/android-components/pull/12284) so let's land this once the AC version bump has also landed (approx tomorrow).

**Comment by cschanaj** [comment]
Thank you!!

**Pull request merged**
