### PR TITLE
[UI smoke test] Clock and calendar PWA form UI tests

### PR DESCRIPTION
**Pull request by AndiAJ**
New date and time picker UI smoke tests:
• `cancelCalendarFormPWATest `
• `setAndClearCalendarFormPWATest `
• `cancelClockFormPWATest `
• `setAndClearClockFormPWATest `

✅  Successfully passed 60x on Firebase

<details>

<summary> 📈 Results (dropdown)</summary>

matrix | result | logs | details
-- | -- | -- | --
matrix-2nryvqjurvx9x | success | logs | 4 test cases passed
matrix-23sa0gpe9l42b | success | logs | 4 test cases passed
matrix-1fyqjmoscuetl | success | logs | 4 test cases passed
matrix-3gb1st7dt6d6m | success | logs | 4 test cases passed
matrix-2uqgm2c10wp5k | success | logs | 4 test cases passed
matrix-28zeogyfem9g7 | success | logs | 4 test cases passed
matrix-3it4gdt7n8zng | success | logs | 4 test cases passed
matrix-32eodk8ypuw9r | success | logs | 4 test cases passed
matrix-5rdpea4rpmv4a | success | logs | 4 test cases passed
matrix-3gbl07ps97yup | success | logs | 4 test cases passed
matrix-f4qzwmx4ucjta | success | logs | 4 test cases passed
matrix-17w8wir4zc5ii | success | logs | 4 test cases passed
matrix-1xi4v5fzrmc0y | success | logs | 4 test cases passed
matrix-4m154aknto0ma | success | logs | 4 test cases passed
matrix-1udquaip8pnxx | success | logs | 4 test cases passed
matrix-znkvilq3johca | success | logs | 4 test cases passed
matrix-3lqse1905cnra | success | logs | 4 test cases passed
matrix-1wxfjydcx7o5j | success | logs | 4 test cases passed
matrix-1q7qedojxzgg5 | success | logs | 4 test cases passed
matrix-1s0a7pglxnx7r | success | logs | 4 test cases passed
matrix-1ttfpgj87gc41 | success | logs | 4 test cases passed
matrix-2aeuw8xr0ix3c | success | logs | 4 test cases passed
matrix-1lqrb4wodi3hy | success | logs | 4 test cases passed
matrix-3d1rosp0zhtxq | success | logs | 4 test cases passed
matrix-hcm2osyhiqlga | success | logs | 4 test cases passed
matrix-272epgufrefpd | success | logs | 4 test cases passed
matrix-3ldcgqmlprfae | success | logs | 4 test cases passed
matrix-12wrhuk18szbx | success | logs | 4 test cases passed
matrix-11kuya78p4vg0 | success | logs | 4 test cases passed
matrix-1ercoc7cjsdxr | success | logs | 4 test cases passed
matrix-wz4gbx9g46d4a | success | logs | 4 test cases passed
matrix-2vcncs74p190c | success | logs | 4 test cases passed
matrix-j9sks4aqovhqa | success | logs | 4 test cases passed
matrix-3vy07e05udg2l | success | logs | 4 test cases passed
matrix-2t8tepanx5tlk | success | logs | 4 test cases passed
matrix-12dvz67at2ebb | success | logs | 4 test cases passed
matrix-3cqw7qpzk562a | success | logs | 4 test cases passed
matrix-2rfgg5hpkont7 | success | logs | 4 test cases passed
matrix-3onyq49qx0j4r | success | logs | 4 test cases passed
matrix-2m8i3lwavtrdz | success | logs | 4 test cases passed
matrix-kh9bqrd1oqgna | success | logs | 4 test cases passed
matrix-3gnocyfo5y50y | success | logs | 4 test cases passed
matrix-20fs2638cvpr2 | success | logs | 4 test cases passed
matrix-1riq1093yxu1l | success | logs | 4 test cases passed
matrix-11n3z2vh9t0ka | success | logs | 4 test cases passed
matrix-23sc04vxpy0bd | success | logs | 4 test cases passed
matrix-1emsj4e48rvhu | success | logs | 4 test cases passed
matrix-2x73et0q2wlgr | success | logs | 4 test cases passed
matrix-1vicr7u2v5azv | success | logs | 4 test cases passed
matrix-14h7d6t2wyvhc | success | logs | 4 test cases passed

</details>

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by Mugurell** [comment]
Drive-by comment: these tests seem nice for the general app functionality but they don't seem to test anything specific to PWAs.
There are important edgecases related to PWAs so having tests to validate the functionality would be great but for this we'd need to know that the properties declared in a PWAs manifest (https://developer.mozilla.org/en-US/docs/Web/Manifest) are properly handled by the app. These are the only differences between a PWA and a normal browser tab.
Some tricky scenarios I can think off (but we should test all possible manifest keys):
- [display mode](https://developer.mozilla.org/en-US/docs/Web/Manifest/display) - it's important to know that the toolbar does not appear / cannot be scrolled into view if the PWA is set as fullscreen.
- [theme color](https://developer.mozilla.org/en-US/docs/Web/Manifest/theme_color) - it's important to know this is properly applied including to the status-bar.
- [orientation](https://developer.mozilla.org/en-US/docs/Web/Manifest/orientation) - there may be PWAs which only look right/work a specific orientation. We'd need to ensure this is supported.

**Comment by AndiAJ** [comment]
Made some refactoring work, re-ran all the PWA tests 5x and successfully passed on firebase.
• Made some small changes to the `externalLinkPWATest` will use DuckDuckGo instead of Google
• Moved `saveLoginsInPWATest` from `SettingsPrivacyTest.kt` class to the `PwaTest.kt` class
• Other minor updates as a consequence of making changes to the PWA test page that will be used

<details>

<summary> 📈 Results (dropdown)</summary>

matrix | result | logs | details
-- | -- | -- | --
matrix-3kyt8tp6orabw | success | logs | 8 test cases passed
matrix-2crf41pjjk49o | success | logs | 8 test cases passed
matrix-1yeqr2ayj31ny | success | logs | 8 test cases passed
matrix-frhy7q5s6i87a | success | logs | 8 test cases passed
matrix-17j5hkevwposk | success | logs | 8 test cases passed



</details>

**Comment by AndiAJ** [comment]
Just added 2 new color picker UI tests that and successfully passed 55x on Firebase.

<details>

<summary> 📈 Results (dropdown)</summary>

matrix | result | logs | details
-- | -- | -- | --
matrix-35swli2lmxb0k | success | logs | 2 test cases passed
matrix-e2peq1dyu6m5a | success | logs | 2 test cases passed
matrix-3hkn0m4392lev | success | logs | 2 test cases passed
matrix-8o7tmzjjp0jsa | success | logs | 2 test cases passed
matrix-12vflr4es4i65 | success | logs | 2 test cases passed
matrix-2t5osol4kg5tm | success | logs | 2 test cases passed
matrix-x625pg0svw4ha | success | logs | 2 test cases passed
matrix-1uxgn7j6t5dqu | success | logs | 2 test cases passed
matrix-1tagedkv0jaoe | success | logs | 2 test cases passed
matrix-1qxrp2mbh1waa | success | logs | 2 test cases passed
matrix-6z5l9h7t0gnaa | success | logs | 2 test cases passed
matrix-2z2xpiebv0gpl | success | logs | 2 test cases passed
matrix-1j6e8rtsoi8no | success | logs | 2 test cases passed
matrix-x5h5xanhjtl0a | success | logs | 2 test cases passed
matrix-3u77n0hn2453n | success | logs | 2 test cases passed
matrix-vvag18f9wawva | success | logs | 2 test cases passed
matrix-1ss3xwpbdb2fd | success | logs | 2 test cases passed
matrix-1shzd8i0g0qoy | success | logs | 2 test cases passed
matrix-uigrl9wrfuewa | success | logs | 2 test cases passed
matrix-1smss2af6wyl5 | success | logs | 2 test cases passed
matrix-3lw2vrp6lvshn | success | logs | 2 test cases passed
matrix-1e8f7dhij5mx8 | success | logs | 2 test cases passed
matrix-3b1ovurcey4hk | success | logs | 2 test cases passed
matrix-2ndvmo1kveuhm | success | logs | 2 test cases passed
matrix-2gapdyz0qpe1e | success | logs | 2 test cases passed
matrix-2ph98iuro5598 | success | logs | 2 test cases passed
matrix-sanq6h2wbsxda | success | logs | 2 test cases passed
matrix-28tbxygtqsvc9 | success | logs | 2 test cases passed
matrix-1z3ca7r6felf9 | success | logs | 2 test cases passed
matrix-1r00gz0ypyq0g | success | logs | 2 test cases passed
matrix-1nyy6zgf3mn7m | success | logs | 2 test cases passed
matrix-1acushsage6lu | success | logs | 2 test cases passed
matrix-vv9mqa8o9slba | success | logs | 2 test cases passed
matrix-363ukqaicl86p | success | logs | 2 test cases passed
matrix-358rm6oi5usrh | success | logs | 2 test cases passed
matrix-6l32nvz5eclta | success | logs | 2 test cases passed
matrix-esiqn093g1v0a | success | logs | 2 test cases passed
matrix-2gb9qfbzl9qze | success | logs | 2 test cases passed
matrix-2s9h1k1mz5obd | success | logs | 2 test cases passed
matrix-hj9m984pi9aqa | success | logs | 2 test cases passed
matrix-57wo48fuejdna | success | logs | 2 test cases passed
matrix-23v3dwsawexfs | success | logs | 2 test cases passed
matrix-1p04ik6123joz | success | logs | 2 test cases passed
matrix-3vskoe0ru94vp | success | logs | 2 test cases passed
matrix-3chyok7gtbi1p | success | logs | 2 test cases passed
matrix-1sm4evlcmziw2 | success | logs | 2 test cases passed
matrix-3qoil7oxm3mhx | success | logs | 2 test cases passed
matrix-18zh4ev96iqjh | success | logs | 2 test cases passed
matrix-13zhfysjc0kkj | success | logs | 2 test cases passed
matrix-2npr9d4boqrcn | success | logs | 2 test cases passed
matrix-y4e4e820l3x1a | success | logs | 2 test cases passed
matrix-3nmgc3gtvuyaq | success | logs | 2 test cases passed
matrix-2i3v19p1saor9 | success | logs | 2 test cases passed
matrix-5k6agdiwjxxua | success | logs | 2 test cases passed
matrix-3rgwlfux0s4up | success | logs | 2 test cases passed

</details>

**Comment by gabrielluong** [comment]
:construction: **Pull Request Maintenance** :construction: Closing this since it's stale. Feel free to reopen.

**Pull request closed without merging**
