### PR TITLE
Closes #4484 - Use IDs when checking HistoryItem equality

### LINKED ISSUE #4484: [Bug]Flicker when deleting History items
## Prerequisites
Have 5 history items 

## Steps to reproduce
1. Tap the 3dot button next the **first** history item and tap delete
2. Tap the 3dot button next the **last** history item and tap delete

### Expected behavior
History items are deleted without any UI problems 

### Actual behavior
When deleting **the first** history item, the History section flickers
When deleting **the last** history item, there are no issues

### Device information

* Android device: 
• Google Pixel 3a (Android 9)
* Fenix version:  RC 1.2-rc2 

#### Notes
► Video

### PR DESCRIPTION
**Pull request by flaszlo198**
This should fix flicker when deleting history items - #4484 .

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by ekager** [comment]
This "ID" is kind of a fake property that we generate. Using `visitedAt` may be a better comparator, but in theory two items _could_ have the same value there. I don't think that's a huge deal, because it won't crash if this collision happens. CC @boek for more info

**Comment by flaszlo198** [comment]
Since `itemAnimator` causes the flicker, disabling it can also solve the problem.

**Comment by ekager** [comment]
Do we lose animations elsewhere though? ie when items are deleted?

**Comment by flaszlo198** [comment]
Delete animation does not work, it flickers instead. I don't think other animations (change, add, move) can happen, because history items cannot be added or modified while browsing history.

**Comment by flaszlo198** [comment]
The flicker seems to affect only the items below the first deleted item. Those items get new IDs after deletion, so `areItemsTheSame` returns false, and `RecyclerView` assumes that those are new items, thus the animation does not work.

Either disabling the animations or fixing them, this pull request should be closed, since the changes are incorrect.

**Comment by ekager** [comment]
Can you try to use visitedAt instead of id and see what that looks like?

**Comment by flaszlo198** [comment]
Using visitedAt solves the flicker, and the animation is working, but there are some bugs:

1. All items below the first deleted item will be redrawn, since `areContentsTheSame` returns false because of the different ids.
2. Since the delete button and group headers are part of list items, they will be animated when the list item is animated:
output

**Pull request closed without merging**
