### PR TITLE
For #20634: remove some unused color resources

### LINKED ISSUE #20634: Remove suppressed `UnusedResources` warnings in lint baseline file
In #7436, we changed the severity of the `UnusedResources` Android Lint check to error to prevent additional unused resources from making it into the app and increasing the APK size. In order to do this, we added existing errors to the baseline file, preventing Android Lint from warning us about these unused resources. **We should go through the lint baseline file and remove the unused resources.** There is one exception: **please read [this document](https://github.com/mozilla-mobile/fenix/wiki/Remove-strings) before removing strings:** they interact with our localization process in special ways so we can't just remove them.

For example, the steps to do this might look like:
- Open `app/lint-baseline.xml` and search for `id="UnusedResources"`. For each error…
- Find the location of the unused resource (it's in the `<issue...` tag)
- Verify if it's unused (e.g. see if there's a reference to the file in our android-components library via our search tool: https://searchfox.org/mozilla-mobile/source/)
- If it's unused, remove it. If it's used, add a suppression to the warning near the the call site
- Remove the corresponding `<issue...>` tag in `app/lint-baseline.xml`

We should also **consider automating part of this using the IDE "Remove unused resources..." action** (hit shift 3 times, then type "remove unused resources"). It may not work correctly with the lint baseline file in place though (or might have a slightly different name).

Some notes:
- you don't have to fix all the unused errors to make a meaningful PR: fix a few, open a PR, and repeat if you'd like
- if possible, try to keep the commits small: large commits are more difficult to review. Thanks for your help!

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17430)

### PR DESCRIPTION
**Pull request by RotBolt**
### Pull Request checklist

- [X] **Tests**: This PR includes thorough tests or an explanation of why it does not
   Fixing issues from lint-baseline.xml. So not added any tests
   
- [X] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
      Fixing issues from lint-baseline.xml. So not added any screenshots
      
- [X] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

Partially closes #20634

### CODE REVIEW

**Comment by RotBolt** [comment]
Hello @mcomella 
I have raised this PR to remove some of the `unused resources`
I have raised another PR for fixing some other issues from `lint-baseline.xml` [here](https://github.com/mozilla-mobile/fenix/pull/21237)

Whichever gets merged first, I will rebase the other then

**Review by gabrielluong — DISMISSED** [review]
Please don't remove `lint-baseline.xml`

**Comment by RotBolt** [comment]
> Please don't remove lint-baseline.xml
@gabrielluong I have not removed the `lint-baseline.xml`. I regenerated the `lint-baseline.xml` due to which there were heavy editions
See its the same branch
Screenshot 2021-09-13 at 9 01 30 PM

**Review by mcomella — APPROVED** [review]
This looks good to me, thank you @RotBolt !

**Comment by mcomella** [comment]
CI in https://github.com/mozilla-mobile/fenix/pull/21273

**Comment by jonalmeida** [comment]
> CI in #21273

Pushed [another CI build](https://github.com/mozilla-mobile/fenix/pull/21282) that seems to have worked.

**Comment by jonalmeida** [comment]
Mergify took away the CI build status after it rebased. 😅 

Let's just land the other PR in that case for now..

**Comment by jonalmeida** [comment]
Landed in https://github.com/mozilla-mobile/fenix/pull/21282.

**Pull request closed without merging**
