### PR TITLE
No delete on swipe bookmarks

### PR DESCRIPTION
**Pull request by Mugurell**
CI run for https://github.com/mozilla-mobile/fenix/pull/16646

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by gabrielluong — APPROVED** [review]
Carrying over the r+ from https://github.com/mozilla-mobile/fenix/pull/16646

**Comment by Mugurell** [comment]
Thank you Gabriel!
Closing and reopening this in the hope that CI tasks would be started on the original PR to then merge that.

**Comment by Mugurell** [comment]
Closing and reopening this in the hope that CI tasks would be started on the original PR to then merge that.

**Comment by Mugurell** [comment]
The original PR was merged. Closing this.

**Pull request closed without merging**
