### PR TITLE
Closes #3880. Add detekt check for license header files. 

### LINKED ISSUE #3880: Add linting rule for adding a license
We should have a linting rule that triggers if a new file does not include the Mozilla license.

### PR DESCRIPTION
**Pull request by dector**
**Depends on**: ~~[mozilla-mobile/android-components/4619](https://github.com/mozilla-mobile/android-components/pull/4619)~~ AC published to [Mozilla Maven Repository](https://maven.mozilla.org/?prefix=maven2/org/mozilla/components/tooling-detekt/).

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] ~~**Tests**: This PR includes thorough tests or an explanation of why it does not~~
- [x] ~~**Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not~~
- [x] ~~**Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features~~

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by ekager** [comment]
Is this ready for review/merge then if the AC piece has been merged in? :)

**Comment by dector** [comment]
Not yet. It seems that there are some issues with publishing required `tooling-detekt` module to maven repository.

**Comment by boek** [comment]
Hey @dector I'm going to close this for now. Feel free to re-open!

**Comment by dector** [comment]
@boek Okay. I'm working on solution to add this rule into built-in detekt rules.

**Pull request closed without merging**
