### PR TITLE
disable lottie and upgrade OkHTTP to 4.5.0 [do not merge]

### PR DESCRIPTION
**Pull request by kbrosnan**
Hacky disabling of the tracking protection shield to allow removal of Lottie so we can try OkHTTP 4.5.0

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by florence443** [comment]
Dont understand what is going all emails r retuning by postal master
Again I have to make new passwords please tel me what is going wrong. Than you

**Comment by florence443** [comment]
What is a pull request were I find it

**Comment by florence443** [comment]
Change my repository ask for url were can I find and what to do

**Comment by florence443** [comment]
How to write and to find my https

**Comment by florence443** [comment]
2 questions please tell me how and were to find https for my settings

**Comment by liuche** [comment]
@kbrosnan is this something that's still useful, or can we close it?

**Pull request closed without merging**
