### PR TITLE
Reverts Disabling Gestures from 81.1.1

### PR DESCRIPTION
**Pull request by ekager**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by liuche — APPROVED** [review]
r+ for reverting 2 PRs
removes preferences, gates features behind feature flag rather than setting

**Comment by Imerion** [comment]
But these will be brought back as options once the issues are fixed right? i got a bit worried seeing issue #10240 closed. To suite all kinds of people software needs accessible options, especially when it comes to not hiding things. If it's one thing I've learned when holding computer courses for people who are recovering from having a stroke, have aphasia, neurodegenerative diseases, motoric issues, etc it is that auto-hiding user interfaces renders applications almost useless for many of these people.There needs to be an easy to find option to disbale this due to accessability reasons. And even if you don't fall into any of the before-mentioned groups, having to jank the screen up and down all the time in order to reach crucial UI elements is just bad and irritating design. I really hope these options will be brought back properly. The way i see it is more options mean a more inclusive and accessible app!

**Comment by cadeyrn** [comment]
#10240 is closed because it's implemented. It's still available in Firefox Nightly, it was only reverted in the Firefox 81 Beta branch.

**Comment by Imerion** [comment]
Oh, I see! Great! It's beta branch I'm using, so I was a bit worried. Sorry for the miss!

**Pull request merged**
