### PR TITLE
For #17855 - Ensure Secure flags are set on Search Dialog

### PR DESCRIPTION
**Pull request by ekager**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by Mugurell — APPROVED** [review]
Nice!

**Review by Mugurell — CHANGES_REQUESTED** [review]
Looks like I can still take screenshots when in SearchDialogFragment.
Testing a bit more now.

**Comment by Mugurell** [comment]
@ekager still being able to take screenshots when coming from a private page to the private homescreen and SearchDialogFragment.
Then because the activity does not have `FLAG_SECURE` the `secure()` won't actually do anything.

Because a video is worth >1k words:
(latest master with this patch applied) 

https://user-images.githubusercontent.com/11428869/107403726-24708480-6b0e-11eb-8729-db483bd166bb.mov

**Comment by Mugurell** [comment]
Looked into this a bit.
What happens is that upon pressing the tab tray button to create a new tab (in this case "+ PRIVATE")
- TabTrayController#handleNewTabTapped is called which [will set the secure flag as expected](https://github.com/mozilla-mobile/fenix/blob/f7b7b25213001e8f766a295a65292722a6cc8946/app/src/main/java/org/mozilla/fenix/tabtray/TabTrayController.kt#L109)
- HomeFragment - onResume
- BrowserFragment - onStop
  This will trigger `SecureWindowFeature#stop` which [will purposely clear the secure flag](https://github.com/mozilla-mobile/android-components/blob/b266ac3d16e15cabc969cfe33c9cf965f557e257/components/feature/privatemode/src/main/java/mozilla/components/feature/privatemode/feature/SecureWindowFeature.kt#L55)
  
 So from now on we are not secure.

**Comment by ekager** [comment]
Hm after our changes in https://github.com/mozilla-mobile/fenix/pull/17842 I'm wondering if we can remove `SecureWindowFeature` entirely... Shouldn't the `HomeActivity` be taking care of the secure flag of the window for private/normal tabs now on `mode` change?

**Comment by Mugurell** [comment]
Looking at the ticket that implemented that `SecureWindowFeature` - https://github.com/mozilla-mobile/android-components/issues/3707 (and the then Fenix usecases) it seems indeed that functionality is superseded by the current Fenix code.
That feature would've automatically set/remove the secure flag for opened tabs but Fenix wants to have more app components secured and does this "manually".
I don't think there are any situations in which a private tab could be opened without the browsingModeManager having a chance to set the expected flags so just removing `SecureWindowFeature` from Fenix would probably be better.

And if we do this I think we won't need to secure the qr dialog .. or any other dialog ..?

**Pull request closed without merging**
