### PR TITLE
 Closes #4890 - Add UI tests to treeherder

### LINKED ISSUE #4890: Show UI test results in treeherder
We'd like to provide more visibility into UI test results.  Adding them to treeherder is a trivial step that would put them alongside other build and test results already accessible there.

### PR DESCRIPTION
**Pull request by rpappalax**
Closes #4890 

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by rpappalax** [comment]
@mitchhentges I was hoping to check that this works on a fenix branch, but i'm getting an insufficient scopes error.  Do i have to wait until this merges to master to verify that it works as expected or am I missing a scope in .taskcluster.yml?

**Comment by rpappalax** [comment]
the ui test job is fixed now so I've rebased the fixes.  @mitchhentges ok if i remove the donotland label?

**Comment by mitchhentges** [comment]
LGTM, yeah :smile:

**Comment by sblatz** [comment]
@rpappalax is there anything blocking this landing? :)

**Comment by JohanLorenzo** [comment]
Patched was imported in https://github.com/mozilla-mobile/fenix/pull/5257. Closing PR as done!

**Pull request closed without merging**
