### PR TITLE
For #6607 Update button theming in no tab pane

### PR DESCRIPTION
**Pull request by mcarare**
### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

add
addd

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by mcarare** [comment]
@brampitoyo This should "fix" https://github.com/mozilla-mobile/fenix/issues/6607#issuecomment-593197479. As a note, without specific mocks for each theme, sometimes theming something is a guess work for us.

**Comment by ekager** [comment]
Do we think maybe we should make this whole button layout a `MaterialButton` with `style="@style/ThemeIndependentMaterialGreyButton"` similar to `component_sign_in`? That would simplify it quite a bit and then it would match other buttons in the app

**Comment by hakkikaancaliskan** [comment]
3 thing with same function? Isn't it confusing?
I think bottom search bar is enough for search function.
75658286-b7ebd500-5c70-11ea-941b-b3a34b2a9af2

**Comment by brampitoyo** [comment]
@hakkikaancaliskan wrote:

> 3 thing with same function? Isn't it confusing?
> I think bottom search bar is enough for search function.

@topotropic is there a difference between tapping:

- The “+ New tab” button underneath “No open tabs”
- The address bar
- The “+” button to the right of the address bar

I think you’ve designed these separate access points for a reason. Perhaps you can help clarify to @hakkikaancaliskan.

**Comment by topotropic** [comment]
@hakkikaancaliskan 

- The search field is probably the most obvious and prominent one especially for people opening the app, having a few open tabs and wanting to search for something new
- The + right to the search bar helps people to quickly open a new tab when they are on a site – they simple tap twice in the same position and have a new tab. 
- The button "+ New tab" is there to support people who don't have any open tabs, we observed over and over again people tapping in this area to open a new tab. 

I agree it seems redundant but each entry point has a purpose. That said, we have plans to restructure home and will revisit this.

**Comment by hakkikaancaliskan** [comment]
@topotropic thanks for answering :) if I appear as rude, sorry, I'm not a native speaker :/
I see the reasons. I also tried press twice to open new tab and if I do it so fast, second tap is throttled (?). Just a little feedback 🤷🏻‍♂️

**Pull request merged**
