### PR TITLE
For #17364: Make search suggestion hint scrollable and avoid overlapping other elements.

### PR DESCRIPTION
**Pull request by mcarare**
### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

**Landscape: Bottom and  Top Toolbar  with a scrollable hint:**
 

**Portrait: Bottom and  Top Toolbar** 
 

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by eliserichards — APPROVED** [review]
This looks good to me! Did the UX change at all? I notice that there are changes to padding/margins/etc in the code. Do you think this needs a UX review?

**Comment by mcarare** [comment]
@eliserichards The layout looks the same as before. The only visible change is that I made the search suggestion hint scrollable, so we can still show it in landscape without overlapping the toolbar.

**Comment by mcarare** [comment]
Can UX approve making the hint scrollable when it does not fit (landscape orientation)? The scrollbar is made always visible in this case, so the user has an indication that the hint is scrollable.

**Comment by topotropic** [comment]
LGTM, thanks!

**Pull request merged**
