### PR TITLE
Update Android Components version

### PR DESCRIPTION
**Pull request by MickeyMoz**

### CODE REVIEW

**Comment by pocmo** [comment]
> [task 2020-11-05T17:19:46.330Z] e: /builds/worker/checkouts/src/app/src/geckoBeta/java/org/mozilla/fenix/engine/GeckoProvider.kt: (73, 17): Unresolved reference: ContentBlocking
[task 2020-11-05T17:19:46.330Z] e: /builds/worker/checkouts/src/app/src/geckoBeta/java/org/mozilla/fenix/engine/GeckoProvider.kt: (74, 17): Unresolved reference: ContentBlocking

**Comment by pocmo** [comment]
Fixing in https://github.com/mozilla-mobile/fenix/pull/16405

**Comment by pocmo** [comment]
@MickeyMoz Yo, please rebase.

**Comment by MickeyMoz** [comment]
Aye, aye captain.

**Review by pocmo — APPROVED** [review]

**Pull request merged**
