### PR TITLE
For #7544 - Show permanent redirect target url in history

### PR DESCRIPTION
**Pull request by Mugurell**
### Pull Request checklist

- [x] **Tests**: This PR includes tests.
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR does not include any user facing features.

ShowingPermanentRedirectTargetUr
[video](https://drive.google.com/file/d/18s5EW2TJxdOjhMO_U1OkXNtUQW3QXJby/view?usp=sharing)

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by gabrielluong** [comment]
We actually end up with 3 entries now. Testing on Fennec, the expected behaviour only included the m.facebook.com entry.

Screen Shot 2020-10-09 at 10 20 02 AM

Screen Shot 2020-10-09 at 10 21 09 AM

**Review by gabrielluong — CHANGES_REQUESTED** [review]
See comments

**Comment by Mugurell** [comment]
> We actually end up with 3 entries now. Testing on Fennec, the expected behaviour only included the m.facebook.com entry.

Indeed.
After accessing "facebook.com" we get to save three visits:

| visit no | link | visit type |
| ------------- | ------------- | ------------- |
| 1  | facebook.com  | LINK |
| 2  | facebook.com  | REDIRECT_PERMANENT |
| 3  | m.facebook.com  | REDIRECT_PERMANENT |

And that would be what we show when we query history.

Will look more closely to what happens on Fennec.

**Comment by Mugurell** [comment]
Marking this as draft until the changes from gecko.

**Comment by gabrielluong** [comment]
> Marking this as draft until the changes from gecko.

@Mugurell do you also have a link to the gecko issue? I am also curious if this is also an issue in https://github.com/mozilla/application-services issue since that is where the history entries are stored. I am also interested to just track the issue since it is relevant for the top sites changes of showing the right visited top sites.

**Comment by Mugurell** [comment]
@gabrielluong Sure, sorry posted it just on the ticket.
I'm waiting for https://bugzilla.mozilla.org/show_bug.cgi?id=1670279 which would send us only the target url to save and not all the redirect links up until that.
With that being a platform change I think this patch would be all that's needed with no change in AS.

**Comment by gabrielluong** [comment]
> @gabrielluong Sure, sorry posted it just on the ticket.
> I'm waiting for https://bugzilla.mozilla.org/show_bug.cgi?id=1670279 which would send us only the target url to save and not all the redirect links up until that.
> With that being a platform change I think this patch would be all that's needed with no change in AS. But we'll see.

This is great. Thank you! I also see that AS is also being consulted in the bug.

**Comment by gabrielluong** [comment]
Hey @Mugurell, I am gonna close this PR for now to clean up our list of PR since we are still waiting for GV. Feel free to reopen whenever.

**Pull request closed without merging**
