### PR TITLE
No issue: Renew/remove metrics set to expire in April 2022

### PR DESCRIPTION
**Pull request by rocketsroger**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by rocketsroger** [comment]
# Request for Data Collection Renewal
### Never expire
Total: 2
———
`events.toolbar_menu_visible`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/18982#pullrequestreview-635098629

2) When will this collection now expire?
    - This probe will never expire.

3) Why was the initial period of collection insufficient?
    - Used to compare relative usage of menu items.

———
`perf.startup.startup_type`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/19028

2) When will this collection now expire?
    - This probe will never expire.

3) Why was the initial period of collection insufficient?
    - Knowing the type of startup can help identify different perf need.

———

**Comment by eliserichards** [comment]
# Data Collection Renewal Review 

> # Request for Data Collection Renewal
> ### Never expire
> 
> Total: 2 ——— `events.toolbar_menu_visible`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Telemetry for #18855, #18851 and #18857  #18982 (review)](https://github.com/mozilla-mobile/fenix/pull/18982#pullrequestreview-635098629)
> 
>     2. When will this collection now expire?
>        
>        * This probe will never expire.
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Used to compare relative usage of menu items.
> 
> 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

> ——— `perf.startup.startup_type`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #18836: add telemetry for start up type #19028](https://github.com/mozilla-mobile/fenix/pull/19028)
> 
>     2. When will this collection now expire?
>        
>        * This probe will never expire.
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Knowing the type of startup can help identify different perf need.
> 
> 
> ———

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

# Result

data-review+

**Review by eliserichards — COMMENTED** [review]
data-review+ pending approval from @kbrosnan and @MarcLeclair 👍

**Review by Amejia481 — APPROVED** [review]

**Comment by rocketsroger** [comment]
@Mergifyio backport releases_v98.0.0

**Pull request merged**
