### PR TITLE
fixes #22943: update androidx.lifecycle to 2.4.0

### LINKED ISSUE #22943: Upgrade androidx.lifecycle version to 2.4.0
The current suggested method of flow collection within UI elements is to use the `repeatOnLifecycle` API. This will automatically cancel the coroutines collecting from a flow during destructive lifecycle events and then relaunch the collection on constructive lifecycle events. This API became available in the above version.

### PR DESCRIPTION
**Pull request by MatthewTighe**
### Pull Request checklist

- [x] **Tests**: Relies on regression
- [x] **Screenshots**: No user-facing changes
- [x] **Accessibility**: No user-facing changes

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by MatthewTighe** [comment]
I think it makes sense to wait this until after the New Year

**Review by pocmo — COMMENTED** [review]
I recommend to create (and test) a matching upgrade in A-C. Otherwise you'll hard-upgrade here and run the A-C code depending on `lifecycle` in an untested state.

**Comment by MatthewTighe** [comment]
Opened a [PR](https://github.com/mozilla-mobile/android-components/pull/11473) for a matching A-C upgrade.

**Comment by jonalmeida** [comment]
Once a new AC version is released, I'll update this PR with that version bump so we have to land just one PR instead of two (this + AC bump).

**Pull request merged**
