### PR TITLE
For #19901: integrate Jetpack Benchmark (microbenchmark)

### PR DESCRIPTION
**Pull request by mcomella**
Review request to both MarcLeclair & jonalmeida to raise awareness of the implementation and its shortcomings. Please ask if you have questions!

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by jonalmeida — COMMENTED** [review]
I've tried to run the sample benchmark test but with no luck. Changing the build variant to debug to see if that would work, didn't help. 🤔 

```
> Task :app:connectedDebugAndroidTest
Starting 0 tests on Pixel 3 - 11
Tests on Pixel 3 - 11 failed: No test results

com.android.build.gradle.internal.testing.ConnectedDevice > No tests found.[Pixel 3 - 11] FAILED
No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations).
```

**Comment by mcomella** [comment]
> I've tried to run the sample benchmark test but with no luck. Changing the build variant to debug to see if that would work, didn't help. 🤔

@jonalmeida iirc, I `@Ignore`d the sample test I wrote so it doesn't run with our usual Firebase runs (I wasn't sure if it was the same command or not). Do you remember if you had removed that before trying to run?

**Comment by jonalmeida** [comment]
> Do you remember if you had removed that before trying to run?

Yeah, I made sure to do that too. I think at one point it was silently running gradle without failures but, I don't see any results in the mentioned results path. I'll come back to this again.

**Review by MarcLeclair — APPROVED** [review]
It worked for me using `./gradlew -Pbenchmark app:connectedCheck` (it did run on nightly and I did have to uninstall previous builds)

**Comment by mcomella** [comment]
@jonalmeida It seems MarcLeclair was able to get this working: would you mind trying again? The steps are to remove the `@Ignore` and follow the instructions in `app/benchmark.gradle`. It's possible some devices aren't well supported: you could try a newer device and a Pixel, if possible. If it still doesn't work, let me know and we can work together to debug it.

I'm going to land it because it seems to work for MarcLeclair and they reviewed the code.

**Pull request merged**
