### PR TITLE
For #7924: Added an undo snackbar when a pinned site is removed

### LINKED ISSUE #7924: Show an undo snackbar when a pinned site is removed
## Acceptance criteria
1. Have pinned site(s)
2. Be on home screen
3. Remove pinned site

**Expected**
See an undo snackbar with "Site removed" as the text and the pinned site is removed, with the ability to add it back when "undo" is pressed.

**Actual**
Pinned site is removed and no snackbar is shown.

Context:
> @gabrielluong can we show an undo snackbar when someone removes a pinned site? Thanks!
https://github.com/mozilla-mobile/fenix/issues/6759#issuecomment-576425110

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15366)

### PR DESCRIPTION
**Pull request by priyanka0906**
fixes: #7924
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

WhatsApp Image 2021-04-08 at 11 03 09 PM

Fixes #7924
Fixes #7924
Fixes #7924
Fixes #7924

### CODE REVIEW

**Comment by priyanka0906** [comment]
@gabrielluong please take a look

**Comment by gabrielluong** [comment]
@priyanka0906 Thanks a lot for the contribution! Could you also include some screenshots of your feature work? Thank you!

**Comment by priyanka0906** [comment]
> @priyanka0906 Thanks a lot for the contribution! Could you also include some screenshots of your feature work? Thank you!

@gabrielluong I have included a screenshot ,please confirm is it fine.

**Comment by eliserichards** [comment]
Tagging @topotropic for UX review: is this string correct?

**Review by eliserichards — COMMENTED** [review]
Let's see if we can add a test here: https://github.com/mozilla-mobile/fenix/blob/master/app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/topsites/TopSiteItemViewHolderTest.kt

**Comment by priyanka0906** [comment]
> Let's see if we can add a test here: https://github.com/mozilla-mobile/fenix/blob/master/app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/topsites/TopSiteItemViewHolderTest.kt

@eliserichards I have to add test here or have to wait for someone's confirmation for this?

**Comment by eliserichards** [comment]
You can add the test here :)

**Comment by priyanka0906** [comment]
> You can add the test here :)
 Okay I will do that.

**Comment by eliserichards** [comment]
These might be a helpful example for creating the test:

https://github.com/mozilla-mobile/fenix/blob/841f1cd265a9ac9979b8e138bb822cacf2ba1d4b/app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingAutomaticSignInViewHolderTest.kt#L120

https://github.com/mozilla-mobile/fenix/blob/841f1cd265a9ac9979b8e138bb822cacf2ba1d4b/app/src/test/java/org/mozilla/fenix/addons/AddonsManagementFragmentTest.kt#L50

**Comment by priyanka0906** [comment]
> These might be a helpful example for creating the test:
> 
> https://github.com/mozilla-mobile/fenix/blob/841f1cd265a9ac9979b8e138bb822cacf2ba1d4b/app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingAutomaticSignInViewHolderTest.kt#L120
> 
> https://github.com/mozilla-mobile/fenix/blob/841f1cd265a9ac9979b8e138bb822cacf2ba1d4b/app/src/test/java/org/mozilla/fenix/addons/AddonsManagementFragmentTest.kt#L50

@eliserichards Thanks for sharing :)

**Review by boek — APPROVED** [review]

**Comment by boek** [comment]
Rebased, tested locally
image

**Pull request merged**
