### PR TITLE
For #8077 - Fixes migration Fenix Beta icon

### PR DESCRIPTION
**Pull request by codrut-topliceanu**
Nightly icons are working as intended according to fenix/7203

### Pull Request checklist

- [x] **Tests**: This PR doesn't include any tests, as none are needed for this icon change.
- [x] **Screenshots**: This PR includes screenshots.
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md)

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

Before migration:

After migration:

### CODE REVIEW

**Comment by NotWoods** [comment]
We should use the full color Firefox logo in the `fennec*` variants instead of the outlined Fenix logo.

**Comment by codrut-topliceanu** [comment]
@NotWoods @ebalazs-sv
I created this PR using my basic understanding [of the issue](https://github.com/mozilla-mobile/fenix/issues/8077) and I have built an image of what I thought the specifications required. If this is not correct please download and modify the image to the correct specifications, then repost it with a more detailed description, so that I can properly solve the issue. Also it might be used as a reference in the future.

**Comment by NotWoods** [comment]
Beta assets pulled from [Fennec](https://searchfox.org/mozilla-esr68/source/mobile/android/branding/beta):

Background color: `#202340`
[fennecBeta.zip](https://github.com/mozilla-mobile/fenix/files/4167152/fennecBeta.zip)

**Comment by pocmo** [comment]
The branding setup and which channel or build type will get what branding is a bit complicated and confusing, we'll update those as part of the following two issues #8278, #8277.

**Pull request closed without merging**
