### PR TITLE
For #26061: Make sure favicons are cropped correctly

### LINKED ISSUE #26061: [Bug]: Firefox will not show favicon for apple.com
### Steps to reproduce

Go to apple.com then tap the tab view button

### Expected behaviour

The apple.com tab should have the Apple favicon

### Actual behaviour

Instead of showing the Apple favicon, it just shows a letter "A" in a blue box (observe screenshot)
Screenshot_20220717-151746

### Device name

Google Pixel 3a XL

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

104.0a1

### Device logs

_No response_

### Additional information

_No response_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21033)

### PR DESCRIPTION
**Pull request by rocketsroger**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #26061

### CODE REVIEW

**Review by MozillaNoah — APPROVED** [review]

**Comment by gabrielluong** [comment]
@rocketsroger could you post a before/after screenshot of the difference between having the icon cropped instead of fit? It's kinda puzzling without a visual guide

**Comment by rocketsroger** [comment]
@gabrielluong One thing that's interesting is that I thought I attached the after image when I put up the PR yesterday.

**Comment by gabrielluong** [comment]
So, is the difference here that we see the Apple favicon instead of the "A" letter because of the crop?

**Comment by rocketsroger** [comment]
> So, is the difference here that we see the Apple favicon instead of the "A" letter because of the crop?

No, the difference is that the apple icon is rectangular rather than a normal square with rounded corners.  I'll update with an after screenshot.

**Comment by rocketsroger** [comment]
Here's the Before (Left) and After (Right) for the history page as record.  Thanks
Screenshot_20220728_124828

**Pull request merged**
