### PR TITLE
fixes #4193 - made close button for tabs more accessible.

### LINKED ISSUE #4193: [Bug][a11y] X to close tab is difficult to tap
## Steps to reproduce
- Open a tab
- Open tabs tray
- Click X on tab to close

### Expected behavior
Tab closes

### Actual behavior
Often, tab is selected instead.

Android accessibility guidelines suggest that minimum touch target size should be 48dp: https://developer.android.com/guide/topics/ui/accessibility/apps#touch-targets Visibly, the button doesn't look that large nor does the touch target feel that large.

The other way to close a single tab is to swipe it closed, however, afaik, that is also not an accessible gesture.

### Device information
* Android device: Pixel 2
* Fenix version: Nightly 190719

### PR DESCRIPTION
**Pull request by mcarare**
set recommended minimum size for accessibility 48x48, while keeping image size the same
removed margin from button and text as it was not needed anymore
aligned close button in center of tab to be visual consistent with alignment of favicon and more visual accessible

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by ekager** [comment]
Could you post a screenshot of the new tab for quick UX verification? :)

**Comment by sblatz** [comment]
image

This is the new close button. It's no longer aligned with the 3 dot menu, though. @mcarare can you please add margins so the center of it aligns?

**Comment by sblatz** [comment]
This is the new layout:

image

**Comment by mcarare** [comment]
The top and right margin cannot be equal, cause the parent view also has margin. Also, I'm not sure If the Talkback rectangle is actually increased when using TouchDelegate.

**Comment by sblatz** [comment]
@mcarare I looked at this some more. Looks like increasing the touch size with a TouchDelegate does **not** make a larger selection square for TalkBack. 

That being said, I was able to fix the visual margins on the button by just getting rid of the [bottom constraint](https://github.com/mozilla-mobile/fenix/pull/4442/files#diff-e02eb983c67e04c93f3ddf6da40d779fR76).

It now looks like this with TalkBack enabled and I think this is good to ship!

image

**Comment by mcarare** [comment]
Looks good. I think we should still check for UI feedback, because the vertically centered placement for the close button has already been accepted and merged for collections, and it would seem weird to have them placed differently for tabs.

**Comment by sblatz** [comment]
@AmyYLee Are you able to take a look at this and let us know whether or not the close button on the tab should be centered vertically or should be aligned to the top?

### Centered
image

### Top

image

**Comment by sblatz** [comment]
To clarify: we likely want consistent behavior here and should either revert the tab collection one to be top aligned or make this one centered :)

### Tab Collection:

image

**Comment by AmyYLee** [comment]
I think these should be top aligned (collections and open tabs). @topotropic do you have feedback?

**Comment by topotropic** [comment]
no additional feedback at this point

**Comment by sblatz** [comment]
Created https://github.com/mozilla-mobile/fenix/pull/5161 to address the tab in collection

**Pull request merged**
