### PR TITLE
Fix 2306: Call SentryService constructor in try/catch

### PR DESCRIPTION
**Pull request by hawkinsw**
Call the SentryService constructor in a try/catch
clause so that it does not crash the application if
it throws an exception. A log message is generated
in the case that the SentryService constructor does
throw an exception. This could be changed in the
future, if necessary.

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by hawkinsw** [comment]
I ran it through ktlint! I swear I follow instructions! Really sorry. Updated patch on its way.

**Comment by hawkinsw** [comment]
New version of the patch is available. It passes detekt and ktlint.

**Comment by boek** [comment]
@hawkinsw @colintheshots In this case I think crashing is ok. My concern with swallowing the error is that it could do more harm than good if we try to build with a bad DSN.

**Comment by boek** [comment]
I'm going to close this for now

**Pull request closed without merging**
