### PR TITLE
Closes #20723: Fix credit card management fragment binding

### LINKED ISSUE #20723: NullPointerException: Missing required view with ID: org.mozilla.fenix:id/add_credit_card_button
https://sentry.prod.mozaws.net/operations/firefox-nightly/issues/12123555/?referrer=github_plugin

```
NullPointerException: Missing required view with ID: org.mozilla.fenix:id/add_credit_card_button
    at org.mozilla.fenix.settings.creditcards.CreditCardsManagementFragment.onCreateView(CreditCardsManagementFragment.kt:32)
...
(10 additional frame(s) were not displayed)

Missing required view with ID: org.mozilla.fenix:id/add_credit_card_button
```

### PR DESCRIPTION
**Pull request by rocketsroger**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by jonalmeida — APPROVED** [review]
Thanks for fixing the crash!

The layout problems can be fixed in a follow-up by correcting the layout that the binding supplies to the `CreditCardsManagementView`. That's my theory based on [this patch](https://github.com/mozilla-mobile/fenix/commit/cca7892e912e2f682ce1ccc4b0a06a4f67511bc9#diff-8fed5531bcd8ff03e4aa072cbb889e487a0ff84c6c5f3fa0761a41758850f64cR54-L56), but let's do that in a follow-up.

**Review by jonalmeida — APPROVED** [review]
Great find and fix! ⚡

**Comment by mcarare** [comment]
While I cannot reproduce this crash, the issue might be a bug in view binding API, due to the fact that the include tag id (`add_credit_card_button`) is different from the id of the root view of the included layout (`add_credit_card_layout`).

**Comment by rocketsroger** [comment]
> While I cannot reproduce this crash, the issue might be a bug in view binding API, due to the fact that the include tag id (`add_credit_card_button`) is different from the id of the root view of the included layout (`add_credit_card_layout`).

To reproduce, add a credit card first then exit the settings.  Then back into settings and tap on `Manage saved cards`.  Should be consistently reproducible.

**Pull request merged**
