### PR TITLE
Update Android Components version

### PR DESCRIPTION
**Pull request by MickeyMoz**

### CODE REVIEW

**Comment by mcarare** [comment]
All failed UI tests seem to be related to saved logins.

**Comment by Amejia481** [comment]
We recently put a patch https://github.com/mozilla-mobile/android-components/commit/cc18078227d1e45a9f962987f1eb7cb46649444d for removing idle prompts fragments

**Comment by mcarare** [comment]
@pocmo It seems that with the new change the save login prompt is immediately dismissed after the login occurs and the page navigates to a new page.
I also tried to log in on a real page and the prompt is dismissed after the login occurs, with no time to save the login from the prompt.

**Comment by pocmo** [comment]
Thanks! I'll investigate. That indeed looks like fallout from the patch.

**Comment by pocmo** [comment]
This was fixed in A-C. This PR should be unblocked now. :)

**Pull request merged**
