### PR TITLE
For #7554: Add App Services Version to About Page. 

### PR DESCRIPTION
**Pull request by joshvocal**
### Pull Request checklist

* Add App Services version in About Firefox Preview page

Screen Shot 2020-01-15 at 10 34 06 PM

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by joshvocal** [comment]
@jonalmeida [mozilla-mobile/fenix/issues/7554](https://github.com/mozilla-mobile/fenix/issues/7554)

**Comment by joshvocal** [comment]
I'm not too sure which test is failing by looking at the [CI](https://firefox-ci-tc.services.mozilla.com/tasks/B4hPzNc2TyyF54tM-ndSkw)

**Comment by jonalmeida** [comment]
> I'm not too sure which test is failing by looking at the [CI](https://firefox-ci-tc.services.mozilla.com/tasks/B4hPzNc2TyyF54tM-ndSkw)

Probably an intermittent. I've started it. :)

**Comment by jonalmeida** [comment]
@joshvocal ah sorry, I jumped the gun there, looks like it's `SettingsAboutTest.verifyAboutFirefoxPreview` that's failing.

Could you please amend the test as well?

The stack trace from the failing test is below:

```
01-18 21:36:19.039: E/TestRunner(9938): failed: verifyAboutFirefoxPreview(org.mozilla.fenix.ui.SettingsAboutTest)
01-18 21:36:19.039: E/TestRunner(9938): ----- begin exception -----
01-18 21:36:19.040: E/TestRunner(9938): androidx.test.espresso.PerformException: Error performing 'single click' on view 'with text: is "Know your rights"'.
01-18 21:36:19.040: E/TestRunner(9938): 	at androidx.test.espresso.PerformException$Builder.build(PerformException.java:86)
01-18 21:36:19.040: E/TestRunner(9938): 	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:87)
01-18 21:36:19.040: E/TestRunner(9938): 	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:59)
01-18 21:36:19.040: E/TestRunner(9938): 	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:322)
01-18 21:36:19.040: E/TestRunner(9938): 	at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:178)
01-18 21:36:19.040: E/TestRunner(9938): 	at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:119)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.assertKnowYourRights(SettingsSubMenuAboutRobot.kt:156)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.assertFirefoxPreviewPage(SettingsSubMenuAboutRobot.kt:63)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobotKt.access$assertFirefoxPreviewPage(SettingsSubMenuAboutRobot.kt:1)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.mozilla.fenix.ui.robots.SettingsSubMenuAboutRobot.verifyAboutFirefoxPreview(SettingsSubMenuAboutRobot.kt:42)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.mozilla.fenix.ui.SettingsAboutTest$verifyAboutFirefoxPreview$4.invoke(SettingsAboutTest.kt:78)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.mozilla.fenix.ui.SettingsAboutTest$verifyAboutFirefoxPreview$4.invoke(SettingsAboutTest.kt:24)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.mozilla.fenix.ui.robots.SettingsRobot$Transition.openAboutFirefoxPreview(SettingsRobot.kt:90)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.mozilla.fenix.ui.SettingsAboutTest.verifyAboutFirefoxPreview(SettingsAboutTest.kt:77)
01-18 21:36:19.040: E/TestRunner(9938): 	at java.lang.reflect.Method.invoke(Native Method)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
01-18 21:36:19.040: E/TestRunner(9938): 	at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
01-18 21:36:19.040: E/TestRunner(9938): 	at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
01-18 21:36:19.040: E/TestRunner(9938): 	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.junit.runners.Suite.runChild(Suite.java:128)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.junit.runners.Suite.runChild(Suite.java:27)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
01-18 21:36:19.040: E/TestRunner(9938): 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
01-18 21:36:19.040: E/TestRunner(9938): 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
01-18 21:36:19.040: E/TestRunner(9938): 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
01-18 21:36:19.040: E/TestRunner(9938): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2145)
01-18 21:36:19.040: E/TestRunner(9938): Caused by: java.lang.RuntimeException: Action will not be performed because the target view does not match one or more of the following constraints:
01-18 21:36:19.040: E/TestRunner(9938): at least 90 percent of the view's area is displayed to the user.
01-18 21:36:19.040: E/TestRunner(9938): Target view: "AppCompatTextView{id=2131296274, res-name=about_item_tit
01-18 21:36:19.040: E/TestRunner(9938): ----- end exception -----
01-18 21:36:19.044: I/TestRunner(9938): finished: verifyAboutFirefoxPreview(org.mozilla.fenix.ui.SettingsAboutTest)
```

**Comment by ekager** [comment]
@joshvocal let us know if you wanna touch up the test so this can land :)

**Comment by joshvocal** [comment]
@ekager I've ran the test and found out why it's failing! I just need a little bit of time to fix it.

**Comment by ekager** [comment]
Closing for #8915
You'll still get contributor credit, but we're having some issue with running CI on contributor PRs. Thanks!

**Pull request closed without merging**
