### PR TITLE
For #22736: Dismiss the fragment on touching home screen behind search.

### PR DESCRIPTION
**Pull request by mcarare**
Just dismissing the keyboard leaves the user in an incomplete state, where search cannot be used without another tap on the toolbar, while that still is in edit mode instead of display mode.

This change follows the same behavior as pressing the back button. 

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by Amejia481 — COMMENTED** [review]
The change looks good.
I just would like to make sure the change doesn't regress to #20701 as it looks @rocketsroger 
changed `dismissAllowingStateLoss` on  https://github.com/mozilla-mobile/fenix/commit/3d33a9422cd443a5a0b105a2a822f37b73c0d411

Would you mind confirming ? :)

**Comment by mcarare** [comment]
> 3d33a94

Yes, I tested that. https://github.com/mozilla-mobile/fenix/commit/3d33a9422cd443a5a0b105a2a822f37b73c0d411 is what introduced this issue (#22736)

**Comment by rocketsroger** [comment]
> Yes, I tested that. [3d33a94](https://github.com/mozilla-mobile/fenix/commit/3d33a9422cd443a5a0b105a2a822f37b73c0d411) is what introduced this issue (#22736). Dismissing the dialog fragment also dismisses the keyboard.

Thanks for fixing this.  I'll try it out and review.

**Comment by mcarare** [comment]
Thank you @rocketsroger! It is good to have another pair of eyes on this!

**Review by rocketsroger — APPROVED** [review]
After some testing, I think we have to land this first to fix the issue at hand.  However, this fix does re-introduce the problem where the user's first scroll will be ignored and have to re-scroll again.  I will try to figure out another solution for that problem.

🚢 Thanks for fixing this.

**Comment by rocketsroger** [comment]
@mcarare actually after playing with this a bit more, the first scroll being ignore is a bit too high of a cost to fix my regression.  Do you mind trying out other fixes to see if we can get a fix that doesn't have the scroll problem?  Thanks

**Review by rocketsroger — CHANGES_REQUESTED** [review]
I think the first scroll being ignore is not a good user experience.  If possible, can we find a better solution.

**Comment by mcarare** [comment]
@rocketsroger what do you mean by "first scroll is ignored"? I have tested this, and on the very first touch/scroll the fragment is dismissed with this patch.

**Comment by mcarare** [comment]
@rocketsroger I added a way to "dispatch" the scroll to the home screen if one is detected. Please let me know if it covers your scenario. Thank you!

**Comment by mcarare** [comment]
After talking more offline with @rocketsroger it seems we would have to choose between one or the other behavior. After testing multiple solutions it seems that dismissing the fragment interferes with any kind of touch handling or dispatching. Even if a scroll would be started programmatically, it would be stoped when the search fragment is dismissed. Tried with delays, and changing action order, the same issue occurs.

Closing this and adding more details to the issue itself. 

Thanks, @rocketsroger for also testing this.

**Pull request closed without merging**
