### PR TITLE
Close #21692: Sort tabs after adding search term tabs without group

### LINKED ISSUE #21692: [Bug]: Tab Group - an ungrouped Search tab always stays at the bottom of the tab list
### Steps to reproduce

Switch to Grid view for tabs (probably also true for List view but I haven't checked)
Open a tab and search for something eg "cat"
(Do not open any links from the "cat" search so it is a normal tab not a group)
The "cat" search tab is last in the tab list
-> correct behavior
Open another tab and navigate to a normal site eg mozilla.org
Go to the tabs tray
The "cat" search tab is still last in the tab list
-> incorrect behavior, the last tab should be mozilla.org since it is the most recently opened

### Expected behaviour

The "cat" search tab should behave like any other tab since it is not a group, so more recently opened tabs should come after it in the list

### Actual behaviour

The "cat" search tab remains the last tab in the list even when I open newer tabs

### Device name

Galaxy A40

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

Today's

### Device logs

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by rocketsroger**
### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by jonalmeida** [comment]
I'm not sure we should do this. What it implies is that every time you select a (normal) tab, that tab will move to a new place. This requires careful consideration. Have we spoken to product/UX about this?

**Comment by rocketsroger** [comment]
> I'm not sure we should do this. What it implies is that every time you select a (normal) tab, that tab will move to a new place. This requires careful consideration. Have we spoken to product/UX about this?

That's true.  I didn't think about that.  I'll have to think about this more.  Thanks for pointing this out.

**Comment by jonalmeida** [comment]
> Would it be a matter of just sorting by `createdAt,` or would it require something more complex?

`createdAt` may work, however it disrupts the order of parent/child tabs. You can create a child tab next to a parent much later on, but that tab needs to stay adjacent to the parent and not last in the list because it is the newest.

**Comment by jonalmeida** [comment]
To clarify, the parent/child sorted relationship is already done in AC and if we try re-write all of that we're creating more work for us. I suggest we punt on this for now since @csadilek will be working on an RFC to upstream these various (for lack of a better word) groupings so we do not need to re-sort things differently in the app.

**Pull request closed without merging**
