### PR TITLE
Bug 1621252 - Move Fenix Raptor  tests to tier 1

### PR DESCRIPTION
**Pull request by liuche**
Pushing this from #9197 to run CI - though I don't think this will run the Raptor CI, will it @JohanLorenzo ? I guess we'll see!

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by bebef1987** [comment]
I think we are OK here
`Decision Task Successful in 1m — FirefoxCI (pull_request) `

Last time Decision Task  was failing with:
```
Exception: raptor-tp6m-13-cold-performance-test-armeabi-v7a (tier 1) cannot depend on signing-performance-test (tier 2)
```

**Comment by bebef1987** [comment]
it would be nice to have the power to trigger a actual raptor test

**Comment by JohanLorenzo** [comment]
Hey @bebef1987!

I have some great news! @tomprince recently enabled a feature. I tested it last week and it worked great. I'm going to document this, but in the meantime, you can just create a file called `try_task_config.json` in the main folder. Commit/push it and you will be able to trigger an actual raptor test.

Here's what the file should contain: 
```json
{
    "parameters": {
        "optimize_target_tasks": true,
        "target_tasks_method": "raptor"
    },
    "version": 2
}
```

**Comment by bebef1987** [comment]
@JohanLorenzo I don't have the power to trigger these builds that's why @liuche had to make a copy of my pull request...

**Pull request merged**
