### PR TITLE
For #15644: update Android Gradle Plugin, restarting custom lint checks

### PR DESCRIPTION
**Pull request by mcomella**
However, I can't fix all these lint errors by myself! Posting as a WIP.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by ekager** [comment]
That should fix all of the immediate "errors" but we should definitely file issues to look into the warnings as well. I'm concerned about some of the a11y ones

**Comment by ekager** [comment]
Oh nice you already did :) https://github.com/mozilla-mobile/fenix/issues/15641

**Comment by mcomella** [comment]
Let's re-run CI.

**Comment by mcomella** [comment]
A bunch of random test failures:
>android.view.InflateException: Binary XML file line #20: Binary XML file line #20: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #20: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
...
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 5: TypedValue{t=0x2/d=0x7f0402eb a=-1}
	at android.content.res.TypedArray.getColorStateList(TypedArray.java:546)

**Comment by ekager** [comment]
Yeah also mentioned here: https://github.com/mozilla-mobile/fenix/pull/15687#issuecomment-703679828

**Comment by pocmo** [comment]
Now I am definitely in favor of landing yours first. :)

**Comment by pocmo** [comment]
What I tried so far is bumping Robolectric (and mockk) since this often was needed for a new plugin or SDK version... but that didn't help.

**Comment by mcomella** [comment]
I added some generally low risk configuration changes to lint.xml. Due to the low risk, I added them here instead of taking extra time to open a new pull request and coordinate the two landing.

**Review by Amejia481 — APPROVED** [review]

**Comment by pocmo** [comment]
I experimented with different runners and configurations with not success so far.

After debugging this a bit I noticed that this is caused by values like `?accent` and `?contastText` in the theme. Somehow at test runtime those cannot be resolved.

**Comment by pocmo** [comment]
Another observation: If I take an isolated test like `OnboardingFinishViewHolderTest` and I wrap `testContext` like:

```Kotlin
val context = ContextThemeWrapper(
    testContext,
    R.style.NormalTheme
)
```

.. and if I use this `context` instead of `testContext` then the test passes. So for some reason `testContext` doesn't seem to have the theme applied.

**Comment by pocmo** [comment]
I did experiment with replacing `testContext` with a `fenixTestContext` that applies the theme and that brought it down to 26 failures (from ~84?). Commit: https://github.com/mozilla-mobile/fenix/pull/15687/commits/826ffca2e9996f47540a4091c21a7c991e38d5aa - Still not sure why/if this is needed.

**Comment by pocmo** [comment]
@mcomella @ekager Is anyone of you still looking into getting this landed?

**Comment by mcomella** [comment]
I found an issue on the Robolectric forums with the same exception as us: https://github.com/robolectric/robolectric/issues/5348#issuecomment-575890396

One commenter said:
> The problem was I had defined different themes for my app, which I didn't need to set for my Splash screen because it was always the same.
> 
>The solution for me was to add
>
>        val settings = applicationContext.getSharedPreferences(Constants.THEME, Context.MODE_PRIVATE)
>        setTheme(settings.getInt(Constants.THEME, R.style.AppTheme_Blue))
>
> to my onCreate and my tests ran as expected

(btw, I tried bumping us to Robolectric 4.4 but it didn't resolve the issue)

**Comment by mcomella** [comment]
> I did experiment with replacing `testContext` with a `fenixTestContext` that applies the theme

I noticed that adding `testContext.setTheme(R.style.NormalTheme)` before the line that throws also seems to work too.

Applying that globally:
```kotlin
class FenixRobolectricTestApplication : FenixApplication() {

    override fun onCreate() {
        super.onCreate()
        setTheme(R.style.NormalTheme)
    }
```

I get one test failure over the whole suite in `GleanMetricsServiceTest. setStartupMetrics sets some base metrics`.

### Cause?
After my change, I noticed the test log output has messages like:

>     [Robolectric] org.mozilla.fenix.session.PrivateNotificationServiceTest.service opens home activity with PBM flag set to false: sdk=28; resources=BINARY

When I run before this PR, I see:

>     [Robolectric] org.mozilla.fenix.components.TrackingProtectionPolicyFactoryTest.GIVEN
 custom policy WHEN some tracking policies THEN tracking policies should match passed po
licies: sdk=28; resources=LEGACY

It looks like we got upgraded to running in BINARY resources mode (legacy has been deprecated for a long time). This comment https://github.com/robolectric/robolectric/issues/4961#issuecomment-488517645 from a robo maintainer mentions:

> Previously with legacy xml resource implementation, if you attempt to look
up an attribute that doesn't exist in your context's theme, Robolectric
would silently ignore it. However, with binary resources, just like real
Android, that results in a runtime error.

In the production app, I'm guessing we're not setting our theme completely at compile time (in XML) but setting it at runtime in the Activity. When Robolectric tries to inflate a view before the Activity is created, it cannot look up the appropriate attributes and crashes (I'm assuming Application is created before `setUp()` due to my fix).

 ### Questions
- Is this really the root cause?
- If so, should we do something differently in the production app? Given that we seem to set the theme in HomeActivity, I'm concerned about the possibility of these:
  - If a different activity starts the app, we won't set a theme and we will crash when certain attributes are accessed (are there crash reports for this?)
  - If we don't provide a theme, we may default to an android framework default theme. This could mean different app appearance between devices because it's not provided by the support library but by specific API levels
  - others...? Themes always seemed complicated to me
- If we make no changes to production, is this the right solution for robolectric? Seems okay? 🤷‍♂️ 
- nit: I guess we should set `android.enableUnitTestBinaryResources` to true?

I don't have the expertise to delve into these theme issues (and should really focus on perf stuff) – @ekager, are these remaining questions something you could look into?

**Comment by mcomella** [comment]
Note: I didn't provide a commit for my test fixes because it might be misleading because it might not be the right solution and the diff (see comment above) is small enough to quickly make locally.

**Comment by pocmo** [comment]
Looks like we have been going through the same debugging paths. We set `NormalTheme` on the `application` node in the manifest, so it should be available everywhere: https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/AndroidManifest.xml#L29 - It doesn't make sense to me that we would have to set it again in tests.

**Comment by mcomella** [comment]
> Looks like we have been going through the same debugging paths. We set `NormalTheme` on the `application` node in the manifest, so it should be available everywhere:

I wonder if 1) our multiple manifest files configurations somehow overrides this value, 2) if having a `FenixRobolectricTestApplication` somehow overrides this value, 3) our activities somehow choose to ignore this style, 4) we're accessing the code before it's ready in robolectric (e.g. maybe it can only be used in `@Test` and not `@Before` ?), or if it's just a dumb bug, perhaps related to things before. :)

**Comment by ekager** [comment]
Hi ya'll. So I looked into this today. 

This looks like a fairly common issue and the recommendation from the team is to [use one of these 3 options](https://github.com/robolectric/robolectric/issues/2641#issuecomment-435213957)

```
Right, that is the problem, your application context will not have your applications theme set on it as declared in it will have the platforms default theme.

I know, I know this is very counter intuitive, but that is how it works on a real device :-)

You can do three things.

Application app = ApplicationProvider.getApplicationContext();
app.setTheme(R.style.myTheme);

Context context = new ContextThemeWrapper(ApplicationProvider.getApplicationContext(), R.style.myTheme)

Activity activity = Robolectric.setupActivity(Activity.class);
```
Mike's [solution from this comment ](https://github.com/mozilla-mobile/fenix/pull/15646#issuecomment-705133690) seems to be using answer number 1. 

Applying [Sebastian's patch from this comment](https://github.com/mozilla-mobile/fenix/pull/15646#issuecomment-704257326) that was option number 2 from the maintainers, but then we hit another issue where we are getting StackOverflowErrors where this is used with spy. What we could do: [we could possibly try to use Mockito.spy instead of Mockk as suggested in this issue.](https://github.com/mockk/mockk/issues/41#issuecomment-547749813) Or we could use the original `testContext` for those cases where we use spy. (I tested this and it works)

With either of these solutions, all of the tests pass except `setStartupMetrics sets some base metrics`.

I think we should go with Mike's since it is less overall change?

**Comment by pocmo** [comment]
> I think we should go with Mike's since it is less overall change?

Agree 👍

> all of the tests pass except `setStartupMetrics sets some base metrics.`

What is the failure you are seeing? Do you know if it's glean related? My PR contained a Glean version bump (via AC) that fixed an issue with version 4 of the plugin. Just wondering if that may be a problem with 3.6 already? Just guessing though. :)

**Comment by ekager** [comment]
Failure is 
```
expected:<true> but was:<false>
Expected :true
Actual   :false
<Click to see difference>

java.lang.AssertionError: expected:<true> but was:<false>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.mozilla.fenix.components.metrics.GleanMetricsServiceTest.setStartupMetrics sets some base metrics(GleanMetricsServiceTest.kt:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Review by MarcLeclair — APPROVED** [review]

**Comment by mcomella** [comment]
Still need to address that last unit test failure:
```
java.lang.AssertionError: expected:<true> but was:<false>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.mozilla.fenix.components.metrics.GleanMetricsServiceTest.setStartupMetrics sets some base metrics(GleanMetricsServiceTest.kt:40)
```

**Comment by mcomella** [comment]
> I know, I know this is very counter intuitive, but that is how it works on a real device :-)

@ekager Could this mean that we're currently using the platform default theme in the production application? Would we want to change that behavior rather than changing the test code?

**Comment by mcomella** [comment]
The test failure occurs because the test package name is `org.mozilla.fenix.debug`, `MozillaProductDetector.getInstalledMozillaProducts` returns false when it doesn't recognize an application, and the debug app ID is not recognized. Looking for a fix...

**Comment by mcomella** [comment]
I'm guessing the app ID behavior changed between versions.

**Comment by mcomella** [comment]
Given that the robolectric app ID is set on the build variant and this test is currently coupled to a specific application ID, I think our solutions are:
- Most robust: pass in mocks of the dependencies to return the values we desire
- Least pain, if possible: override application ID in robolectric

**Comment by mcomella** [comment]
I pushed a fix for the test failure and a few other small clean-ups. I added a comment for why we replace the context but I need the answer to my previous comment https://github.com/mozilla-mobile/fenix/pull/15646#issuecomment-708646969 to finish it – @ekager, let me know if you have thoughts.

**Comment by ekager** [comment]
@mcomella I am good with just changing the test code (since this was all working before the upgrades) if you are!

**Comment by mcomella** [comment]
Failure is a timeout:

```
[task 2020-10-15T05:01:33.998Z]   TEST: GIVEN sharedprefs contains installed engines WHEN installedSearchEngineIdentifiers THEN defaultEngines + customEngines ids are returned
[task 2020-10-15T05:01:33.998Z]     [Robolectric] org.mozilla.fenix.components.searchengine.FenixSearchEngineProviderTest.GIVEN sharedprefs contains installed engines WHEN installedSearchEngineIdentifiers THEN defaultEngines + customEngines ids are returned: sdk=28; resources=BINARY
[task 2020-10-15T05:01:36.898Z]     I/MonitoringInstr: Instrumentation started!
[task 2020-10-15T05:01:59.598Z]   SUCCESS
[task 2020-10-15T05:01:59.598Z] 
[task 2020-10-15T05:01:59.598Z] 
[task 2020-10-15T05:01:59.598Z] SUITE: org.mozilla.fenix.library.history.HistoryItemMenuTest
[task 2020-10-15T05:01:59.698Z]   TEST: builds menu items
[task 2020-10-15T05:02:00.298Z]     [Robolectric] org.mozilla.fenix.library.history.HistoryItemMenuTest.builds menu items: sdk=28; resources=BINARY
[task 2020-10-15T05:02:04.898Z]     I/MonitoringInstr: Instrumentation started!
[task 2020-10-15T05:02:08.298Z]   SUCCESS
[task 2020-10-15T05:02:08.298Z] 
[task 2020-10-15T05:02:08.298Z]   TEST: delete item has special styling
[task 2020-10-15T05:02:08.898Z]     [Robolectric] org.mozilla.fenix.library.history.HistoryItemMenuTest.delete item has special styling: sdk=28; resources=BINARY
[task 2020-10-15T05:02:17.998Z]     I/MonitoringInstr: Instrumentation started!
[task 2020-10-15T05:02:22.498Z]   SUCCESS
[task 2020-10-15T05:02:22.498Z] 
[task 2020-10-15T05:02:22.499Z] 
[task 2020-10-15T05:02:22.499Z] SUITE: org.mozilla.fenix.library.history.HistoryFragmentStoreTest
[task 2020-10-15T05:02:23.698Z]   TEST: startSync
[taskcluster:error] Task timeout after 7200 seconds. Force killing container.
```

TaskCluster was going strangely slow for this ^ look how long it took between tests. It could be:
- TC running slowly for some reason
- Spawning too many threads in roboletric: apparently they're not automatically cleaned up between tests:
> DO limit the number of the threads that are running during each test. Rogue threads often cause test pollution because they are not automatically cleaned up between tests. Oftentimes threads are inadvertently spawned when using third-party libraries (e.g for networking) or background processing components. One of the main sources of additional threads during tests are ExecutorServices that maintain thread pools. If possible, mock dependent components that spawn threads, or use a DirectExecutor. If it’s necessary to run multiple threads during a test, make sure to explicitly stop all threads and ExecutorServices to avoid test pollution.

http://robolectric.org/best-practices/

**Comment by mcomella** [comment]
> @mcomella I am good with just changing the test code (since this was all working before the upgrades) if you are!

@ekager I was concerned that, in production, if we are using the platform default theme and not our theme, who provides that platform default theme? e.g. is it provided by the OEM? is it provided by the API level? In those two cases, the theme may be different between devices and cause inconsistent visuals (visuals changing on API level, OEM was a common problem a few years ago but less common today so perhaps it's not a problem). If it's by jetpack, it's should be fine.

I briefly looked into this though and I think we're using our theme as expected: `HomeActivity.onApplyThemeResource` is called before `onCreate` and seems to be called with the `NormalTheme` as `resources.getResourceEntryName(resid)` for the resid passed in returns NormalTheme. `applicationInfo.theme` returned the same resid so I think the Application is fine too.

I wonder why robolectric doesn't work if "that is how it works on a real device". I feel like it must be a robolectric bug...

🤷‍♂️ I guess I'm fine to ship it too.

**Comment by mcomella** [comment]
I removed the TODO from the comment with an amended commit and force pushed.

**Comment by mcomella** [comment]
`toolchain-linux64-android-gradle-dependencies` failed:
```
[task 2020-10-15T15:49:33.353Z] FAILURE: Build failed with an exception.
[task 2020-10-15T15:49:33.353Z] 
[task 2020-10-15T15:49:33.353Z] * What went wrong:
[task 2020-10-15T15:49:33.353Z] Could not determine the dependencies of task ':app:compileBetaJavaWithJavac'.
[task 2020-10-15T15:49:33.353Z] > Could not resolve all task dependencies for configuration ':app:betaCompileClasspath'.
[task 2020-10-15T15:49:33.353Z]    > Could not find com.leanplum:leanplum-core:5.4.0.
[task 2020-10-15T15:49:33.353Z]      Required by:
[task 2020-10-15T15:49:33.353Z]          project :app
[task 2020-10-15T15:49:33.353Z]          project :app > com.leanplum:leanplum-fcm:5.4.0
[task 2020-10-15T15:49:33.353Z]          project :app > com.leanplum:leanplum-push:5.4.0
```

I wonder if these were unpublished? 😱

**Comment by mcomella** [comment]
I rebased on master locally and confirmed lintDebug still passes so I think we're good to merge! 🥳

**Pull request merged**
