### PR TITLE
For #1744: Open search shortcuts when entering search mode

### PR DESCRIPTION
**Pull request by jyeontaek**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by ekager** [comment]
Do we even still need this argument if it's defaulting to true now? Are there fragments that use the directions with `false`?

**Comment by jyeontaek** [comment]
> Are there fragments that use the directions with `false`?
No there isn't. I kept the argument just in case, but should I just get rid of it?

**Comment by ekager** [comment]
I think you should get rid of the argument altogether if we don't use it anymore. Another part of #1744 was making sure these search shortcutes get dismissed as you start typing. Could you make sure that works as well?

**Comment by jyeontaek** [comment]
Yeah, the shortcuts get dismissed properly. I removed the argument, so let me know if there are other changes I should make!

**Pull request merged**
