### PR TITLE
For #4892: Replaced straight single quote with curly apostrophe in contractions

### PR DESCRIPTION
**Pull request by mcarare**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by ekager** [comment]
This may have the same issue as https://github.com/mozilla-mobile/fenix/pull/5081 ? I'm not sure we can change strings in our files because they changes may be overwritten with the next l10n import

**Comment by mcarare** [comment]
I haven't seen the process documented somewhere, but I thought only new strings are being imported.

**Comment by Delphine** [comment]
This should be good because it's dealing with the original en-US strings (vs actual localizations like in https://github.com/mozilla-mobile/fenix/pull/5081).
However, the backslash should be taken out as well in these strings (so, just leave the curly apostrophe).
Localizers have probably decided to use their correct apostrophe already, so we don't need a string ID here to notify them all of this change. Just udpating these strings should be enough, and we'll pick them up once they land on master on your side
(CC @Pike just in case I'm missing something here)

**Comment by mcarare** [comment]
@Delphine Thank you for clarifying these string issues. I've also removed the preceding backslash not needed for escaping anymore.

**Comment by Pike** [comment]
This fix is right, en-US strings are maintained here, l10n strings are maintained in l10n.

Also, typographic fixes shouldn't get ID changes.

**Pull request merged**
