### PR TITLE
Unnecessary space issue resolved

### PR DESCRIPTION
**Pull request by Biren-Nayak**
This is my first contribution. So please help me with this contribution if anything is wrong or anything i should know about.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### Screenshot

- Before
image

- After
image

### CODE REVIEW

**Comment by Biren-Nayak** [comment]
@ekager I know this is not much important and is just a UI glitch, but I am new to this so kindly let me know for any updates.

**Review by Amejia481 — APPROVED** [review]

**Comment by Amejia481** [comment]
Thanks for @Biren-Nayak the patch and congrats on your first contribution. Hope this is the first one of many :)

**Comment by Biren-Nayak** [comment]
Thanks @Amejia481 for your quick response.

**Comment by Amejia481** [comment]
@Biren-Nayak 
Closing as we are not able to merged it due to CI issues, I created a new PR and added you as an author https://github.com/mozilla-mobile/fenix/pull/21638

**Pull request closed without merging**
