### PR TITLE
Update Android Components version

### PR DESCRIPTION
**Pull request by MickeyMoz**

### CODE REVIEW

**Comment by mavduevskiy** [comment]
@badboy
Could you kindly take a look? Seems, something is off with glean. Thank you!

**Comment by gabrielluong** [comment]
This looks like it is downgrading AC version.

**Comment by gabrielluong** [comment]
Closing this since it's trying to downgrade the AC version.

**Comment by badboy** [comment]
wat. weird. I'll check.

**Comment by badboy** [comment]
No idea what's going on.
The code to update this [is in this repository](https://github.com/mozilla-mobile/fenix/blob/af5b2c94d3889585b5bc748866d9fa8fafc086df/automation/taskcluster/update_android_components.sh).
I didn't touch that code.
It grabs the latest version from [the `maven-metadata.xml`](https://nightly.maven.mozilla.org/maven2/org/mozilla/components/browser-engine-gecko/maven-metadata.xml). Maybe a caching issue or otherwise broken file?

**Pull request closed without merging**
