### PR TITLE
For #12571: Rename 'Shortcuts' to 'Search engines'

### PR DESCRIPTION
**Pull request by hakkikaancaliskan**
cc @NotWoods 

Continue of #12583
For #12571 

I've also migrated string keys for removing further confusions.  Should be easy for translators (copy-paste).

Co-authored-by: Khushraj Rathod <khushrajrathod@gmail.com>

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [x] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by hakkikaancaliskan** [comment]
> LGTM!
> 
> Can you also add a co-authored note to the commit message?
> ```
> Co-authored-by: Khushraj Rathod <khushrajrathod@gmail.com>
> ```

Is there an easy way to edit commit message?

**Comment by hakkikaancaliskan** [comment]
@eliserichards done

**Comment by ekager** [comment]
Because we're still in string quarantine for release, we're not supposed to be removing strings right now. Let's keep the deprecated string. Thanks!

**Comment by hakkikaancaliskan** [comment]
> Because we're still in string quarantine for release, we're not supposed to be removing strings right now. Let's keep the deprecated string. Thanks!

Ok, re-adding now 👍

**Comment by hakkikaancaliskan** [comment]
@ekager Could you please re-check?

**Comment by liuche** [comment]
Okay, string freeze ended on July 18, so we should actually remove this string now since it's taken a while to actually land this, sorry for the delay @hakkikaancaliskan !

**Comment by hakkikaancaliskan** [comment]
> Okay, string freeze ended on July 18, so we should actually remove this string now since it's taken a while to actually land this, sorry for the delay @hakkikaancaliskan !

So should I delete that deprecated string again?

**Comment by hakkikaancaliskan** [comment]
@NotWoods I think this one too ready to land

**Comment by NotWoods** [comment]
@liuche Please double check and land :)

**Comment by ekager** [comment]
Closing because #12830 has been merged

**Pull request closed without merging**
