### PR TITLE
Re-enable raptor jobs

### PR DESCRIPTION
**Pull request by rwood-moz**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by mitchhentges** [comment]
Additionally, we need to wait for #2468 to be fixed before we can merge this.

**Comment by rwood-moz** [comment]
> I believe we need to to bump
> 
> https://github.com/mozilla-mobile/fenix/blob/c5e5ef4b258751dc444370ff9a032692f4b5851f/buildSrc/src/main/java/Gecko.kt#L6
> 
> Otherwise, the change landed in bug 1549948 won't be taken into account.

Thanks @JohanLorenzo. Sorry but can you please show me where to find that gecko nightly_version value? I've pulled the latest inbound and did a new nightly build, and do ./mach run but don't see that in console or in the about info.

**Comment by mitchhentges** [comment]
I think I can help here: @rwood-moz it should be in `buildSrc/src/main/java/Gecko.kt`, I think you need to change the `nightly_version` value :)

**Comment by JohanLorenzo** [comment]
You can find what value to fill in by looking at https://maven.mozilla.org/?prefix=maven2/org/mozilla/geckoview/geckoview-nightly-x86/. The patterns is `$MAJOR_FIREFOX_VERSION.0.$BUILD_ID_OF_A_NIGHTLY`

**Comment by rwood-moz** [comment]
Oh cool! Thank you both. Updating now.

**Comment by rwood-moz** [comment]
Note: There's an additional Raptor fix needed that landed today (Bug 1551972). So the gecko_nightly version needs to be updated first, to grab this:

https://hg.mozilla.org/integration/autoland/rev/2c3426c42411

**Comment by rwood-moz** [comment]
@mitchhentges We solved another Raptor issue, so let's wait and update the gecko version to grab this Moz hg patch too (it's not landed yet):

https://bugzilla.mozilla.org/show_bug.cgi?id=1551972#c28

**Comment by rwood-moz** [comment]
This is the 2nd fix that we need, it's just landed autoland but not yet merged to central:

https://hg.mozilla.org/integration/autoland/rev/8c01df028cc2

**Comment by rwood-moz** [comment]
Closing as @mitchhentges is taking care of updating this along with the activity class name in a future PR.

**Pull request closed without merging**
