### PR TITLE
No issue: Enable tabs tray re-write by default in nightly

### PR DESCRIPTION
**Pull request by jonalmeida**
With https://github.com/mozilla-mobile/fenix/pull/18999 in review, all our existing functionality has complete code paths. So it we can flip the flag for nightly only users to get some feedback from our users. 🎉 

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by jonalmeida** [comment]
Do not land until #18999 is merged.

**Review by rocketsroger — DISMISSED** [review]
💪

**Comment by jonalmeida** [comment]
Oh hey, we broke .. _checks_... MANY UI tests! 😄 

My guess is probably related to the missing Undo/toast notifications.

**Comment by jonalmeida** [comment]
Re-running to see if the collections tests go away with the parent PR fixed now.

**Comment by jonalmeida** [comment]
Some of these have genuine bugs that we didn't catch! ❤️ 

Here are two of them:
- https://github.com/mozilla-mobile/fenix/pull/19012
- https://github.com/mozilla-mobile/fenix/pull/19014

> Re-running to see if the collections tests go away with the parent PR fixed now.

I forgot to rebase before doing this. No matter, after the above two PRs land, we can re-run them again.

**Comment by jonalmeida** [comment]
A lot of these tests rely on the tabs tray closing after the last tab is closed. So I filed https://github.com/mozilla-mobile/fenix/issues/19045 and added a probable fix to this PR to re-run everything and see which ones still fail.

**Comment by jonalmeida** [comment]
> # [Codecov](https://codecov.io/gh/mozilla-mobile/fenix/pull/19001?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mozilla-mobile) Report
> 
> > Merging [#19001](https://codecov.io/gh/mozilla-mobile/fenix/pull/19001?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mozilla-mobile) ([d0a688c](https://github.com/mozilla-mobile/fenix/commit/d0a688cd8e488bf6b5b0f3de3ebb7aaf4202a0cc)) into [master](https://codecov.io/gh/mozilla-mobile/fenix/commit/cba68faac61f8ea87781595a5347a2f0896dccd7?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=mozilla-mobile) ([cba68fa](https://github.com/mozilla-mobile/fenix/commit/cba68faac61f8ea87781595a5347a2f0896dccd7)) will **decrease** coverage by `0.01%`.
> > The diff coverage is `50.00%`.

Three days later and now you decide to post a report. Cool cool cool.

**Comment by jonalmeida** [comment]
There are three implementations to open the tab tray in different classes and they're all slightly different in non-trivial ways. 🤔 

`NavigationToolbarRobot.openTabTray`, `BrowserRobot.openTabDrawer`, and `TabDrawerRobot.openTabDrawer`.

`BrowserRobot` seems to be the the most accurate way to do it: click the button, wait for the tray, _then_ perform the rest of the actions.

**Comment by jonalmeida** [comment]
All green! ✨ 

Requesting a re-review because there is now more in this PR than when it was originally reviewed. Particularly, these commits which are bug fixes in the code:
 - c7104b45c43b5dcd1c3de9f7d241705355ed3296
 - b9425819b9bbfc4254bf65a3446dfe18784515e8
 - 82fd8044d799903001bdbda0d43a74192c046c57

**Review by rocketsroger — APPROVED** [review]

**Comment by jonalmeida** [comment]
Let's do it! 🎉

**Comment by jonalmeida** [comment]
external-content duckduckgo com

**Pull request merged**
