### PR TITLE
For #4127 - Converts Exceptions to LibState, adds empty state, adds tests

### PR DESCRIPTION
**Pull request by ekager**
Going to follow up with converting this to new state while I'm here
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by ekager** [comment]
Oof. I'm working on redoing the tracking protection panel now so I think it makes sense to file a new issue and I'll make sure to address it there.

**Comment by csadilek** [comment]
@ekager OK, I've filed https://github.com/mozilla-mobile/fenix/issues/4228. Definitely an edge case though. So, we could just add the store test here and address this as a follow-up. Up to you :).

**Comment by ekager** [comment]
Ah sorry I didn't mean you had to file it, but thank you!! Updated with the store test now and I'll assign myself to that ticket

**Comment by ekager** [comment]
Yeah let's do that! :) Thanks!

**Pull request merged**
