### PR TITLE
Bug 1577479 - Run UI tests on PRs

### PR DESCRIPTION
**Pull request by JohanLorenzo**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by rpappalax** [comment]
looks go to me,  thanks, @JohanLorenzo

**Comment by JohanLorenzo** [comment]
@rpappalax hey Richard! The new scopes have been deployed, but the UI job is perma red. I guess it's a problem either in the product or in the test https://tools.taskcluster.net/groups/CX-4qfqZQjurDmPeUnMDZQ/tasks/S13FelwtQ9K6VPrLU3jfJA/runs/2/logs/public%2Flogs%2Flive_backing.log. What do you think?

**Comment by rpappalax** [comment]
> @rpappalax hey Richard! The new scopes have been deployed, but the UI job is perma red. I guess it's a problem either in the product or in the test https://tools.taskcluster.net/groups/CX-4qfqZQjurDmPeUnMDZQ/tasks/S13FelwtQ9K6VPrLU3jfJA/runs/2/logs/public%2Flogs%2Flive_backing.log. What do you think?

The log indicates that the job is only failing because of a failed test.  This is by design and I'm currently working on a fix for that failing test.  The PR looks good!

**Comment by JohanLorenzo** [comment]
@sblatz I discussed with @rpappalax and he fine with me merging the PR as is. I don't have the permissions because of the breakage. Can an admin do it for me? cc @mozilla-mobile/fenix

**Comment by rpappalax** [comment]
@sblatz UI test failures have been fixed.  Shall we land this now while builds are green?

**Comment by sblatz** [comment]
@rpappalax im still seeing a UI test failure on the taskcluster. I’m happy to land this once that’s passing!

**Comment by JohanLorenzo** [comment]
Thanks for the rebase @sblatz !

**Pull request merged**
