### PR TITLE
Bug 1671415 - Remove 2019 youtube-playback tests.

### PR DESCRIPTION
**Pull request by gmierz**
This patch removes the 2019 youtube-playback tests (which are replaced by the 2020 tests).

### CODE REVIEW

**Comment by gmierz** [comment]
You can find the tests here: https://github.com/mozilla-mobile/fenix/runs/1259861258

The single failure is a known intermittent failure and has nothing to do with this patch.

**Comment by gmierz** [comment]
@JohanLorenzo this patch is ready for your review and landing if it all looks good.

@mcomella would you be able to remove the fenix reviewers or give it a rubber stamp?

**Review by JohanLorenzo — APPROVED** [review]
This PR looks good to me from a taskgraph perspective. I'm rubber-stamping the test config. I don't know what `chimera` is in this context, for instance.

**Comment by gmierz** [comment]
Thanks @JohanLorenzo! Chimera is a new test mode we're using which combines cold and warm pageload tests into a single test run (saving CI time, and improving the variance in the warm pageloads).

**Pull request merged**
