### PR TITLE
For #20996: Telemetry renewals for september and october

### PR DESCRIPTION
**Pull request by eliserichards**
For #20996

Doc ~[waiting for approval from Vesta]~: https://docs.google.com/document/d/1NGlnTa9TPyTnd3ciUPbwujbITjkX8p8vJybXcZrrM2w/edit# 

Needs: 
- [x] product review (see doc)
- [x] data review
- [x] include data review link in renewed metrics
- [x] eng review

## Probes to renew
- `progressive_web_app`: homescreen_tap, install_tap, foreground, background
- `android_keystore_experiment`: experiment_failure, get_failure, get_result, write_failure, write_success, reset:
- `default_browser_changed`
- `toolbar_menu_visible`
- `experiments_default_browser`: toolbar_menu_clicked
- `startup_type`
- `home_menu`: settings_item_clicked
- `home_screen`: home_screen_displayed
- `set_default_newtab_experiment`: set_default_browser_clicked, close_experiment_card_clicked
- `set_default_setting_experiment`: set_default_browser_clicked

## Probes to delete
We let the majority of these probes expire already. These commits are just to remove the dead probes.

- `master_password` ([commit](https://github.com/mozilla-mobile/fenix/pull/21076/commits/41ded8a07dedb1bd3f189a303934c0ed19986012)): displayed, migration
- `download_notification` ([commit](https://github.com/mozilla-mobile/fenix/pull/21076/commits/ad747564b3085269e45ef6178d64483f8ad1e335)): .resume, .pause, .cancel, .try_again, .open, .in_app_open, .in_app_try_again
- `downloads_misc`([commit](https://github.com/mozilla-mobile/fenix/pull/21076/commits/1e709ce07e4681da6fcd7aa04222f1822385f53f)): .download_added
- `downloads_management:`([commit](https://github.com/mozilla-mobile/fenix/pull/21076/commits/d40a5982f9cbc37da93ae81a3b1cabbf7c754584)): .downloads_screen_opened, .item_opened, .item_deleted
- `about_page`([commit](https://github.com/mozilla-mobile/fenix/pull/21076/commits/435fcf150047ea42cd0bc165efae450b67a61739)): support_tapped, .privacy_notice_tapped
- `total_uri_count`([commit](https://github.com/mozilla-mobile/fenix/pull/21076/commits/26f8c546e215c64e537bb03520543ac6ce8eb91d))
- `find_in_page`([commit](https://github.com/mozilla-mobile/fenix/pull/21076/commits/762373d00a44c9b188b8e99766641ad261fa53c8)): opened, closed, searched_page
- `open_links_in_private`([commit](https://github.com/mozilla-mobile/fenix/pull/21076/commits/))
- `private_search_suggestions`([commit](https://github.com/mozilla-mobile/fenix/pull/21076/commits/))
- `tip`([commit](https://github.com/mozilla-mobile/fenix/pull/21076/commits/)): displayed, pressed, closed
- `private_browsing_mode`([commit](https://github.com/mozilla-mobile/fenix/pull/21076/commits/)): snackbar_undo, notification_tapped 
- `private_browsing_mode`([commit](https://github.com/mozilla-mobile/fenix/pull/21076/commits/c6362f64288ea0beead716d6690ff271a5ccaa92)): snackbar_undo, notification_tapped
- `private_browsing_shortcut`([commit](https://github.com/mozilla-mobile/fenix/pull/21076/commits/f2009096f4fb11454406f7188e44eea020d4a39c)): create_shortcut, cfr_add_shortcut, cfr_cancel, pinned_shortcut_priv. static_shortcut_tab, static_shortcut_priv
- `user_specified_search_engines`([commit](https://github.com/mozilla-mobile/fenix/pull/21076/commits/b60c9b6ea6d3a3671c16434430eff3b3ac53fcff)): custom_engine_added, custom_engine_deleted
- `search_suggestions`([commit](https://github.com/mozilla-mobile/fenix/pull/21076/commits/c1ae45cd85db0ecc6c618ff8211218780988f646)): enable_in_private
- `banner_open_in_app`([commit](https://github.com/mozilla-mobile/fenix/pull/21076/commits/0e8145d6876f26e66311f3e931c852496dddbae1)): displayed, dismissed, go_to_settings

## Probes to let expire 
N/A

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by eliserichards** [comment]
# Request for Data Collection Renewal

`progressive_web_app`: homescreen_tap, install_tap, foreground, background
  
1) Provide a link to the initial Data Collection Review Request for this collection.
      - https://github.com/mozilla-mobile/fenix/pull/11859

2) When will this collection now expire?

      - All probes that were set to expire in September 2021 will now expire on March 1, 2022 (2022-03-01). See [doc](https://docs.google.com/document/d/1NGlnTa9TPyTnd3ciUPbwujbITjkX8p8vJybXcZrrM2w/edit) for breakdown of individual probes and expiration dates.

3) Why was the initial period of collection insufficient?
      - We are continuing to monitor this data through the MR2 release.

`android_keystore_experiment`: experiment_failure, get_failure, get_result, write_failure, write_success, reset:

1) Provide a link to the initial Data Collection Review Request for this collection.
      - https://github.com/mozilla-mobile/fenix/pull/18333#pullrequestreview-612447395

2) When will this collection now expire?

      - All probes that were set to expire in September 2021 will now expire on March 1, 2022 (2022-03-01). 

3) Why was the initial period of collection insufficient?
      - We are continuing to monitor this data through the MR2 release.

`default_browser_changed`:

1) Provide a link to the initial Data Collection Review Request for this collection.
      - https://github.com/mozilla-mobile/fenix/pull/18982#pullrequestreview-635098629

2) When will this collection now expire?

      - All probes that were set to expire in October 2021 will now expire on April 1, 2022 (2022-04-01). 

3) Why was the initial period of collection insufficient?
      - We are continuing to monitor this data through the MR2 release to help track engagement.

`toolbar_menu_visible`:

1) Provide a link to the initial Data Collection Review Request for this collection.
      - https://github.com/mozilla-mobile/fenix/pull/18982#pullrequestreview-635098629

2) When will this collection now expire?

      - All probes that were set to expire in October 2021 will now expire on April 1, 2022 (2022-04-01). 

3) Why was the initial period of collection insufficient?
      - This will be important for our work post-MR2 and we want to continue collecting data so we have a comparison.

`experiments_default_browser`: toolbar_menu_clicked:

1) Provide a link to the initial Data Collection Review Request for this collection.
      - https://github.com/mozilla-mobile/fenix/pull/18982#pullrequestreview-635098629

2) When will this collection now expire?

      - All probes that were set to expire in October 2021 will now expire on April 1, 2022 (2022-04-01). 

3) Why was the initial period of collection insufficient?
      - We are continuing to monitor data from our experiments through the MR2 release.

`startup_type`

1) Provide a link to the initial Data Collection Review Request for this collection.
      - https://github.com/mozilla-mobile/fenix/pull/19028

2) When will this collection now expire?

      - All probes that were set to expire in October 2021 will now expire on April 1, 2022 (2022-04-01). 

3) Why was the initial period of collection insufficient?
      - Continues to be used to monitor performance.

`home_menu`: settings_item_clicked

1) Provide a link to the initial Data Collection Review Request for this collection.
      - https://github.com/mozilla-mobile/fenix/pull/18987

2) When will this collection now expire?

      - All probes that were set to expire in October 2021 will now expire on April 1, 2022 (2022-04-01). 

3) Why was the initial period of collection insufficient?
      - This will be important for our work post-MR2 and we want to continue collecting data so we have a comparison.


`home_screen`: home_screen_displayed:

1) Provide a link to the initial Data Collection Review Request for this collection.
      - https://github.com/mozilla-mobile/fenix/pull/19025

2) When will this collection now expire?

      - All probes that were set to expire in October 2021 will now expire on April 1, 2022 (2022-04-01). 

3) Why was the initial period of collection insufficient?
      - This is important data for the MR2 release.

`set_default_newtab_experiment`: set_default_browser_clicked, close_experiment_card_clicked:

1) Provide a link to the initial Data Collection Review Request for this collection.
      - https://github.com/mozilla-mobile/fenix/pull/18895

2) When will this collection now expire?

      - All probes that were set to expire in October 2021 will now expire on April 1, 2022 (2022-04-01). 

3) Why was the initial period of collection insufficient?
      - We are continuing to monitor data from our experiments through the MR2 release.

`set_default_setting_experiment`: set_default_browser_clicked:

1) Provide a link to the initial Data Collection Review Request for this collection.
      - https://github.com/mozilla-mobile/fenix/pull/19047

2) When will this collection now expire?

      - All probes that were set to expire in October 2021 will now expire on April 1, 2022 (2022-04-01).

3) Why was the initial period of collection insufficient?
      - We are continuing to monitor data from our experiments through the MR2 release.

**Comment by travis79** [comment]
> # Request for Data Collection Renewal
> 
> `progressive_web_app`: homescreen_tap, install_tap, foreground, background
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #10261: PWA Telemetry #11859](https://github.com/mozilla-mobile/fenix/pull/11859)
> 
>     2. When will this collection now expire?
>        
>        * All probes that were set to expire in September 2021 will now expire on March 1, 2022 (2022-03-01). See [doc](https://docs.google.com/document/d/1NGlnTa9TPyTnd3ciUPbwujbITjkX8p8vJybXcZrrM2w/edit) for breakdown of individual probes and expiration dates.
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * We are continuing to monitor this data through the MR2 release.
> 

# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+


> 
> `android_keystore_experiment`: experiment_failure, get_failure, get_result, write_failure, write_success, reset:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Android keystore experiment #18333 (review)](https://github.com/mozilla-mobile/fenix/pull/18333#pullrequestreview-612447395)
> 
>     2. When will this collection now expire?
>        
>        * All probes that were set to expire in September 2021 will now expire on March 1, 2022 (2022-03-01).
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * We are continuing to monitor this data through the MR2 release.
> 
> 

# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

> `default_browser_changed`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Telemetry for #18855, #18851 and #18857  #18982 (review)](https://github.com/mozilla-mobile/fenix/pull/18982#pullrequestreview-635098629)
> 
>     2. When will this collection now expire?
>        
>        * All probes that were set to expire in October 2021 will now expire on April 1, 2022 (2022-04-01).
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * We are continuing to monitor this data through the MR2 release to help track engagement.
> 
> 

# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

> `toolbar_menu_visible`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Telemetry for #18855, #18851 and #18857  #18982 (review)](https://github.com/mozilla-mobile/fenix/pull/18982#pullrequestreview-635098629)
> 
>     2. When will this collection now expire?
>        
>        * All probes that were set to expire in October 2021 will now expire on April 1, 2022 (2022-04-01).
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This will be important for our work post-MR2 and we want to continue collecting data so we have a comparison.
> 
> 

# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

> `experiments_default_browser`: toolbar_menu_clicked:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Telemetry for #18855, #18851 and #18857  #18982 (review)](https://github.com/mozilla-mobile/fenix/pull/18982#pullrequestreview-635098629)
> 
>     2. When will this collection now expire?
>        
>        * All probes that were set to expire in October 2021 will now expire on April 1, 2022 (2022-04-01).
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * We are continuing to monitor data from our experiments through the MR2 release.
> 
> 

# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

> `startup_type`
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #18836: add telemetry for start up type #19028](https://github.com/mozilla-mobile/fenix/pull/19028)
> 
>     2. When will this collection now expire?
>        
>        * All probes that were set to expire in October 2021 will now expire on April 1, 2022 (2022-04-01).
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Continues to be used to monitor performance.
> 
> 

# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

> `home_menu`: settings_item_clicked
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #18856: Add metrics for opening settings screen from home menu. #18987](https://github.com/mozilla-mobile/fenix/pull/18987)
> 
>     2. When will this collection now expire?
>        
>        * All probes that were set to expire in October 2021 will now expire on April 1, 2022 (2022-04-01).
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This will be important for our work post-MR2 and we want to continue collecting data so we have a comparison.
> 
> 

# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

> `home_screen`: home_screen_displayed:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #18854: Add metrics for home screen being displayed. #19025](https://github.com/mozilla-mobile/fenix/pull/19025)
> 
>     2. When will this collection now expire?
>        
>        * All probes that were set to expire in October 2021 will now expire on April 1, 2022 (2022-04-01).
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This is important data for the MR2 release.
> 
> 

# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

> `set_default_newtab_experiment`: set_default_browser_clicked, close_experiment_card_clicked:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #18853: Add metrics for default browser new tab experiment. #18895](https://github.com/mozilla-mobile/fenix/pull/18895)
> 
>     2. When will this collection now expire?
>        
>        * All probes that were set to expire in October 2021 will now expire on April 1, 2022 (2022-04-01).
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * We are continuing to monitor data from our experiments through the MR2 release.
> 
> 

# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

> `set_default_setting_experiment`: set_default_browser_clicked:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #18852: Add metrics for default browser settings screen experiment. #19047](https://github.com/mozilla-mobile/fenix/pull/19047)
> 
>     2. When will this collection now expire?
>        
>        * All probes that were set to expire in October 2021 will now expire on April 1, 2022 (2022-04-01).
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * We are continuing to monitor data from our experiments through the MR2 release.

# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

@eliserichards don't forget to update the `data-reviews` in the `metrics.yaml` to add this comment to the list, thanks!

**Review by travis79 — APPROVED** [review]
data-review+

**Review by rocketsroger — APPROVED** [review]
Looks good.  Thanks for this!

**Comment by eliserichards** [comment]
@Mergifyio backport releases_v92.0.0

**Pull request merged**
