### PR TITLE
Update Android Components version

### PR DESCRIPTION
**Pull request by MickeyMoz**

### CODE REVIEW

**Comment by pocmo** [comment]
```
[task 2020-08-25T14:23:27.502Z] e: /builds/worker/checkouts/src/app/src/main/java/org/mozilla/fenix/customtabs/WebAppSiteControlsBuilder.kt: (17, 1): Class 'WebAppSiteControlsBuilder' is not abstract and does not implement abstract member public abstract fun buildNotification(context: Context, builder: Notification.Builder): Unit defined in mozilla.components.feature.pwa.feature.SiteControlsBuilder
[task 2020-08-25T14:23:27.502Z] e: /builds/worker/checkouts/src/app/src/main/java/org/mozilla/fenix/customtabs/WebAppSiteControlsBuilder.kt: (26, 5): 'buildNotification' overrides nothing
[task 2020-08-25T14:23:27.502Z] e: /builds/worker/checkouts/src/app/src/main/java/org/mozilla/fenix/customtabs/WebAppSiteControlsBuilder.kt: (31, 42): Type mismatch: inferred type is androidx.core.app.NotificationCompat.Builder but android.app.Notification.Builder was expected
[task 2020-08-25T14:23:27.502Z] e: /builds/worker/checkouts/src/app/src/main/java/org/mozilla/fenix/customtabs/WebAppSiteControlsBuilder.kt: (31, 51): Too many arguments for public open fun buildNotification(context: Context, builder: Notification.Builder): Unit defined in mozilla.components.feature.pwa.feature.SiteControlsBuilder.CopyAndRefresh
```

**Comment by jonalmeida** [comment]
`toolchain-linux64-android-gradle-dependencies` is failing from breaking APIs in AC, but how did that AC upgrade land without the build breaking first? 🤔

**Comment by mcarare** [comment]
The version update should be included in https://github.com/mozilla-mobile/fenix/pull/14115.
cc @NotWoods

**Comment by liuche** [comment]
Unclear why this is happening, looks like it might be an infra problem.

**Comment by pocmo** [comment]
Update happened in #14115.

**Pull request closed without merging**
