### PR TITLE
For #3291 - use synthetic binding instead of findviewbyid

### LINKED ISSUE #3291: [Bug] Use synthetic binding instead of findviewbyid
### Expected behavior
Synthetic binding should be used instead of findviewbyid to keep the code clean

I would love to work on this issue.

### PR DESCRIPTION
**Pull request by nikit19**
fixes #3291 
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by nikit19** [comment]
Sure! @colintheshots if there are any changes required would love to make those changes.

**Comment by boek** [comment]
Hey @nikit19, sorry this took so long to land. If you can resolve the conflicts I'll test it and merge it in :)

**Comment by nikit19** [comment]
@boek Thanks! I have resolved all the conflicts.

**Comment by colintheshots** [comment]
Looks great! Thanks @nikit19.

**Pull request merged**
