### PR TITLE
For #11563: Set ic_close.xml to use full width and height

### PR DESCRIPTION
**Pull request by hakkikaancaliskan**
ic_close.xml used in this places, i guess there will be no problem because i've compared with other icons and same alignment.
resim

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [x] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by gabrielluong** [comment]
Can you note the source of the svg path that you took? Usually SVG will scale automatically given the width/height. So, it would be streamline the reviews if people can review that the SVG path is coming from our photon design.

Also, tagging @AmyYLee for a UX review

**Comment by hakkikaancaliskan** [comment]
> 
> 
> Can you note the source of the svg path that you took? Usually SVG will scale automatically given the width/height. So, it would be streamline the reviews if people can review that the SVG path is coming from our photon design.
> 
> Also, tagging @AmyYLee for a UX review

https://github.com/FirefoxUX/photon-icons/blob/master/icons/android/close-24.svg

**Comment by gabrielluong** [comment]
> > Can you note the source of the svg path that you took? Usually SVG will scale automatically given the width/height. So, it would be streamline the reviews if people can review that the SVG path is coming from our photon design.
> > Also, tagging @AmyYLee for a UX review
> 
> https://github.com/FirefoxUX/photon-icons/blob/master/icons/android/close-24.svg

That's a nice find. Didn't even know about it myself 😅

**Comment by mcarare** [comment]
This will also change appearance in other places the close button is used (collections, library menus). I this desired?

**Comment by hakkikaancaliskan** [comment]
@mcarare this icon was 24x24 but wrong padding than other icons. This will match rest of the icons. There will be no problem, actually will match the ux mocks.
Of course need verify.

**Comment by brampitoyo** [comment]
@hakkikaancaliskan This is a “no merge” for us.

When comparing the two icons side by side, our close icon is optically smaller and has a larger padding, by design.

Screen Shot 2020-06-29 at 1 23 52 PM

**Comment by hakkikaancaliskan** [comment]
@brampitoyo hmm, smaller close icon is intended. Amy said this so i did this or:
> @cadeyrn I agree the close icon is too small and should match the size of the other icons in the list. Let me know if you need anything from me to fix this. Thanks!

You can close the issue.

**Comment by brampitoyo** [comment]
@hakkikaancaliskan Sorry! I didn’t know that Amy wrote to match the size of the icon.

In that case, let me update the close icon. It’s now enlarged and optically matches the plus.

Instead of modifying the SVG itself, you can use this icon outright in your PR.

https://share.getcloudapp.com/8Lu7Dg04

Here’s the plus icon alongside the enlarged x, for comparison:

Screen Shot 2020-06-30 at 10 11 38 AM

**Comment by hakkikaancaliskan** [comment]
> 
> 
> @hakkikaancaliskan Sorry! I didn’t know that Amy wrote to match the size of the icon.
> 
> In that case, let me update the close icon. It’s now enlarged and optically matches the plus.
> 
> Instead of modifying the SVG itself, you can use this icon outright in your PR.
> 
> https://share.getcloudapp.com/8Lu7Dg04
> 
> Here’s the plus icon alongside the enlarged x, for comparison:
> 
> Screen Shot 2020-06-30 at 10 11 38 AM

Could you please convert it to xml? We're using xml in fenix.

**Comment by hakkikaancaliskan** [comment]
@brampitoyo this pr will change all close icons across app, do you want screenshots or good to go?

**Comment by hakkikaancaliskan** [comment]
> Instead of modifying the SVG itself, you can use this icon outright in your PR.
Android Studio converted it to xml automatically.

**Comment by brampitoyo** [comment]
@hakkikaancaliskan Would you be able to post a screenshot?

No need to post screenshots of all the places. Just the place where the icon occur alongside the plus icon. Then @AmyYLee and I will be able to review it.

Thanks!

**Comment by hakkikaancaliskan** [comment]
@brampitoyo @AmyYLee Here it is:
86063332-51869000-ba73-11ea-8c6a-da2ad5fa92f3

**Comment by brampitoyo** [comment]
@hakkikaancaliskan Looks good to me. The x is now optically aligned with the +.

**Comment by hakkikaancaliskan** [comment]
@gabrielluong do we need Amy's review too or ready for landing?

**Comment by gabrielluong** [comment]
@brampitoyo @AmyYLee Wondering if we need to update any photon (mobile) icon library with the changes here for future reference?

@AmyYLee Should we still block on your review?

**Comment by AmyYLee** [comment]
@gabrielluong This looks good to me.

**Comment by ekager** [comment]
Closing for https://github.com/mozilla-mobile/fenix/pull/12322

**Pull request closed without merging**
