### PR TITLE
Fix #8693 - Add rtl onboarding theme picker images 

### LINKED ISSUE #8693: Support RTL for theme / toolbar position picker images in Onboarding
This would provide a better RTL experience.
Initially reported in https://github.com/mozilla-mobile/fenix/issues/8469, it was seen in https://github.com/mozilla-mobile/fenix/issues/8673 that simply mirroring the existing imagery is not a solution.
For actually fixing this we need new images that would reflect the actual experience RTL users would have.

### PR DESCRIPTION
**Pull request by Mugurell**
### Pull Request checklist

- [x] **Tests**: This PR does not include tests as it encompasses just layout changes
- [x] **Screenshots**: This PR includes before and after screenshots.
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md).

&#8203;
Before and after screenshots:
Fenix-onboarding-rtl-theme-picker-images

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by ekager** [comment]
Changes look good! Think this just needs a rebase to resolve CI issues.
Random question - looking at the screenshot, does the automatic description "adapts to your device settings" look normal when a real RTL language is used? Otherwise could you file an issue? Thanks!

**Comment by Mugurell** [comment]
> Changes look good! Think this just needs a rebase to resolve CI issues.
> Random question - looking at the screenshot, does the automatic description "adapts to your device settings" look normal when a real RTL language is used? Otherwise could you file an issue? Thanks!

Thanks!
Indeed, that issue does not exist in a real RTL language as can be seen here
https://drive.google.com/file/d/11-3sSjg9PvJAjTbRJ_UMC1gghWnPelVS
On a closer look I had to though make sure `onboarding_toolbar_position_picker` always use -7dp as x translation, even in rtl, as those images will not be mirrored.

**Comment by ekager** [comment]
Oh should we also ask @brampitoyo for the mirrored toolbar position picker images here? It's a bit weird to mirror the theme picker images and not the toolbar ones!

**Comment by Mugurell** [comment]
Thanks to Adam Bitner we now have rtl images for the toolbar position picker also.
Video showing the new rtl experience - https://drive.google.com/file/d/1wMcxhfaPExGBOX4q56TB3iqfoZXO_mlP

**Comment by ekager** [comment]
Looks great! Thank you!

**Pull request merged**
