### PR TITLE
Bug 1812616 - Enable clear button on the Password and Host fields

### PR DESCRIPTION
**Pull request by titooan**
Two bugs were fixed in this PR, because they relate to the same screen and I could update the related UI test at once, avoiding further conflicts that could appear if I had opened two separate PRs. 

This PR fixes the behavior of the clear button on both the `Password` and the `Host` fields: the buttons should be visible and enabled as soon as the field contains a valid value.

| Bug id  | Screenshot **before** fix |  Screenshot **after** fix
| ------------- | ------------- | ------------- |
|[1812616](https://bugzilla.mozilla.org/show_bug.cgi?id=1812616) - Password field |Screenshot of the clear button disabled on Password field|Screenshot of the button enabled on Password field
|[1812613](https://bugzilla.mozilla.org/show_bug.cgi?id=1812613) - Host field |Screenshot of the clear button invisible on Host field|Screenshot of the clear button enabled and visible on Host field

Closes [1812616](https://bugzilla.mozilla.org/show_bug.cgi?id=1812616) 

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation

Used by GitHub Actions.

### CODE REVIEW

**Comment by gabrielluong** [comment]
@titooan Just a consideration for your PR title and commit message to do `Bug 1812616, Bug 1812613 - Enable clear button on the Password and Host fields` to ensure that it's linked in Bugzilla. This will match the regex used by our Bugzilla integration which parses these GitHub PRs so that it will automatically attach your PR to the provided bugs in Bugzilla. Alternatively, you could flag one as duplicate and change the description of the other one.

**Review by gabrielluong — APPROVED** [review]

**Comment by gabrielluong** [comment]
When you land this, could you make sure to also set in Bugzilla the QA flags https://mozilla-hub.atlassian.net/wiki/spaces/Mobile/pages/113443418/Android+Bugzilla+GitHub+workflow#How-to-ask-QA-to-verify-a-bug-fix

**Review by kycn — APPROVED** [review]
LGTM! Congrats on your first patches 🎉 
(i guess the failing test is a flaky one as i could not notice an interdependence between this patch and the failing test). Maybe, we can run the ci again?

**Comment by titooan** [comment]
I'm a bit confused with one point:

> If they aren't linked or the commit message doesn't have the second Bug in the commit message, then the Bugzilla issue won't close. [...] Do note the commit message currently doesn't have 1812613 so we just want to make sure that gets closed one way or another.

Actually the [commit message](https://github.com/mozilla-mobile/fenix/pull/28676/commits/2fa0e42b126657401ceca043db739bdf2db24eeb) is:

> Bug 1812616 - Enable clear button on the Password field even after it has been clicked once
> Bug 1812613 - Show clear button on the Host field when its content is valid

Does it mean that the regex can detect only one Bugzilla link per commit message?
(I'm not sure I understand well the [Bugzilla regexp](https://github.com/mozilla-bteam/bmo/commit/8509bbaa68c31c00621832728bd799b724e94751#diff-7c417a2dd5c9150d5d680d5506ea703dae0b1933954dcdec522ef71bc00f6b77R23))

Also, I changed the title of the PR to follow your advice, but it seems that the [bug 1812613](https://bugzilla.mozilla.org/show_bug.cgi?id=1812613) is still not linked to this PR. Should I trigger the Bugzilla integration again somehow? 

Thanks a lot for your helpful comments!

**Comment by titooan** [comment]
I closed the [Bug 1812613](https://bugzilla.mozilla.org/show_bug.cgi?id=1812613) and tagged it as duplicate of the [Bug 1812616](https://bugzilla.mozilla.org/show_bug.cgi?id=1812616).
Then I edited the description of the latter so that it describes both issues. 

After talking with @gabrielluong it seems to be the better way of: 
- helping the QA team to easily test the patch for both bugs 
- closing the corresponding bugs on Bugzilla when this PR is merged.

I also edited the commit message to follow the right format ("Bug XX, Bug XX" instead having the second bug in the description of the commit). This triggered the CI again and the flacky test passed succesfully this time (FYI @kycn)

**Pull request merged**
