### PR TITLE
For #14629 - Enable showing frequently visited sites ON by default

### LINKED ISSUE #14629: Enable showing frequently visited sites ON by default

### PR DESCRIPTION
**Pull request by gabrielluong**
Fixes #14629 

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by liuche — APPROVED** [review]
Tested this out, turns off nightly flag and sets the default setting to ON

**Comment by liuche** [comment]
[verifyRemoveTopSite](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6012536756397953293/executions/bs.89eaf264075c723f/testcases/1/test-cases)
@gabrielluong do you think this breaks now that we have frecency turned on by default? I'll re-run these in any case though.

and probably unrelated:
testStrictVisitSheetDetails

And unit tests also failing for some reason 🤔  https://firefoxci.taskcluster-artifacts.net/euFL0hvkT7eEYOTtyWLzUw/0/public/reports/test/testDebugUnitTest/index.html

**Comment by liuche** [comment]
This is a correct test failure - we try to remove the wikipedia site but since we visit another site we delete the incorrect site.

**Comment by gabrielluong** [comment]
We need to wait for AC https://github.com/mozilla-mobile/android-components/pull/8325 to get this test to pass.

**Comment by liuche** [comment]
We still need #14538 (which should be fixed by #14230), but since we need Top Sites for 81, this is fine to land on Nightly.

**Pull request merged**
