### PR TITLE
For #23551 - Change the spacing between Pocket header and content to 16dp

### LINKED ISSUE #23551: Verify Pocket headers padding
Based on the designs there should be a 17dp space between Pocket stories/categories headers and their content.

image

image

This was raised as an issue in https://github.com/mozilla-mobile/fenix/pull/22067#discussion_r798027368
Asking @Kate-Galetski what the values should be.

### PR DESCRIPTION
**Pull request by sunilk9211**
Changed the spacing from 17dp to 16dp.

Fixes #23551
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by gabrielluong** [comment]
@sunilk9211 Thanks for the patch, there are 2 more places we need to change. https://searchfox.org/mozilla-mobile/search?q=17.dp&path=

**Comment by sunilk9211** [comment]
> @sunilk9211 Thanks for the patch, there are 2 more places we need to change. https://searchfox.org/mozilla-mobile/search?q=17.dp&path=

Thanks @gabrielluong That's done

**Comment by gabrielluong** [comment]
@sunilk9211 Thanks, this looks almost ready. Could you also update your commit message since the change goes beyond PocketStoriesCategories? Something like: `Change the spacing between Pocket header and content to 16dp`

**Comment by sunilk9211** [comment]
> @sunilk9211 Thanks, this looks almost ready. Could you also update your commit message since the change goes beyond PocketStoriesCategories? Something like: `Change the spacing between Pocket header and content to 16dp`

Updated @gabrielluong

**Review by gabrielluong — APPROVED** [review]

**Comment by gabrielluong** [comment]
@sunilk9211 Thanks so much! I think we are good to go here, we'll need to wait for CI to pass prior to landing.

**Comment by gabrielluong** [comment]
Landed this in https://github.com/mozilla-mobile/fenix/pull/23779

**Pull request closed without merging**
