### PR TITLE
Update some Gradle dependencies

### PR DESCRIPTION
**Pull request by rvandermeulen**
Similar to https://github.com/mozilla-mobile/android-components/pull/12888. Probably nothing super critical in here, but might as well.

### CODE REVIEW

**Comment by rvandermeulen** [comment]
For future reference, mockk 1.13.2 had a number of test-debug failures:
```
DefaultBrowserToolbarMenuControllerTest. GIVEN a shortcut page is open WHEN remove from shortcuts is pressed THEN show snackbar
SessionControlInteractorTest. GIVEN a PocketStoriesInteractor WHEN a story is clicked THEN handle it in a PocketStoriesController
SessionControlInteractorTest. GIVEN a PocketStoriesInteractor WHEN a story is shown THEN handle it in a PocketStoriesController
SearchDialogControllerTest. WHEN the search engine is added by the application THEN do not load URL
SearchDialogControllerTest. handleAddonsUrlCommitted
SearchDialogControllerTest. handleBlankUrlCommitted
SearchDialogControllerTest. handleCrashesUrlCommitted
SearchDialogControllerTest. handleMozillaUrlCommitted
SearchDialogControllerTest. handleSearchCommitted
SearchDialogControllerTest. handleSearchTermsTapped
SearchDialogControllerTest. handleUrlCommitted
AboutLibrariesFragmentTest. item click should open license dialog
DefaultInactiveTabsControllerTest. WHEN all inactive tabs are closed THEN perform the deletion and report the telemetry event and show a Snackbar
```

**Comment by rvandermeulen** [comment]
I tried updating oss-licenses-plugin to version 0.10.5, but it breaks `AboutLibrariesFragmentTest` due to changes in how that gets populated in debug builds.
license

Which leads to: `java.lang.IllegalArgumentException: No item found containing text "org.mozilla.geckoview:geckoview"`

Which appears to be from upstream commit https://github.com/google/play-services-plugins/commit/138a15dc9209192c6a9397b341b0ef7ddc346af4

Not sure how we want to handle that eventually, but I guess we can take it to a different issue.

**Comment by rvandermeulen** [comment]
I filed #27287 for the oss-licenses-plugin issue and added a comment to Dependencies.kt referencing it.

**Comment by jonalmeida** [comment]
Gut feeling: These are a lot of misc dependency updates happening at once. I'm a bit worried about random intermittent and runtime crashes that we haven't explored yet.

**Comment by rvandermeulen** [comment]
I'm happy to break this up into more than one patch so we can track regressions more easily. Any thoughts on how you want to break them up @jonalmeida?

**Comment by rvandermeulen** [comment]
Per discussion with Jon on Slack, I'm going to break this into a set of smaller PRs.

**Pull request closed without merging**
