### PR TITLE
Update Mozilla Android Components to 28.0.0-SNAPSHOT.

### PR DESCRIPTION
**Pull request by pocmo**
Updating master to use the latest snapshot version (27 -> 28).

### CODE REVIEW

**Comment by pocmo** [comment]
We'll push another snapshot update to fix an AS issue.

**Comment by jonalmeida** [comment]
Hold off on this. Let me test it to make sure that it doesn't crash on start-up from the a-s upgrade.

**Comment by jonalmeida** [comment]
I'm still seeing this a-s failure from a local build of this branch with push enabled:

```
2020-01-08 13:04:01.073 30569-30646/org.mozilla.fenix.debug E/AndroidRuntime: FATAL EXCEPTION: pool-5-thread-1
    Process: org.mozilla.fenix.debug, PID: 30569
    java.lang.reflect.UndeclaredThrowableException
        at $Proxy4.push_connection_new(Unknown Source)
        at mozilla.appservices.push.PushManager.<init>(PushManager.kt:36)
        at mozilla.components.feature.push.RustPushConnection.updateToken(Connection.kt:74)
        at mozilla.components.feature.push.AutoPushFeature$$special$$inlined$let$lambda$1.invokeSuspend(AutoPushFeature.kt:101)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: mozilla.appservices.support.native.MegazordNotAvailable: Failed to locate megazord library: 'push'
        at mozilla.appservices.push.LibPushFFI$Companion$$special$$inlined$loadIndirect$1.invoke(Helpers.kt:186)
        at mozilla.appservices.push.LibPushFFI$Companion$$special$$inlined$loadIndirect$1.invoke(Unknown Source:0)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy4.push_connection_new(Unknown Source) 
        at mozilla.appservices.push.PushManager.<init>(PushManager.kt:36) 
        at mozilla.components.feature.push.RustPushConnection.updateToken(Connection.kt:74) 
        at mozilla.components.feature.push.AutoPushFeature$$special$$inlined$let$lambda$1.invokeSuspend(AutoPushFeature.kt:101) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'fenix':
    dlopen failed: cannot locate symbol "arm_aes_decrypt_cbc_192" referenced by "/data/app/org.mozilla.fenix.debug-FdbImHcDCvxNBmCnQ-nwig==/lib/arm64/libfenix.so"...
    dlopen failed: cannot locate symbol "arm_aes_decrypt_cbc_192" referenced by "/data/app/org.mozilla.fenix.debug-FdbImHcDCvxNBmCnQ-nwig==/lib/arm64/libfenix.so"...
    dlopen failed: cannot locate symbol "arm_aes_decrypt_cbc_192" referenced by "/data/app/org.mozilla.fenix.debug-FdbImHcDCvxNBmCnQ-nwig==/lib/arm64/libfenix.so"...
    Native library (android-aarch64/libfenix.so) not found in resource path (.)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:302)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
        at com.sun.jna.Library$Handler.<init>(Library.java:179)
        at com.sun.jna.Native.load(Native.java:596)
        at com.sun.jna.Native.load(Native.java:570)
        at mozilla.appservices.push.LibPushFFI$Companion.<clinit>(LibPushFFI.kt:98)
        at mozilla.appservices.push.LibPushFFI.<clinit>(Unknown Source:0)
        	... 8 more
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "arm_aes_decrypt_cbc_192" referenced by "/data/app/org.mozilla.fenix.debug-FdbImHcDCvxNBmCnQ-nwig==/lib/arm64/libfenix.so"...
        at com.sun.jna.Native.open(Native Method)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
        		... 14 more
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "arm_aes_decrypt_cbc_192" referenced by "/data/app/org.mozilla.fenix.debug-FdbImHcDCvxNBmCnQ-nwig==/lib/arm64/libfenix.so"...
        at com.sun.jna.Native.open(Native Method)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
        		... 14 more
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "arm_aes_decrypt_cbc_192" referenced by "/data/app/org.mozilla.fenix.debug-FdbImHcDCvxNBmCnQ-nwig==/lib/arm64/libfenix.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:218)
        		... 14 more
    	Suppressed: java.io.IOException: Native library (android-aarch64/libfenix.so) not found in resource path (.)
        at com.sun.jna.Native.extractFromResourcePath(Native.java:1089)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:276)
        		... 14 more
```

**Comment by jonalmeida** [comment]
With push disabled, the app starts up, but I can't sign into FxA, pairing or email sign-in. Trying to do both shows no change to the UI and this in the logs:

```
2020-01-08 13:10:18.501 31519-31588/org.mozilla.fenix.debug I/FirefoxAccountStateMachine: Processing event Authenticate for state NotAuthenticated. Next state is NotAuthenticated
```

**Comment by jonalmeida** [comment]
We downgraded to 0.46.0 in a-c so when that releases, we can upgrade the version number of this.

**Comment by pocmo** [comment]
@jonalmeida The snapshot is now available. This should be able to work now.

**Comment by sblatz** [comment]
We need to change this back to 44.0 now right? 

https://github.com/mozilla-mobile/fenix/pull/7538/files#diff-f6dcd12435c476b2cedd79bcd292b929R41

**Comment by jonalmeida** [comment]
The a-c snapshot just finished building and I tested the changes. I've put an updated PR based off this one, so I'm closing this.

**Comment by vladikoff** [comment]
@jonalmeida  published 0.48.1 https://github.com/mozilla/application-services/releases/tag/v0.48.1

Try that

**Pull request closed without merging**
