### PR TITLE
For #1719: tracking protection icon in quick settings is almost invis…

### PR DESCRIPTION
**Pull request by cadeyrn**
…ible

There was already a fix for the text color, but the icon is also affected.

### CODE REVIEW

**Comment by colintheshots** [comment]
I thought the icon color was deliberate. It certainly seemed so from the code.

**Comment by ekager** [comment]
Both the icon and text were deliberate and supposed to look disabled when TP is off. In our color audit, these values are still being figured out, so this is fine for now and we'll have to add them back.

**Comment by yoasif** [comment]
This still feels like a bug to me, since it looks like a "disabled" color which would generally indicate that the control is insensitive to user input, not that it is disabled. It is also not internally consistent - see the TP control and text in settings -- that isn't grayed out when TP is disabled.

**Comment by cadeyrn** [comment]
What @yoasif said. And I want to add that chaning the color is not only not consistent within Fenix - neither Firefox Focus nor Firefox for desktop does this.

**Pull request merged**
