### PR TITLE
Run UI test nightly

### PR DESCRIPTION
**Pull request by isabelrios**
This is based on PR that has not landed yet, all those changes are needed and a few more... Just trying to have something similar to tests running on Beta but for Nightly while the work with that PR is finished

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by isabelrios** [comment]
We will need PR #16981 and #16786 before landing this, but would like to know your feedback in the meantime if that's possible @JohanLorenzo, thank you in advance!!!

**Review by JohanLorenzo — APPROVED** [review]
Commit 2111adbf2f75f18f6dedfb87811bb96a83440ac0 looks great to me! I haven't looked to closely at the former ones because, they're from https://github.com/mozilla-mobile/fenix/pull/16786, if I remember correctly.

**Comment by isabelrios** [comment]
> Commit [2111adb](https://github.com/mozilla-mobile/fenix/commit/2111adbf2f75f18f6dedfb87811bb96a83440ac0) looks great to me! I haven't looked to closely at the former ones because, they're from #16786, if I remember correctly.

Yes, that's right! thanks for taking a look at it! 🙏

**Comment by isabelrios** [comment]
Closing this PR.  A new one will be open to address the new changes needed for UI tests on Nightly builds

**Pull request closed without merging**
