### PR TITLE
[WIP] For #8791: replace Fenix tab counter

### PR DESCRIPTION
**Pull request by eliserichards**
For #8791 

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by ekager** [comment]
General comment before actually looking at the code closely!

I had previously fixed a bug about the tab counter not working quite properly: 
https://github.com/mozilla-mobile/fenix/issues/12721

and I know AC is trying to move away from using `SessionManager` in more places. 

Comment 1 is we should definitely make sure we're not regressing this behavior, but also ideally maybe we should file an AC issue/do the work to remove the SessionManager dependency in `TabCounterToolbarButton` and port over the changes we made to use the Store that I did previously in https://github.com/mozilla-mobile/fenix/pull/12881

**Comment by gabrielluong** [comment]
Assuming this is a WIP and depends on https://github.com/mozilla-mobile/android-components/issues/2743

**Comment by eliserichards** [comment]
This is not ready for a review yet @ekager :) We have a meeting today with Christian to go over the session manager changes

**Comment by eliserichards** [comment]
Closing this to open a fresh PR

**Pull request closed without merging**
