### PR TITLE
Update Android Components version

### PR DESCRIPTION
**Pull request by MickeyMoz**

### CODE REVIEW

**Comment by pocmo** [comment]
I backed out the plugin upgrade. So hopefully this will just pass now. :)

**Comment by jonalmeida** [comment]
This will fail now with a new breaking API I introduced. Will update this PR now.

**Comment by jonalmeida** [comment]
`audioPlaybackSystemNotificationTest`, `openHistoryItemInNewTabTest`, `tabMediaControlButtonTest`, `videoPlaybackSystemNotificationTest` are failing.

**Comment by jonalmeida** [comment]
I've pushed an updated PR with the breaking changes here, but the media tests are still failing there as well: https://github.com/mozilla-mobile/fenix/pull/15734

**Comment by jonalmeida** [comment]
I'm posting updates in https://github.com/mozilla-mobile/fenix/pull/15734#issuecomment-705099077 so I'll close this issue for now since it has more green CI checks there.

**Pull request closed without merging**
