### PR TITLE
Create SettingsSubMenuDeleteBrowsingDataRobot.kt

### PR DESCRIPTION
**Pull request by carolinemusyoka**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by carolinemusyoka** [comment]
@sv-ohorvath

**Comment by liuche** [comment]
@rpappalax is this something that we want to add? We're getting some extra tests in PRs recently, would like to know what you think. I could also send this to my eng team instead of you next time!

**Comment by liuche** [comment]
@AaronMT what do you think? still necessary and need a rebase or can we close this.

**Comment by AaronMT** [comment]
Ooh missed this. Apollogies @carolinemusyoka, my bad I don't track every single issue that comes in, so many :) 

This Robot looks ok to me, but I'm not sure there's any current usage https://github.com/mozilla-mobile/fenix/blob/aa0b8f65b1ea9e9637ee733917cda66cd6276c4b/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt#L465 is a stubbed out test that hasn't been written. Would you be interested in writing an Espresso test for verifying UI functionality of clearing private data?

**Comment by carolinemusyoka** [comment]
Yeah.
Thanks for the heads up. I'll be interested.

**Comment by liuche** [comment]
Sounds like we'll transfer this work into SettingsPrivacyTest, so I'll close this one (but it will be available to reference).

**Pull request closed without merging**
