### PR TITLE
For #4840: Follow system theme on widget

### PR DESCRIPTION
**Pull request by hakkikaancaliskan**
Follows system theme and if theming not supported (API 21 etc) default is light theme. This pr doesn't change light theme. Just adds dark theme.

For testing: Currently widget doesn't listen system theme changes and updates in 60mins programmatically. So you need to resize widget to update.
### Pull Request checklist

- [x] **Tests**: This PR doesn't test dark theme on widget.
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by hakkikaancaliskan** [comment]
@ekager should we listen system theme changes and apply immediately or wait for itself to update (30 mins)?

**Comment by sblatz** [comment]
We're going to hold off reviewing/landing this until after we cut release since we've had issues with theming in the past. I'll look at this in a bit 😄

**Comment by hakkikaancaliskan** [comment]
> 
> 
> We're going to hold off reviewing/landing this until after we cut release since we've had issues with theming in the past. I'll look at this in a bit 😄

After I did this pr i saw there was another :( i thinked that was committed and deleted. So bad. Select one of them :/
#10209

**Comment by Mugurell** [comment]
> > We're going to hold off reviewing/landing this until after we cut release since we've had issues with theming in the past. I'll look at this in a bit 😄
> 
> After I did this pr i saw there was another :( i thinked that was committed and deleted. So bad. Select one of them :/
> #10209

Thank you for working on this!
I share your excitement for this feature!
But since https://github.com/mozilla-mobile/fenix/pull/10209 predates this I think it's fair to give priority to that PR, I hope you agree also.

Even so, since some time passed between the initial PRs and now I wanted to ask you also if you are still interested into updating this PR with some needed changes in the eventuality that the author of the other PR cannot update it anymore?
The changes I'm thinking of would simply involve using the night qualifier for the new dark themes layouts and so avoid modifying the widget provider with if/else and then focusing on the best approach for automatic refresh when the system theme changes.

**Comment by hakkikaancaliskan** [comment]
> > > We're going to hold off reviewing/landing this until after we cut release since we've had issues with theming in the past. I'll look at this in a bit 😄
> > 
> > 
> > After I did this pr i saw there was another :( i thinked that was committed and deleted. So bad. Select one of them :/
> > #10209
> 
> Thank you for working on this!
> I share your excitement for this feature!
> But since #10209 predates this I think it's fair to give priority to that PR, I hope you agree also.

Yep, of course. You can close this pr if you want.

**Comment by Mugurell** [comment]
Thank you!

**Pull request closed without merging**
