### PR TITLE
Fix 6665 - Improve the alignment of private session text

### PR DESCRIPTION
**Pull request by darkwing**
fix-indent

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by darkwing** [comment]
@lime124 Any thoughts here?

**Comment by lime124** [comment]
thanks for the ping @darkwing. i'm going to ask amy to provide a quick review for you as she's led the effort for private mode features. i'll also check in with bram and make sure needs ux on pull requests are making it into the GH view he's using.

**Comment by AmyYLee** [comment]
@darkwing 

There are a few items missing here
 - 1. Header copy should read “Private tabs”

- 2. Increase line spacing (leading) to 20px in the body copy "Firefox Nightly clears your search and browsing history..." Text should be 14px (please confirm)

- 3. Snackbar colour should be #312A65 (same as light theme) - Can I see a screenshot of the snackbar to confirm correct colour? 

Thanks

**Comment by ekager** [comment]
Ah okay I see #6739 includes a margin change for here as well. Let's close this one for that so it's less confusing

**Pull request closed without merging**
