### PR TITLE
Fix #4419: Do not prefetch the domain public suffix list.

### LINKED ISSUE #4419: [Bug] The fix for #4089 introduces startup performance regression
#4089 invokes `components.utils.publicSuffixList.prefetch()` which causes the instantiation of utilities which triggers the (very) long process of synchronously loading the entire list of search engines.

Not doing this prefetch here will cause the first invocation of `String.urlToTrimmedHost()` to be slower than normal (while that list of public suffixes is loaded). That said, I see no place in the code where that function is called. 

Patch coming. 

cc @csadilek

### PR DESCRIPTION
**Pull request by hawkinsw**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by boek** [comment]
@ekager @sblatz. Can we do this on an IO thread?

**Comment by hawkinsw** [comment]
Talked to @jonalmeida and @csadilek -- do not land, we will land tomorrow (?).

**Comment by hawkinsw** [comment]
> @ekager @sblatz. Can we do this on an IO thread?

We cannot quite do this. If we did the `prefetch()` on an IO thread and then invoked `urlToTrimmedHost` before the `prefetch()` finished, then we will have them both racing to initialize at the same time. This type of race condition is okay if the `prefetch()` is idempotent. Unfortunately, we need to analyze the implementation before making that assessment.

**Comment by boek** [comment]
I'm going to close this for now and we can have the discussion in the ticket :)

**Pull request closed without merging**
