### PR TITLE
For #5304 - Align ETP Onboarding Tool Tip PopupWindow

### PR DESCRIPTION
**Pull request by ekager**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### CODE REVIEW

**Comment by Amejia481** [comment]
For some reason I'm not seeing the popup anymore :(

**Comment by ekager** [comment]
Are you on a fresh install? On fresh install on my pixel 3:
Screenshot_20190913-150121

**Comment by Amejia481** [comment]
Found the issue 🤦‍♂ , I have be on site that have trackers blocked:
image

**Comment by Amejia481** [comment]
It looks awesome, great job!

**Pull request merged**
