### PR TITLE
A-C 57 updates: Topsites, CustomTab search, EngineSession refactoring

### PR DESCRIPTION
**Pull request by csadilek**
Keeping all commits separate so we can back out individually should we have to. We're just combining so we have one build to test on CI (and run the 🐌 toolchain task).

### CODE REVIEW

**Comment by csadilek** [comment]
Argh. Old top sites PR just landed and put this in conflict.

**Comment by csadilek** [comment]
OK, reverted the outdated topsites fix on master here. @gabrielluong @jonalmeida can you chat w/ @MarcLeclair as we now have new API to fetch topsites :).

**Comment by ekager** [comment]
e: /builds/worker/checkouts/src/app/src/test/java/org/mozilla/fenix/tabhistory/TabHistoryControllerTest.kt: (19, 51): Type mismatch: inferred type is SessionManager but BrowserStore was expected
[task 2020-08-26T20:56:34.456Z] e: /builds/worker/checkouts/src/app/src/test/java/org/mozilla/fenix/tabhistory/TabHistoryControllerTest.kt: (19, 65): No value passed for parameter 'sessionManager'

**Comment by csadilek** [comment]
@ekager yes, pushing a fix shortly for the unit test. We just also need to land https://github.com/mozilla-mobile/fenix/pull/14193/ first, because the UI tests also fail. The strict mode violation popup prevent the tests from running.

**Comment by jonalmeida** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by ekager** [comment]
what a trip

**Comment by liuche** [comment]
!!!!!!!

**Comment by csadilek** [comment]
omg 😱

**Pull request merged**
