### PR TITLE
Fix #9461 - Re-trigger taskcluster jobs on dep download fail

### LINKED ISSUE #9461: Provide solution/handler for intermittent taskcluster job dependency download failures
In an effort to better handle intermittent taskcluster job failures, we'd like to address the issue where dependencies temporarily fail to download by retriggering the job. This will handle the most common case where there was a network interruption or momentary service outage (but probably not the case where there was a longer service outage).

@JohanLorenzo mentions we can do this in the following way:
[1] capture exit code returned by gradle 
[2] update the task payload to rerun the task whenever that same exit code is returned 

@JohanLorenzo is there a good example of updating task payload we could follow to implement this?

### PR DESCRIPTION
**Pull request by rpappalax**
Fixes #9461 
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by rpappalax** [comment]
> From a taskgraph point of view, this patch is the right one! I don't know if we need to catch any other exit code. `1` seems quite generic to me and we may end up rerunning genuine failures.
> 
> That said, let's give it a try and see how it goes!

Will do, thanks, @JohanLorenzo!  would there be an `easy` of distinguishing re-running genuine failures vs. a retry (so we wouldn't do that)?  I assume this option quits after x number of attempts?

**Comment by JohanLorenzo** [comment]
When `retry-exit-status` is set, tasks will stop retrying after 5 attempts. I remember the Taskcluster UI shows this counter: click on "See more" on the task view, then the second item shows "Retries left: X of 5". Treeherder doesn't but maybe displays these jobs with a different color (I need to check). 

From a programmatic point of view, I think there's no way to catch a genuine failure from a regular retry.

**Comment by AaronMT** [comment]
I've seen deps fail to fetch on signed builds too.

**Comment by JohanLorenzo** [comment]
Interesting! Do you have a link to one of these failures? I don't think the root causes are the same and I'd like to know what this is about.

**Comment by AaronMT** [comment]
> Interesting! Do you have a link to one of these failures? I don't think the root causes are the same and I'd like to know what this is about.

Not right no, I think when I did (last week) I just rebased to get a new run triggered and things were good from there.

**Pull request merged**
