### PR TITLE
For #4383: Enable dynamic bottom toolbar 

### PR DESCRIPTION
**Pull request by sblatz**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by cadeyrn** [comment]
I tested this PR. I noticed one problem: content which is fixed on the bottom (like a cookie banner on websites like soeren-hentzschel.at) is truncated until you scroll and the browser toolbar hides.

**Comment by ekager** [comment]
Looks like there are some more things we have do here: 
https://github.com/mozilla-mobile/fenix/issues/4383#issuecomment-583671723

Namely tell engineView our toolbar height in fullscreen/not with `setDynamicToolbarMaxHeight`? Not sure if not full screen does this through AC already

**Comment by sblatz** [comment]
I am also seeing what @cadeyrn is seeing with Twitter. Is this something we previously had working?

image

**Comment by darkwing** [comment]
@ekager @boek  I can modify the PR with the comment's suggestion:

```
diff --git a/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt b/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
index f63dc866..343f175c 100644
--- a/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
+++ b/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
@@ -383,12 +383,14 @@ abstract class BaseBrowserFragment : Fragment(), UserInteractionHandler, Session
                             .show()
                         activity?.enterToImmersiveMode()
                         browserToolbarView.view.visibility = View.GONE
+                        engineView.setDynamicToolbarMaxHeight(0)
                     } else {
                         activity?.exitImmersiveModeIfNeeded()
                         (activity as? HomeActivity)?.let { activity ->
                             activity.themeManager.applyStatusBarTheme(activity)
                         }
                         browserToolbarView.view.visibility = View.VISIBLE
+                        engineView.setDynamicToolbarMaxHeight(R.dimen.browser_toolbar_height)
                     }
                 },
                 owner = this,
```

How do I test what this accomplishes?  Outside of this modification, any other remaining tasks?

This works really well, btw.

**Comment by ekager** [comment]
@darkwing I'm not positive but we may have to also add a `setDynamicToolbarMaxHeight` outside of not entering/existing fullscreen in `BaseBrowserFragment.initializeUI` ? We can also ask the GV engineers on Riot what they recommend here.

I would test that entering/exit fullscreen looks normal with the dynamic toolbar and then also that on a site with a bottom banner you are both able to see the bottom banner and dismiss it.

**Comment by darkwing** [comment]
Comments from the GV team on riot:

>  you probably want to look at the EngineView behaviour in a-c: https://github.com/mozilla-mobile/android-components/tree/master/components/feature/session/src/main/java/mozilla/components/feature/session/behavior/EngineViewBottomBehavior.kt

> And maybe: https://github.com/mozilla-mobile/android-components/pull/5404

> (and yes, you definitely need to call setDynamicToolbarMaxHeight

> we need to call setDynamicToolbarMaxHeight(0) when entering fullscreen mode, and restore the value when exiting from the fullscreen mode

**Comment by hiikezoe** [comment]
I just checked the behavior on a build got in [this link](https://firefox-ci-tc.services.mozilla.com/tasks/AtER-KBNSV-_GNWpVinhxQ#artifacts), it seems we don't properly call setDynamicToolbarMaxHeight yet. Doesn't that build including this PR?

**Comment by hiikezoe** [comment]
here is an example to see issues with the dynamic toolbar.  There are two red box, you can see the bottom one is covered by the dynamic toolbar, but it shouldn't be.  If setDynamicToolbarMaxHeight is called properly, the red box is completely in visible area and will be moving along with the dynamic toolbar.

https://bug1610959.bmoattachments.org/attachment.cgi?id=9122794

**Comment by sblatz** [comment]
When I do `setDynamicToolbarMaxHeight` unfortunately we get another weird behavior on sites like Twitter:



This also happens on Reddit which has a popup asking you to download the app.

I'm asking the GV team if this is a known issue

**Pull request merged**
