### PR TITLE
Update Android Components version

### PR DESCRIPTION
**Pull request by MickeyMoz**

### CODE REVIEW

**Comment by ekager** [comment]
Failing on 
e: /builds/worker/checkouts/src/app/src/main/java/org/mozilla/fenix/sync/SyncedTabsLayout.kt: (37, 27): 'when' expression must be exhaustive, add necessary 'NO_TABS_AVAILABLE' branch or 'else' branch instead
[task 2020-06-22T14:28:03.960Z]

**Comment by ekager** [comment]
cc @codrut-topliceanu do you have a WIP for this SyncedTabs change from https://github.com/mozilla-mobile/android-components/issues/7422 ?

**Comment by ekager** [comment]
Closing for #11820

**Comment by codrut-topliceanu** [comment]
@ekager Sorry about that. Some changes were needed to https://github.com/mozilla-mobile/fenix/pull/11634 in order to solve and implement it.

**Pull request closed without merging**
