### PR TITLE
Closes #7861: position text based on layout direction, not on text directionality

### LINKED ISSUE #7861: [Bug][RTL] Potentially don't set automatic direction based on the text directionality, for text across the UI
[Original bug filed under GeckoView by @itiel](https://bugzilla.mozilla.org/show_bug.cgi?id=1608218). Screenshots attached to original bug to demonstrate.

> Currently, (almost) everywhere in the UI the alignment of varios text elements is decided based of the text directionality.
> This usually makes sense, but this an issue where English text actually should appear.
> See the attached screenshots with examples for this.
> 
> While it's possible to address each text element separately, I don't see any reason (well, from RTL POV anyway) not to make the text align to the left for LTR, and to the right for RTL.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-15324)

### PR DESCRIPTION
**Pull request by mavduevskiy**
There is a number of visual issues coming from positioning text according to its direction, ignoring the layout direction. Setting a RTL language makes the design inconsistent, because English text would still appear LTR. Considering orientation over locale could make the UI more consistent. This change is aiming for that.

Was also considering  `android:textDirection="locale"` solution, but it lead to edge cases, where the first strong character of the string would override the direction, so "This time search in:" would become ":This time search in" in RTL mode.

Is part of a general [push](https://github.com/mozilla-mobile/fenix/issues/7861#issuecomment-1352156860) for more RTL support. This patch is focused on the text positioning only. Also fixes [this](https://github.com/mozilla-mobile/fenix/issues/22222) and [this](https://github.com/mozilla-mobile/fenix/issues/21306#issuecomment-1101778924) bugs.

Old|New
---|---
saved_accounts_old|saved_accounts_new
opened_tabs_old|opened_tabs_new
search_engines_old|search_engines_new

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #7861

### CODE REVIEW

**Review by sarah541 — COMMENTED** [review]
We will want to add this to PrivateThemeBase as well

**Comment by mavduevskiy** [comment]
@sarah541 
a keen eye you have! thanks, Sarah!

**Comment by sarah541** [comment]
Although this does solve the bugs mentioned, it may have introduced a new one (please test more and let know). When setting an RTL language, everything looks good, but changing it back to an LTR one, causes the start position same as RTL start position. Screenshots may help better understand.
|

**Comment by mavduevskiy** [comment]
@sarah541 
I believe you are mentioning a bug I am fixing [here](https://github.com/mozilla-mobile/fenix/pull/28343): layout isn't redrawn after switching between RTL/LTR without restarting the app. 

It wasn't introduced with this patch though, sadly it looks like switching between RTL/LTR  never worked correctly.

**Review by sarah541 — APPROVED** [review]

**Pull request merged**
