### PR TITLE
Closes #9293: Fix toggleSearchSuggestions UI test

### LINKED ISSUE #9293: Intermittent UI test failure - SettingsBasicsTest.toggleSearchSuggestions UI test
This test relies on network access to fetch search suggestions (e.g, "mozilla") which can be intermittent based on network. The test should wait for async background operations.

fails with the following error: `The suggestion count is less than or equal to the minimum suggestions`

firebase log: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5749887503750778646/executions/bs.6b67056cb14d27ab/testcases/1/test-cases

### PR DESCRIPTION
**Pull request by AaronMT**
Trying out a RecyclerViewIdlingResource for `toggleSearchSuggestions`. Will run a few times to see if it sticks.

### CODE REVIEW

**Comment by AaronMT** [comment]
On Firebase, this is hitting: 

`java.lang.RuntimeException: No activities found. Did you forget to launch the activity by calling getActivity() or startActivitySync or similar?
`

Is this because I see

"04-17 14:04:57.156: D/LifecycleMonitor(9441): Lifecycle status change: org.mozilla.fenix.HomeActivity@8cedf25 in: DESTROYED"

Which is the activity in test?

**Comment by ekager** [comment]
Sorry for the delay @AaronMT ! If you rebase on latest master are you still hitting the same issue?

**Comment by liuche** [comment]
@AaronMT I think we've fixed a lot of these crashes recently, so if you could rebase let's see how that looks!

**Comment by boek** [comment]
rebased

**Comment by AaronMT** [comment]
Might need more work as it still fails in the rebase run. Not a priority at the moment.

**Comment by boek** [comment]
@AaronMT it passed on CI. I'm going to land and we can re-add the ignore if it fails again.

**Comment by boek** [comment]
@AaronMT sound good. I'm going to close the PR for now. Feel free to re-open when you want to land it.

**Pull request closed without merging**
