### PR TITLE
For #20229 - Use the AC common implementation for ads/search telemetry

### PR DESCRIPTION
**Pull request by Mugurell**
Everything should work exactly as before.

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by Mugurell** [comment]
# Request for Data Collection Renewal

1) Provide a link to the initial Data Collection Review Request for this collection.
https://github.com/mozilla-mobile/fenix/pull/10112#issuecomment-617703289
2) When will this collection now expire?
2022-07-01
3) Why was the initial period of collection insufficient?
This measure will continue to help Mozilla better understand revenue trends and (potentially) aids future forecasting.

**Comment by Mugurell** [comment]
Setting `do-not-land` to update the metrics documentation with the telemetry renewal review first.

**Comment by travis79** [comment]
> # Request for Data Collection Renewal
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        [Feature/#6558 Ad click attribution #10112 (comment)](https://github.com/mozilla-mobile/fenix/pull/10112#issuecomment-617703289)
> 
>     2. When will this collection now expire?
>        2022-07-01
> 
>     3. Why was the initial period of collection insufficient?
>        This measure will continue to help Mozilla better understand revenue trends and (potentially) aids future forecasting.

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

**Review by csadilek — APPROVED** [review]
👍

**Pull request merged**
