### PR TITLE
For #17904: Resized to private shortcut button

### PR DESCRIPTION
**Pull request by fevziomurtekin**
Hi! I resized to private shortcut button. You can see this change from the picture

Screen Shot 2021-02-13 at 13 24 44

### CODE REVIEW

**Comment by Mugurell** [comment]
Thank you @fevziomurtekin for looking into this!

Asking UX to confirm we want this changes.
| Before | After |
| ----------- | ----------- |
| Screenshot 2021-02-19 at 17 59 23 | image |

**Comment by Mugurell** [comment]
@fevziomurtekin if you want to leave a small comment in the ticket I can assign it to you.

**Comment by fevziomurtekin** [comment]
Thank you @Mugurell I've no comment.

**Comment by Mugurell** [comment]
Thank you for helping with this but looks like another PR was approved and confirmed by UX in the meantime.
Closing this but feel free to pick other tickets to work on .

**Pull request closed without merging**
