### PR TITLE
Run ci for 27521

### LINKED ISSUE #27522: [UI test automation] Improve coverage of the search test suite
### Summary
Improve coverage of the search test suite :
• Create new UI tests
• Add missing steps

### PR DESCRIPTION
**Pull request by Mugurell**
Run CI tasks for https://github.com/mozilla-mobile/fenix/pull/27521 which is ready to land.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #27522

### CODE REVIEW

**Comment by Mukuljangir372** [comment]
Hey @Mugurell, Can you please tell me why I'm getting this error? 
The `allowPullRequests` configuration for this repository (in `.taskcluster.yml` on the
default branch) does not allow starting tasks for this pull request.

**Comment by Mugurell** [comment]
> Hey @Mugurell, Can you please tell me why I'm getting this error? The `allowPullRequests` configuration for this repository (in `.taskcluster.yml` on the default branch) does not allow starting tasks for this pull request.

Like discussed here - https://github.com/mozilla-mobile/fenix/pull/27567#issuecomment-1294766679 certain CI tasks - long running / time consuming / expensive will only run for specific contributors.
All CI tasks are required to have run before merging so the official team working on the project will help with running all CI tasks for external contributors by resubmitting the same commits in their PRs like I've done here.

**Comment by Mukuljangir372** [comment]
@Mugurell Then, what should I do next? Is have to do anything further so that PR can merged.

**Comment by Mugurell** [comment]
> @Mugurell Then, what should I do next? Is have to do anything further so that PR can merged.

The reviewer of your PR will help you with everything needed for landing.

**Comment by Mugurell** [comment]
Seems like the PR is stucked at "Queue: Embarked in merge train".
Closing the PR to unblock other merges.

**Pull request closed without merging**
