### PR TITLE
For #21294: remove allocations from Fact.toEvent (second simpler PR)

### PR DESCRIPTION
**Pull request by mcomella**
This comment is copied from the primary commit in this series:

> This commit was generated primarily by a macro that:
> - appends `== component &&`
> - appends `== item`
> - (if applicable) Skips to the ending brace
> - Go down one line and move cursor to the front of the line to prep for repeat
> 
> My only intervention was to skip extra lines to line it up to run again
> and specify how many times in a row it should run.
> 
> ---
> 
> The `to` in this code is an infix function that calls instantiates a
> Pair under the hood. Subjectively observed, when this method is called
> it generally hits the else case so 35 Pairs are instantiated each call -
> that's 560 bytes. This method is called frequently - for example, an estimated
> 4 times each time a letter is typed on the homescreen and a measured 116 times
> in a simple navigation (see the issue). The latter generates an estimated
> 63.4 KiB.
> 
> It was straightforward to remove these allocations so that's what this
> change does.
> 
> The primary risk from this change is that it's difficult to test each
> case to ensure it's working.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by pocmo — APPROVED** [review]

**Comment by mcomella** [comment]
Part of the test failure seems like intemittent https://github.com/mozilla-mobile/fenix/issues/21534. Rerunning.

**Comment by mcomella** [comment]
Seems like another intermittent: `SettingsBasicTest.changeAccessibiltySettings`. Rerunning...

**Comment by mcomella** [comment]
Intermittent in FenixSnackbarDelegateTest. Rerunning...

**Comment by pocmo** [comment]
All checks are green, but mergify doesn't merge because of "`linear-history` [🛡 GitHub branch protection]" not being checked. We saw that in the Focus repository happen too. In the past mergify would just rebase the PR and then merge, but now that PR is not even in the queue.

**Pull request merged**
