### PR TITLE
Add Arabic strings.xml

### PR DESCRIPTION
**Pull request by ibrahimAlii**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by pocmo** [comment]
@ibrahimAlii Thank you for helping us to translate the app! Unfortunately we can't merge this PR since we do not translate the app in this repository. Instead we use Pontoon and translations get merged into this repository automatically:

https://pontoon.mozilla.org/projects/android-l10n/

@Delphine @Pike Do we have documentation about how to join the L10N community and get new locales added? :)

@ibrahimAlii Since Arabic would be the first RTL locale we support: Did you notice any issues with RTL support? Please feel free to file issues in this repository! :)

**Comment by Pike** [comment]
When we add Arabic to Fenix, we should use the file here to bootstrap the localization in mozilla-l10n/android-l10n, so there won't be any work wasted.

**Comment by ibrahimAlii** [comment]
@pocmo uh, I didn't know that.

AND yes there are some issues related to text/icon appearance i.e:



The Issue related to the **text** itself, latin chars start from left, btw arabic/hebrew/persians etc.. start from right.
So I think once the text itself become arabic, the issue will be solved.

**Comment by Delphine** [comment]
@pocmo Could I edit the Readme for Fenix and a-c repos, to add a note saying that localization happens on Pontoon in the android-l10n project? (https://pontoon.mozilla.org/projects/android-l10n/). Also adding a link to our documentation, that could be helpful to insert as well: https://mozilla-l10n.github.io/localizer-documentation/

**Comment by pocmo** [comment]
Sure absolutely!

**Comment by Delphine** [comment]
@pocmo Any objection to add RTL locales to Fenix/Firefox Preview at this point? I think it could be a good testing ground for this, and help us get in a better state once we release. Let me know what your priorities are and if this could be helpful. Thanks!

**Comment by pocmo** [comment]
CC @liuche 

We should definitely add it to our planning. In Focus we found quite some issues. We haven't yet ported over the mechanism to have languages that do not go into the release version yet - that may be helpful until we are happy with the result on Nightly.

**Comment by liuche** [comment]
Currently in our roadmap we have this as a "Should" for Q3.

**Pull request closed without merging**
