### PR TITLE
For #20257 - Sets min no. of grid columns to 2 in TabsTray

### PR DESCRIPTION
**Pull request by codrut-topliceanu**
For https://github.com/mozilla-mobile/fenix/issues/20257
### Pull Request checklist

- [x] **Tests**: This PR includes no tests as it's only a minor change.
- [x] **Screenshots**: This PR includes screenshots.
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md).

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

image

### CODE REVIEW

**Comment by Mugurell** [comment]
The thumbnails shown in the screenshot are very blurry.
Is that only from setting the minimum number of columns to be two? 😏

**Comment by codrut-topliceanu** [comment]
@Mugurell 😆 No, that's from the low dpi emulator used.

**Comment by jonalmeida** [comment]
Looks like [the old code](https://github.com/mozilla-mobile/fenix/blob/v86.1.1/app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt#L468) defaulted to 2 columns as well, but this was missed during the refactor. Thank you for catching and fixing this!

Could you update/add a test to avoid this regression from happening again?

**Comment by codrut-topliceanu** [comment]
> Looks like [the old code](https://github.com/mozilla-mobile/fenix/blob/v86.1.1/app/src/main/java/org/mozilla/fenix/tabtray/TabTrayView.kt#L468) defaulted to 2 columns as well, but this was missed during the refactor. Thank you for catching and fixing this!

Sooo... no need for UX-feedback in that case right?

I'll get started on those tests.

**Comment by codrut-topliceanu** [comment]
😄 🙏 @jonalmeida

**Review by jonalmeida — APPROVED** [review]
✅✅

**Pull request merged**
