### PR TITLE
Bug 1784122 - Add non-fission variant for Fenix perf tests.

### PR DESCRIPTION
**Pull request by gmierz**
This patch adds the non-fission variants for Fenix performance tests. Currently they are all running with Fission enabled.

### CODE REVIEW

**Comment by gmierz** [comment]
Tasks selected are expected: https://firefoxci.taskcluster-artifacts.net/UQVo724wTbqWVWveljzLYA/0/public/target-tasks.json

Note how the youtube-playback tests only run with fission disabled which is expected. Only the tp6m tests should be running with fission enabled.

See here for the test runs: https://github.com/mozilla-mobile/fenix/runs/7994028377

**Comment by gmierz** [comment]
I'm not sure why the tests failed, but I think it might have something to do with how I made the PR in a fork. I don't think this patch could cause the signing builds to fail.

**Review by escapewindow — APPROVED** [review]
Looks reasonable, and it looks like the tests passed.

**Comment by gmierz** [comment]
Thanks for the review @escapewindow!

**Pull request merged**
