### PR TITLE
For #21313: Renew product telemetry expiring in December

### PR DESCRIPTION
**Pull request by eliserichards**
For #21313

- [x] Product approval - see [doc](https://docs.google.com/document/d/1NGlnTa9TPyTnd3ciUPbwujbITjkX8p8vJybXcZrrM2w/edit#)
- [x] data review
- [x] update data review TBDs in PR

This PR renews product telemetry probes for the month of December (no product renewals for november). See other related PRs for Nov/Dec telemetry:
* [Removing unused/unneeded probes](https://github.com/mozilla-mobile/fenix/pull/21789)
* Update probes to [never expire](https://github.com/mozilla-mobile/fenix/pull/21788)
* [Perf renewals](https://github.com/mozilla-mobile/fenix/pull/21315) 
* [Fission renewals](https://github.com/mozilla-mobile/fenix/pull/21779)

## Breakdown of renewal dates
Grand total: 45

### Renew for 1 year
Total: 21
- `error_page` (1)
  - `visited_error` 
- `collections` (13)
  - `renamed` 
  - `tab_restored` 
  - `all_tabs_restored` 
  - `tab_removed`  
  - `shared` 
  - `removed` 
  - `saved` 
  - `tabs_added`  
  - `tab_select_opened` 
  - `add_tab_button` 
  - `long_press`  
  - `save_button` 
  - `rename_button` 
- `app_theme`(1)
  - `dark_theme_selected` 
- `browser_menu_action` (1) 
- `preference_toggled` (1) 
- `whats_new_tapped` (1)
- `synced_tab_opened` (1) 
- `copy_url_tapped` (1) 
- `browser_toolbar_home_tapped` (1) 

### Renew for 8 mo
Total: 15
- `bookmarks_management` (12)
  - `open_in_new_tab` 
  - `open_in_new_tabs` 
  - `open_in_private_tab` 
  - `open_in_private_tabs` 
  - `edited`
  - `moved` 
  - `removed` 
  - `multi_removed` 
  - `shared` 
  - `copied` 
  - `folder_add` 
  - `folder_remove`  
- `addons` (3)
  - `open_addons_in_settings` 
  - `open_addon_in_toolbar_menu` 
  - `enabled_addons` 

### Renew for 6 mo
Total: 9
- `recently_closed_tabs_opened` (1) 
- `context_menu`(1)
  - `item_tapped` 
- `custom_tab`(3)
  - `closed` 
  - `menu`
  - `action_button` 
- `contextual_menu`(4)
  - `copy_tapped` 
  - `search_tapped` 
  - `select_all_tapped` 
  - `share_tapped` 

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by travis79** [comment]
> # Request for Data Collection Renewal
> 
>  Grand total: 45 renewals
> ## Renew for 1 year
> 
> Total: 21
> 
> `error_page`
> 
>     * `visited_error`
> 
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #1242: Adds telemetry for error pages #2491 (comment)](https://github.com/mozilla-mobile/fenix/pull/2491#issuecomment-492414486)
> 
>     2. When will this collection now expire?
>        
>        * This probe will now expire in December 2022 (one year).
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This probe helps the engineering team with triage and monitoring
> 

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

> `collections` (9)
> 
>     * `renamed`
> 
>     * `tab_restored`
> 
>     * `all_tabs_restored`
> 
>     * `tab_removed`
> 
>     * `shared`
> 
>     * `removed`
> 
>     * `saved`
> 
>     * `tabs_added`
> 
>     * `tab_select_opened`
> 
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #969: Adds telemetry for collections #3935](https://github.com/mozilla-mobile/fenix/pull/3935)
> 
>     2. When will this collection now expire?
>        
>        * These probes will now expire in December 2022 (one year).
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * These metrics will be important for our 2022 strategic focus.
> 

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

> `collections` (cont.)(3)
> 
>     * `add_tab_button`
> 
>     * `long_press`
> 
>     * `save_button`
> 
>     * `rename_button`
> 
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [ For #969: Adds more telemetry for collections  #4358](https://github.com/mozilla-mobile/fenix/pull/4358)
> 
>     2. When will this collection now expire?
>        
>        * This probe will now expire in December 2022 (one year).
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * These metrics will be important for our 2022 strategic focus.
> 

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

> `collections` (cont.)
> 
>     * `rename_button`
> 
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #969: Adds more telemetry for collections #4539](https://github.com/mozilla-mobile/fenix/pull/4539)
> 
>     2. When will this collection now expire?
>        
>        * This probe will now expire in December 2022 (one year).
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This metric will be important for our 2022 strategic focus.
> 

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

> `app_theme`
> 
>     * `dark_theme_selected`
> 
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #7289: Adds telemetry for selecting dark theme #7968](https://github.com/mozilla-mobile/fenix/pull/7968)
> 
>     2. When will this collection now expire?
>        
>        * This probe will now expire in December 2022 (one year).
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This metric helps us make decisions around personalization. It will also be useful for our 2022 strategic focus.
> 

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

> `browser_menu_action`
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Adds Metrics for Crash reporter and browser menu items #1214 (comment)](https://github.com/mozilla-mobile/fenix/pull/1214#issue-264756708)
> 
>     2. When will this collection now expire?
>        
>        * This probe will now expire in December 2022 (one year).
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This is part of the core browser functionality and helps us understand usage patterns and make UX decisions.
> 

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

> `preference_toggled`
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #975: Adds telemetry for settings toggles #1896](https://github.com/mozilla-mobile/fenix/pull/1896)
> 
>     2. When will this collection now expire?
>        
>        * This probe will now expire in December 2022 (one year).
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This metric helps us make decisions around personalization and helps us understand user preferences.
> 

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

> `whats_new_tapped`
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #5021: Adds metric for what's new button #5090](https://github.com/mozilla-mobile/fenix/pull/5090)
> 
>     2. When will this collection now expire?
>        
>        * This probe will now expire in December 2022 (one year).
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This probe will help us evaluate if we need to add additional “what’s new” entry points.
> 

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

> `synced_tab_opened`
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #15369: Add synced tabs metrics. #16727](https://github.com/mozilla-mobile/fenix/pull/16727)
> 
>     2. When will this collection now expire?
>        
>        * This probe will now expire in December 2022 (one year).
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This is a foundational metric that helps us understand our cross-device strategy.
> 

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

> `copy_url_tapped`
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #16827: Add telemetry for copy url. #16915](https://github.com/mozilla-mobile/fenix/pull/16915)
> 
>     2. When will this collection now expire?
>        
>        * This probe will now expire in December 2022 (one year).
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This probe will help us evaluate search bar optimization in the future.
> 

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

> `browser_toolbar_home_tapped`
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #19915: Add telemetry for the toolbar Home screen button. #19936](https://github.com/mozilla-mobile/fenix/pull/19936)
> 
>     2. When will this collection now expire?
>        
>        * This probe will now expire in December 2022 (one year).
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This probe is necessary to evaluate MR2 success.
> 

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

> ## Renew for 8 months
> 
> Total: 15
> 
> `bookmarks_management` (11)
> 
>     * `open_in_new_tab`
> 
>     * `open_in_new_tabs`
> 
>     * `open_in_private_tab`
> 
>     * `open_in_private_tabs`
> 
>     * `edited`
> 
>     * `moved`
> 
>     * `removed`
> 
>     * `multi_removed`
> 
>     * `shared`
> 
>     * `copied`
> 
>     * `folder_add`
> 
>     * `folder_remove`
> 
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #974: Telemetry for Bookmarks #1708](https://github.com/mozilla-mobile/fenix/pull/1708)
> 
>     2. When will this collection now expire?
>        
>        * These probes will now expire in August 2022 (2022-08-01). We are renewing them for 8 months instead 6 months so that we can align the dates with the rest of the `bookmark_management` probes.
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * These metrics will be important for our 2022 strategic focus and cross-device design alignment.
> 

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

> `bookmarks_management` (1) (cont.)
> 
>     * `folder_remove`
> 
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #3174: Adds telemetry for bookmarks #3724](https://github.com/mozilla-mobile/fenix/pull/3724)
> 
>     2. When will this collection now expire?
>        
>        * These probes will now expire in August 2022 (2022-08-01). We are renewing them for 8 months instead 6 months so that we can align the dates with the rest of the `bookmark_management` probes.
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This metric will be important for our 2022 strategic focus and cross-device design alignment.
> 

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

> `addons` (2)
> 
>     * `open_addons_in_settings`
> 
>     * `open_addon_in_toolbar_menu`
> 
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #6174 - Add telemetry for WebExtensions #8318](https://github.com/mozilla-mobile/fenix/pull/8318)
> 
>     2. When will this collection now expire?
>        
>        * These probes will now expire in August 2022 (2022-08-01). We are renewing them for 8 months instead 6 months so that we can align the dates with the rest of the `addons` probes.
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * These probes will help us with future UX optimizations.
> 

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

> `addons` (cont.)
> 
>     * `enabled_addons`
> 
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #8920 - [Telemetry] Send add-on ids in a metrics ping #11080](https://github.com/mozilla-mobile/fenix/pull/11080)
> 
>     2. When will this collection now expire?
>        
>        * This probe will now expire in August 2022 (2022-08-01). We are renewing them for 8 months instead 6 months so that we can align the dates with the rest of the `addons` probes.
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * These probes will help us with future UX optimizations and helps us understand our contributions to the Firefox ecosystem.
> 

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

> ## Renew for 6 months
> 
> Total: 9
> 
> `recently_closed_tabs_opened`
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #15366: Add recently closed tabs metrics. #16739](https://github.com/mozilla-mobile/fenix/pull/16739)
> 
>     2. When will this collection now expire?
>        
>        * This probe will now expire in June 2022 (2022-06-01).
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This probe is for an MR2 feature and has not been evaluated yet.
> 

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

> `context_menu`
> 
>     * `item_tapped`
> 
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Adds Telemetry for Context Menu and Find in page #1344 (comment)](https://github.com/mozilla-mobile/fenix/pull/1344#issuecomment-479285010)
> 
>     2. When will this collection now expire?
>        
>        * This probe will now expire in June 2022 (2022-06-01).
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * This probe is important for “Share” projects that are ongoing.
> 

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

> `custom_tab`(3)
> 
>     * `closed`
> 
>     * `menu`
> 
>     * `action_button`
> 
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Closes #977: Adds telemetry for custom tabs #1697](https://github.com/mozilla-mobile/fenix/pull/1697)
> 
>     2. When will this collection now expire?
>        
>        * This probe will now expire in June 2022 (2022-06-01).
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * These probes are actively being used to evaluate default browser changes.
> 

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

> `contextual_menu`(4)
> 
>     * `copy_tapped`
> 
>     * `search_tapped`
> 
>     * `select_all_tapped`
> 
>     * `share_tapped`
> 
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #11580 - Tracks text selection context menu usage #16968](https://github.com/mozilla-mobile/fenix/pull/16968)
> 
>     2. When will this collection now expire?
>        
>        * This probe will now expire in June 2022 (2022-06-01).
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * These probes are important for “Share” projects that are ongoing.

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

**Comment by eliserichards** [comment]
Updating this PR since these two updates ([1](https://github.com/mozilla-mobile/fenix/pull/21038), [2](https://github.com/mozilla-mobile/fenix/pull/21788)) have made a lot of these "never expire"

**Review by rocketsroger — APPROVED** [review]

**Comment by rocketsroger** [comment]
@Mergifyio backport releases_v95.0.0

**Comment by rocketsroger** [comment]
@Mergifyio backport releases_v94.0.0

**Pull request merged**
