### PR TITLE
For #15707: enable lint test CI; write a few lint tests

### PR DESCRIPTION
**Pull request by mcomella**
@JohanLorenzo Can you help review the changes to the taskcluster files? I want the tests to run from the custom lint rules Gradle modules.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by JohanLorenzo — APPROVED** [review]
The taskcluster changes look correct to me 😃👍 

I see both the deteck and the regular lint task got the changes:
 * https://firefox-ci-tc.services.mozilla.com/tasks/UNzwMqKmRBmNF4Do2toDvQ/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FUNzwMqKmRBmNF4Do2toDvQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L214
 * https://firefox-ci-tc.services.mozilla.com/tasks/VKzGPgBqTcqC2wMvTWhBBg/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FVKzGPgBqTcqC2wMvTWhBBg%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L706

If I understand the patch correctly, the new command may have a different set of maven dependencies. If so, I'd recommend to update https://github.com/mozilla-mobile/fenix/blob/c40b93715fc890d006933d0585ffd07618fe2c4c/taskcluster/scripts/toolchain/android-gradle-dependencies.sh#L24 too. This command line populates the gradle cache that further builds use.

**Review by MarcLeclair — APPROVED** [review]
Looks good to me

**Comment by mcomella** [comment]
> If I understand the patch correctly, the new command may have a different set of maven dependencies. If so, I'd recommend to update

@JohanLorenzo Thanks for the note – I updated the script if you wanted to skim. I'm also not sure how to test this. I added the following note to the extended commit summary:
> `assemble` doesn't assemble the tests so we need to run `test`.
`testClasses` isn't good enough because, according to `--profile`, it
doesn't include dependencies for `testRuntimeClasspath`.

**Comment by mcomella** [comment]
Task failure via timeout. Strangely, it seems to be splicing in some downloads into the tests:
>[task 2020-10-28T00:38:38.160Z] java.lang.OutOfMemoryError: Java heap space
[task 2020-10-28T00:38:38.160Z] 	at org.robolectric.res.android.FileMap.getDataPtr(FileMap.java:253)
[task 2020-10-28T00:38:38.162Z] 	at org.robolectric.res.android.Asset$_FileAsset.openChunk(Asset.java:736)
...
[task 2020-10-28T00:38:38.204Z]   TEST: isKeyboardVisible returns false when the keyboard height is less than or equal to the minimum threshold
[task 2020-10-28T00:38:38.205Z]     Downloading from maven
[task 2020-10-28T00:38:39.157Z]     Downloading: org/robolectric/android-all/5.1.1_r9-robolectric-r2/android-all-5.1.1_r9-robolectric-r2.pom from repository sonatype at https://oss.sonatype.org/content/groups/public/
[task 2020-10-28T00:38:40.857Z]     Transferring 2K from sonatype
[task 2020-10-28T00:38:42.257Z]     Downloading: org/robolectric/android-all/5.1.1_r9-robolectric-r2/android-all-5.1.1_r9-robolectric-r2.jar from repository sonatype at https://oss.sonatype.org/content/groups/public/
[task 2020-10-28T00:38:42.957Z]     Transferring 56086K from sonatype

Not sure what's up with that. Let's try re-running.

**Comment by mcomella** [comment]
```
[task 2020-10-28T17:57:39.347Z] SUITE: org.mozilla.fenix.ext.ContextTest
[task 2020-10-28T17:57:40.646Z]   TEST: initializationError
[task 2020-10-28T17:57:41.847Z]   FAILURE
[task 2020-10-28T17:57:41.847Z] 
[task 2020-10-28T17:57:41.847Z] java.lang.OutOfMemoryError: GC overhead limit exceeded
[task 2020-10-28T17:57:41.847Z] 
[task 2020-10-28T17:57:41.847Z] 
[task 2020-10-28T17:57:41.847Z] SUITE: org.mozilla.fenix.ext.NavControllerTest
[task 2020-10-28T17:57:41.847Z]   TEST: Test record id exception fun
[task 2020-10-28T17:57:43.846Z]     Oct 28, 2020 5:57:43 PM io.mockk.impl.log.JULLogger warn
[task 2020-10-28T17:57:43.846Z]     WARNING: Failed to transform class androidx/navigation/NavOptions
[task 2020-10-28T17:57:43.846Z]     java.lang.OutOfMemoryError: GC overhead limit exceeded
[task 2020-10-28T17:57:43.846Z]     
[task 2020-10-28T17:57:53.747Z]   FAILURE
[task 2020-10-28T17:57:53.747Z] 
[task 2020-10-28T17:57:53.747Z] java.lang.OutOfMemoryError: GC overhead limit exceeded
[task 2020-10-28T17:57:53.747Z] 
[task 2020-10-28T17:57:53.747Z]   TEST: Nav with id, directions, and options args
[taskcluster:error] Task timeout after 7200 seconds. Force killing container.
```

This seems unrelated to my change... Maybe I'll rebase on master.

**Comment by mcomella** [comment]
Similar error:
```
[task 2020-10-28T21:55:39.378Z] java.lang.OutOfMemoryError: GC overhead limit exceeded
[task 2020-10-28T21:55:39.379Z] 
[task 2020-10-28T21:55:39.379Z] 
[task 2020-10-28T21:55:39.380Z] SUITE: org.mozilla.fenix.ext.ImageButtonTest
[task 2020-10-28T21:55:39.381Z]   TEST: Remove and disable
[task 2020-10-28T21:55:39.382Z]     [Robolectric] org.mozilla.fenix.ext.ImageButtonTest.Remove and disable: sdk=28; resources=BINARY
[taskcluster:error] Task timeout after 7200 seconds. Force killing container.
```

I see a similar failure on master: https://github.com/mozilla-mobile/fenix/runs/1327191814 I'm guessing we need to increase the memory available to our TC instances or there is a crazy memory leak in our test frameworks.

**Comment by mcomella** [comment]
> I see a similar failure on master: https://github.com/mozilla-mobile/fenix/runs/1327191814 I'm guessing we need to increase the memory available to our TC instances or there is a crazy memory leak in our test frameworks.

I filed https://github.com/mozilla-mobile/fenix/issues/16262

**Comment by mcomella** [comment]
Let's try rebasing.

**Pull request merged**
