### PR TITLE
Closes #5913: Add new sessionToken scope

### LINKED ISSUE #5913: Manage Account: declare sessionToken scope during FxA initialization
We need a new sessionToken scope in order to enable "Manage Account" functionality in Fenix's Account Settings.

For existing FxA users, introduction of this scope will be a non-issue, until they will need to interact with upcoming "Manage Account" functionality (a button, which opens up FxA web-content and passes it the sessionToken via webchannel). Once that happens, we will need to trigger a "need to re-authenticate" state. This is unfortunate, but the alternative is worse - triggering that state for everyone upon introduction of this scope. See a-c where this work is tracked: https://github.com/mozilla-mobile/android-components/issues/4703

### PR DESCRIPTION
**Pull request by vladikoff**
Relanding https://github.com/mozilla-mobile/fenix/pull/5914

@grigoryk r?

### CODE REVIEW

**Comment by grigoryk** [comment]
Still seems to crash in @vladikoff 's local testing.

**Comment by grigoryk** [comment]
@vladikoff any updates on this?

**Comment by vladikoff** [comment]
> @vladikoff any updates on this?

We should probably wait for Firefox 71. 

@rfk do you have any other ideas? I am wondering if we can do something to "handle" crashes that happen if the OAuth `code` cannot be exchanged.

**Comment by grigoryk** [comment]
I'm fine with waiting for 71 (a month from now).

**Comment by rfk** [comment]
> I'm fine with waiting for 71 (a month from now).

Depends how we feel about the experience on ESR.

The reason this is a problem on 70 but not 71, is that 70 uses BrowserID assertions for authorizing OAuth codes, while 71 directly uses its sessionToken. Since BrowserID assertions don't tell you what sessionToken was used to generate them, we can't track the sessionToken info through the OAuth code grant and use it to generate a cloned session on the other side.

ow that danny has landed phase 2 of the auth/oauth server merger, it's possible that we could do something more clever on the server-side here. For example, I believe BrowserID assertions embed the originating deviceId, we might be able to use that to look up the sessionToken that should be associated with a particular OAuth code.

Alternately, when claiming the code, the server could detect the case where we can't generate a sessionToken and could remove it from the list of granted scopes, rather than failing the whole request. The client would need to be prepared to handle the case where it doesn't get granted all the scopes it requested, but OAuth clients should in theory be prepared for that at any time.

**Comment by vladikoff** [comment]
@grigoryk Rebased!

**Pull request merged**
