### PR TITLE
For #17904: resized add shortcut button

### PR DESCRIPTION
**Pull request by liacds**
Add shortcut button size looks like this now
Screenshot_1617220812
and accessibility scan doesn't produce any suggestions for the button
Screenshot_1617220798

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by eliserichards — APPROVED** [review]
Great job! 🚀

**Comment by gabrielluong** [comment]
Let's get a UX review from @topotropic or @brampitoyo since there's screenshots.

**Comment by topotropic** [comment]
Thanks for the ping! If this is a problem with the button here, it might be a problem in other places as well. Our component in Figma has a height of 36dp – I remember that Sawyer worked on componentizing buttons at some point last year, so it would be great if we could systematically solve this and not just increase the size of the button here to fix this single case.

**Comment by liacds** [comment]
> Thanks for the ping! If this is a problem with the button here, it might be a problem in other places as well. Our component in Figma has a height of 36dp – I remember that Sawyer worked on componentizing buttons at some point last year, so it would be great if we could systematically solve this and not just increase the size of the button here to fix this single case.

Hi again! I would like to look into this, but I would need some guidance as to how to tackle this issue.

**Comment by brampitoyo** [comment]
@liacds I am working together with @gabrielluong to resolve this problem, and the approach that I was thinking of taking, is to introduce 6dp “padding” on top and bottom. They’re invisible, but they can still be tapped. By doing this, we’ll increase the tappable area to 48dp, while keeping the button height 36dp.

But I’m not sure whether Android gives us the ability to extend tappable area past the content area itself?

**Review by eliserichards — CHANGES_REQUESTED** [review]
Let's try @topotropic's suggestion and make the tappable area bigger while keeping the same visual "size" of the button

**Comment by boek** [comment]
Closing in favor of #28056

**Pull request closed without merging**
