### PR TITLE
Remove deprecated success path for Firefox Accounts login

### PR DESCRIPTION
**Pull request by vladikoff**
Requires https://github.com/mozilla-mobile/android-components/pull/2678 SNAPSHOT
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by vladikoff** [comment]
> Is this a real error or do I just need to dump the build cache to get a newer Android Components?

waiting for cache

**Comment by boek** [comment]
@vladikoff after your changes landed in A-C was a new snapshot built?

**Comment by vladikoff** [comment]
Yea so it turned green here: https://github.com/mozilla-mobile/reference-browser/pull/705 a few minutes ago, I'm pushing this branch again, hoping it would also turn green!

**Comment by boek** [comment]
@vladikoff I just dumped the bitrise cache again to be safe :)

**Comment by boek** [comment]
@vladikoff There we go! :D

**Comment by vladikoff** [comment]
yay!

**Comment by vladikoff** [comment]
Thank you for merging my PR!

Thank you!

**Comment by ekager** [comment]
Thanks for the dog gif :)

**Pull request merged**
