### PR TITLE
[Perf/22682 navigation kotlin dsl

### LINKED ISSUE #22862: Try switching to Navigation library Kotlin DSL (35ms COLD start improvement?)
For cold start up, we identified the Navigation library takes 35ms on a Moto G5 (via profiler) to inflate the nav graph XML: see https://issuetracker.google.com/issues/181320543. It turns out there is a Kotlin DSL to perform the same operation that theoretically take much less time: https://developer.android.com/guide/navigation/navigation-kotlin-dsl We should implement it as a prototype and measure the difference in start up.

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/FNXV2-18933)

### PR DESCRIPTION
**Pull request by RotBolt**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

closes #22862 

Fixes #22682
Fixes #22682

### CODE REVIEW

**Comment by RotBolt** [comment]
cc @mcomella @Amejia481 
I am making a draft PR for now for visibility. I have lay down the foundation
Next step is to integrate which I will do in next commits and the profile it
will be pushing into this only for next commits.

**Comment by RotBolt** [comment]
I will fix the commit message to fix the issue number in the next commit. Will edit the previous commit

**Comment by RotBolt** [comment]
Hi @Amejia481 @mcomella 
Can you take a look at this draft PR and have a look over my query here 
https://matrix.to/#/!nJKrjaXIWSApOYfJfv:mozilla.org/$s8fkSAP0_JKqCVCAMc2TMRNrDGWtItwfLdLpCeS3Ovg?via=mozilla.org&via=matrix.org&via=kde.org



since we are just trying to profile Navigation Kotlin DSL, I think just creating a graph and measuring it's time should be enough

Integrating each navigation would be humongous task IMHO

For integration, I have pushed commits on how integration might look like

**Comment by csadilek** [comment]
Thanks @RotBolt for your contributions, and sorry for the long delay here. We're getting ready to migrate this repo to https://github.com/mozilla-mobile/firefox-android and need to close old PRs/drafts.

For this particular change, I would recommend first continuing the discussion on the ticket: https://bugzilla.mozilla.org/show_bug.cgi?id=1807347

It's a substantial change and we should verify the performance gains before landing it. We can help with that. /cc @Amejia481

**Comment by RotBolt** [comment]
Hi @csadilek meanwhile the migration is being worked upon, where one can contribute to fenix or will outside org contributions will be closed for transition period?

**Comment by csadilek** [comment]
@RotBolt The repo already migrated and contributions are welcome at https://github.com/mozilla-mobile/firefox-android.

**Pull request closed without merging**
