### PR TITLE
For #20440 - Forces TopSitePager bind if no. of pages changed

### PR DESCRIPTION
**Pull request by codrut-topliceanu**
For https://github.com/mozilla-mobile/fenix/issues/20440
### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests.
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md).

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

https://user-images.githubusercontent.com/60002907/126976952-bbb3371a-33a5-449b-8950-db5bf90d767b.mp4

### CODE REVIEW

**Comment by codrut-topliceanu** [comment]
Hey @jonalmeida check out this cool PR! 😅

**Review by jonalmeida — APPROVED** [review]
tumblr_n2pzwz0ueV1rrkahjo4_250

**Comment by jonalmeida** [comment]
I filed https://github.com/mozilla-mobile/fenix/issues/20533 for the intermittent.

**Comment by jonalmeida** [comment]
🤷 
```
 * What went wrong:
Could not determine the dependencies of task ':app:compileDebugKotlin'.
> Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not determine artifacts for org.mozilla.appservices:places:81.0.1: Skipped due to earlier error
```

**Pull request merged**
