### PR TITLE
Update Android Components version to 61.0.20200929000932.

### PR DESCRIPTION
**Pull request by jonalmeida**
Manual upgrade to test out some new AC changes quicker.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by ekager — APPROVED** [review]

**Comment by jonalmeida** [comment]
Thanks @ekager !

**Comment by ekager** [comment]
It looks like there's a real UI test failure where the media never starts to play. Every media test is failing. 
One example and if you watch the video it doesn't start playing and times out on `waitForPlaybackToStart`: https://console.firebase.google.com/u/0/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5348986008745133402/executions/bs.29440915fd1bc74c/test-cases

**Comment by jonalmeida** [comment]
Hmm.. I don't see any media related land in AC. The most recent thing would be this change in GV: https://bugzilla.mozilla.org/show_bug.cgi?id=1658937

**Comment by jonalmeida** [comment]
Looking at the [build timestamp](https://hg.mozilla.org/mozilla-central/rev/d15245dad149) from when that change landed it seems like this landed after the last successful AC version on Friday.

**Comment by eamsen** [comment]
> Hmm.. I don't see any media related land in AC. The most recent thing would be this change in GV: https://bugzilla.mozilla.org/show_bug.cgi?id=1658937

That bug only affects the `MediaSession` API. Are there any Gecko/GV logs that seem relevant?

**Comment by eamsen** [comment]
Filed a GV bug for the regression: https://bugzilla.mozilla.org/show_bug.cgi?id=1668112.

**Comment by jonalmeida** [comment]
Closing this in place of the new https://github.com/mozilla-mobile/fenix/pull/15459 from MickeyMoz which uses a more recent version of AC.

**Pull request closed without merging**
