### PR TITLE
Updating the code to work with application-services v95.0.0

### PR DESCRIPTION
**Pull request by bendk**
This required updating the code to handle the new app-services error hierarchy.

This should be merged alongside https://github.com/mozilla-mobile/firefox-android/pull/80

No tests or screenshots because this doesn't change any behavior.

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [ ] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation

Used by GitHub Actions.

### CODE REVIEW

**Comment by rvandermeulen** [comment]
@bendk Are Focus and r-b going to need updating as well?

**Comment by jonalmeida** [comment]
> @bendk Are Focus and r-b going to need updating as well?

Doesn't look like it [here](https://searchfox.org/mozilla-mobile/search?q=Urlparsefailed&path=&case=false&regexp=false).

**Comment by bendk** [comment]
Wow, I never realized how useful searchfox was for mobile.

I don't think that focus or r-b need updating either, but is there a good way for me to test that?

**Comment by jonalmeida** [comment]
> Wow, I never realized how useful searchfox was for mobile.
Wait till you try cs.github.com 😄 

> I don't think that focus or r-b need updating either, but is there a good way for me to test that?
Building them against a local AC is the only way I can think of. When we move to the firefox-android repo, that will change.

I'm not too concerned about this patch though if the the only changes are the exception name.

**Comment by jonalmeida** [comment]
Landing this AC release when it's done building: https://firefox-ci-tc.services.mozilla.com/tasks/groups/NBpBBCutQgOUrUcTH4rJVw

**Review by jonalmeida — APPROVED** [review]

**Comment by Mugurell** [comment]
Getting compile time errors:
> BaseBrowserFragment.kt: (42, 42): Unresolved reference: PlacesApiException
> BookmarksUseCase.kt: (9, 42): Unresolved reference: PlacesApiException
> ...

**Comment by bendk** [comment]
> Getting compile time errors:
> 
> > BaseBrowserFragment.kt: (42, 42): Unresolved reference: PlacesApiException
> > BookmarksUseCase.kt: (9, 42): Unresolved reference: PlacesApiException
> > ...

I believe this just required an a-c update to pull in https://github.com/mozilla-mobile/firefox-android/pull/80.  Tell me if you're still getting those errors after the bump.

**Comment by Mugurell** [comment]
Thank you!
It seems indeed to be a local issue.

**Pull request merged**
