### PR TITLE
Fixes #4324 - l10n Add more screenshots tests

### LINKED ISSUE #4324: l10n Screenshots tests - Tests needed to cover missing menus/views
There are menus and views that are not covered by the screenshots tests yet, and so issues like #4323 may not be detected soon enough. So, let´s try to add tests for those menus, for example: 
- [ ] Collection menu and each of its options
- [ ] Open tab menu and each of its options
- [ ] Bookmarks folder management
- [ ] Remove tab/collection/bookmarks/history
- [ ] Open site menu and options

### PR DESCRIPTION
**Pull request by isabelrios**
Fixes #4324 
Adding more screenshots test to try to cover new and missing views to be able to check all the strings in the different locales

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not

### CODE REVIEW

**Comment by boek** [comment]
@sblatz can you take a look at this :)

**Comment by isabelrios** [comment]
> @sblatz can you take a look at this :)

oh I need to do a few changes to add one more screenshot and will remove the WIP, hopefully later today :) Thanks!

**Comment by boek** [comment]
@isabelrios Oh, sorry! Don't know how I missed that :see_no_evil: 

For future reference Github introduced Draft PRs for WIP. This will not assign anyone to review it until you're finished with it :)

https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by isabelrios** [comment]
> @isabelrios Oh, sorry! Don't know how I missed that 🙈
> 
> For future reference Github introduced Draft PRs for WIP. This will not assign anyone to review it until you're finished with it :)
> 
> https://github.blog/2019-02-14-introducing-draft-pull-requests/

Oh I didn't know that...I will use it in the future, thanks!

Removing now the WIP @sblatz  :)

**Pull request merged**
