### PR TITLE
Bug 1756153 - Move startup perf measurements to a background thread

### PR DESCRIPTION
**Pull request by badboy**
This is required to avoid loading the Glean core library (provided by libxul) early on.
Fenix needs to do the time measurement itself for now.

---

This also requires the Glean v51.0.0 update coming (hopefully) by tomorrow to A-C.
Glean is now backed by mostly Rust code and thus requires loading the library, that's why early calls load it.
My local tests on a Pixel 3 showed some measurable improvements, as done in #25607.
When Glean v51.0.0 landed it would be good if someone can take this PR and run the benchmarks on the Moto G5 again (cc @Amejia481).

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [ ] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation

Used by GitHub Actions.

### CODE REVIEW

**Comment by Amejia481** [comment]
This branch
image

Main brach

image

**Comment by badboy** [comment]
Ah sorry for the lack of updates. We haven't yet upgraded to 51.0.0, so no changes are expected yet.

**Comment by badboy** [comment]
Rebased. The latest A-C should have Glean 51, so now I hope some of the startup regression might be addressed by this.

**Comment by Amejia481** [comment]
Sure no problem, here are the results!

🎉 !


### This branch
image

### Main
image

**Review by Amejia481 — APPROVED** [review]

**Pull request merged**
