### PR TITLE
For #162 - add feature build flag to disable firebase push service

### LINKED ISSUE #162: F-Droid
Would be nice to have this browser available in the F-Droid repository, when it'll be released (I hope soon). That's why I should ask, do you support this idea?

### PR DESCRIPTION
**Pull request by gilbsgilbs**
Fixes #162 

This PR introduces a build flag that allows to enable/disable firebase push service. To build fenix without the firebase push service, just run:

> ./gradlew -Porg.mozilla.fenix.enableFeatureFirebase=false assembleDebug

Or add the following line to your `$GRADLE_HOME/gradle.properties` to make the config persistent:

> org.mozilla.fenix.enableFeatureFirebase=true

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by opusforlife2** [comment]
@gilbsgilbs Is this waiting for code review?

**Comment by gilbsgilbs** [comment]
@opusforlife2 Yes, but I won't be able to re-work on it very soon. If someone wants to pickup with this work, I can give write access to my repo or they can open their own PR.

**Comment by opusforlife2** [comment]
Could you leave a comment in the F-Droid issue saying you're busy, then? Maybe someone will read it and pick up where you've left off.

**Comment by gabrielluong** [comment]
Hi @gilbsgilbs, thank you for your contribution! Since #162 seems to be resolved now (it's a long discussion that I am not fully caught up with), I am closing this PR for the now to clean up our PR backlog. We can always reopen this.

**Pull request closed without merging**
