### PR TITLE
For #25810 - Unified search should give hint to user that there are more menu items available by scrolling

### LINKED ISSUE #25810: Unified search engine menu popup should give hints to the user that more selection is available by scrolling
If the unified search engine menu popup does not fit completely, always show hint (by cutting off the end entry) that there are more selection available by scrolling.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20846)

### PR DESCRIPTION
**Pull request by t-p-white**
Bulk of changes are in AC: See https://github.com/mozilla-mobile/firefox-android/pull/181 for AC details.

The unified search 'search popup menu' should give hint to the user that there are more menu items available by scrolling. This is indicated by displaying a half menu item if the available height will not fit the full list of items.

Existing behaviour :

https://user-images.githubusercontent.com/1833156/202675300-ab202c8f-5d3c-4fa9-aed5-bca265d872d7.mov

New behaviour LTR: 

https://user-images.githubusercontent.com/1833156/210393163-c7e3aece-c3da-4ccd-8eef-b221d7821ba3.mov

New behaviour RTL: 

https://user-images.githubusercontent.com/1833156/210393280-c810b7a4-b8e9-4d80-988c-150c4c69e01c.mov

### UI states:
* Does menu fit or does menu have to scroll
* Search bar Top/Bottom
  * Portrait keyboard open
  * Portrait keyboard closed
  * Landscape keyboard open
  * Landscape keyboard closed

Note: This issue is covering the direction and popup height only, another issue is in progress for positioning https://github.com/mozilla-mobile/fenix/issues/27998.

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [ ] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #25810

### CODE REVIEW

**Comment by Mugurell** [comment]
Talked with @Verdi about what's still needed for the unified search feature and understood that we won't need to have the selector be shown above the keyboard. 
Pinging him for visibility.

**Comment by Verdi** [comment]
Yes - after trying the menu positioned over the keyboard, I think it's better to show the whole thing when we can and it's ok to cover the keyboard in this case.

**Comment by t-p-white** [comment]
Thanks @Mugurell 

> Yes - after trying the menu positioned over the keyboard, I think it's better to show the whole thing when we can and it's ok to cover the keyboard in this case.

@Verdi ok thanks for the feedback, what is the preference on the orientation? Would a 'down' orientation perhaps more thumb friendly?

**Comment by mavduevskiy** [comment]
> Thanks @Mugurell
> 
> > Yes - after trying the menu positioned over the keyboard, I think it's better to show the whole thing when we can and it's ok to cover the keyboard in this case.
> 
> @Verdi ok thanks for the feedback, what is the preference on the orientation? Would a 'down' orientation perhaps more thumb friendly?

@Verdi 
I would also follow up with the question if we want to give the hint about more items if there is just not enough space for the list? For example, the landscape mode will not allow to show the whole list even with the hidden keyboard.

**Pull request merged**
