### PR TITLE
Auto-publish & substitute local Glean package

### PR DESCRIPTION
**Pull request by badboy**
I'm simplifying how to test out a local Glean dev version in a-c and Fenix.
See https://github.com/mozilla/glean/pull/2019.

These are the only Fenix changes needed.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by Amejia481 — APPROVED** [review]

**Comment by badboy** [comment]
@Amejia481 I think this failed, but because of something completely unrelated as I didn't touch any code really. Can you take a look?

**Comment by mcarare** [comment]
`verifyMultipleLoginsSelectionsTest` has intermittent failures: https://github.com/mozilla-mobile/fenix/issues/23816
Closing and reopening to run CI again.

**Comment by Amejia481** [comment]
@mcarare thanks for the help ❤️ !
It looks like there are other intermittent tests, I added a separated commit to disabled them.

**Comment by Amejia481** [comment]
🎉 !!

**Pull request merged**
