### PR TITLE
Add profiler markers for HomeActivity.load and DefaultTabTrayController.onNewTabTapped methods

### PR DESCRIPTION
**Pull request by canova**
Hi all, I'm on the profiler team and was working on the profiler marker API for Android for a while. [This is the GeckoView bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1624993) and [this is the android-components PR](https://github.com/mozilla-mobile/android-components/pull/7510). Since android-components side is merged now, it's possible to use the marker API inside the Fenix codebase. This PR adds the first markers of Fenix, to demonstrate two different usages.
I wanted to add these markers to somewhere relevant for Fenix devs, but keep in mind that I don't know the codebase that much, so correct me if they are not great places :)

For example you can see an example profile here with these markers: https://share.firefox.dev/2YWKpXS
Here's the documentation about this new API: https://github.com/mozilla-mobile/android-components/blob/master/components/concept/engine/src/main/java/mozilla/components/concept/engine/profiler/Profiler.kt

Lastly, I was using my local android-components repo while writing this patch, I hope the latest a-c is merged here as well :)

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by kbrosnan** [comment]
@mcomella and @ekager do you have bandwidth to review these changes from the perf team? If not please redirect.

**Comment by MarcLeclair** [comment]
@canova  that's awesome. It works fine on my end and I was able to add some random markers to test it out. It doesn't seem to have much overhead ( was <3ms I think at its "highest"). I was wondering, would it be possible to add markers on start up if we had an environment variable that we set or something?  This is more of a question out of curiosity 😄

**Comment by canova** [comment]
@MarcLeclair thanks!
Yes, startup profiling should also work with the marker API 🙂. Although BaseProfiler(profiler that records pre-xul stuff) doesn't work on Android iirc. But you should still be able to capture the markers in a startup after the xul initialization.

**Comment by mcomella** [comment]
We can't run CI on this PR because you're not part of our GH org so I reopened it, unmodified, under my name https://github.com/mozilla-mobile/fenix/pull/12460 (you still have git commit authorship). I'm going to close this in favor of that PR.

**Comment by canova** [comment]
Thanks for reviewing and landing it!

**Pull request closed without merging**
