### PR TITLE
Update Android Components version

### PR DESCRIPTION
**Pull request by MickeyMoz**

### CODE REVIEW

**Comment by pocmo** [comment]
Toolchain task failed:

> [task 2021-12-08T15:48:01.757Z] e: /builds/worker/checkouts/vcs/app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt: (130, 65): 'when' expression must be exhaustive, add necessary 'ERROR_HTTPS_ONLY' branch or 'else' branch instead

**Comment by pocmo** [comment]
That should be my change. I'll take a look.

**Comment by Amejia481** [comment]
When we cut 96 we did this https://github.com/mozilla-mobile/fenix/commit/a7afdb776ca202bf5eafc29d6a84f047c1609e0f

**Comment by pocmo** [comment]
Okay, needs this change too after all.

> [task 2021-12-08T20:15:35.662Z] e: /builds/worker/checkouts/vcs/app/src/test/java/org/mozilla/fenix/exceptions/trackingprotection/TrackingProtectionExceptionsInteractorTest.kt: (72, 13): 'restore' overrides nothing

**Pull request merged**
