### PR TITLE
Closes #778 - Progressive Web Apps!

### LINKED ISSUE #769: Use PWAs while offline
### User Story
As a user, I want to use my installed PWAs while I am offline, so I can have a continuous app-like experience. 

### Acceptance Criteria
- When I open my PWAs while offline, I can access the site web content

### LINKED ISSUE #770: Open installed PWAs in fullscreen / standalone mode
### User Story
As a user, I want my installed PWAs to open in fullscreen/standalone mode, so I can enjoy an app-like experience. 

### Dependencies:
https://github.com/mozilla-mobile/android-components/issues/1830

### Acceptance Criteria
- My installed PWAs open in fullscreen/standalone mode.

### LINKED ISSUE #772: As a User I want websites that I have saved to my phone's home screen to look like native applications
Need some help here to understand what the experience is for sites started from the home screen. Would these just open the browser and then appear in a new tab or would it look more like a minimal browser with no ability outside of the website. If so, what would the functionality be? Just basic navigation?

### LINKED ISSUE #778: Install a PWA to my home screen
### User Story
As a user, I want to be able to install a PWA to my home screen, so I can launch it later directly from my homescreen similar to a standalone app.

#Acceptance Criteria
-I can install a PWA to my homescreen
-The launcher icon uses the PWA's icon (web app manifest)

### LINKED ISSUE #779: Refresh the currently displayed page in a PWA
### User Story
As a user, I want to be able to refresh the currently displayed page in a PWA, so I can see updated content. 

Since there's no browser chrome in most display modes there is no way to refresh the current page. In Chrome this is done by using the pull-to-refresh gesture.

### Acceptance Criteria
I can refresh my currently displayed page in PWA

### PR DESCRIPTION
**Pull request by NotWoods**
Closes #778
Closes #772
Closes #770 
Closes #769
Closes #779

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".

### CODE REVIEW

**Comment by TitanNano** [comment]
I tested the Debug build from TaskCluster for this PR and there are a few things that leave room for improvement:

1. when launching a PWA from the home screen there is a lot of flickering because the PWA appears to open the main fenix activity before starting its own activity
2. because of 1. every PWA also launches the main fenix activity
3. there is no way to tell if a site will be added to the home screen in standalone mode or as a simple shortcut
4. the navigation bar is always white which does not work well on devices with android < 8 
5. when choosing to add a new shortcut to the home screen, nothing happens. Fennec usually navigates to the home screen, showing the newly created shortcut.

**Comment by TitanNano** [comment]
Two additional things:

  6. Home screen icons often take 2 - 3 taps until an activity is opened
  7. It's not possible to navigate out of the scope of an PWA

**Comment by NotWoods** [comment]
Filed additional issues:
1. mozilla-mobile/android-components#4388
2. mozilla-mobile/android-components#4388
3. #774
4. mozilla-mobile/android-components#4373
5. mozilla-mobile/android-components#4386
6. mozilla-mobile/android-components#4387
7. Needs investigation since navigation works properly in Reference Browser.

**Comment by TitanNano** [comment]
@NotWoods I also want to add to @sblatz review that the launch of PWAs is quite slower than it was in Fennec. There is a delay of about 2s before the PWA activity is actually launched. Also, the entry animation of the activity is wrong and feels weird since it doesn't behave like other activities. 



## Fennec:
recording_20190922_151048_edit

Video:
https://drive.google.com/file/d/1-gFKo7Zxds8nc0MDkHClwDQhELzr7sMY/view?usp=sharing

## Fenix:
recording_20190922_151133_edit

Video:
https://drive.google.com/file/d/1b_qOEhHeNMTbC_JccrxhMF6c_P7NiBil/view?usp=sharing

**Comment by NotWoods** [comment]
@TitanNano The launching issue should be addressed when we start displaying a splash screen while some background processing is done. See mozilla-mobile/android-components#2294

**Comment by TitanNano** [comment]
@NotWoods also the fact that it takes about 2s longer than Fennec?

**Comment by NotWoods** [comment]
@sblatz 
1. mozilla-mobile/android-components#4414
2. #779 (PWAs can be refreshed in the site controls notification instead for now)
3. mozilla-mobile/android-components#4510
4. mozilla-mobile/android-components#4505
5. Needs investigation

**Comment by sblatz** [comment]
@NotWoods please let me know when you want me to look at this again 😄

**Comment by TitanNano** [comment]
@NotWoods I just noticed that clicking a link inside a PWA which takes the user to a page outside the PWAs scope, transforms the PWA into a custom tab. When I then close the custom tab, my PWA is also gone. 
This should actually behave like in a native app and similar to how it works in Fennec right now. If the navigation sends the user out of the PWA, a new custom tab intent should be created.

**Comment by sblatz** [comment]
@NotWoods or @TitanNano can we file a follow-up issue for that so we can get this landed and start testing in nightly? :)

**Comment by NotWoods** [comment]
I updated Android Components to fix that custom tab issue today. Currently waiting to fix the crash before landing this in nightly.

**Pull request merged**
