### PR TITLE
For #26191 - Add telemetry for jump back in onboarding message

### LINKED ISSUE #26191: Add telemetry for jump back in onboarding message
The following telemetry should be captured:
- Impression counts 

- Click counts on the X

- Clicks elsewhere on the screen that close the message are counted

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21116)

### PR DESCRIPTION
**Pull request by Alexandru2909**
Added telemetry for jump back in cfr show, dismiss and cancel.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #26191

### CODE REVIEW

**Comment by Alexandru2909** [comment]
Waiting for https://github.com/mozilla-mobile/fenix/pull/26203 to land.

**Comment by Alexandru2909** [comment]
<h1 dir="auto">Request for data collection review form</h1>
<p dir="auto">All questions are mandatory. You must receive review from a
 data steward peer on your responses to these questions before shipping 
new data collection.</p>
<ol dir="auto">
<li>What questions will you answer with this data?</li>
</ol>
<ul dir="auto">
<li>
    How many users saw the jump back in onboarding message?
</li>
<li>
    After the onboarding message was displayed, how many users dismissed the CFR using the `X` button?
</li>
<li>
    After the onboarding message was displayed, how many users cancelled the CFR by touching elsewhere on the screen?
</li>
</ul>
<ol dir="auto" start="2">
<li>Why does Mozilla need to answer these questions? Are there benefits 
for users? Do we need this information to address product or business 
requirements?</li>
</ol>
<ul dir="auto">
<li>We need to count the impressions, clicks on the `X` button and clicks elsewhere on the screen to understand how many users see the jump back in cfr and how they interact with it.</li>
</ul>
<ol dir="auto" start="3">
<li>What alternative methods did you consider to answer these questions? Why were they not sufficient?</li>
</ol>
<ul dir="auto">
<li>No other alternatives. </li>
</ul>
<ol dir="auto" start="4">
<li>Can current instrumentation answer these questions?</li>
</ol>
<ul dir="auto">
<li>No. </li>
</ul>
<ol dir="auto" start="5">
<li>List all proposed measurements and indicate the category of data 
collection for each measurement, using the Firefox data collection 
categories found on the Mozilla wiki. <br>
Note that the data steward reviewing your request will characterize your
 data collection based on the highest (and most sensitive) category.</li>
</ol>

Measurement Description | Data Collection Category | Tracking Bug #
-- | -- | --
Jump back in cfr shown: Jump back in CFR has been displayed to the user. | Category 2 - interaction data | https://github.com/mozilla-mobile/fenix/issues/26190
Jump back in cfr dismissed: Jump back in CFR has been dismissed clicking the X button. | Category 2 - interaction data | https://github.com/mozilla-mobile/fenix/issues/26190
Jump back in cfr cancelled: Jump back in CFR has been cancelled clicking the outside the CFR. | Category 2 - interaction data | https://github.com/mozilla-mobile/fenix/issues/26190

<ol dir="auto" start="6">
<li>Please provide a link to the documentation for this data collection 
which describes the ultimate data set in a public, complete, and 
accurate way.</li>
</ol>
<ul dir="auto">
<li><a href="https://dictionary.telemetry.mozilla.org/apps/fenix" rel="nofollow">https://dictionary.telemetry.mozilla.org/apps/fenix </a></li>
</ul>
<ol dir="auto" start="7">
<li>How long will this data be collected? Choose one of the following:</li>
</ol>
<ul dir="auto">
<li>Up until version 118, with the option to renew at that point.</li>
</ul>
<ol dir="auto" start="8">
<li>What populations will you measure?</li>
</ol>
<ul dir="auto">
<li>All channels, all locales, all countries. </li>
</ul>
<ol dir="auto" start="9">
<li>If this data collection is default on, what is the opt-out mechanism for users?</li>
</ol>
<ul dir="auto">
<li>Default Glean SDK opt-out mechanism. </li>
</ul>
<ol dir="auto" start="10">
<li>Please provide a general description of how you will analyze this data.</li>
</ol>
<ul dir="auto">
<li>Glean. </li>
</ul>
<ol dir="auto" start="11">
<li>Where do you intend to share the results of your analysis?</li>
</ol>
<ul dir="auto">
<li> Only on Glean and with mobile teams. </li>
</ul>
<ol dir="auto" start="12">
<li>Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?</li>
</ol>
<ul dir="auto">
<li>No third-party tools.</li>
</ul>

**Review by Mugurell — APPROVED** [review]
LGTM code wise

**Comment by travis79** [comment]
Thanks for picking up this data-review @rocketsroger :)

**Pull request merged**
