### PR TITLE
Adding support for Site Permissions.

### PR DESCRIPTION
**Pull request by Amejia481**
First contribution 🎉 

We added some support for site permissions in a-c and we are adding more features to it. It will be great to have the Fenix feedback :).

[Demo](https://drive.google.com/file/d/1HsvbZ9yCfz1elQiF6yZ2D5_tbQN9fQeC/view?usp=sharing) 🌮

### CODE REVIEW

**Comment by colintheshots** [comment]
Does this depend on AC 0.44 or 0.45? We just downgraded to work around a bug. If so, this PR will be blocked.

**Comment by Amejia481** [comment]
It's been there since 0.43. I Tested it locally and it's working fine with 0.43

**Comment by colintheshots** [comment]
Do you need help rebasing the commit?

**Comment by Amejia481** [comment]
@colintheshots I'm not authorized to merge.

**Comment by boek** [comment]
@Amejia481 the branch has conflicts with master

**Comment by Amejia481** [comment]
Oh weird ,thanks @boek. GitHub is not showing me that maybe because I do not have enough privileges to resolve it online. I will fix the issue and re-push.

image

**Comment by Amejia481** [comment]
@boek  @colintheshots  done!

**Pull request merged**
