### PR TITLE
For #20848 - Hide Download List delete icon in multiselect mode

### LINKED ISSUE #20848: Downloaded items can be deleted individually in multiselect mode
The delete button, either it can be hidden in multiselect or the number of selected items can be updated when any item is deleted individually.

screenshot_1
screenshot_2
screenshot_3

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-17589)

### PR DESCRIPTION
**Pull request by sunilk9211**
Fixes #20848 

Disable & Hide delete icon for Download item in multiselect mode.

https://user-images.githubusercontent.com/36289013/151707647-1d1efa6b-abd6-4f1b-a520-e0343d931fc9.mp4

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by rocketsroger — APPROVED** [review]
Thanks!

**Comment by rocketsroger** [comment]
@sunilk9211 Looks like the new detekt rule is complaining about `bind()` in `DownloadsListItemViewHolder.kt`  Please add kdoc for the bind function.  Thanks

**Comment by sunilk9211** [comment]
> @sunilk9211 Looks like the new detekt rule is complaining about `bind()` in `DownloadsListItemViewHolder.kt` Please add kdoc for the bind function. Thanks

Okay. Thanks

**Comment by sunilk9211** [comment]
> @sunilk9211 Looks like the new detekt rule is complaining about `bind()` in `DownloadsListItemViewHolder.kt` Please add kdoc for the bind function. Thanks

Okay, But i am not aware of how that's done. I have to check. Thanks for the review.

**Pull request closed without merging**
