### PR TITLE
Fix 3809 - Show entire URL in security info view

### PR DESCRIPTION
**Pull request by darkwing**
Shows the full URL when clicking on the security icon

---

FullUrl

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### CODE REVIEW

**Comment by darkwing** [comment]
The other thingn Chrome does, which is nice, is show the `https` in green.

**Comment by cadeyrn** [comment]
> The other thingn Chrome does, which is nice, is show the `https` in green.

For the Desktop Firefox Mozilla decided to move *away* from emphasizing secure connections: 

> The formerly green lock icon will now become gray, with the intention of de-emphasizing the default (secure) connection state and instead putting more emphasis on broken or insecure connections.

https://blog.mozilla.org/security/2019/10/15/improved-security-and-privacy-indicators-in-firefox-70/

Fenix shouldn't do the opposite. Instead of making the https green Fenix shouldn't do this and instead making the green lock also grey.

**Comment by kbrosnan** [comment]
@cadeyrn that is not what this pr is about. The green lock has been in this view for quite some time. Please file a new issue describing the changes you are suggesting.

**Comment by cadeyrn** [comment]
> that is not what this pr is about. The green lock has been in this view for quite some time. Please file a new issue describing the changes you are suggesting.

It was not my intention to use this issue for an unrelated proposal, maybe I was not clear. It was meant as response to the proposal to make the https green. What I wanted to say was: Instead of emphasizing secure connections more secure connections should be emphasized less or it should be unchanged at least because that's what Mozilla decided for Desktop and I think security indicators should not move in different directions on different platforms.

**Comment by ekager** [comment]
Looks good! One quick question before merging - could you just test that this will wrap correctly when the URL is very long?

**Comment by darkwing** [comment]
Good shout; an ultra-long URL is partially cut off on the bottom; I'll look for a solution.

Screenshot_20191118-143742

**Comment by darkwing** [comment]
Panel now grows to show entire URL text despite length:

Screenshot_20191118-153712

**Pull request merged**
