### PR TITLE
For #14637 - Fix sitePermissionsFeature breaking change + AC bump

### PR DESCRIPTION
**Pull request by codrut-topliceanu**
This PR needs landing after [AC PR 8555](https://github.com/mozilla-mobile/android-components/pull/8555) which is a fix for [AC Issue 8554](https://github.com/mozilla-mobile/android-components/issues/8554).

### Pull Request checklist

- [x] **Tests**: This PR does not include any tests as it is only a minor change.
- [x] **Screenshots**: This PR has no visual changes
- [x] **Accessibility**: The code in this PR does not include any user facing features.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by codrut-topliceanu** [comment]
@Amejia481 Sorry to bother you once again, but you know the whole story with https://github.com/mozilla-mobile/android-components/pull/8555 🥇

**Comment by Amejia481** [comment]
It's now a problem glad to help!

**Comment by Amejia481** [comment]
As this is breaking change we need to update the ac version here as the @MickeyMoz pr for bumping the ac version is going to fail as it will need this change

**Review by Amejia481 — APPROVED** [review]

**Comment by Amejia481** [comment]
Timeout 🎲 

```
[task 2020-10-29T16:52:13.064Z]   TEST: adaptPolicyToChannel MUST only update properties that have changed per given channel
[task 2020-10-29T16:52:13.664Z]     [Robolectric] org.mozilla.fenix.components.TrackingProtectionPolicyFactoryTest.adaptPolicyToChannel MUST only update properties that have changed per given channel: sdk=28; resources=BINARY
[task 2020-10-29T16:55:00.264Z]     I/MonitoringInstr: Instrumentation started!

[taskcluster:error] Task timeout after 7200 seconds. Force killing container.
[taskcluster 2020-10-29 17:48:19.401Z] === Task Finished ===
[taskcluster 2020-10-29 17:48:19.401Z] Unsuccessful task run with exit code: -1 completed in 7201.086 seconds

```

**Comment by Amejia481** [comment]
Time out :( 
```
[task 2020-10-29T18:50:57.392Z]   TEST: OverlappingFxaLogoutRequest detected
[task 2020-10-29T18:50:57.392Z]     [Robolectric] org.mozilla.fenix.components.AccountAbnormalitiesTest.OverlappingFxaLogoutRequest detected: sdk=28; resources=BINARY
[task 2020-10-29T18:52:15.792Z]     I/MonitoringInstr: Instrumentation started!
[task 2020-10-29T19:33:06.592Z]     W [AccountAbnormalities] Overlapping logout request
[task 2020-10-29T19:34:10.892Z]   SUCCESS
[task 2020-10-29T19:34:10.892Z] 
[task 2020-10-29T19:34:10.892Z]   TEST: logout happy case
[task 2020-10-29T19:34:10.892Z]     [Robolectric] org.mozilla.fenix.components.AccountAbnormalitiesTest.logout happy case: sdk=28; resources=BINARY
[task 2020-10-29T19:35:26.292Z]     I/MonitoringInstr: Instrumentation started!
[taskcluster:error] Task timeout after 7200 seconds. Force killing container.
[taskcluster 2020-10-29 20:14:44.815Z] === Task Finished ===
[taskcluster 2020-10-29 20:14:44.816Z] Unsuccessful task run with exit code: -1 completed in 7201.168 seconds

```

**Pull request merged**
