### PR TITLE
For #19931: Add telemetry probes for recent bookmarks on home screen

### PR DESCRIPTION
**Pull request by eliserichards**
For #19931
~Waiting on https://mozilla-hub.atlassian.net/browse/DO-542~ ✅ 

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.
- [x] **Data review**

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by eliserichards** [comment]
# Request for data collection review form

All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.

1. What questions will you answer with this data? 
   * This data will help us understand how users are interacting with the new section on the Home Screen that shows their recently saved bookmarks. 
2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements? 

   * We are building out the features on our Home Screen, and we need to know how useful this new section is for the users and how we can best utilize the real estate of the Home Screen. This data will help us establish a baseline to make product decisions as we build this feature and others on the Home Screen. 
3. What alternative methods did you consider to answer these questions? Why were they not sufficient? 
   * There are no other alternatives. 
4. Can current instrumentation answer these questions? 
   * No. 
5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories found on the Mozilla wiki. 
Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.

Measurement Description | Data Collection Category | Tracking Bug #
-- | -- | --
Recent_bookmarks.bookmark_clicked: Metric, a counter of times a recently saved bookmark was clicked on the home screen. | Category 2 - interaction data | https://github.com/mozilla-mobile/fenix/issues/20316
Recent_bookmarks.show_all_clicked: Metric, a counter of times that the "show all" button was clicked on the recently saved bookmarks section of the home screen. | Category 2 - interaction data | https://github.com/mozilla-mobile/fenix/issues/20316

6. Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.

   * https://dictionary.telemetry.mozilla.org/apps/fenix 
7. How long will this data be collected? Choose one of the following:

   * I want this data to be collected for 6 months initially (ending on February 1, 2021), with the option to renew at that point. 
8. What populations will you measure?

   * All channels, all locales, all countries 
9. If this data collection is default on, what is the opt-out mechanism for users? 
    * Default Glean SDK opt-out mechanism. 
10. Please provide a general description of how you will analyze this data. 
    * Glean and Amplitude. 
11. Where do you intend to share the results of your analysis?
    *  Only on Glean, Amplitude, and with mobile teams. 
12. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection? 
    * No third-party tools.

**Comment by eliserichards** [comment]
Test failure: 

```
TEST: test other tip
    [Robolectric] org.mozilla.fenix.components.tips.providers.MigrationTipProviderTest.test other tip: sdk=28; resources=BINARY
  FAILURE
```

```
io.mockk.MockKException: no answer found for: Settings(#492).getRecentBookmarkClickedCount()
	at io.mockk.impl.stub.MockKStub.defaultAnswer(MockKStub.kt:90)
	at io.mockk.impl.stub.MockKStub.answer(MockKStub.kt:42)
	at io.mockk.impl.recording.states.AnsweringState.call(AnsweringState.kt:16)
	at io.mockk.impl.recording.CommonCallRecorder.call(CommonCallRecorder.kt:53)
	at io.mockk.impl.stub.MockKStub.handleInvocation(MockKStub.kt:263)
	at io.mockk.impl.instantiation.JvmMockFactoryHelper$mockHandler$1.invocation(JvmMockFactoryHelper.kt:25)
	at io.mockk.proxy.jvm.advice.Interceptor.call(Interceptor.kt:20)
	at org.mozilla.fenix.utils.Settings.getRecentBookmarkClickedCount(Settings.kt:1098)
	at org.mozilla.fenix.FenixApplication.setStartupMetrics$app_debug(FenixApplication.kt:581)
	at org.mozilla.fenix.FenixApplicationTest.WHEN setStartupMetrics is called THEN sets some base metrics(FenixApplicationTest.kt:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	
```

**Comment by travis79** [comment]
> # Request for data collection review form
> 
> All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.
> 
>     1. What questions will you answer with this data?    
>        
>        * This data will help us understand how users are interacting with the new section on the Home Screen that shows their recently saved bookmarks.
> 
>     2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
>        
>        * We are building out the features on our Home Screen, and we need to know how useful this new section is for the users and how we can best utilize the real estate of the Home Screen. This data will help us establish a baseline to make product decisions as we build this feature and others on the Home Screen.
> 
>     3. What alternative methods did you consider to answer these questions? Why were they not sufficient?    
>        
>        * There are no other alternatives.
> 
>     4. Can current instrumentation answer these questions?    
>        
>        * No.
> 
>     5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories found on the Mozilla wiki.    
>        Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.
> 
> 
> Measurement Description 	Data Collection Category 	Tracking Bug #
> Recent_bookmarks.bookmark_clicked: Metric, a counter of times a recently saved bookmark was clicked on the home screen. 	Category 2 - interaction data 	#20316
> Recent_bookmarks.show_all_clicked: Metric, a counter of times that the "show all" button was clicked on the recently saved bookmarks section of the home screen. 	Category 2 - interaction data 	#20316
> 
>     1. Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
>        
>        * [https://dictionary.telemetry.mozilla.org/apps/fenix      ](https://dictionary.telemetry.mozilla.org/apps/fenix%E2%80%A8)
> 
>     2. How long will this data be collected? Choose one of the following:
>        
>        * I want this data to be collected for 6 months initially (ending on February 1, 2021), with the option to renew at that point.
> 
>     3. What populations will you measure?
>        
>        * All channels, all locales, all countries
> 
>     4. If this data collection is default on, what is the opt-out mechanism for users?    
>        
>        * Default Glean SDK opt-out mechanism.
> 
>     5. Please provide a general description of how you will analyze this data.    
>        
>        * Glean and Amplitude.
> 
>     6. Where do you intend to share the results of your analysis?
>        
>        * Only on Glean, Amplitude, and with mobile teams.
> 
>     7. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?    
>        
>        * No third-party tools.

# Data Review

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way? 

Yes, through the metrics.yaml file and the Glean Dictionary.

2) Is there a control mechanism that allows the user to turn the data collection on and off? 

Yes, through the "Send Usage Data" toggle in the application preferences.

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

N/A, collection is set to expire or be renewed in 6 months (2021-02-01).

4) Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Category 2, Interaction Data

5) Is the data collection request for default-on or default-off?

Default-on

6) Does the instrumentation include the addition of **any *new* identifiers**?

No

7) Is the data collection covered by the existing Firefox privacy notice? 

Yes

8) Does the data collection use a third-party collection tool? 

No

## Result

data-review+

**Review by rocketsroger — COMMENTED** [review]
I think with our recent findings working with the Data Science and the Glean team we should update this pr so:
1. No need to create preferences to store user lifetime count.  Just need to get the count since last app start with counters.
2. Put these new probes in their own category.
3. Create the objects in `events.kt`.

Thanks

**Review by rocketsroger — CHANGES_REQUESTED** [review]
I'll mark this as need changes since we want to use counters from now on.  Thanks

**Review by rocketsroger — APPROVED** [review]
🚢

**Review by rocketsroger — DISMISSED** [review]

**Comment by eliserichards** [comment]
@Mergifyio rebase

**Review by MozillaNoah — DISMISSED** [review]

**Comment by eliserichards** [comment]
@Mergifyio rebase

**Comment by eliserichards** [comment]
@Mergifyio rebase

**Review by MozillaNoah — APPROVED** [review]

**Pull request merged**
