### PR TITLE
[WIP] Uses geckoview-version index to find raptor artifacts

### PR DESCRIPTION
**Pull request by mitchhentges**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by mitchhentges** [comment]
Running into an issue where [the index-linked tasks have a different artifact layout](https://taskcluster-ui.herokuapp.com/tasks/MR7ZKDeaS6eoY1GxAwnLvg)

**Comment by boek** [comment]
@mitchhentges is this still something we want to land?

**Comment by mitchhentges** [comment]
Yeah, I'm still hoping to land this, so we don't have to do any version-string-rebuilding :)
The thing that's blocking this is that some artifacts from `m-c` have their names prefixed by local (`en-US`), but others aren't. @JohanLorenzo is also running into this difference in naming in some work that he's doing, so I'm going to follow his solution. This PR isn't that high-priority, and it might take a while before we can land :)

**Comment by mitchhentges** [comment]
Replaced by #3646

**Pull request closed without merging**
