### PR TITLE
For #20824: use fast service loader for MainDispatcherFactory.

### LINKED ISSUE #20824: (fenix) `MainDispatcherLoader.<clinit>` unexpectedly takes 266ms on COLD start up
See https://github.com/mozilla-mobile/focus-android/issues/5102 for details and analysis.

### PR DESCRIPTION
**Pull request by mcomella**
For details on the root cause, see the commit. We replaced the similar
proguard rules because:
- the key line was returning false instead of true
- the other line had the same outcome as the written code. I believe it
  was a micro-optimization. Since perf seems fine without it, let's
  remove it

I benchmarked this change on COLD MAIN first frame. We see an
improvement of 89ms:
- before: 1346ms
- after: 1257ms

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by jonalmeida — APPROVED** [review]

**Comment by mcomella** [comment]
Test failure appears to be intermittent: https://github.com/mozilla-mobile/fenix/issues/20875

Queuing to land

**Comment by mcomella** [comment]
Maybe I need to get green CI before I can land?

**Comment by jonalmeida** [comment]
> Test failure appears to be intermittent: #20875
> 
> Queuing to land

This was fixed in https://github.com/mozilla-mobile/fenix/issues/20792 so I think you need to rebase your PR to get that change to be in your PR's history.

**Comment by mcomella** [comment]
@Mergifyio rebase

**Comment by mcomella** [comment]
@Mergifyio backport releases_v92.0.0

**Pull request merged**
