### PR TITLE
Closes #15410: Ripple Animations on Home Screen Toolbar actions

### LINKED ISSUE #15410: [Bug] Home Toolbar actions have no ripple animations on click
## Steps to reproduce
1. On home, click the tab counter or menu icon on toolbar

### Expected behavior
See ripple that matches ripple while browsing

### Actual behavior
No ripple or indication they were clicked. 

### Device information

* Android device: ?
* Fenix version: ?

### PR DESCRIPTION
**Pull request by philippbara**
Closes #15410: Ripple Animations on Home Screen Toolbar actions:
Added on-click ripple effect for both buttons in the home screen toolbar (tab selection + 3-dot menu). See screenshots below.
Also works during private browsing + Pre-push hook tests all succeeded

Screenshot from 2020-09-26 23-03-54

Screenshot from 2020-09-26 23-04-11

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by ekager — CHANGES_REQUESTED** [review]
Thanks! Let's use `selectableItemBackgroundBorderless` so the ripple will extend past the square of the icon. :)

**Comment by philippbara** [comment]
When using `selectableItemBackgroundBorderless` the ripple is "hidden" by the background of the View element (see screenshot). The only way I found to make the ripple visible is by removing the `android:background="?bottomBarBackground"`line from the View element which I guess is not wanted. I found the issue that might be causing this:  

https://github.com/googlecodelabs/constraint-layout/issues/50

Maybe the View's background (`@drawable/home_bottom_bar_background`) could be changed somehow?
If not I would reconsider the "square ripple" :-)

Thanks for any advice

Screenshot from 2020-09-29 20-08-23

**Comment by gabrielluong** [comment]
> When using `selectableItemBackgroundBorderless` the ripple is "hidden" by the background of the View element (see screenshot). The only way I found to make the ripple visible is by removing the `android:background="?bottomBarBackground"`line from the View element which I guess is not wanted. I found the issue that might be causing this:
> 
> [googlecodelabs/constraint-layout#50](https://github.com/googlecodelabs/constraint-layout/issues/50)
> 
> Maybe the View's background (`@drawable/home_bottom_bar_background`) could be changed somehow?
> If not I would reconsider the "square ripple" :-)
> 
> Thanks for any advice
> 
> Screenshot from 2020-09-29 20-08-23

@ekager any advice here?

**Comment by pocmo** [comment]
Could we consider using the actual toolbar here? I think some time ago we added all needed functionality in AC for that. And those are exactly the issues we fixed in the toolbar - we kind of relive all of that again here. :)

**Comment by mcarare** [comment]
This PR is obsolete, as the issue is fixed in AC.

**Pull request closed without merging**
