### PR TITLE
Bug 1608874 - part 3: Let fennec-production upload APKs on Google Pla…

### PR DESCRIPTION
**Pull request by JohanLorenzo**
…y's alpha track

Same as https://github.com/mozilla-mobile/fenix/pull/8686 but for `fennec-production`.

Follows https://github.com/mozilla-mobile/fenix/pull/11048 and https://github.com/mozilla-mobile/fenix/pull/11225 up

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by JohanLorenzo** [comment]
Feel free to merge this PR whenever you want to use the `fennec/production` branch, @pocmo

**Comment by pocmo** [comment]
@JohanLorenzo Is this a requirement for using the hook. Or can we create "release" builds with the hook (that we download from taskcluster) and land this as soon as we need something on Google Play?

**Comment by JohanLorenzo** [comment]
@pocmo, the latter! I kicked the hook off yesterday (without this patch) and it populated https://firefox-ci-tc.services.mozilla.com/tasks/index/mobile.v2.fenix.fennec-production.latest/x86_64. 

This patch is just about shipping things to Google Play.

**Comment by liuche** [comment]
We're getting pretty close to release! Do we need this for release @pocmo ?

**Comment by pocmo** [comment]
Yeah, we will for the fennec production migration release.

**Pull request merged**
