### PR TITLE
For #18195: Handle Package visibility changes in Android 11

### PR DESCRIPTION
**Pull request by mcarare**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by pocmo — COMMENTED** [review]
The fix looks good. But I wonder if we should go to `QUERY_ALL_PACKAGES` directly. It seems like we will not get around if for some functionality. Even Google lists browsers as an exception.

**Comment by mcarare** [comment]
I thought of that, but I am not sure if and what downside would be to using `QUERY_ALL_PACKAGES`. There are none mentioned and browsers are in the apps listed as proper use cases for that. 

Besides privacy concerns, I am not sure why there is also a warning about using it. I thought we could use specific queries on the Fenix side as there are fewer use cases here, and as our policy is to gahter just info we strictly need.

I am not sure about possible changes in AC. For example, using `QUERY_ALL_PACKAGES` in Fenix manifest does not fix https://github.com/mozilla-mobile/fenix/issues/18223

**Comment by pocmo** [comment]
> Besides privacy concerns, I am not sure why there is also a warning about using it. I thought we could use specific queries on the Fenix side as there are fewer use cases here, and as our policy is to gahter just info we strictly need.

I don't necessarily see a privacy concern since that is not data that gets shared outside of the application.

> I am not sure about possible changes in AC. 

One thing I was thinking about is Android Autofill (password managers seem to be another exception managed by Google). In that situation I need to query the package manager to read the signatures of the application to autofill. And that I cannot really express as an intent query.

**Comment by Amejia481** [comment]
> One thing I was thinking about is Android Autofill (password managers seem to be another exception managed by Google). In that situation I need to query the package manager to read the signatures of the application to autofill. And that I cannot really express as an intent query.

Same requirements for allowing external download managers https://github.com/mozilla-mobile/fenix/issues/18236

**Comment by mcarare** [comment]
> I don't necessarily see a privacy concern since that is not data that gets shared outside of the application.

Personally, I do not see privacy concerns either, I just brought it up because it is mentioned several times in the documentation. So I am not sure how it will impact our Google Play listing for example.

Quoted from [package-visibility](https://developer.android.com/training/basics/intents/package-visibility):
>By making some apps not visible by default, the system helps encourage the principle of least privilege by telling the system which other apps to make visible to your app, and it helps app stores like Google Play assess the privacy and security that your app provides for users.

>To respect user privacy, your app should request the smallest amount of package visibility necessary in order for your app to work.

>In an upcoming policy update, look for Google Play to provide guidelines for apps that need the QUERY_ALL_PACKAGES permission.


IMO using `QUERY_ALL_PACKAGES` is the most direct and simple solution, I just wished the documentation was more clear about it's usage implications.

**Comment by Amejia481** [comment]
Adding  `<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />` fixes #18236, I think we should add the permission as we have a valid use case for it.

**Comment by mcarare** [comment]
I have updated the PR with the permission. We should follow-up on the future Google Play policies changes about using this permission and implications to our app listing in the store.

**Review by pocmo — APPROVED** [review]
👍 

Maybe this will cause a manual or more thorough review of the app the next time we publish it on Google Play. A couple of times in the past review/updates were delayed. Let's see, maybe this will trigger something too. :)

**Pull request merged**
