### PR TITLE
For #26511: apply wallpapers immediately and observe updates

### LINKED ISSUE #26511: [Bug]: Wallpaper loading on launch is delayed
### Steps to reproduce

1. Install the latest Nightly 105.0a1 from 08/17 or Update the app to the latest version and perform a clear data.
2. From Settings > Homepage > Opening screen select "Homepage".
3. From Settings > Homepage > Wallpapers select any wallpaper.
4. Close and Re-open Fenix. 
5. On start-up, observe the wallpaper on the homepage.

### Expected behaviour

The wallpaper loads without visual issues or significant delay, given a good and stable network connection. 

### Actual behaviour

The wallpaper loading on homepage is delayed with 1-3 seconds when launching the app, even with a good and stable network connection.
The issue occurs after every restart, not only the first launch. 

### Device name

Xiaomi 12 Pro

### Android version

Android 12

### Firefox release type

Firefox Nightly

### Firefox version

latest Nightly 105.0a1 from 08/17 

### Device logs

_No response_

### Additional information

Also reproduced with: Samsung Galaxy A32 (Android 11), Samsung Galaxy S22 Ultra (Android 12), Lenovo Yoga Tab 11 (Android 11).

https://user-images.githubusercontent.com/89388888/185162020-4c023311-7032-4a2c-836b-d7ae3b0ac62a.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21318)

### PR DESCRIPTION
**Pull request by MatthewTighe**
I'm having trouble uploading a recording to Github, but this should address the issue of applying the wallpaper too late and causing a flash. It will also ensure that orientation changes work correctly. If the reviewer would like video please ping me. 

This will hopefully simplify things a bit, such that the wallpaper application workflow looks like the follow:
- when home screen is created apply wallpaper saved in settings, then start observing for updates. ignore updates that try to apply the last applied wallpaper
- on orientation changes apply wallpaper saved in settings

I ran perf tests on a Samsung A51 with no wallpaper set to make sure that this also did not include a regression. Here are the results:

| | main | patch |
| --- | --- | --- |
| replicate count: | 50 | 50 | 
| max: | 675 | 668 |
| mean: | 597 | 602 |
| median: | 584 | 598 |
| min: | 565 | 558 |

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #26511

### CODE REVIEW

**Comment by Mugurell** [comment]
This blocks `onCreateView` to load and set the wallpapers (what happens in Release 104) and will then start observing the store for changes (new functionality).
It works but I think by blocking onCreateView to load the bitmap there will be a performance penalty.
I would've still prefer to have this wallpapers functionality extracted from `HomeFragment` but in the end it solves the issue now.

**Review by Mugurell — APPROVED** [review]
This blocks `onCreateView` to load and set the wallpapers (what happens in Release 104) and will start observing the store for changes after (new functionality).
It works but I think by blocking onCreateView to load the bitmap there will be a performance penalty.
I would've still prefer to have this wallpapers functionality extracted from `HomeFragment` but in the end it solves the issue now.

**Comment by MatthewTighe** [comment]
> This blocks onCreateView to load and set the wallpapers (what happens in Release 104) and will start observing the store for changes after (new functionality).
It works but I think by blocking onCreateView to load the bitmap there will be a performance penalty.
I would've still prefer to have this wallpapers functionality extracted from HomeFragment but in the end it solves the issue now.

I think these are both valid concerns. However, since we this shouldn't be a performance regression from the last known working release version I would still prefer to land this for the MR and revisit any performance concerns as they arise. Additionally, any performance hit should only affect users with wallpapers and those users will need to wait for the wallpaper to load before the screen becomes interactive anyway.

I would be happy to move the logic from the `HomeFragment` back into a utility if you would prefer, this was mostly a choice for expedience. Since this is now approved I would also consider doing it in a follow-up in order to land before soft freeze.

**Comment by MatthewTighe** [comment]
I compared this patch with today's main on my Moto G5 as well to get a fuller sense of the performance impact and am seeing that there is still no impact to users without a wallpaper. 

| | main | patch |
| --- | --- | --- |
| replicate count: | 50 | 50 | 
| max: | 1094.0 | 1088.0 |
| mean: |  1052.34 | 1044.66 |
| median: |  1053.0 | 1051.5 |
| min: | 1012.0 | 1016.0 |

With these findings establish I am going to go ahead and land this patch

**Pull request merged**
