### PR TITLE
Change hyphens to underscores in ic_launcher_round.png

### PR DESCRIPTION
**Pull request by mitchhentges**
---

Should resolve [this build failure](https://tools.taskcluster.net/groups/HbU-SGC7T5aE1KtMm-sktA/tasks/NnCubyRTQjCWj9qMyYN4Hw/runs/1/logs/public%2Flogs%2Flive.log)

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by mitchhentges** [comment]
The build is failing, but so is [recent `master` builds](https://github.com/mozilla-mobile/fenix/commits/master)

**Comment by sblatz** [comment]
I'm rebasing off of master and pushing again :)

**Comment by sblatz** [comment]
Oops accidentally closed this 🤦‍♂

**Comment by sblatz** [comment]
Okay I somehow really messed up this PR... @mitchhentges can you push again after doing a `git pull origin master --rebase`?

**Comment by mitchhentges** [comment]
I did a [copy of this PR](https://github.com/mozilla-mobile/fenix/pull/6505) for the release branch which landed. I think it got landed on `master`, and that's why git can't see a difference between this branch and `master` :)

**Comment by sblatz** [comment]
That makes sense. Just panicked I ruined your PR 😅

**Pull request closed without merging**
