### PR TITLE
Closes #1657 - Use Gecko for downloads

### LINKED ISSUE #1657: FNX-2437 ⁃ Fenix should use Gecko's downloading streaming API instead of the Android manager
## Steps to reproduce
1. Visit https://ebookclub.tor.com/ and provide an email address to prove you've signed up (sorry, the download's behind an account. Maybe other downloads are similarly affected, I don't know.)
1. Download the `.epub` edition of Cory Doctorow's "Walkaway"

### Expected behavior
1. The download completes properly and is about 1.36MB in size.
(This is what happens when I do this with Firefox for Android Beta)

### Actual behavior
1. The download "completes" at 25.79KB, and is an invalid file

### Device information
* Android device: Samsung Galaxy A5
* Fenix version: 1.0.1916 build#11051220 68.0a1-20190408104625

### LINKED ISSUE #2809: [Bug] Saving images from Google Images downloads an image.bin file
## Steps to reproduce
Search something on google.com
Touch "images" 
Touch an image
Long press the image
Select save image on the context menu

### Expected behavior
Fenix downloads the image with its actual name and file extension 

### Actual behavior
Fenix download an images.bin file

### Device information
* Android device: Galaxy A5 2017 8.0 
* Fenix version: 1.0.1921

### LINKED ISSUE #3465: FNX3-17034 ⁃ [Bug] File downloads do not show up in notifications
## Steps to reproduce
1. Go to any web site offering a download of a file. Technical datasheets work best since they are easiest to get.
1. Initiate the download.

### Expected behavior
The file downloads and a notification is shown updating the user on the download progress and results.

### Actual behavior
No notification is shown, it is impossible to determine if the download has failed or succeeded unless the file is seen in any file manager.

### Device information
Notifications are enabled for both Firefox and the Files app. 

* Android device: Nokia 8, running Android 9 with May security patch.
* Fenix version: 1.0.1924, build 11641808

### LINKED ISSUE #4336: [Bug] Some download file names truncated inappropriately
Trying to download files with periods in their name will have everything after the first period truncated.

## Steps to reproduce
Many ways to trigger this but for the sake of testing try downloading these 2 files:

1. https://www.apkmirror.com/apk/google-inc/messenger-google-inc/messenger-google-inc-4-7-056-release/messages-4-7-056-kraken_rc13_xxxhdpi-arm64-v8a-phone-android-apk-download/download/

2. https://download.msfjarvis.website/caesium/wahoo/beta/Caesium-wahoo-v3.6-b792615ced1b.zip

### Expected behavior
Actual file names are:

1. `com.google.android.apps.messaging_4.7.056_(Kraken_RC13_xxxhdpi.arm64-v8a.phone)-47056249_minAPI21(arm64-v8a)(560,640dpi)_apkmirror.com.apk`. 

2. `Caesium-wahoo-v3.6-b792615ced1b.zip`

These are also the file names when downloaded on other browsers (Chrome, Firefox desktop, etc).

### Actual behavior
In fenix the downloaded file names are: 

1. `com.apk`

2. `Caesium-wahoo-v3.zip`

### Device information

* Android device: Pixel 2XL Android 9
* Fenix version: Nightly 190726 06:03 (Build #12070610) 📦: 6.0.0 🦎: 68.0-20190711090008 (but has been happening for a few versions now)

Could https://github.com/mozilla-mobile/android-components/commit/b2a1f28277c91cfc2db0369d01b7572ccba8d001 be related?

This is a huge problem in my opinion as most apk downloads are named com.apk and files with version numbers in their name (e.g. v3.1.zip and v3.2.zip) also get the same name (v3.zip).

Screenshot_Firefox_Preview_20190727-075729
Screenshot_Firefox_Preview_20190726-094241

### PR DESCRIPTION
**Pull request by NotWoods**
Turns on the new gecko based downloader.

Also: 
- For #999
- Closes #2809
- Closes #3465
- Closes #4336

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by pocmo** [comment]
https://github.com/mozilla-mobile/android-components/issues/3900

**Comment by boek** [comment]
Let's land this after the 1.2 release branch gets cut so this cane bake on Nightly for some time :+1:

**Comment by NotWoods** [comment]
Now that we've cut 1.2 should this get merged?

**Comment by ekager** [comment]
Let's do it!

**Pull request merged**
