### PR TITLE
Increasing the "Scan" and "Search engine" option items from 40 dp, to…

### PR DESCRIPTION
**Pull request by Debanshu777**
… 48 dp. Solution: #16829
Initial Imge of the layout

Final image of layout

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by cadeyrn** [comment]
It's not my decision, someone from Mozilla's UX people has to decide - but to me it looks like the border radius of the active button should be increased a bit as well with the new height.

**Comment by Debanshu777** [comment]
@cadeyrn okay that's a good point that you mentioned. Let's see what are others view on the changes

**Comment by apbitner** [comment]
@Debanshu777 Thank you for taking a look at this. Couple questions:

1. When you used the accessibility scanner, did you scan the entire app? Reason I ask is if we're changing something like a button size, it should be changed in all instances of the button.
2. While 48dp is the ideal touch target size, it's also acceptable to have an element that is smaller in size, but has enough margin/padding around it to create a 48dp touch target area, do you know if that's the case here?

**Comment by topotropic** [comment]
To pick this up again, is there a way to define the touch target without changing the button size? Changing button sizes has a ripple effect and if it's not possible to define the touch target independent of the visual button size, we have to make sure we address all instances in the app. Thanks!

**Comment by Mugurell** [comment]
There are multiple such issues in the SearchFragment which can be resolved by just increasing the tap area with no visible change to the layout. 
Opened https://github.com/mozilla-mobile/fenix/issues/24461 about that,

@Debanshu777 If you are still interested in helping this, I will close this PR in favor of the work to be done on for #24461.

**Comment by sharbet** [comment]
A quick question: Can the "Scan" button be hidden through preferences/about:config?

"Search engine" I know it can be hidden by selecting only having one engine and removing all others in pref.

For people who do not ever use the "Scan" function, it takes up viewing space in a small screen device.

Screenshot_20220328-222413_Firefox Nightly

**Comment by cadeyrn** [comment]
> A quick question: Can the "Scan" button be hidden through preferences/about:config?

No. An option is already suggested as #14150.

**Pull request closed without merging**
