### PR TITLE
For #6048 BookmarksScreenAlign

### PR DESCRIPTION
**Pull request by kglazko**
---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by kglazko** [comment]
Screen Shot 2019-12-02 at 3 44 34 PM

**Comment by kglazko** [comment]
@lime124 Attaching screenshot above, is this what you had in mind?

**Comment by ekager** [comment]
Hi @kglazko ! I don't love using negative margins here (and if we do have to use them to get what we want we should use `marginStart` and not `marginLeft`). Is there another way to get the same effect without negative margins? :)

**Comment by brampitoyo** [comment]
I’m reviewing the design on behalf of @lime124, and it looks good: r+

**Pull request closed without merging**
