### PR TITLE
Close #27320: Include testing regex to Google Maven allowlist

### LINKED ISSUE #27320: When running UI tests locally, the android-device-provider-local dependency cannot be found
@kycn and I were trying to run UI tests locally but were met with a missing dependency when trying to run on an emulator. There have been some dependency upgrades recently, so I suspect this is some fallout where the location of the dependency was moved to the google maven repo.

```
Execution failed for task ':app:connectedDebugAndroidTest'.
> Could not resolve all files for configuration ':app:_internal-unified-test-platform-android-test-plugin-host-additional-test-output'.
   > Could not find com.google.testing.platform:android-device-provider-local:0.0.8-alpha07.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/google/testing/platform/android-device-provider-local/0.0.8-alpha07/android-device-provider-local-0.0.8-alpha07.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :app > com.android.tools.utp:android-test-plugin-host-additional-test-output:30.3.0

```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21755)

### PR DESCRIPTION
**Pull request by jonalmeida**
When running UI tests locally, we found that the `android-device-provider-local` dependency is no longer available on mavenCentral. Our dependency repository uses various regex to allow only google dependencies to be fetched from Google Maven, but somehow these did not include the test ones everywhere.

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [ ] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #27320

### CODE REVIEW

**Review by Amejia481 — APPROVED** [review]

**Review by kycn — APPROVED** [review]
Great! I have one question in my mind though: What is keeping us away from generalizing it to `RepoMatching.comGoogle` in order to prevent future inconveniences for Google maven repositories in other usecases? Performance and security concerns?

**Comment by jonalmeida** [comment]
> Great! I have one question in my mind though: What is keeping us away from generalizing it to `RepoMatching.comGoogle` in order to prevent future inconveniences for Google maven repositories in other usecases? Performance and security concerns?

I'm not aware of the reason for the separation, but looking a bit deeper at the git history, I suspect that the first addition was made to be as specific as possible `com.google.firebase` and as new dependencies moved to Google Maven over time, new scopes were added instead of expanding the existing one.

The commit messages do not make it clear if there were any other concerns which is why the pattern continued. Although, I suspect we could argue that it does help with build speed if we scope these regex for our dependencies to be as specific as possible.

Maybe if a wild @mcomella appears, they might know!

**Comment by mcomella** [comment]
> What is keeping us away from generalizing it to RepoMatching.comGoogle in order to prevent future inconveniences for Google maven repositories in other usecases? Performance and security concerns?

When `comGoogleAndroid` and `comGoogleFirebase` was originally added ([commit](https://github.com/mozilla-mobile/fenix/commit/f0464b9e72e0ea4dca94a46f8e0f05a285955c44#diff-75b31066e97e27961c3c9e9668c539a133d73c10398dc76552df3f0119810ac0R236)), I don't think it was possible (or at least easy) to generalize because `comGoogleAndroid` explicitly excluded some `com.google.android.*` deps that hadn't yet migrated from maven central to the google repo, i.e. it was defined as:
```kotlin
    const val comGoogleAndroid = "com\\.google\\.android\\.(?!apps\\.common\\.testing\\.accessibility\\.framework).*"
```

Now that it's defined more generically (i.e. Google is hosting more packages on their repo), it might be possible. In that case, it'd also be preferable to reduce duplication (like the root cause of this issue).

**Comment by jonalmeida** [comment]
Thanks Mike for the context, that's really helpful! I've filed https://github.com/mozilla-mobile/fenix/issues/27336 as a good first bug with detailed instructions on how to combine these regex into one.

**Pull request merged**
