### PR TITLE
For #26708 - Add search widget preview for nightly

### LINKED ISSUE #26708: [Bug]: Incorrect widget logo displayed in preview for Fenix Nightly
### Steps to reproduce

1. Long tap on the home screen of the device.
2. Search for the widget for Fenix Nightly.
3. Observe the logo displayed on the widget preview.

### Expected behaviour

The Firefox Nightly logo is displayed on the Firefox Nightly widget.

### Actual behaviour

The Firefox Preview logo is displayed on the Firefox Nightly widget.

### Device name

Google Pixel 6, Lenovo Yoga Tab 11

### Android version

Android 13, Android 11

### Firefox release type

Firefox Nightly

### Firefox version

106.0a1 from 08/30

### Device logs

_No response_

### Additional information

Also reproducible on other devices.
Note that for RC and Beta the logos are displayed accordingly.

widget

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21420)

### PR DESCRIPTION
**Pull request by Alexandru2909**
Added search widget preview for nightly.

https://user-images.githubusercontent.com/35462038/196936917-c25baedf-c60b-433f-9a3b-7643b62818b7.mp4

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #26708

### CODE REVIEW

**Comment by Alexandru2909** [comment]
The design was taken from [figma](https://www.figma.com/file/Is1zrCIke3CnqZWQkyfRuQ/search-widget?node-id=0%3A1068). Pinging @lime124 to check if this is the intended result for the widget preview.

**Review by MozillaNoah — APPROVED** [review]
the preview looks a little off on Github but looks good locally.

Engineering r+

**Comment by lime124** [comment]
sorry i didn't see the notification until just now. for what i can see in the video it looks like the icons are changing sizes between the different widgets? is that just an illusion?

**Comment by Alexandru2909** [comment]
> sorry i didn't see the notification until just now. for what i can see in the video it looks like the icons are changing sizes between the different widgets? is that just an illusion?

I agree the Fenix search widget previews do differ, as can be seen here: 
| Release | Beta | Nightly | Debug |
| --- | --- | --- | --- |
| https://raw.githubusercontent.com/mozilla-mobile/fenix/main/app/src/release/res/drawable-hdpi/fenix_search_widget.png</img> | https://raw.githubusercontent.com/mozilla-mobile/fenix/main/app/src/beta/res/drawable-hdpi/fenix_search_widget.png</img> | https://raw.githubusercontent.com/mozilla-mobile/fenix/main/app/src/main/res/drawable-hdpi/fenix_search_widget.png</img> | https://raw.githubusercontent.com/mozilla-mobile/fenix/5ab41b5344786e4e6daf19a79cb1199af35682f8/app/src/nightly/res/drawable-hdpi/fenix_search_widget.png</img> |

Do you think we could use a ticket to update the previews so theirs sizes won't differ ? Also, as can be seen in the video, Focus supports dark themed previews (the device I recorded on had dark theme set). Is this something we should see in Fenix too?

**Comment by lime124** [comment]
@Alexandru2909 idk if you last comment was to me, but yes, i think it would be worth looking into why the sizes are differing. i would expect them to be the same size.

**Comment by mavduevskiy** [comment]
@Alexandru2909 
Shouldn't we merge this and then [normalize](https://github.com/mozilla-mobile/fenix/issues/27877) icon sizes as a follow up? It looks like something that could be done asynchronously.

**Pull request merged**
