### PR TITLE
For #3174: Adds telemetry for bookmarks

### PR DESCRIPTION
**Pull request by sblatz**
### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by sblatz** [comment]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) **What questions will you answer with this data?**
- How often bookmark folders are deleted

2) **Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?**

* To measure how useful these features are

3) **What alternative methods did you consider to answer these questions? Why were they not sufficient?**

* N/A (These are baseline metrics)

4) **Can current instrumentation answer these questions?**

* Currently no, as these are some of the first metrics we're recording

5) **List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox [data c](https://wiki.mozilla.org/Firefox/Data_Collection)[ollection ](https://wiki.mozilla.org/Firefox/Data_Collection)[categories](https://wiki.mozilla.org/Firefox/Data_Collection) on the found on the Mozilla wiki.**

* All data is Category 2.

6) **How long will this data be collected?**

Until 04/01/2020

7) **What populations will you measure?**

* All release, beta, and nightly users with telemetry enabled.

8) **Please provide a general description of how you will analyze this data.**

* Glean / Amplitude

9) **Where do you intend to share the results of your analysis?**

* Only on Glean, Amplitude and with mobile teams.

**Comment by boek** [comment]
@sblatz Can you add documentation for the new metric to this file as well https://github.com/mozilla-mobile/fenix/blob/master/docs/metrics.md#bookmarks_management?

**Comment by sblatz** [comment]
@boek fixed!

**Comment by boek** [comment]
R+

# Data Review Form 
1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way?
Yes, in metrics.yaml and metrics.md

2) Is there a control mechanism that allows the user to turn the data collection on and off?
Fenix allows the user to disable telemetry in settings

3) If the request is for permanent data collection, is there someone who will monitor the data over time?
Has expiry  - 04/01/2020

4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?
All data is category 2

5) Is the data collection request for default-on or default-off?
telemetry is on by default

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?
no

7) Is the data collection covered by the existing Firefox privacy notice?
yes

8) Does there need to be a check-in in the future to determine whether to renew the data?
Will check-in near expir

9) Does the data collection use a third-party collection tool? **If yes, escalate to legal.**
no

**Pull request merged**
