### PR TITLE
For #22869: Renew metrics expiring in January

### PR DESCRIPTION
**Pull request by eliserichards**
For #22869

Renewing the following metrics for **one year**:
`android_autofill:`
     - supported 
     - enabled
     - request_matching_logins
     - request_no_matching_logins
     - search_displayed
     - search_item_selected 
     - unlock_cancelled
     - unlock_successful 
     - confirm_cancelled
     - confirm_successful

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by eliserichards** [comment]
# Request for Data Collection Renewal

 ## Renew for 1 year
Total: 10

`android_autofill:`
     - `supported`
     - `enabled`
     - `request_matching_logins`
     - `request_no_matching_logins`
     - `search_displayed`
     - `search_item_selected`
     - `unlock_cancelled`
     - `unlock_successful`
     - `confirm_cancelled`
     - `confirm_successful`

1) Provide a link to the initial Data Collection Review Request for this collection.
      - https://github.com/mozilla-mobile/fenix/pull/20547#issuecomment-889051503

2) When will this collection now expire?
      - This probe will now expire in January 2023 (one year). 

3) Why was the initial period of collection insufficient?
      -  These probes help the engineering team understand how our autofill service is being used. We want to continue monitoring this.

**Comment by rocketsroger** [comment]
> # Request for Data Collection Renewal
> 
>  ## Renew for 1 year
> 
> Total: 10
> 
> `android_autofill:` - `supported` - `enabled` - `request_matching_logins` - `request_no_matching_logins` - `search_displayed` - `search_item_selected` - `unlock_cancelled` - `unlock_successful` - `confirm_cancelled` - `confirm_successful`
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Add telemetry for Android Autofill feature. #20547 (comment)](https://github.com/mozilla-mobile/fenix/pull/20547#issuecomment-889051503)
> 
>     2. When will this collection now expire?
>        
>        * This probe will now expire in January 2023 (one year).
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * These probes help the engineering team understand how our autofill service is being used. We want to continue monitoring this.

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

**Comment by rocketsroger** [comment]
Change looks good, please update the data-review URL

**Comment by eliserichards** [comment]
Ready for review @rocketsroger 🚀

**Review by rocketsroger — APPROVED** [review]

**Pull request merged**
