### PR TITLE
Closes #4075: Add Feature Flag class

### LINKED ISSUE #4075: Add a single source class for feature flags
From the review comments here: https://github.com/mozilla-mobile/fenix/pull/4073#discussion_r303875989

### PR DESCRIPTION
**Pull request by jonalmeida**

### CODE REVIEW

**Comment by jonalmeida** [comment]
Oh yes, I removed all references to all the flags so removed the old flags.

**Comment by jonalmeida** [comment]
Hmm, this causes warnings that aren't very helpful..

Screen Shot 2019-07-16 at 4 01 27 PM

**Comment by jonalmeida** [comment]
What do y'all thing about making those convenience attributes lazy inits? Feels like an overkill for sure, but removes the misleading lint issues that would otherwise need a suppress annotation everywhere it's used?

```kotlin
// A convenience flag for production builds.
private val production by lazy { BuildConfig.BUILD_TYPE == "production" }
// A convenience flag for beta builds.
private val beta by lazy { BuildConfig.BUILD_TYPE == "beta" }
// A convenience flag  for the nightly build and (legacy) nightly channel in Google Play.
private val nightly by lazy { BuildConfig.BUILD_TYPE == "nightly" || BuildConfig.BUILD_TYPE == "nightlyLegacy" }
// A convenience flag for production builds.
private val debug by lazy { BuildConfig.BUILD_TYPE == "debug" }
```

**Comment by sblatz** [comment]
@jonalmeida 

> What do y'all thing about making those convenience attributes lazy inits? Feels like an overkill for sure, but removes the misleading lint issues that would otherwise need a suppress annotation everywhere it's used?

I'd say go for it. Getting these warnings everywhere would definitely confuse me 😅

**Comment by boek** [comment]
<3 thanks @jonalmeida!

**Pull request merged**
