### PR TITLE
For #4212: Control text not translated 

### PR DESCRIPTION
**Pull request by joshvocal**
* Replace the "quick brown fox" text in accessibility scale setting to:
This is sample text. It is here to show how text will appear when you increase or decrease the size with this setting.

* Replace original resource name to something different to allow translation to pick it up

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by joshvocal** [comment]
@apbitner I've added a screenshot for review. [Issue](https://github.com/mozilla-mobile/fenix/issues/4212#issue-471054972)

**Comment by apbitner** [comment]
Thanks, looks good 👍🏻

**Comment by joshvocal** [comment]
@mcarare Is there a way for me to check which UI test failed? I checked over [here on the CI](https://firefox-ci-tc.services.mozilla.com/tasks/JjBd7rquR3G6pxhmbcvFrg/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FJjBd7rquR3G6pxhmbcvFrg%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log) but I'm not sure which one failed.

**Comment by mcarare** [comment]
> @mcarare Is there a way for me to check which UI test failed? I checked over [here on the CI](https://firefox-ci-tc.services.mozilla.com/tasks/JjBd7rquR3G6pxhmbcvFrg/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FJjBd7rquR3G6pxhmbcvFrg%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log) but I'm not sure which one failed.

Can you do a rebase? I think the test will pass after that.

**Comment by liuche** [comment]
@joshvocal you just need a rebase, one of the dependencies from when you pulled from master is now out of date and a rebase on current master will fix that!

Excited for this change :)

**Pull request closed without merging**
