### PR TITLE
For #22870: Renew/remove metrics set to expire in February (backport #23453)

### PR DESCRIPTION
**Pull request by rocketsroger**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by eliserichards — APPROVED** [review]
r+ pending CI passes 👍

**Comment by jonalmeida** [comment]
In StorageStatsMetricsTest: `WHEN reporting THEN the values from the storageStats are accumulated` and `WHEN reporting THEN the query duration is measured` are failing because of the perf metrics expired.

If we're fine with losing the metrics for a week, (and in a Slack thread it sounds like we are) we can probably ignore these test failures.

**Comment by eliserichards** [comment]
I'm fine with merging this once the UI tests finish. Perf metrics are fixed [here](https://github.com/mozilla-mobile/fenix/pull/23506) and [here](https://github.com/mozilla-mobile/fenix/pull/23515) for nightly/beta

**Comment by eliserichards** [comment]
Unrelated UI test failure (mainMenuInstallPWATest). I think we can merge @rocketsroger

**Comment by rocketsroger** [comment]
> Unrelated UI test failure (mainMenuInstallPWATest). I think we can merge @rocketsroger

I think @jonalmeida will be updating this pr

**Comment by jonalmeida** [comment]
Let's let it run once more with the storage tests ignored and we should be good.

**Comment by jonalmeida** [comment]
I believe the UI tests are failing because it's missing: https://github.com/mozilla-mobile/fenix/pull/23335

Need to investigate.

**Comment by jonalmeida** [comment]
> I believe the UI tests are failing because it's missing: #23335
> 
> Need to investigate.

Confirmed we need this.

**Pull request merged**
