### PR TITLE
No issue: remove lint baseline file

### PR DESCRIPTION
**Pull request by mcomella**
More code for you to remove! 😁 

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by jonalmeida** [comment]
With warningsAsErrors, would this cause the builds to fail now or just clog up the build log? There's an unused import so I'm not sure if that would happen or not. Maybe we should incrementally remove those baseline warnings instead if that's the case?

**Comment by mcomella** [comment]
> With warningsAsErrors, would this cause the builds to fail now or just clog up the build log? 

This is a change for Android Lint, which does not have `warningsAsErrors` enabled (that's kotlin). It also runs as a separate task so it will not clog up the build log (but in any case, I believe it writes it to an HTML/XML report instead of printing straight to the build log anyway).

> There's an unused import so I'm not sure if that would happen or not.

This is for ktlint, which is unrelated.

> Maybe we should incrementally remove those baseline warnings instead if that's the case?

I think I've addressed your concerns in a good way but let me know if you disagree. :)

**Comment by mcomella** [comment]
Addressed the ktlint error.

**Comment by mcomella** [comment]
> # Configuration problem
> 
> bors.toml: not found

# 🙀

**Comment by hakkikaancaliskan** [comment]
Isn't bors removed from Fenix?

**Comment by jonalmeida** [comment]
Oh right, I forget. :)

**Pull request merged**
