### PR TITLE
No issue: add script to generate filled telemetry renewal request

### PR DESCRIPTION
**Pull request by MatthewTighe**
I had initially planned to automatically update `metrics.yaml` as well, but have run out of time for now to fiddle with it and get it working correctly. The _very_ WIP version of that work can still be found on [this branch](https://github.com/MatthewTighe/fenix/tree/script-renewal-metrics-update), in case anyone ever sees this and the work still needs to be done

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation

Used by GitHub Actions.

### CODE REVIEW

**Comment by gabrielluong** [comment]
I think this is a great effort to really automate and improve developer productivity. Just wanted to make sure that we also have some documentation somewhere about how to use this script.

**Comment by MatthewTighe** [comment]
> I think this is a great effort to really automate and improve developer productivity. Just wanted to make sure that we also have some documentation somewhere in the wiki about how to use this script.

Thanks! I'd been planning to update the release cutting wiki with the new step. Do you think there is additional need to better document usage in the script itself as well?

**Comment by MatthewTighe** [comment]
Added additional detail to the 4th step in [renew telemetry step of release cutting](https://github.com/mozilla-mobile/fenix/wiki/Creating-a-release-branch#dev-team-renew-telemetry)

**Review by rocketsroger — APPROVED** [review]

**Comment by MatthewTighe** [comment]
Had a last minute push to align some of the string formatting for `output_string`

**Pull request merged**
