### PR TITLE
For #11498 and #11499 - Add Sync tabs error view (with/without CTA)

### PR DESCRIPTION
**Pull request by BranescuMihai**
As per [this documentation](https://app.abstract.com/share/cb14ade9-a5a1-4ca9-8012-4350363cf5b4?collectionId=4d5f57be-0965-4faa-8ed4-8635c1f16660&collectionLayerId=20567809-1aac-4853-9b80-c52512f2eef2&present=true&preview=false&sha=2573c6a5589f3fb2e399c0c4027b69fc9a477d5d):

<details>
  <summary>Sign-in error</summary>

</details>
<details>
  <summary>No tabs error</summary>

</details>
<details>
  <summary>Re-authenticate error</summary>

</details>

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by BranescuMihai** [comment]
Currently waiting on https://github.com/mozilla-mobile/android-components/issues/7422 to get fixed on AC

**Comment by jonalmeida** [comment]
> Cold starting Fenix and rushing to synced tabs fragment leads to some strange concurrency issues.

We have two bugs filed that needs more account manager support:
 - https://github.com/mozilla-mobile/android-components/issues/7119
 - https://github.com/mozilla-mobile/android-components/issues/6879

**Comment by codrut-topliceanu** [comment]
@BranescuMihai Related AC issue/PR is now closed/merged

**Comment by BranescuMihai** [comment]
Progress: Still not merging this because there are some issues on AC that call `refreshSyncedTabs` twice, and the first time since the tabs are not yet synced, it will send to Fenix the NO_TABS error, leading to wrong UI behaviour. Will investigate after code freeze.

**Comment by ekager** [comment]
Product wants this CTA in our Sept release. Can we prioritize the blocking issues in AC or find a workaround @jonalmeida @BranescuMihai ?

**Comment by BranescuMihai** [comment]
Since the related bug is now explained in a different issue: https://github.com/mozilla-mobile/fenix/issues/12195, and this PR is only about a UI change, we can proceed with this one

**Pull request merged**
