### PR TITLE
Log FxA errors to Sentry and Socorro

### PR DESCRIPTION
**Pull request by Mugurell**
### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: No screenshots. No visible change.
- [x] **Accessibility**: The code in this PR follows does not include any user facing features.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by Mugurell** [comment]
This PR depends on https://github.com/mozilla-mobile/android-components/pull/8344 which is a breaking change.

**Comment by Mugurell** [comment]
Regarding what will be sent to Sentry, I tested with changing the password before sharing a tab and saw [this exception](https://github.com/mozilla-mobile/fenix/blob/5a1838e7022bb1bb438eceec29deaaa5fbd20dad/app/src/main/java/org/mozilla/fenix/share/ShareController.kt#L145) having the following stacktrace:

> mozilla.appservices.fxaclient.FxaException$Unauthorized: Remote server error: '401' '110' 'Unauthorized' 'Invalid authentication token in request signature' 'https://github.com/mozilla/fxa/blob/main/packages/fxa-auth-server/docs/api.md#response-format'
	at mozilla.appservices.fxaclient.rust.RustError.intoException(RustError.kt:44)
	at mozilla.appservices.fxaclient.FirefoxAccount.sendSingleTab(FirefoxAccount.kt:1045)
	at mozilla.components.service.fxa.FxaDeviceConstellation$sendCommandToDeviceAsync$1$1.invoke(FxaDeviceConstellation.kt:116)
	at mozilla.components.service.fxa.FxaDeviceConstellation$sendCommandToDeviceAsync$1$1.invoke(FxaDeviceConstellation.kt:35)
	at mozilla.components.service.fxa.UtilsKt$executeAndGetFxaExceptions$3.invokeSuspend(Utils.kt:80)
	at mozilla.components.service.fxa.UtilsKt$executeAndGetFxaExceptions$3.invoke(Unknown Source:10)
	at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:28)
	at mozilla.components.service.fxa.UtilsKt.handleFxaExceptions(Utils.kt:60)
	at mozilla.components.service.fxa.UtilsKt.executeAndGetFxaExceptions(Utils.kt:79)
	at mozilla.components.service.fxa.FxaDeviceConstellation$sendCommandToDeviceAsync$1.invokeSuspend(FxaDeviceConstellation.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by liuche** [comment]
@st3fan could you help get this through? it's been open waiting for feedback for a while.

**Comment by grigoryk** [comment]
I don't think we'll need this PR at all - see https://github.com/mozilla-mobile/android-components/pull/8344#pullrequestreview-515078421

**Comment by gabrielluong** [comment]
> I don't think we'll need this PR at all - see [mozilla-mobile/android-components#8344 (review)](https://github.com/mozilla-mobile/android-components/pull/8344#pullrequestreview-515078421)

@Mugurell it doesn't look like we need this PR judging by the activity in AC. I am closing this PR for now to tidy up our PR backlog, but feel free to reopen. Thanks!

**Pull request closed without merging**
