### PR TITLE
For #7978 - Remove ScrollView from migration activity 

### PR DESCRIPTION
**Pull request by codrut-topliceanu**
### Pull Request checklist

- [x] **Tests**: This PR includes a small layout change, no test needed.
- [x] **Screenshots**: This PR doesn't include screenshots or GIF because the change is not immediately visible. 
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) 

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by codrut-topliceanu** [comment]
@pocmo  This PR removes the scrollView and changes the views' constraints to be inline with the [abstract](https://app.abstract.com/share/b1b9f719-fbb5-4c94-b45d-556232a3cd52?collectionLayerId=41a90258-2dbf-434a-9cb2-b6b28e7b5fbc&present=true&preview=false&sha=abfe4a5d2df1d032690e4b5e693a5213cb78f064). It should all fit now without needing a scroll view. I've tested on a low DPI, small screen emulator. In case that is still not enough I've also made the RecyclerView scrollable.

**Comment by pocmo** [comment]
@codrut-topliceanu Oh, there's actually a conflict in `app/src/main/res/layout/activity_migration.xml` now. Can you resolve this?

**Comment by codrut-topliceanu** [comment]
@pocmo Should be okay now. Thank you.

**Comment by pocmo** [comment]
@codrut-topliceanu Great, thank you! I'll land this once the tasks have completed.

**Comment by pocmo** [comment]
The UI test failure seems umrelated and this screen is not part of the automated test suite. Landing!

**Pull request merged**
