### PR TITLE
For #21138: re-enable excessive resource use test.

### PR DESCRIPTION
**Pull request by mcomella**
This test wasn't running in CI
https://github.com/mozilla-mobile/fenix/issues/20386 so we changed the
CI configuration so that it will. However, the test was then failing so
this is the revision that unignores the test.

I wonder if componentInit count is useful - it seems like it'd cause
more false positives than not - but I figure we can leave it in and see
how it goes.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by MarcLeclair — APPROVED** [review]
Looks good to me. Hopefully we can keep track of it this time 👍

**Comment by mcomella** [comment]
The test failure was:
```
 java.lang.AssertionError: runBlockingIncrement count does not match expected count.
...
expected:<0> but was:<1> 
```

Unfortunately, I can't reproduce this failure on either of my devices. That implies this test takes a different code path in Firebase UI testing than it does locally. I'm concerned this could also happen on other physical devices which would make this test confusing to debug in the future. That being said, if we really want this to run, perhaps we can specify a range instead, e.g. 0-1 failures is okay. And if we need to increment, we could increment both ends of the range.

**Comment by mcomella** [comment]
@MarcLeclair I pushed a fix for the test failure: please re-review.

**Review by MarcLeclair — APPROVED** [review]
👍

**Comment by mcomella** [comment]
It passed so let's land.

**Pull request merged**
