### PR TITLE
Basic Firefox Accounts integration

### PR DESCRIPTION
**Pull request by grigoryk**
Marking this as a DRAFT because the PR currently has the wrong Fxa Client ID. Blocked on https://bugzilla.mozilla.org/show_bug.cgi?id=1528355.

This PR does three things:
- configures Fenix to consume a Fenix Megazord (necessary because we're now going to use multiple appservices native dependencies - fxa and places)
- configures Rust logging
- adds a basic Firefox Accounts integration. Sign-in is supported. Profile information is displayed in the settings.

There's currently no "Accounts UI", so no interaction with the account is possible just yet. E.g. to sign-out, clear application data.

I'm hesitant to land sync support right now since that part of a-c is going to see a lot of churn soon (see https://github.com/mozilla-mobile/android-components/pull/2076 and https://github.com/mozilla-mobile/android-components/issues/1369). However, once we have an accounts UI, we _could_ trivially do a very simple integration via currently available `FirefoxSyncFeature` that will provide a "Sync Now" functionality.

### CODE REVIEW

**Comment by grigoryk** [comment]
I've left some TODOs in the code that are necessary to make the UI integration nicer. Should be fine to address in a follow-up, cc @sblatz  .

**Comment by grigoryk** [comment]
Once we have a real Client ID, I'll update the PR and "undraft" it.

**Comment by grigoryk** [comment]
@vladikoff I'm getting a 500 error when I use the clientId assigned in https://bugzilla.mozilla.org/show_bug.cgi?id=1528355. Switching back to clientId used in reference-browser, and it all works. Can you help debug this?

**Comment by vladikoff** [comment]
@grigoryk we need to wait for 1.131.1 to be deployed at https://accounts.firefox.com/ver.json

per: https://github.com/mozilla/fxa-content-server/blob/master/CHANGELOG.md#chore

**Comment by vladikoff** [comment]
@jrgm do we have an ETA for 1.131.1 deploy or should we backport the Fenix support for 1.130?

**Comment by jrgm** [comment]
> @jrgm do we have an ETA for 1.131.1 deploy or should we backport the Fenix support for 1.130?

I'm ready to put that live in the next hour.

**Comment by vladikoff** [comment]
@jrgm amazing!

**Comment by grigoryk** [comment]
@jrgm @vladikoff so just to confirm, no Fenix-side changes are necessary?

**Comment by vladikoff** [comment]
> @jrgm @vladikoff so just to confirm, no Fenix-side changes are necessary?

Should not be :), I will follow up

**Comment by vladikoff** [comment]
try now?

**Comment by grigoryk** [comment]
@vladikoff it works!

**Comment by colintheshots** [comment]
Will this work if we land it with A-C 0.43? We had to downgrade because of a bug in 0.45 that seems to cause repeated crashes.

**Comment by grigoryk** [comment]
@colintheshots 0.43 is fine.

**Comment by csadilek** [comment]
Closing this in favour of: https://github.com/mozilla-mobile/fenix/pull/720 (rebased and conflicts resolved.)

**Pull request closed without merging**
