### PR TITLE
For #11456: AddonDetailsFragment should use ConstraintLayout, not RelativeLayout

### PR DESCRIPTION
**Pull request by hakkikaancaliskan**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by NotWoods** [comment]
The margins should be the same as the current RelativeLayout. It looks like the bottom margins aren't being applied, you should try [chaining](https://constraintlayout.com/basics/create_chains.html) the items.

**Comment by hakkikaancaliskan** [comment]
> 
> 
> The margins should be the same as the current RelativeLayout. It looks like the bottom margins aren't being applied, you should try [chaining](https://constraintlayout.com/basics/create_chains.html) the items.



> 
> 
> The margins should be the same as the current RelativeLayout. It looks like the bottom margins aren't being applied, you should try [chaining](https://constraintlayout.com/basics/create_chains.html) the items.

There is just android:layout_below="@+id/details" used in code and I'm unable to find dp's.
What should be they?
Screenshot_20200611-184212_Firefox_Nightly

**Comment by NotWoods** [comment]
The `details` text view has a bottom margin of 20dp, the lines between each item have a vertical margin of 10dp

**Comment by hakkikaancaliskan** [comment]
> 
> 
> The `details` text view has a bottom margin of 20dp, the lines between each item have a vertical margin of 10dp

details view's bottom margin doesn't worked. So I moved it to author_label via top margin and it worked. Used chains.
Screenshot_1591891853

**Comment by liuche** [comment]
@NotWoods I see that this has some test failures when trying to push it to run CI:
    DefaultBrowserToolbarControllerTest. handleToolbarCloseTabPress
    DefaultBrowserToolbarControllerTest. handleToolbarNewPrivateTabPress
    DefaultBrowserToolbarControllerTest. handleToolbarNewTabPress

**Comment by NotWoods** [comment]
I think those are unrelated to this change, we have issues on master too.

**Comment by ekager** [comment]
Pulled into https://github.com/mozilla-mobile/fenix/pull/11491 to run CI and land

**Pull request closed without merging**
