### PR TITLE
Public API changes related to 0.52.0 A-S bump ⪮ 

### PR DESCRIPTION
**Pull request by grigoryk**
Requires https://github.com/mozilla-mobile/android-components/pull/6060

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by grigoryk** [comment]
https://github.com/mozilla-mobile/android-components/pull/6060 is in the process of landing. I'll trigger a snapshot build once that happens, and will land this PR right after.

**Comment by grigoryk** [comment]
New snapshot should be available now. Let's re-run.

**Comment by grigoryk** [comment]
Latest UI test failure:
```
02-26 02:37:02.420: E/TestRunner(9041): failed: goForwardTest(org.mozilla.fenix.ui.NavigationToolbarTest)
02-26 02:37:02.420: E/TestRunner(9041): ----- begin exception -----
02-26 02:37:02.421: E/TestRunner(9041): androidx.test.espresso.PerformException: Error performing 'replace text(http://localhost:58848/pages/generic2.html)&#39; on view 'with id: org.mozilla.fenix.debug:id/mozac_browser_toolbar_edit_url_view'.
02-26 02:37:02.421: E/TestRunner(9041): 	at androidx.test.espresso.PerformException$Builder.build(PerformException.java:86)
02-26 02:37:02.421: E/TestRunner(9041): 	at androidx.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:87)
02-26 02:37:02.421: E/TestRunner(9041): 	at androidx.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:59)
02-26 02:37:02.421: E/TestRunner(9041): 	at androidx.test.espresso.ViewInteraction.waitForAndHandleInteractionResults(ViewInteraction.java:322)
02-26 02:37:02.421: E/TestRunner(9041): 	at androidx.test.espresso.ViewInteraction.desugaredPerform(ViewInteraction.java:178)
02-26 02:37:02.421: E/TestRunner(9041): 	at androidx.test.espresso.ViewInteraction.perform(ViewInteraction.java:119)
02-26 02:37:02.421: E/TestRunner(9041): 	at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:57)
02-26 02:37:02.421: E/TestRunner(9041): 	at org.mozilla.fenix.ui.NavigationToolbarTest.goForwardTest(NavigationToolbarTest.kt:82)
02-26 02:37:02.421: E/TestRunner(9041): 	at java.lang.reflect.Method.invoke(Native Method)
02-26 02:37:02.421: E/TestRunner(9041): 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
02-26 02:37:02.421: E/TestRunner(9041): 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
02-26 02:37:02.421: E/TestRunner(9041): 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
02-26 02:37:02.421: E/TestRunner(9041): 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
02-26 02:37:02.421: E/TestRunner(9041): 	at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
02-26 02:37:02.421: E/TestRunner(9041): 	at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
02-26 02:37:02.421: E/TestRunner(9041): 	at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
02-26 02:37:02.421: E/TestRunner(9041): 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
02-26 02:37:02.421: E/TestRunner(9041): 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
02-26 02:37:02.421: E/TestRunner(9041): 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
02-26 02:37:02.421: E/TestRunner(9041): 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
02-26 02:37:02.421: E/TestRunner(9041): 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
02-26 02:37:02.421: E/TestRunner(9041): 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
02-26 02:37:02.421: E/TestRunner(9041): 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
02-26 02:37:02.421: E/TestRunner(9041): 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
02-26 02:37:02.421: E/TestRunner(9041): 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
02-26 02:37:02.421: E/TestRunner(9041): 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
02-26 02:37:02.421: E/TestRunner(9041): 	at org.junit.runners.Suite.runChild(Suite.java:128)
02-26 02:37:02.421: E/TestRunner(9041): 	at org.junit.runners.Suite.runChild(Suite.java:27)
02-26 02:37:02.421: E/TestRunner(9041): 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
02-26 02:37:02.421: E/TestRunner(9041): 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
02-26 02:37:02.421: E/TestRunner(9041): 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
02-26 02:37:02.421: E/TestRunner(9041): 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
02-26 02:37:02.421: E/TestRunner(9041): 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
02-26 02:37:02.421: E/TestRunner(9041): 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
02-26 02:37:02.421: E/TestRunner(9041): 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
02-26 02:37:02.421: E/TestRunner(9041): 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
02-26 02:37:02.421: E/TestRunner(9041): 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
02-26 02:37:02.421: E/TestRunner(9041): 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
02-26 02:37:02.421: E/TestRunner(9041): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)
02-26 02:37:02.421: E/TestRunner(9041): Caused by: java.lang.RuntimeException: Action will not be performed because the target view does not match one or more of the following constraints:
02-26 02:37:02.421: E/TestRunner(9041): (is displayed on the screen to the user and is assignable from class: class android.widget.EditText)
02-26 02:37:02.421: E/TestRunner(9041): Target view: "InlineAutocompleteEditText{id=2131296953, res-name=mozac_browser_toolbar_edit_url_view, visibility=VISIBLE, width=1342, height=140, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=true, is-enabled=true, is-focused=false, is-focusable=true, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@5869561, tag=null, root-is-layout-requested=false, has-input-connection=true, editor-info=[inputType=0x11 imeOptions=0x12000002 privateImeOptions=null actionLabel=null actionId=0 initialSelStart=0 initialSelEnd=0 
02-26 02:37:02.421: E/TestRunner(9041): ----- end exception -----
02-26 02:37:02.423: I/TestRunner(9041): finished: goForwardTest(org.mozilla.fenix.ui.NavigationToolbarTest)
```

**Comment by mcarare** [comment]
If the UI test fails again I am going to try to fix it or disable it, so we can land this today.

**Comment by ekager** [comment]
@mcarare they've been a bit better today but still flaky. Try rerunning once more if it fails again before putting too much effort into it. Thank you for taking care of this! 💕

**Comment by pocmo** [comment]
tests = 💚

**Pull request merged**
