### PR TITLE
For #15796: Show device language under "Follow device language"

### PR DESCRIPTION
**Pull request by joc-a**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

Here is what it looks like now. My device language is English (United States).

Screenshot_1602429825
Screenshot_1602429843

### CODE REVIEW

**Comment by Poopooracoocoo** [comment]
And can you also see this in the main settings page?

**Comment by gabrielluong** [comment]
bors try

**Comment by gabrielluong** [comment]
@joc-a Thank you for the PR! This look great. I will bring this up tomorrow with product and ux to get some feedback about this before we proceed further.

**Comment by apbitner** [comment]
@brampitoyo I believe you worked on this screen originally, are you okay with the above change?

**Comment by brampitoyo** [comment]
@apbitner @gabrielluong Ah, I’m really sorry for the overdue reply! Yes. This is an excellent change. That way, people know exactly what language they’re switching from (or to).

**Review by brampitoyo — APPROVED** [review]
r+

**Review by gabrielluong — APPROVED** [review]

**Comment by gabrielluong** [comment]
bors try

**Comment by gabrielluong** [comment]
Closing this for https://github.com/mozilla-mobile/fenix/pull/15941 to run try.

**Comment by liuche** [comment]
Test failure here: https://firefoxci.taskcluster-artifacts.net/EhG1v7oDQ9CIOpWqv9aCdg/0/public/reports/test/testDebugUnitTest/index.html

Could you fix the test, and then re-push?

**Comment by gabrielluong** [comment]
Pushed a fix in https://github.com/mozilla-mobile/fenix/pull/15966. Closing to land the changes there.

**Pull request closed without merging**
