### PR TITLE
Fixes #22956: Define "tags" for metrics in the app repository

### LINKED ISSUE #22956: Define "tags" for metrics in the app repository
To make it easier to find Fenix metrics assigned to a particular feature area, we assign metrics tags. You can use them in the Glean Dictionary to quickly narrow down areas of interest. For example:

https://dictionary.telemetry.mozilla.org/apps/fenix?page=1&search=tags%3AWebExtensions

Currently the telemetry "tags" for Fenix are defined in the glean-annotations repository. For example:

https://github.com/mozilla/glean-annotations/tree/main/annotations/fenix/metrics/bookmarks_management.open_in_new_tabs

This has proven cumbersome to maintain (see, for example, [this wiki page](https://github.com/mozilla-mobile/fenix/wiki/Add-a-Glean-Annotation-for-an-event)). The latest glean release also allows defining these tags alongside the implementation, we should replace the annotations implementation with this, at least for the tags (the annotations repository also has documentation and other things stored in it, which is useful).

### PR DESCRIPTION
**Pull request by wlach**
Using the new "tags" feature in Glean, we can remove most of the
manual process/pain of defining tags in a seperate Glean annotations
repository (see: https://github.com/mozilla-mobile/fenix/wiki/Add-a-Glean-Annotation-for-an-event)
and just put them beside the metrics themselves. This should make it
much easier to keep this metadata up to date, since it can be added
in the same pull request as the instrumentation itself.

To keep the list of tags up to date with the Fenix issue labels, a new
script `update-glean-tags.py` has been added to the repository. It
should not need to be run often.

This pull request uses a scraped version of the defined tags in the
Glean annotations repository. After it lands, we can remove those and
just use the tagging information here as the main source of information.

### CODE REVIEW

**Comment by wlach** [comment]
The script to modify metrics.yaml is pretty simple: https://gist.github.com/wlach/3cf79411a043f32504db9a44af4abc69

I had to do a bit of (minor) formatting to make sure that only tag information actually got changed.

**Comment by wlach** [comment]
Hmm, CI is failing: it looks like the glean gradle plugin needs an update as the current version of glean parser currently used doesn't know about tags. It should be updated in the glean repo here as part of the `v42.2.0` release:

https://github.com/mozilla/glean/blob/main/CHANGELOG.md#v4220-2021-11-03

**Comment by wlach** [comment]
With the upgrade to android-services (and new glean) this seems to be working well now. Ready for review

**Review by rocketsroger — COMMENTED** [review]
Looks good to me.  🚢

**Comment by wlach** [comment]
> Looks good to me. ship One question. Does this mean that we should add new tags (if needed) to `tags.yaml` when adding new telemetry?

The idea (right now) is that the tags are a mirror of the `feature:` labels on GitHub:

https://github.com/mozilla-mobile/fenix/labels?q=feature%3A

There's a script in the repository added as part of this PR to allow regenerating `tags.yaml` when these labels are added or removed (note that you'll also need to update the metrics in that case). See the comment in the tags file itself:

https://github.com/mozilla-mobile/fenix/pull/22954/files#diff-da7ea8df1d4843419cfa6570993d3a350d1a4bd3ecda6f17a081c119ae45a8afR6

---

I attempted to document the details of this here: https://gist.github.com/wlach/2b058da4c4171fa3810f4080f89f02a0 -- perhaps this could replace https://github.com/mozilla-mobile/fenix/wiki/Add-a-Glean-Annotation-for-an-event once this lands?

**Comment by rocketsroger** [comment]
> I attempted to document the details of this here: https://gist.github.com/wlach/2b058da4c4171fa3810f4080f89f02a0 -- perhaps this could replace https://github.com/mozilla-mobile/fenix/wiki/Add-a-Glean-Annotation-for-an-event once this lands?

Thanks!

**Review by rocketsroger — APPROVED** [review]

**Comment by rocketsroger** [comment]
I've put up this change in https://github.com/mozilla-mobile/fenix/pull/23274.  I'll close this ones the other PR is merged.

**Comment by rocketsroger** [comment]
This change has been merged.

**Comment by rocketsroger** [comment]
> > This change has been merged.
> 
> Thank you! Don't forget to update the documentation when you have time:
> 
> [#22954 (comment)](https://github.com/mozilla-mobile/fenix/pull/22954#issuecomment-1012138578)

Sure, I'll update the documentation.  Thanks!

**Pull request closed without merging**
