### PR TITLE
Workflow to build contributor PRs

### PR DESCRIPTION
**Pull request by st3fan**
Experimental GitHub Actions Workflow to build contributor pull requests. I took most of this workflow from https://github.com/fork-maintainers/iceraven-browser and modified it slightly.

TODO Enable the checks to make sure this only runs on forks.

### CODE REVIEW

**Review by escapewindow — APPROVED** [review]
Stamp!

**Comment by sv-ohorvath** [comment]
Please rebase, the blocking test was disabled: https://github.com/mozilla-mobile/fenix/commit/f0b7b3b987202339a5affbe76c5b857405f004a6

**Comment by pocmo** [comment]
Do we really want that though? We had travis/buddybuild and others in parallel and it was always triple the pain to have two build systems.

**Comment by st3fan** [comment]
> Do we really want that though? We had travis/buddybuild and others in parallel and it was always triple the pain to have two build systems.

@pocmo Very good point. We met with RelEng and agreed this would be a temporary solution until we can build contributor PRs on on Task Cluster using the same CI (or subset) of what we use.  I also included checks in this workflow so that it will only run on forks so it should not get in the way of work happening in the main repo.

**Review by eliserichards — APPROVED** [review]
Awesome 🎉

**Comment by st3fan** [comment]
Is this a test that requires a device?

```
2021-02-17T18:37:56.1296626Z SUITE: org.mozilla.fenix.utils.ManufacturerCodesTest
2021-02-17T18:37:56.1297736Z   TEST: testIsLG
2021-02-17T18:37:56.6293639Z   FAILURE
```

**Comment by st3fan** [comment]
This is odd?

```
2021-02-17T18:34:58.6299793Z SUITE: org.mozilla.fenix.home.sessioncontrol.viewholders.onboarding.OnboardingAutomaticSignInViewHolderTest
2021-02-17T18:34:58.7295652Z   TEST: sign in on click - MigrationResult WillRetry treated the same as Success
2021-02-17T18:34:58.7301080Z     [Robolectric] org.mozilla.fenix.home.sessioncontrol.viewholders.onboarding.OnboardingAutomaticSignInViewHolderTest.sign in on click - MigrationResult WillRetry treated the same as Success: sdk=28; resources=BINARY
2021-02-17T18:34:58.7305415Z     I/MonitoringInstr: Instrumentation started!
2021-02-17T18:34:59.6300874Z     Error transferring file: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
2021-02-17T18:34:59.6307354Z     [WARNING] Unable to get resource 'org.robolectric:android-all:pom:5.0.2_r3-robolectric-r0' from repository sonatype (https://oss.sonatype.org/content/groups/public/): Error transferring file: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
2021-02-17T18:34:59.6311129Z     Downloading: org/robolectric/android-all/5.0.2_r3-robolectric-r0/android-all-5.0.2_r3-robolectric-r0.pom from repository central at http://repo1.maven.org/maven2
2021-02-17T18:34:59.7303134Z     Error transferring file: Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/org/robolectric/android-all/5.0.2_r3-robolectric-r0/android-all-5.0.2_r3-robolectric-r0.pom
2021-02-17T18:34:59.7307897Z     [WARNING] Unable to get resource 'org.robolectric:android-all:pom:5.0.2_r3-robolectric-r0' from repository central (http://repo1.maven.org/maven2): Error transferring file: Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/org/robolectric/android-all/5.0.2_r3-robolectric-r0/android-all-5.0.2_r3-robolectric-r0.pom
2021-02-17T18:34:59.7311291Z     Downloading: org/robolectric/android-all/5.0.2_r3-robolectric-r0/android-all-5.0.2_r3-robolectric-r0.jar from repository sonatype at https://oss.sonatype.org/content/groups/public/
2021-02-17T18:34:59.8328664Z     Error transferring file: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
2021-02-17T18:34:59.8334003Z     [WARNING] Unable to get resource 'org.robolectric:android-all:jar:5.0.2_r3-robolectric-r0' from repository sonatype (https://oss.sonatype.org/content/groups/public/): Error transferring file: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
2021-02-17T18:34:59.8337784Z     Downloading: org/robolectric/android-all/5.0.2_r3-robolectric-r0/android-all-5.0.2_r3-robolectric-r0.jar from repository central at http://repo1.maven.org/maven2
2021-02-17T18:34:59.8340384Z     Error transferring file: Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/org/robolectric/android-all/5.0.2_r3-robolectric-r0/android-all-5.0.2_r3-robolectric-r0.jar
2021-02-17T18:34:59.8343931Z     [WARNING] Unable to get resource 'org.robolectric:android-all:jar:5.0.2_r3-robolectric-r0' from repository central (http://repo1.maven.org/maven2): Error transferring file: Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/org/robolectric/android-all/5.0.2_r3-robolectric-r0/android-all-5.0.2_r3-robolectric-r0.jar
2021-02-17T18:35:00.4295057Z   FAILURE
2021-02-17T18:35:00.8307886Z 
2021-02-17T18:35:00.8407141Z Unable to resolve artifact: Missing:
2021-02-17T18:35:00.8408382Z ----------
2021-02-17T18:35:00.8409444Z 1) org.robolectric:android-all:jar:5.0.2_r3-robolectric-r0
2021-02-17T18:35:00.8411525Z   Try downloading the file manually from the project website.
2021-02-17T18:35:00.8426089Z 
2021-02-17T18:35:00.8426778Z   Then, install it using the command: 
2021-02-17T18:35:00.8428401Z       mvn install:install-file -DgroupId=org.robolectric -DartifactId=android-all -Dversion=5.0.2_r3-robolectric-r0 -Dpackaging=jar -Dfile=/path/to/file
2021-02-17T18:35:00.8429263Z 
2021-02-17T18:35:00.8430007Z   Alternatively, if you host your own repository you can deploy the file there: 
2021-02-17T18:35:00.8431659Z       mvn deploy:deploy-file -DgroupId=org.robolectric -DartifactId=android-all -Dversion=5.0.2_r3-robolectric-r0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
2021-02-17T18:35:00.8432912Z 
2021-02-17T18:35:00.8433302Z   Path to dependency: 
2021-02-17T18:35:00.8434043Z   	1) org.apache.maven:super-pom:pom:2.0
2021-02-17T18:35:00.8434950Z   	2) org.robolectric:android-all:jar:5.0.2_r3-robolectric-r0
2021-02-17T18:35:00.8435428Z 
2021-02-17T18:35:00.8436010Z ----------
2021-02-17T18:35:00.8436470Z 1 required artifact is missing.
2021-02-17T18:35:00.8436788Z 
2021-02-17T18:35:00.8437146Z for artifact: 
2021-02-17T18:35:00.8437923Z   org.apache.maven:super-pom:pom:2.0
2021-02-17T18:35:00.8438297Z 
2021-02-17T18:35:00.8438978Z from the specified remote repositories:
2021-02-17T18:35:00.8440124Z   central (http://repo1.maven.org/maven2),
2021-02-17T18:35:00.8441055Z   sonatype (https://oss.sonatype.org/content/groups/public/)
```

**Comment by st3fan** [comment]
I switched to JDK 1.8 instead of 11 and that seems to have gotten rid of the weird failures (SSL related and those tests for LG and Samsung). What is left are now these:

```
2021-02-17T19:42:48.4077082Z   TEST: Updating SearchFragmentState from SearchState - shortcuts disabled
2021-02-17T19:42:48.6064772Z   FAILURE
```

```
2021-02-17T19:42:49.0078634Z   TEST: Updating SearchFragmentState from SearchState
2021-02-17T19:42:49.1074987Z   FAILURE
```

What do you think @pocmo - these are fine on TaskCluster - what could make these run different on GitHub?

**Comment by st3fan** [comment]
Fix for failing tests at https://github.com/mozilla-mobile/fenix/pull/18048 - when that lands, rebase this patch and it is ready to land.

**Pull request merged**
