### PR TITLE
For #28498: Fixed empty list text alignment in Tabs tray, history and downloads

### LINKED ISSUE #28498: [Bug]: Misplaced empty tabs tray, history and downloads messages
### Steps to reproduce

1. Open the tabs tray
2. Check empty tabs tray message
3. Tap the private open tabs
4. Check empty private tabs tray message
5. Open "History" from the home screen ⋮ button
6. Check empty history list message
7. Open "Downloads" from the home screen ⋮ button
8. Check empty history list message

### Expected behaviour

The messages should be centered

### Actual behaviour

Misplaced messages

### Device name

Google Pixel 2, Pixel 3a 

### Android version

Android 11

### Firefox release type

Firefox Nightly

### Firefox version

110.0a1

### Additional information

► Video

https://user-images.githubusercontent.com/51314259/211844988-da3b04c2-0c21-4a4a-afe9-a1e094efd96d.mp4

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-22265)

### PR DESCRIPTION
**Pull request by gitstart**
The PR fixes the text alignment of empty tabs tray, history and downloads messages.

### Steps to reproduce

1. Open the tabs tray
2. Check empty tabs tray message
3. Tap the private open tabs
4. Check empty private tabs tray message
5. Open "History" from the home screen ⋮ button
6. Check empty history list message
7. Open "Downloads" from the home screen ⋮ button
8. Check empty Downloads list message

### Issue video
https://www.loom.com/share/ec33cb283a324f60a78b6da4441172b4

### Demo video after fix
https://www.loom.com/share/04a3b526e7ad440f8efa01d76da029e5

### Pull Request checklist
- [ ] **Tests:** This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots:** This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility:** The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

**QA**
- [x] QA Needed
### To download an APK when reviewing a PR (after all CI tasks finished running):

1. Click on Checks at the top of the PR page.
2. Click on the firefoxci-taskcluster group on the left to expand all tasks.
3. Click on the build-debug task.
4. Click on View task in Taskcluster in the new DETAILS section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #28498

### CODE REVIEW

**Comment by Mugurell** [comment]
Thank you for working on this!
Before merging can you please squash the commits and rename the resulting commit and PR to follow our recommended structure from https://github.com/mozilla-mobile/shared-docs/blob/main/android/CONTRIBUTING_code.md#creating-a-pull-request (eg: `For #28498: Fix text alignment in ...`)?

**Comment by gitstart** [comment]
> Thank you for working on this! Before merging can you please squash the commits and rename the resulting commit and PR to follow our recommended structure from https://github.com/mozilla-mobile/shared-docs/blob/main/android/CONTRIBUTING_code.md#creating-a-pull-request (eg: `For #28498: Fix text alignment in ...`)?

Thank you for reviewing the PR @Mugurell,
Requested changes are done. Please check..

**Comment by jonalmeida** [comment]
Thanks for fixing this! @mavduevskiy and I have just reverted the change the introduced this bug. So we should hold off on landing this fix.

**Comment by gitstart** [comment]
> Looks good! Thank you for being quick to help with this!

Thank you @Mugurell for reviewing the PR and approving it

**Comment by gitstart** [comment]
> Thanks for fixing this! @mavduevskiy and I have just reverted the change that introduced this bug. So we should hold off on landing this fix.

Thank you @jonalmeida hope the PR get merged soon..

**Comment by jonalmeida** [comment]
> Thank you jonalmeida hope the PR get merged soon..

It was merged! Hopefully, you see the new update soon in the next nightly build.

**Comment by Mugurell** [comment]
Closing this PR as not needed anymore.
Thank you @gitstart!

**Pull request closed without merging**
