### PR TITLE
CI for #20808

### PR DESCRIPTION
**Pull request by mcomella**
CI for #20808

@MarcLeclair I r+'d this in https://github.com/mozilla-mobile/fenix/pull/20808#pullrequestreview-733065819 – can you carry over the rubberstamp?

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by MarcLeclair — APPROVED** [review]

**Comment by mcomella** [comment]
Unit test failure is https://github.com/mozilla-mobile/fenix/issues/20776 & UI test failure is https://github.com/mozilla-mobile/fenix/issues/20716. Restarting CI

**Comment by mcomella** [comment]
More intermittents:
- BookmarkItemMenuTest. edit item appears for folders
- mainMenuInstallPWATest

Hmm.

**Comment by mcomella** [comment]
@Mergifyio rebase

**Comment by mcomella** [comment]
Another intermittent failure: 
- DeleteAndQuitTest. delete only tabs and quit

**Comment by mcomella** [comment]
I ran the failed UI test three times locally (on on this PR, once on the commit before the PR, and once on up/main) and it failed every time. I can't explain why it doesn't seem to fail on commits in `up/main` (maybe this test doesn't run everytime?) but I noticed the test page it uses has moved locations – perhaps that's the cause of the error? Changing the test page makes it work correctly so let's try that?

**Comment by jonalmeida** [comment]
Test failure is a new intermittent that I'll have a fix up for soon: https://github.com/mozilla-mobile/fenix/issues/20945

Let's restart one more time.

**Comment by mcomella** [comment]
```
com.android.build.gradle.internal.testing.ConnectedDevice > runTests[test(AVD) - 9] FAILED 
	com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_FAILED_INSUFFICIENT_STORAGE
		at com.android.build.gradle.internal.testing.ConnectedDevice.installPackage(ConnectedDevice.java:133)
```

Oi.

**Comment by jonalmeida** [comment]
Blerg, another instance of this happened on [another PR](https://github.com/mozilla-mobile/fenix/pull/20949#issuecomment-902955195)..

**Comment by mcomella** [comment]
From Slack:

> Roger fixed the test page being moved in a recent commit, and I believe Codrut/Petru disabled the permafailing UI test on main and release branches. So I think you would only need to rebase the PR now.

I removed the commit I added to fix the test and rebased the PR on up/main.

**Comment by mcomella** [comment]
Insufficient storage again: maybe the docker image is broken. Maybe we wait on https://github.com/mozilla-mobile/fenix/issues/20952

**Comment by AaronMT** [comment]
@jonalmeida @mcomella There's some confusion here. The `Android build PR / run-ui (28, google_apis) ` is a Github Action: https://github.com/mozilla-mobile/fenix/blob/main/.github/workflows/build-contributor-pr.yml which is executed on this condition

`if: github.event.pull_request.head.repo.full_name != github.repository && github.actor != 'MickeyMoz'`  which is intended to be ran on contributor forks `on: [pull_request]` as a sort of non blocking sanity check. It uses an https://github.com/ReactiveCircus/android-emulator-runner which is an A GitHub Action for installing, configuring and running hardware-accelerated Android Emulators on macOS virtual machines.

These are configurable AVD's and I'm guessing we just need to adjust the default size as our APK continues to grow.
e.g, `sdcard-path-or-size: 2G`

**Comment by jonalmeida** [comment]
@AaronMT for this PR, I think there are more intermittent failures blocking it. We've landed PRs that had run-ui fail.

**Review by jonalmeida — APPROVED** [review]

**Pull request merged**
