### PR TITLE
Issue #21172: Replace BrowserAwesomeBar view with AwesomeBar() composable.

### PR DESCRIPTION
**Pull request by pocmo**
This replaces the `BrowserAwesomeBar` (`browser-awesomebar`) with the new `AwesomeBar()` composable (`compose-awesomebar`). It's feature complete and looking and behaving as before.

To keep the changes minimal I introduced `AwesomeBarWrapper` which wraps the compose code and pretends to still be a `concept-awesomebar` `View` implementation. This way I didn't need to change any of the code interacting with the awesome bar for now.

I need to investigate how to refactor our UI tests. Some of them seem to look into the adapter for assertions and the compose code doesn't have an adapter.

### CODE REVIEW

**Comment by pocmo** [comment]
I tried to fix the directly affected UI tests.

However I fail to understand why so many unrelated UI tests seem to fail here:
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8140806191013136917

@rpappalax @sv-ohorvath Do you have any idea? It looks like Espresso is unable to click some of the views... but those areas are unrelated to the change.

**Comment by pocmo** [comment]
Actually there might be still some valid broken cases, that I will try to find. There's such a wall of red that I don't understand why that would be related. :|

**Comment by AaronMT** [comment]
Looking at the Firebase Test Lab (looking at a few Shards) there seems to be a common bump of entering the address bar causing a problem

```Log
at org.mozilla.fenix.ui.robots.NavigationToolbarRobotKt.openEditURLView(NavigationToolbarRobot.kt:263)
at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:93)
```

https://github.com/mozilla-mobile/fenix/blob/main/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt#L95

Does this function just need to be tweaked?

**Comment by pocmo** [comment]
Thank you! I'll take a look if/how the new awesomebar somehow affected that area.

**Comment by mcarare** [comment]
> ```
> at org.mozilla.fenix.ui.robots.NavigationToolbarRobotKt.openEditURLView(NavigationToolbarRobot.kt:263)
> at org.mozilla.fenix.ui.robots.NavigationToolbarRobot$Transition.enterURLAndEnterToBrowser(NavigationToolbarRobot.kt:93)
> ```
> 
> https://github.com/mozilla-mobile/fenix/blob/main/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt#L95

This happens because the views are identified by using the view id.

**Comment by pocmo** [comment]
> This happens because the views are identified by using the view id.

Which is fine for this part of the screen, I think. Note that the `awesomeBar()` helper may be a bit misleading since it's actually targeting the toolbar in edit mode (`R.id.mozac_browser_toolbar_edit_url_view`).

**Review by mcarare — APPROVED** [review]
LGTM!

**Comment by pocmo** [comment]
Rebased and added `onScroll = { hideKeyboard() }`.

**Pull request merged**
