### PR TITLE
For #17804: Fix setSystemUiVisibility and flags deprecation.

### PR DESCRIPTION
**Pull request by mcarare**
### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by mcarare** [comment]
cc @boek for data review.

**Review by jonalmeida — COMMENTED** [review]
I'm not sure what the data review is for, but I tested out this patch and found so inconsistencies on Android 11:

When you enter then exit a fullscreen video, the system navigation bar disappears.

Left is this PR, right is original behaviour:
out

On the other hand, I've tested out [this PR](https://github.com/mozilla-mobile/android-components/pull/8577) and when using the AC `enterToImmersiveMode` in place of this code, it seems to work fine. So we could land it and use this PR to remove the Fenix implementation.

If you'd like to land this change, I _think_ we need to take out the `setDecorFitsSystemWindows`. We can land the AC change in a future update. 🙂

**Comment by mcarare** [comment]
@jonalmeida Thanks for testing, I have removed `setDecorFitsSystemWindows(false) `. I think it should be used only after we change the way we set the window adjust/ resize for SDK >=30 and do it properly. I was using it because the documentation suggests it should be set to false in order to not check the deprecated flags anymore. I will revisit this at a later time.

There is no data review requested here, I am not sure what are you referring to. 🤔 

As for the AC extension, this was also my initial thought (https://github.com/mozilla-mobile/fenix/issues/17804#issuecomment-783395001) but when looking into the code I've seen this comment:
>We don't use the equivalent function from Android Components because the stable flag messes
  with the toolbar. See #1998 and #3272.`

**Comment by jonalmeida** [comment]
> There is no data review requested here, I am not sure what are you referring to. 🤔

Maybe this comment was meant for another PR? https://github.com/mozilla-mobile/fenix/pull/18169#issuecomment-788088636




> As for the AC extension, this was also my initial thought ([#17804 (comment)](https://github.com/mozilla-mobile/fenix/issues/17804#issuecomment-783395001)) but when looking into the code I've seen this comment:
> 
> > We don't use the equivalent function from Android Components because the stable flag messes
> > with the toolbar. See #1998 and #3272.`

I agree with your comment on the issue. In my testing those two bugs are no longer seen when we use the AC version now.

**Pull request closed without merging**
