### PR TITLE
For #14866: Telemetry for Open Saved Data in New Tab

### PR DESCRIPTION
**Pull request by kglazko**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by kglazko** [comment]
@eliserichards @ekager I am stuck in that I'm not sure how to add the Telemetry counter events for opening a history, bookmark, or sync tab to the AwesomeBarView.kt. It looks like AwesomeBarView just takes all of these options and consolidates them into a map of providers. There's a check for tapping on search terms or URL but I don't know if it's possible to check whether or not you can tap on an a specific type of provider (i.e. History or Bookmarks or Sync) from AwesomeBar.

**Comment by ekager** [comment]
Hi! I would have to look at exactly which telemetry we are looking to add, but it's possible you might need to emit facts for these in AC in the corresponding Suggestion Providers for example for bookmarks in the `BookmarkStorageSuggestionProvider` `onSuggestionClicked` lambda?

**Comment by kglazko** [comment]
Thank you, Emily! Do you think it's possible to have the same Telemetry event for both the actions in Fenix and in AC? (basically, tapping on a bookmark, not the open bookmark menu item) in Library and Suggestions, and same for history. This PR only address the taps in the Library section so far, but the telemetry event should be the same for both Library opens and Suggestions opens..

**Comment by gabrielluong** [comment]
Closing this since this is done according to https://github.com/mozilla-mobile/fenix/issues/14866.

**Pull request closed without merging**
