### PR TITLE
Issue #16648: Expose Nexus logs

### PR DESCRIPTION
**Pull request by mnbpdx**
### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

**Issue:** #16648 
**Changes:** Added code to `toolchain-linux64-android-gradle-dependencies` to expose Nexus logs to better diagnose toolchain task failure.
**Tests:** I accidentally set up hooks after pushing my changes, so this has not been tested locally. Could someone explain to me how to manually run these tests?
**Screenshots:** No user facing work.
**Accessibility:** No user facing work.

### CODE REVIEW

**Comment by JohanLorenzo** [comment]
bors try

**Comment by JohanLorenzo** [comment]
bors try

**Comment by JohanLorenzo** [comment]
Hey @mnbpdx! Thanks a lot for this PR 👍 It looks good to me at first.

> This pull request has conflicts when rebasing. Could you fix it @mnbpdx? 🙏

Don't mind this message, I'm the one who made the mistake. I'm working on testing your patch before formally approving it 🙂

**Comment by JohanLorenzo** [comment]
bors try

**Comment by JohanLorenzo** [comment]
It worked! We now have these logs exposed thanks to your patch @mnbpdx 🎉 

https://firefox-ci-tc.services.mozilla.com/tasks/d03c83qZR16pkA454mJZ0g/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2Fd03c83qZR16pkA454mJZ0g%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Fnexus%2Fwrapper.log

**Review by JohanLorenzo — APPROVED** [review]
Looks good to me and we tested this has the expected effect in my previous comment. Thanks a lot for this contribution @mnbpdx 💯

**Comment by mnbpdx** [comment]
Fantastic! Thanks for the opportunity 😄🎉

**Comment by JohanLorenzo** [comment]
bors try

**Review by pocmo — APPROVED** [review]

**Pull request merged**
