### PR TITLE
Update not yet unavailable add-on string for fennec/beta branch

### PR DESCRIPTION
**Pull request by psymoon**

### CODE REVIEW

**Comment by pocmo** [comment]
Actually, let's wait with merging this. I think I need to uplift the string first since that may not be in the AC release we are using on this branch. I can look at this on Monday.

**Comment by psymoon** [comment]
@pocmo we should also wait for the translations to be in place, right?

**Comment by pocmo** [comment]
For the previous string change we decided to ship the new one even if it is not translated to all languages yet.

**Comment by ekager** [comment]
@psymoon can we do a rebase and land assuming we still need this?

**Comment by pocmo** [comment]
This is no longer needed! :)

**Pull request closed without merging**
