### PR TITLE
For #20952 - Increase run-ui emulator storage to 2GB

### PR DESCRIPTION
**Pull request by Mugurell**
### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by Mugurell** [comment]
Seems like 2GB wasn't enough. Trying with 3GB.

**Comment by Mugurell** [comment]
Same `INSTALL_FAILED_INSUFFICIENT_STORAGE` error wven with 3GB though on a local emulator with just 2GB the ui tests run fine.
Maybe there's a deeper problem.

**Comment by AaronMT** [comment]
Thank you for taking this. 

https://github.com/marketplace/actions/android-emulator-runner

`sdcard-path-or-size`

> Path to the SD card image for this AVD or the size of a new SD card image to create for this AVD, in KB or MB, denoted with K or M. - e.g. path/to/sdcard, or 1000M.

Might just need to denote `M` instead. Here's someones [example](https://github.com/owntracks/android/blob/a12842d2b9fe4d83976b171607ae5e25559d5546/.github/workflows/android.yml#L119) on Github. 

While in this file it's probably helpful to also add `disable-animations: true`

**Comment by Mugurell** [comment]
I see the same "INSTALL_FAILED_INSUFFICIENT_STORAGE" error even though both now and previously at the beginning of logs it says `SD card path or size: 3072M`.
So the value was set. It just didn't help. Don't know where this VM is hosted. Maybe there's a problem there?

**Comment by AaronMT** [comment]
Hello @Mugurell,

I think for now while we investigate let's disable `run-ui` as part of the workflow. The full UI-test suite are still ran normally on Firebase (`ui-test-x86-debug`).

https://github.com/mozilla-mobile/fenix/pull/20981

**Pull request closed without merging**
