### PR TITLE
For #15116: Do not use bottom toolbar custom behavior in PWA

### PR DESCRIPTION
**Pull request by mcarare**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by ekager — CHANGES_REQUESTED** [review]
Could we just add a few comments about the behavior here? It's a bit confusing that we *aren't* setting the behavior if `isUrlbarHidingEnabled` is NOT enabled. I would assume from a point of not knowing about this part of the codebase that we would set the behavior if we want to do something with URL hiding. Thanks!

**Comment by ekager** [comment]
Just tested this locally and it fixes the crashes I saw! Nice!

I did notice that when you click away from the main PWA scope (ie in Twitter go to Settings -> About Twitter -> About) the toolbar will no longer scroll. Ideally we would maintain the same behavior we had before - that might mean changing where/when we add or check for this behavior?

If that doesn't sound like an easy fix to find then we can merge these changes for now and file a followup! Just tag me for review again whenever

**Comment by mcarare** [comment]
@ekager Thank you for pointing out, I was also confused by that Boolean. My first instinct is that it is set incorrectly in AC for PWA's. Because custom tabs should have `isUrlbarHidingEnabled` set to true, and custom tabs for PWA should have it set to false in config. I will investigate and come back with the changes. :)

**Comment by mcarare** [comment]
@ekager I have changed to a more reliable indicator for PWA - `externalAppType,` also added this checks for TWA, as I tested and they also crashed.

**Comment by ekager** [comment]
So I think `isUrlbarHidingEnabled` actually refers to when there is NO url shown at all (like when using the Twitter PWA). Let me pull this down and try it!

**Review by ekager — APPROVED** [review]
Tested locally on PWA and changing scope and looks good!

**Pull request merged**
