### PR TITLE
For #8017: fix wifi string

### PR DESCRIPTION
**Pull request by Baron-Severin**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by Baron-Severin** [comment]
@betsymi would you mind verifying these strings before we merge?  Please lmk if you would like any additional changes.  [These mocks](https://user-images.githubusercontent.com/4400286/72918787-1f6e4680-3cfb-11ea-9520-bcdafe562618.png) provide some context of where they will be used in app (#8017).

**Comment by flodolo** [comment]
@Baron-Severin 
I'm having a hard time understanding this patch.

1) Why do you need to keep around the old strings? A "DEPRECATED" comment is not going to prevent 100 languages from translating them, and will waste time and resources. 
2) Why are we deprecating more than just the Wi-Fi string? Does it mean that we need new strings to replace them? If that's the case, we should remove all these strings, and land them when they're ready. As far as I can tell, these strings landed without code behind in https://github.com/mozilla-mobile/fenix/pull/8911

**Comment by Baron-Severin** [comment]
@flodolo 

> Why do you need to keep around the old strings?

Our process has been to mark as deprecated then periodically go through and remove old strings.  I don't remember what problem it was solving, tbh.  I'll bring it up with my team since it sounds like it doesn't work well for you.

> Why are we deprecating more than just the Wi-Fi string? 

I forgot to deprecate a few while adding new strings in #8911.

> Does it mean that we need new strings to replace them? 

No, we should have everything we need here unless requirements change.

> we should remove all these strings, and land them when they're ready.

Normally we would.  This close to deadlines we've been avoiding adding any strings at all.  Where they're absolutely necessary, we're landing them early (before code is ready) to give localizers as much time as possible.

**Comment by flodolo** [comment]
> > Why do you need to keep around the old strings?
> 
> Our process has been to mark as deprecated then periodically go through and remove old strings. I don't remember what problem it was solving, tbh. I'll bring it up with my team since it sounds like it doesn't work well for you.

That makes sense if you're already shipping a feature, and want to be able to ship more updates while the new strings are not used yet. At that point you definitely need the old (deprecated) strings in the repository. 

As I said, these strings seem to have landed without code behind, so we're asking to localize twice the content for no good reason. Is that assumption correct?

Note that both deprecated and new strings haven't been exposed to localization yet, they're stuck in quarantine until I understand if we can avoid this.

**Comment by Baron-Severin** [comment]
`preference_option_autoplay_allowed` and `preference_option_autoplay_blocked` have been in the app since September of last year, they need to be deprecated following the normal approach.  `preference_option_autoplay_allowed_wifi_only` has not yet been released, I duplicated it because I have been told to never change strings that have been committed to master.  I don't know how the localization implementation details work, I can remove `preference_option_autoplay_allowed_wifi_only` if this is an exception to that rule.

If that looks good to you @flodolo, please take a look at https://github.com/mozilla-mobile/fenix/pull/9068 and verify that we're set to move forward.

**Comment by flodolo** [comment]
> `preference_option_autoplay_allowed` and `preference_option_autoplay_blocked` have been in the app since September of last year, they need to be deprecated following the normal approach.

Thanks, I missed that.

> `preference_option_autoplay_allowed_wifi_only` has not yet been released, I duplicated it because I have been told to never change strings that have been committed to master. I don't know how the localization implementation details work, I can remove `preference_option_autoplay_allowed_wifi_only` if this is an exception to that rule.

"Do not change strings in master" is the correct approach, because you don't know if a string is only in quarantine, or exposed for localization. In this case, it's stuck in quarantine and can be removed, or changed without a new ID.

**Comment by Baron-Severin** [comment]
👍  thanks for helping clear that up @flodolo

**Pull request merged**
