### PR TITLE
Fixes #896 - Fetch leanplum secret from taskcluster

### LINKED ISSUE #896: Pull in api keys from taskcluster for Leanplum

### PR DESCRIPTION
**Pull request by boek**
I created the secret in Taskcluster. Though I'm not sure how to grant the proper scope.

### CODE REVIEW

**Comment by MihaiTabara** [comment]
@pocmo is this needed for `pull-requests` and `release` just like `sentry` counterpart? If so, just another line [here](https://hg.mozilla.org/ci/ci-configuration/file/tip/grants.yml#l676) should suffice.

**Comment by pocmo** [comment]
@MihaiTabara Only for releases (Sentry too!!). What is actually the process for that? File a Bugzilla issue and attach a patch via phabricator? I haven't landed code in any hg.mozilla.org repository for quite a while :D

**Comment by MihaiTabara** [comment]
@pocmo That's a good question 🤔 Let me get back to you with an answer later on today. In the meantime, I'll handle this asap to unblock you folks.

As to `sentry` secrets, oups, good to know. I let it there in `pull-requests` because it was already there when I redid the scopes mechanics. I'll fix it along the way.

**Comment by MihaiTabara** [comment]
https://phabricator.services.mozilla.com/D22728 tracks that for now.

**Comment by MihaiTabara** [comment]
Talked privately with @pocmo about this.  `ci-admin` currently supports only the Github related scopes (pull-requests graphs, master pushes graphs and github releases counterpart graphs). For hook-based ones, I have WIP to enable those but not yet. So roles can still be amended in the old way until then.

1. I've edited the fenix nightly hook [role](https://tools.taskcluster.net/auth/roles/hook-id%3Aproject-mobile%2Ffenix-nightly) to enable `project/mobile/fenix/leanplum` as well. 

2. https://phabricator.services.mozilla.com/D22728 currently tracks the cleanup of the old secrets `project/fenix/sentry` from `pull-requests` and `github releases`.

**Comment by pocmo** [comment]
Aaand Nightly is broken :)

**Comment by MihaiTabara** [comment]
I suspect for `leanplum` secrets missing from https://github.com/mozilla-mobile/fenix/blob/master/.taskcluster.yml#L51 ? I'm digging now

**Comment by MihaiTabara** [comment]
There's a missing comma [here](https://github.com/mozilla-mobile/fenix/blob/master/automation/taskcluster/decision_task_nightly.py#L66)

**Pull request merged**
