### PR TITLE
[#4089] Moved PublicSuffixList to a sub-component(Utilities) class.

### LINKED ISSUE #4089: Move PublicSuffixList to a sub-component class
PublicSuffixList isn't a top-level component class and is probably better fit for the `Utilities.kt` sub-component instead (or any other that might make more sense).

```kotlin
val publicSuffixList by lazy { PublicSuffixList(context) }
```

### PR DESCRIPTION
**Pull request by chiragmantri**
Fixes #4089 
PR contains :
1) Moved PublicSuffixList to Utilities.kt.
2) Corrected References which were using PublicSuffixList.

### CODE REVIEW

**Comment by jonalmeida** [comment]
@chiragmantri congrats on your first contribution! ✨ 

It looks like the build failed on the linter:
```
/bitrise/src/app/src/main/java/org/mozilla/fenix/components/Components.kt:8:1: Unused import
```

**Comment by chiragmantri** [comment]
@jonalmeida thanks, mate. :) fixed the build error in the next commit.

**Comment by chiragmantri** [comment]
@jonalmeida i don't have the merge access, shall i wait for more approvals?

**Comment by jonalmeida** [comment]
All done!

**Pull request merged**
