### PR TITLE
For #21292: Enable or disable Glean metrics upload directly.

### PR DESCRIPTION
**Pull request by mcarare**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by mcarare** [comment]
This should only be merged after all `metrics.track` calls have been replaced by direct Glean calls.
That is determined by the fact that the `MetricController` holds a list of "initialized" services and decides based on that list if the metric should be sent or not. (Even though Glean is very much capable of handling it's state on its own).

**Comment by mcarare** [comment]
@rocketsroger `GleanMetricsService` is not used anymore after the wrapper removal. `AdjustMetricsService` was never used. But it was kept for eventual use in the future.

**Comment by rocketsroger** [comment]
> @rocketsroger `GleanMetricsService` is not used anymore after the wrapper removal. `AdjustMetricsService` was never used. But it was kept for eventual use in the future.

But it looks like they are being started https://github.com/mozilla-mobile/fenix/blob/6a798ebfbc0a525d39780e22aae3f9ba29b08035/app/src/main/java/org/mozilla/fenix/components/Analytics.kt#L117

**Comment by mcarare** [comment]
Yes, I kept that to easily allow using Adjust (Marketing metrics) to be used in the future if we want to. But as the track function is not used anymore it is redundant to keep the enable/disable state in `GleanMetricsService` when Glean manages this state internally.

**Comment by rocketsroger** [comment]
> Yes, I kept that to easily allow using Adjust (Marketing metrics) to be used in the future if we want to. But as the track function is not used anymore it is redundant to keep the enable/disable state in `GleanMetricsService` when Glean manages this state internally.

But wouldn't this block will be skipped? https://github.com/mozilla-mobile/fenix/blob/6a798ebfbc0a525d39780e22aae3f9ba29b08035/app/src/main/java/org/mozilla/fenix/components/metrics/GleanMetricsService.kt#L81

**Comment by mcarare** [comment]
Closing this and keeping the refactoring for a later evaluation.

**Pull request closed without merging**
