### PR TITLE
For #4064: Update R8/ProGuard config for new Kotlin coroutines library

### PR DESCRIPTION
**Pull request by colintheshots**
This is a Proguard/R8 config fix for performance as recommended in the examples for the new coroutines update.
---

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by colintheshots** [comment]
profile

**Comment by hawkinsw** [comment]
Scenario | Status | Time (ms)
---------|--------|----------
Cold Startup | success | 1500
Enable private browsing | success | 470
Turn On Sync | fail | 0
Search or enter address | fail | 0
Add tab | fail | 0
More options | success | 390
Disable private browsing | success | 380
Text | success | 300
Text | fail | 0
Enable private browsing | success | 410
Title | fail | 0
Summary | fail | 0
Title | fail | 0
Title | fail | 0
Summary | fail | 0
Title | fail | 0
Title | success | 300
Title | fail | 0
Summary | success | 190

**Comment by hawkinsw** [comment]
@colintheshots That time looks really, really good! I think that we want to commit this and then see what happens in production. But, let's hold off on that while I run some other tests, if that's okay?

**Comment by hawkinsw** [comment]
I just looked at the profile generated for this PR and confirmed that 

a) the startup scenario time is "back" and
b) the functions that caused the regression are no longer present in the profile.

**Comment by colintheshots** [comment]
Ok now I just need one approving review. 👍

**Pull request merged**
