### PR TITLE
Update Mozilla Android Components to 28.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by jonalmeida**
Working off https://github.com/mozilla-mobile/fenix/pull/7538, we need to downgrade to 0.44.0 for app services as well.

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by jonalmeida** [comment]
Fixed the conflict with the glean plugin version.

**Comment by jonalmeida** [comment]
I've tested these changes locally and app services now works as expected.

**Comment by sblatz** [comment]
Hmm looks like we have a couple of test failures in `BookmarkNodeTest` I'm assuming that's unrelated to this PR.

**Comment by jonalmeida** [comment]
Those look like assertion failures so they aren't intermittent, but I don't believe this is related. 🤷‍♂

**Comment by jonalmeida** [comment]
I filed https://github.com/mozilla-mobile/fenix/issues/7556 for the intermittent failing tests.

**Pull request merged**
