### PR TITLE
Ci for 26733

### LINKED ISSUE #26733: [Bug]: Language search doesn't reset to full list view anymore
### Steps to reproduce

1. Go to Settings>Language
2. Tap the search button, and type a language name (e.x. French)
3. From the search results, select the new language.

### Expected behaviour

When a selection is made, the search results are dismissed and the full languages list is shown. This is the last known expected behavior.

### Actual behaviour
Not sure if intentional, I couldn't find an issue: the search results remain displayed after a language is set. You can exit the Language list and come back again if you need to make another selection.

### Device name

Pixel 2

### Android version

Android 9

### Firefox release type

Firefox Nightly

### Firefox version

106, 104.1.0

### Device logs

_No response_

### Additional information

_No response_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21435)

### PR DESCRIPTION
**Pull request by mavduevskiy**
CI for contributor [pr](https://github.com/mozilla-mobile/fenix/pull/26890#pullrequestreview-1211545152)
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #26733

### CODE REVIEW

**Comment by gabrielluong** [comment]
@mavduevskiy Let's go ahead with amending this commit with your suggested changes from https://github.com/mozilla-mobile/fenix/pull/26890. I think we did our best engaging with the contributor to see if they were still interested in amending the changes. Since it's just a minor change, I think it's typically better if we amend the changes and proceed along with landing.

**Comment by mavduevskiy** [comment]
@gabrielluong Good point! At the same time, the original PR was opened 3 months ago – giving just 3 days to respond seems like a short notice. Let's wait for a week.

As a side note, do you have any context on what might have caused the bug? Reading through the code, it looks like it should have always be the expected behavior.

**Comment by gabrielluong** [comment]
> @gabrielluong Good point! At the same time, the original PR was opened 3 months ago – giving just 3 days to respond seems like a short notice. Let's wait for a week at least.
> 
> As a side note, do you have any context on what might have caused the bug? Reading through the code, it looks like it should have always be the expected behavior.

I do not have any context here. Could you ask Product/UX in #firefox-mobile-eng-ux just in case?

**Comment by jonalmeida** [comment]
> I do not have any context here. I can try to look up the PR and original issues where this was implemented to see if the requirements were written down anywhere for our own reference. Could you ask Product/UX in #firefox-mobile-eng-ux just in case?

Mike and I worked on this offline - it seems that the bug was caused during the initial implementation and plainly wrong so does not require UX feedback.

I'm going to merge this in that case now that we've amended the patch with Mike's comments.

**Review by jonalmeida — APPROVED** [review]

**Comment by jonalmeida** [comment]
@mergifyio refresh

**Pull request merged**
