### PR TITLE
Fixes #5351 - use session icon in tab view on home

### LINKED ISSUE #5351: [Bug] Page title and favicon are not shown.
### Steps to reproduce
I could reproduce it only in Wikipedia. Open one Wikipedia page, then open another in a new tab. (I did this by "Open in new tab")

### Expected behavior
Favicons and site titles for all tabs.

### Actual behavior
image

### Device information

* Android device: Samsung Galaxy S6 Android 7.0
* Fenix version: 1.4.1

### PR DESCRIPTION
**Pull request by pt2121**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not

<details><summary>GIF</summary>
<p>

</p>
</details>

- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by ekager** [comment]
Do we also want to listen to `onIconChanged` in the same way as `onTitleChanged` here? 
https://github.com/mozilla-mobile/fenix/blob/master/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt#L110

**Comment by ekager** [comment]
See https://github.com/mozilla-mobile/fenix/issues/3846 step 3 
We could also have a follow up PR if you'd rather us merge this first :)

**Comment by pt2121** [comment]
Updated!
Thank you both for the reviews.

**Comment by ekager** [comment]
Thanks for the contribution!

**Pull request merged**
