### PR TITLE
For #26329 Refactor the search widget to use the A-C common behaviour

### LINKED ISSUE #26329: Refactor the search widget to use the A-C common behaviour
This task should contain the implementation of search widget the Fenix part. I moved and refactored  the search widget from Fenix in AC . 
This has appear based on this https://github.com/mozilla-mobile/focus-android/issues/7249#issuecomment-1195533956
This is the task from AC https://github.com/mozilla-mobile/android-components/issues/12565 .
This is the task from Focus https://github.com/mozilla-mobile/focus-android/issues/7249

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21203)

### PR DESCRIPTION
**Pull request by iorgamgabriel**
It should behave like the current version .

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #26329

### CODE REVIEW

**Review by Mugurell — APPROVED** [review]
LGTM.
Though nothing stands out I saw a case in which the widget would not show the app icon, don't know if it's a new issue / device issue, to be assessed by QA.

**Comment by Mugurell** [comment]
> LGTM. Though nothing stands out I saw a case in which the widget would not show the app icon, don't know if it's a new issue / device issue, to be assessed by QA.

The issue reproduces on main also for any update of [`search_widget_info.xml`](https://github.com/mozilla-mobile/fenix/blob/0b0e31aae8ae2697b3f449327e85f9b206906787/app/src/main/res/xml/search_widget_info.xml) like this patch needs to do. Looks like this needs more investigations.

**Comment by iorgamgabriel** [comment]
I can reproduce the issue with disappearing icons on Pixel 3XL .
If I install the old version from main , I added the search widget and after that I install this version from this branch both the app icon and the microphone icon will disappear . 
If I keep exactly the layout search_widget_info only the app icon is disappearing .
Until now I didn't find any fix . @Mugurell @jonalmeida

**Comment by Mugurell** [comment]
This then seems like a framework / launcher issue.
If we can't update the configuration without users seeing a broken widget looks like Fenix shouldn't be refactored.
Curious if there are other reports online about this, seems like an important issue. if not - giving how easy it is to reproduce maybe we should at least report it to Google - [issuetracker.google.com](https://issuetracker.google.com)

**Comment by mcarare** [comment]
> > LGTM. Though nothing stands out I saw a case in which the widget would not show the app icon, don't know if it's a new issue / device issue, to be assessed by QA.
> 
> The issue reproduces on main also for any update of [`search_widget_info.xml`](https://github.com/mozilla-mobile/fenix/blob/0b0e31aae8ae2697b3f449327e85f9b206906787/app/src/main/res/xml/search_widget_info.xml) like this patch needs to do. Looks like this needs more investigations.

We could send a one-time `APPWIDGET_UPDATE` as a workaround if we still want to go ahead and change something related to the widget. But maybe that should be a last resort solution.

**Comment by Mugurell** [comment]
> We could send a one-time `APPWIDGET_UPDATE` as a workaround if we still want to go ahead and change something related to the widget. But maybe that should be a last resort solution.

Not sure when and where from if the issue reproduces immediately after updating the app but without the app having a chance to open. ?

**Comment by mcarare** [comment]
For me, the bug reproduced only after opening the updated app.

**Comment by iorgamgabriel** [comment]
For the bug with icons disappearing at update I made a fix (an APPWIDGET_UPDATE in FenixApplication only one time ) , but sometimes I saw that the icons have disappeared random . 
I don't have a scenario how to reproduce this bug and I don't know if this is happening in the old version of the app. 
@jonalmeida what is your opinion regarding this ? Do we merge the patch or not ?

**Comment by jonalmeida** [comment]
@iorgamgabriel I would not land this Fenix if are unsure of what is causing the widget to be removed. For now, the original intention was to share the component in Focus, so we don't need to block that work on this PR. What do you think?

**Comment by iorgamgabriel** [comment]
@jonalmeida It's ok . Thank you for the answer.

**Pull request closed without merging**
