### PR TITLE
For #11631: Move report site issue extension to main menu.

### PR DESCRIPTION
**Pull request by mcarare**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by gabrielluong** [comment]
Looks like this needs some changes before it should be reviewed.

**Review by Amejia481 — APPROVED** [review]
When the new ac version is available we can this :)

**Comment by gabrielluong** [comment]
@mcarare would you be able to add a screenshot of the change and add @apbitner for a ux-review, and add a "needs:ux-feedback" label for ux visibility? Thanks!

**Comment by mcarare** [comment]
> @mcarare would you be able to add a screenshot of the change and add @apbitner as a reviewer for a ux-review, and add a "needs:ux-feedback" label for ux visibility? Thanks!

I will post the screenshot after the AC change has been merged. But IMO this should not require UX feedback, because it is a simple adding of a menu item that looks the same as others. It should just require QA.

**Comment by apbitner** [comment]
> > @mcarare would you be able to add a screenshot of the change and add @apbitner as a reviewer for a ux-review, and add a "needs:ux-feedback" label for ux visibility? Thanks!
> 
> I will post the screenshot after the AC change has been merged. But IMO this should not require UX feedback, because it is a simple adding of a menu item that looks the same as others. It should just require QA.

I'm not too concerned about the appearance, just want to make sure it's in the right location. So far as I'm aware, no one on UX approved moving the menu item out of the main menu, so just want to make sure we're all on the same page.

**Comment by mcarare** [comment]
UI test failures seem unrelated.

**Comment by apbitner** [comment]
@mcarare A couple design tweaks are needed:

**1)** 'Report Site Issue...' is not aligned with the other menu items, see screenshot below:
alignment

**2)** Please use the attached icons for the menu item, the one in the screenshot has borders that are too thick.

[Report Site Icons.zip](https://github.com/mozilla-mobile/fenix/files/5402793/Report.Site.Icons.zip)

**Comment by mcarare** [comment]
@apbitner This is the design of the web extension. This PR just moves the extension from a menu to another. The icon is the extension icon.

**Comment by mcarare** [comment]
@apbitner I have opened https://github.com/mozilla-mobile/fenix/issues/16029 for the alignment issue.
This: https://github.com/mozilla-mobile/fenix/issues/11367 is for the icon issue.
Can this be merged before those issues are solved, or should it wait?

**Comment by apbitner** [comment]
@mcarare Thank you for filing those, this can be merged for now.

**Pull request merged**
