### PR TITLE
For #7594: Doesn't allow for hint in URL bar on main page in two lines

### PR DESCRIPTION
**Pull request by marcinwiacek**
Closes https://github.com/mozilla-mobile/fenix/issues/7594

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by ekager** [comment]
Talked to @boek and I'm not sure this is the right fix. People make their font size bigger so that they can actually read the text. If we ellipsize these types of layouts, then their problem only gets worse. In addition to other languages with longer strings etc, I think I'm leaning towards letting it wrap but formatting correctly for that. 

CC UX - @topotropic for feedback on this since I'm sure this is a pattern we will run into again

**Comment by marcinwiacek** [comment]
Dear @ekager 

1. "As a small team, we have to prioritize our work, and reviewing PRs takes time. We receive lots of PRs every day, so if you can keep your PRs small, it helps our small team review and merge code faster, minimizing stale code.

Keep in mind that the team is very overloaded, so PRs sometimes wait for a very long time. However this is not for lack of interest, but because we find ourselves in a constant need to prioritize certain issues/PRs over others."

2. http://mwiacek.com/www/?q=node/374

3. I've submitted here just few (easy) test bugs...and didn't get into more details and

Up to now it looks for me, that crashes or compatibility (performance probably also) are not so important, UI bugs are not resolved for long time... or they get comment "do not land" or "needs-ux review" after preparing code for them.

This is my experience and it looks for me (perspective of dev with 20 years of experience) that you're not assigning resources in very effective way, also you're concentrating sometimes on very minor details instead of the most important things.

for example - when people look more, if something is one pixel aligned with mockup in situation when more important things are not touched, it's bad.

Let's look on this:

Somebody made some mockup, somebody made review, somebody approved, somebody coded, somebody tested. 

Now after 5 checks we get this:

Screenshot_1578665476

I don't believe, that UX will allow for two lines box for this. So, maybe ellipsis is wrong? If small team is sometimes wasting time for such things, it's not very good.

After getting trivial fix it returns to the whole UX process. My experience say, that something like that happens, when SWE don't want to make decisions and just want to make "safe" decisions only. It also makes, that some projects are stagnating.

Please think, what you're doing - for now I'm very disappointed with level which I've seen here (but also it could explain some results, which I showed in URL in point 2 in the beginning of this post).

**Comment by ekager** [comment]
We appreciate contributor contributions but we can't merge unsolicited PRs for issues that haven't had any decisions made on them (you opened the issue, designed a fix, and implemented it without discussing it with anyone on the team).

This is in our [README](https://github.com/mozilla-mobile/fenix#i-want-to-open-a-pull-request): 

> Since we are a small team, however, we do not have the bandwidth to review unsolicited PRs. 

Generally I would actually close this PR since it goes against our guidelines, but I thought it warranted a discussion because it was a small enough contribution. While your solution might be fine and the issue was a valid issue to talk about, we don't land random PRs that change UX or add features in the app without team discussion and feedback or it would be chaos and no one on the team would know the state of the app at any time.

UI bugs and performance are important to us, but we are a small time-zone distributed team with many things to do in a work day. Sometimes an issue or PR will take more than 1 day to get the right people time to discuss and we appreciate your patience.

**Comment by marcinwiacek** [comment]
Dear @ekager 

you didn't get the point, I will try to explain it differently:

Somebody told you "all GUI changes are going over UX", but I what I see on examples:

https://github.com/mozilla-mobile/fenix/issues/6086 - was marked with "needs UX" after 3 months (maybe because it's external, but still...)

https://github.com/mozilla-mobile/fenix/issues/6073 - was marked with "needs UX" after 3 months (maybe because it's external, but still...)

https://github.com/mozilla-mobile/fenix/issues/6944 - opened in Dec, very annoying, perfect candidate for discussing with UX what do to (I was thinking about removing flags from toolbar, but maybe it's better to update error msg)

https://github.com/mozilla-mobile/fenix/pull/7596 - marked after making trivial & stupid fix

Last one should not take team resources too much (This is my point - some details SWE should decide on them-self), in the same time 6944 is not touched, 6073 and 6086 (which could great improve usability) are not taken over time.

I see the same with resolving bugs - for example https://github.com/mozilla-mobile/fenix/issues/1833 opened in Apr 2019 & very annoying was not touched (I have done fix in Jan 2020 and happily Android components team seems to be probably more experienced and processed it without unnecessary bureaucracy).

What I'm trying to say is - team seems to be small, but non-important things are moved into full process, in the same time much more important things not. This is connected with wrong setup targets or maturity of people, who are doing triage. And I'm saying this not because I want to troll or something, just trying to show you where you leak resources (I'm saying it in good faith).

The same one word about marketing - saying very loud "we don't have resources for external changes" it's very discouraging (you should do something totally opposite and many times external changes should be on first place as external people can give you much more and can fill resources gap you have).

Dear @cadeyrn,

You don't have to agree with everything, what I say. I just try to show where resources could be assigned in more effective way. Mozilla is less popular than Chrome and they definitely need some help.

**Comment by cadeyrn** [comment]
> Dear @cadeyrn,
>
> You don't have to agree with everything, what I say. I just try to show where resources could be assigned in more effective way.

(to be clear: I do _not_ work for Mozilla, I am a contributor like you, it's my personal opinion)

This is only partly true. I am sure your intentions were good but to show where resources could be assigned in more effective way was not the only thing you did. I gave a "thumbs down" reaction to your comment because of sentences like: "you're concentrating sometimes on […] instead of the most important things", "probably mean, that you have not looked into it", "details like this should be resolved in five minutes", "You will not make FP fast more popular […] without users". These sentences are not helpful and not needed at all if you really want to help to improve processes.

(By the way, it should not be necessary for me to justify myself for giving a reaction to your comment.)

**Comment by marcinwiacek** [comment]
Dear @cadeyrn ,

Experience show, that saying everything with very nice political correctness words doesn't help many times in IT projects, because it's not notified. Linus is not nice, Jobs was not nice. Let's see, if Mozilla will take feedback and change some things (which obviously are not working) or ignore and say "we're the best".

Peace.

**Comment by topotropic** [comment]
@ekager Makes sense to keep it to one line for the search bar hint. 

When URLs are longer we fade them out, would be great to keep this pattern and also fade the search bar hint out if feasible – up to you. Thanks.

**Comment by marcinwiacek** [comment]
what about this? are they specs anywhere?

this is picture from regular url bar (not the one changed here):

Screenshot_20200114-102717_Firefox Nightly

**Comment by marcinwiacek** [comment]
@topotropic , could you guide, where are the specs and guidelines for this ? Also what about hint from picture from previous screenshot?

**Comment by ekager** [comment]
We can merge this in and investigate the fading hints in a followup. 

A reminder @marcinwiacek that the Fenix team and AC team work together closely and comments like the ones above and https://github.com/mozilla-mobile/android-components/pull/5534#issuecomment-574273458 are not productive and are against our guidelines. This is your final warning that if you want to continue contributing to both of these projects, you should not continue to communicate with the team this way. Our COC states you should be "respectful", "professional", and never "disruptive".

**Comment by marcinwiacek** [comment]
This is nothing personal, I'm just very tired with UX reviews stuck over months, lack of response and  wasting resources (visible in many projects). If you can please help with https://github.com/mozilla-mobile/fenix/issues/6944. That's it for now, thx.

**Pull request merged**
