### PR TITLE
CI for #27425

### LINKED ISSUE #16162: Shorten the name of the protocol (https) in the site address in the list of Logins
The name of the protol https:// is not needed in the Logins list because:
1. Occupies space (especially on narrow screens)
2. Passwords are secret information that should be transmitted by https by default, so you should specify the protocol when it is different from https.

Screenshot_2020-10-23-13-39-53

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-8488)

### PR DESCRIPTION
**Pull request by jonalmeida**
We're going to land this PR to verify that we actually do so from this branch.
Fixes #16162
Fixes #16162

### CODE REVIEW

**Review by mavduevskiy — APPROVED** [review]
looking good!

**Comment by jonalmeida** [comment]
> ⚠️ The sha of the head commit of this PR conflicts with #27425. Mergify cannot evaluate rules on this PR. ⚠️

Screen Shot 2022-10-24 at 6 35 52 PM

Despite the secondary approval and @mavduevskiy 's approval above, Mergify is still not re-evaluating this PR's rules for merging.

**Comment by jonalmeida** [comment]
We did verify that creating a secondary PR is still required for triggering the taskcluster CI and still allows you to land the original PR as can be seen here (so long as the secondary PR and the original have matching git SHAs): https://github.com/mozilla-mobile/fenix/pull/27527

**Comment by jonalmeida** [comment]
Removing the needs-landing label for now in case it causes any future issues with the merge queue.

**Comment by JohanLorenzo** [comment]
> Despite the secondary approval and @mavduevskiy 's approval above, Mergify is still not re-evaluating this PR's rules for merging.

Hey there! I wonder how mergify ended up in this state. Maybe one of the branch protection rule was still pending? Mergify does wait on them per [1]:

image

In any case, you can force mergify to re-evaluate the PR's rule. It's a matter of saying[2]: 

@mergifyio refresh

Mergify will 👍 this comment and run another check. Let me know if it that doesn't work. 

[1] https://github.com/mozilla-mobile/fenix/pull/27530/checks?check_run_id=9079070803
[2] https://docs.mergify.com/commands/#commands

**Comment by JohanLorenzo** [comment]
@mergifyio refresh

**Comment by JohanLorenzo** [comment]
> ⚠️ The sha of the head commit of this PR conflicts with #27425. Mergify cannot evaluate rules on this PR. ⚠️

Although, I left some instructions about forcing Mergify to re-evaluate a PR, I'm not sure this will fix the error above. I'm actually unsure on whether this a bug on our end or on Mergify's. I looked up for instructions/context but I couldn't find anything in the FAQ, the open tickets or the open conversations. I just reached to someone at Mergify to see if they can help us out.

**Comment by JohanLorenzo** [comment]
Status update: I got an answer from Mergify:

> Hi Johan,
>
> Nothing to worry about. We detected that two pull requests had the same sha1 and therefore the same content. That means Mergify cannot evaluate both PRs as the report Mergify does is tied to a sha1, and not a PR number (GitHub API limitation). So until the PR have different sha1, you might see this warning. :slightly_smiling_face: Amending or closing the original PR would work either case indeed. It really depends on your workflow I would say.

**Comment by jonalmeida** [comment]
Interesting, so if we want to merge the clone of the contributor PR, we have to close the original first and then tell mergify to refresh - that's what I understand from their message at least.

**Comment by jonalmeida** [comment]
@mergifyio refresh

**Comment by jonalmeida** [comment]
Yup, that seems to be doing it. ☝️ 

cc: @mavduevskiy

**Pull request merged**
