### PR TITLE
Issue #20664: Do not consider newly created tabs as inactive

### LINKED ISSUE #20674: Remove elevation from inactive tabs section
UX left a review offline to remove the elevation of the inactive tabs card which fell through the cracks. Using this ticket to track that work.

### PR DESCRIPTION
**Pull request by jonalmeida**
- Renamed `DEFAULT_INACTIVE_DAYS` -> `DEFAULT_ACTIVE_DAYS` because it's usage was conflicting with the name.
- Also fixes #20674 - putting it in this PR since it's only removing one attribute from the layout files.

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by csadilek — APPROVED** [review]
✨

**Comment by csadilek** [comment]
@jonalmeida looks like one of the new tests failed: "TabSessionStateKtTest. WHEN normal tab is recently used THEN return true"

**Comment by jonalmeida** [comment]
Fascinating, this passes consistently for me locally. I'll look into it.

**Comment by jonalmeida** [comment]
Ah of course..`DEFAULT_ACTIVE_DAYS` is in days, but you need to convert it to milliseconds to use it. Yesterday-Jonathan was careful for Future-Jonathan, but Today-Jonathan can still forget to read. 🤪

**Pull request merged**
