### PR TITLE
For #4631: TaskCluster should comment on PRs with an APK link  

### PR DESCRIPTION
**Pull request by colintheshots**
Still testing. Do not land yet.

### CODE REVIEW

**Comment by jonalmeida** [comment]
Super cool! You should talk to the TC folks to see how they setup their own CI builds to have a link to a live server based on that PR. 

For example, in [this PR](https://github.com/taskcluster/taskcluster/pull/1126) there is a `netlify/taskcluster-web/deploy-preview` task that links to a test server. Maybe that could work as well? I think we'd need a github bot otherwise to comment, right?

**Comment by mitchhentges** [comment]
[Patch that adds scope that allows comments](https://phabricator.services.mozilla.com/D41406)

**Comment by mitchhentges** [comment]
The scope patch has been landed and applied

**Comment by colintheshots** [comment]
I'll re-open this when I'm ready to work on it again.

**Pull request closed without merging**
