### PR TITLE
Use new async API to load and access search engines

### PR DESCRIPTION
**Pull request by hawkinsw**
Use the new asynchronous features of the search engine
manager from a-c to avoid the latency required to load
the default search engine.

@csadilek and I worked on this PR together (I mostly typed what he told me to type). 

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by csadilek** [comment]
> @csadilek and I worked on this PR together (I mostly typed what he told me to type).

@hawkinsw deserves more credit :). He found these two cases where we (unnecessarily) block the main thread waiting for the default search engine to be loaded. We added new API to AC to make this easier.

With this we can create the `SearchSuggestionProvider` without the default search engine by providing the `SearchEngineManager`, which will load the default engine asynchronously. We can start rendering the UI and load the engine(s) in parallel. Fenix already has logic in place to update the UI when the search engines are loaded (e.g. in case it hasn't completed by the time the HomeFragment is created).

There's some follow-up work here to switch all calls to `getDefaultSearchEngine` over to the new `getDefaultSearchEngineAsync`, but this small change here should address the performance problem Will identified.

The "worst case" here is that the user resumes directly to the BrowserFragment and immediately starts typing a search, which could cause the main thread to block if the search engines haven't been loaded. We weren't able to reproduce this case and it seems like the right trade-off. I will do another round of testing tomorrow.

**Comment by boek** [comment]
@csadilek sounds good. Can you file issues for any follow up that is needed for this? 👍

**Comment by csadilek** [comment]
@boek will do, I am also just testing this change and actually running into a problem where the `HomeFragment` doesn't update once the engines are loaded. I'll investigate and file follow-up issues or put up a fix.

**Comment by csadilek** [comment]
Follow-up PR to fix the race I found when testing this earlier: https://github.com/mozilla-mobile/fenix/pull/5049

**Pull request merged**
