### PR TITLE
Pad the tab count box in the tab tray in the same way that the tab count box in the toolbar is padded.

### PR DESCRIPTION
**Pull request by kleintom**
- [ X] **Tests**: This PR includes thorough tests or an explanation of why it does not
No tests for changing the padding on the tab tray tab counter box.

- [ X] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
tabs_tray_tab_counter_comparison
For comparison, here's what the old and new toolbar tab counter look like (the appearance should be unchanged with this pr) - the new toolbar and tab tray tab counters should now look the same:
toolbar_tab_counter_comparison
The appearance when there are more than 99 tabs is unchanged:
many_tabs_comparison

- [ X] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

tab_tray_accessibility_report

The report does include a suggestion on counter_text: "Text Contrast: Consider increasing this item's text foreground to background contrast ratio", but this PR didn't change any colors.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by ekager** [comment]
@topotropic could you review the padding here?

**Review by topotropic — COMMENTED** [review]
Thanks for the effort!

It would be great to keep the font-size consistent at 10sp (Inter bold) and center it no matter the digits.

**Comment by kleintom** [comment]
New screenshots (I didn't include any of the private browsing mode toolbar):
inter_tabtray_comparisons
inter_toolbar_comparisons

I reran the accessibility tool on all four light/dark toolbar/tabstray screens, and the only note on the tab counter was the one I mentioned/screenshotted in my initial comment.

One other thing to mention: the ttf files for the Inter font all seem to be 3-4 times the size of the Metropolis font (the only other font introduced for the project), I don't know if there's anything that can be done about that or not. (I'm also not sure if it matters if we include all the font files vs. just the one we're actually using.)

**Comment by kleintom** [comment]
(Managed to trick the pre-push hook and myself by fixing the errors it found but then not changing the pushed commit at all by amending it without adding the fixed file...)

**Comment by topotropic** [comment]
Thanks! LGTM

Re: accessibility – so you're saying the contrast of URL in dark mode isn't sufficient, correct?

**Comment by kleintom** [comment]
Thanks for the review!

> Re: accessibility – so you're saying the contrast of URL in dark mode isn't sufficient, correct?

I meant to say the contrast of the tab counter number in dark mode isn't sufficient - I figured out how to screenshot the specific warning this time:
Screenshot_20201001-161009_Accessibility Scanner
But yes, there's also a warning for the URL text color in dark mode :-)
Screenshot_20201001-161827_Accessibility Scanner

**Review by gabrielluong — COMMENTED** [review]
@kleintom thank you for the contribution! Would you be able to rebase your commit? I am also curious about all the res/font changes and if those were necessary? Thanks!

**Comment by kleintom** [comment]
> I am also curious about all the res/font changes and if those were necessary?

I rebased. As far as all the res/font changes, I don't know anything about font handling, so I'm not sure what approach is best. I couldn't find the Inter font that topotropic requested in the Google Fonts list, so I downloaded a copy.  It looks like the other downloaded font in the app, Metropolis, includes all of the font varieties (extra bold, light, etc.) even though some of them don't appear to be used, so I just did the same with the Inter font [I assume those unused .ttfs don't wind up in the apk, but I don't know that].  (Also I didn't create an Inter.xml file like the corresponding Metropolis.xml file.) I'm happy to change it up if anybody has suggestions.

One note on the rebase: I noticed that in my previous push in the layout xml files I changed the font family to `         android:fontFamily="@font/inter_bold"` without removing the existing `android:textStyle="bold"`. It seemed redundant to have a bold style on a bold fontFamily, so in addition to the rebase, this time I removed the `android:textStyle="bold"` - by comparing a zoomed version of the resulting tab counts, it looks like that didn't change the onscreen appearance at all, as hoped/expected, so I haven't included more screenshots (the top is inter_bold font with bold style, the bottom is inter_bold font without bold style):
bold_bold-vs-bold

But then I also wondered if it might be clearer to have the fontFamily be inter_regular and keep the style bold, so I tried that, and it actually turned out differently than using fontFamily inter_bold (the upper left and lower right are font family inter_bold without bold style, the lower left is font family inter_regular with bold style):
regular_vs_bold_comparison
Looks like inter_bold is a little wider and shorter than inter_regular with bold style. Sorry to muddy the waters, but let me know if inter_regular would be preferred or if you'd like to see more screenshots (of course there are many other possible combinations and inter_bold was already approved, but thought I should mention it given that I overlooked the whole bold family vs. bold style issue the first time).

**Comment by kleintom** [comment]
Closing, I didn't look closely, but looks like some of this goes away and the rest will need to be done is some other way in the not too distant future.

**Comment by eliserichards** [comment]
Hey @kleintom! I'm working on https://github.com/mozilla-mobile/fenix/pull/16605 and https://github.com/mozilla-mobile/android-components/pull/8872 to move the Tab Counter into Android Components. I'm going to take some inspiration from this PR to get the padding right, but I'd love to tag you for a review once my PRs have landed since you have done such spectacular work on this! Let me know if you'd be interested 😄

**Comment by kleintom** [comment]
Hi Elise, thanks for reaching out, but I'm going to pass this time.

**Comment by eliserichards** [comment]
No worries! Thanks!

**Pull request closed without merging**
