### PR TITLE
For #8765: shared selection item widget and bookmarks

### PR DESCRIPTION
**Pull request by NotWoods**
Builds ontop of #13883 and #14308.

Sets up a wrapper around WidgetSiteItemView that can handle selection, and integrates it with bookmarks.

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by eliserichards — APPROVED** [review]
Looks good! Let's get this last piece merged 🚀

**Comment by eliserichards** [comment]
bors r=eliserichards

**Comment by eliserichards** [comment]
ktlint needs fix @NotWoods --

```

[task 2020-10-05T20:15:32.457Z] > Task :ktlint
[task 2020-10-05T20:15:32.458Z] /builds/worker/checkouts/src/app/src/main/java/org/mozilla/fenix/library/bookmarks/selectfolder/SelectBookmarkFolderAdapter.kt:14:1: Unused import
[task 2020-10-05T20:15:34.655Z] 
[task 2020-10-05T20:15:34.655Z] > Task :ktlint FAILED
[task 2020-10-05T20:15:34.755Z] 
[task 2020-10-05T20:15:34.756Z] FAILURE: Build failed with an exception.
```

**Comment by gabrielluong** [comment]
@NotWoods do you have time to rebase? Thanks!

**Comment by liuche** [comment]
Build failure: 
`fenix/app/src/main/java/org/mozilla/fenix/library/bookmarks/selectfolder/SelectBookmarkFolderAdapter.kt: (68, 30): Unresolved reference: view`

**Comment by gabrielluong** [comment]
Quite a bit of errors. Posting just some in case they are helpful

addBookmarkTest

> androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: org.mozilla.fenix.debug:id/favicon and has parent matching: has parent matching: has child: (with id: org.mozilla.fenix.debug:id/url and with text: is "http://localhost:46888/pages/generic1.html"))

multipleBookmarkDeletionsTest
```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertNotNull(Assert.java:712)
at org.junit.Assert.assertNotNull(Assert.java:722)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull(WaitNotNull.kt:20)
at org.mozilla.fenix.helpers.ext.WaitNotNullKt.waitNotNull$default(WaitNotNull.kt:19)
at org.mozilla.fenix.ui.robots.BookmarksRobot$Transition.openThreeDotMenu(BookmarksRobot.kt:217)
at org.mozilla.fenix.ui.BookmarksTest.multipleBookmarkDeletionsTest(BookmarksTest.kt:439)
```

deleteBookmarkTest
> androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: org.mozilla.fenix.debug:id/overflow_menu and has parent matching: has child: (with id: 2131363022 and with text: is "http://localhost:44756/pages/generic1.html"))

undoDeleteBookmarkTest
> androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: org.mozilla.fenix.debug:id/overflow_menu and has parent matching: has child: (with id: 2131363022 and with text: is "http://localhost:56345/pages/generic1.html"))

copyBookmarkURLTest

> androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: org.mozilla.fenix.debug:id/overflow_menu and has parent matching: has child: (with id: 2131363022 and with text: is "http://localhost:38966/pages/generic1.html"))

**Comment by NotWoods** [comment]
Would someone be able to take over this PR? Tests are probably breaking on different ID names

**Comment by eliserichards** [comment]
Closing this to re-evaluate later.

**Pull request closed without merging**
