### PR TITLE
For 17868: Removes listener to avoid leak

### PR DESCRIPTION
**Pull request by CharlesAdam**
## Tests:
Given this PR only adds a line to the onPause method I felt there was no need to add tests.

## Screenshots:
There are no screenshots due to the issue not being a visible feature neither a visible bug, the only feedback we get is from the LeakCanary

## Accessibility
There were no changes in the screen layout. I'm trying to change the language of the scanner because my results were in other language
### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by CharlesAdam** [comment]
I've noticed this same fragment is causing another leak, if you go to android home after entering the Saved Logins and return to the app you should receive this leak:
image

**Comment by CharlesAdam** [comment]
> I've noticed this same fragment is causing another leak, if you go to android home after entering the Saved Logins and return to the app you should receive this leak:

Should this be described in other issue or solved in this PR? It seems this was happening before this changes.

**Comment by CharlesAdam** [comment]
Also I feel removing the listener is not the correct way to do it, but I cannot think of any other solution

**Comment by mcarare** [comment]
@CharlesAdam yes, nullifying the listener is a good approach.

I cannot reproduce the second leak. What Android version are you using?

**Comment by CharlesAdam** [comment]
> @CharlesAdam yes, nullifying the listener is a good approach.
> 
> I cannot reproduce the second leak. What Android version are you using?

I'm using Android 11

**Comment by mcarare** [comment]
@CharlesAdam can you reliably reproduce the second leak? Do you have a STR?

**Comment by CharlesAdam** [comment]
@mcarare yes I can reproduce the leak, what do you mean with STR?

Here is a gif of the leak
[

**Comment by mcarare** [comment]
@CharlesAdam STR means _Steps To Reproduce_. Thank you for the video. As I cannot reproduce the leak myself, I would ask you to try adding `setHasOptionsMenu(false)` in `onPause` and test if it still leaks.

**Comment by CharlesAdam** [comment]
@mcarare Thanks for the tip, that solved it. however, should this be added to this PR or should we create another issue?

**Comment by mcarare** [comment]
You can keep it here, as the original issue was referring to leaks in `SavedLoginsFragment`, not a specific one.

**Comment by mcarare** [comment]
You should squash your commits, and also rebase because a fix for some intermittent test failures was merged recently.
Then you should mark your PR as ready for review.

**Comment by CharlesAdam** [comment]
@mcarare Done

**Comment by mcarare** [comment]
You still have 2 commits. At one point the PR was fine, that is when I opened a PR to run CI for yours.

**Pull request closed without merging**
