### PR TITLE
Update to Mozilla Android Components 12.0.0-SNAPSHOT. 

### PR DESCRIPTION
**Pull request by pocmo**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by jonalmeida** [comment]
Leaving for Fenix team to merge.

**Comment by grigoryk** [comment]
#5114 needs to land alongside this; or just land #5114 instead (it's built on top of this PR).

**Comment by jonalmeida** [comment]
Closing since we should just merge the one mentioned above. ^

**Comment by pocmo** [comment]
Mh, this one was green and ready to land. #5114 has test and build errors :|

**Comment by jonalmeida** [comment]
My bad, sorry!

**Pull request closed without merging**
