### PR TITLE
For #22304 re-enable visitedUrlHistoryTest UI test

### PR DESCRIPTION
**Pull request by AndiAJ**
For #22304 re-enable `visitedUrlHistoryTest` UI test ✅  successfully passed 100x on Firebase.

<details>

<summary> 📈 Results (dropdown)</summary>

matrix | result | logs | details
-- | -- | -- | --
matrix-1usf661wt1wrj | success | logs | 1 test cases passed
matrix-3jukrva7s9or1 | success | logs | 1 test cases passed
matrix-1lwh6ujb242jt | success | logs | 1 test cases passed
matrix-347akyobwhcfg | success | logs | 1 test cases passed
matrix-q3dlu1ifef78a | success | logs | 1 test cases passed
matrix-ofse31eh1lyca | success | logs | 1 test cases passed
matrix-26cbtusjvy1qe | success | logs | 1 test cases passed
matrix-2b8u69mv6uw9k | success | logs | 1 test cases passed
matrix-2lhqpvp53k49w | success | logs | 1 test cases passed
matrix-2kyx9vkjmj66r | success | logs | 1 test cases passed
matrix-2yyxjs28658te | success | logs | 1 test cases passed
matrix-2qku0wcvatv9n | success | logs | 1 test cases passed
matrix-3swp6dzzyagjt | success | logs | 1 test cases passed
matrix-38o7ueka43twz | success | logs | 1 test cases passed
matrix-282azl4fqsb8d | success | logs | 1 test cases passed
matrix-3app8ygpx5znl | success | logs | 1 test cases passed
matrix-340y1c992r3io | success | logs | 1 test cases passed
matrix-1bbgfumotbvdu | success | logs | 1 test cases passed
matrix-rv20fqvj2w0va | success | logs | 1 test cases passed
matrix-8nvj21mafzbsa | success | logs | 1 test cases passed
matrix-1lpz08f0q8una | success | logs | 1 test cases passed
matrix-3ht1pp0qa7weg | success | logs | 1 test cases passed
matrix-14yjuku4y1z1k | success | logs | 1 test cases passed
matrix-3rdggp75t1i2a | success | logs | 1 test cases passed
matrix-1czjhpbpvfkp3 | success | logs | 1 test cases passed
matrix-14zmz8m5zzx7a | success | logs | 1 test cases passed
matrix-34owi6su15brf | success | logs | 1 test cases passed
matrix-2awro8124ozjj | success | logs | 1 test cases passed
matrix-34cmbkq6bkacs | success | logs | 1 test cases passed
matrix-3tmj2uoks38lk | success | logs | 1 test cases passed
matrix-3vepdadl89kd8 | success | logs | 1 test cases passed
matrix-2524b2seu11oh | success | logs | 1 test cases passed
matrix-351le2frzl9v2 | success | logs | 1 test cases passed
matrix-yt7wlfwzclcga | success | logs | 1 test cases passed
matrix-1c9ulk0eawkw8 | success | logs | 1 test cases passed
matrix-dq3w5apkew1oa | success | logs | 1 test cases passed
matrix-z7fmicu04ilba | success | logs | 1 test cases passed
matrix-16fxx6rz4g1h8 | success | logs | 1 test cases passed
matrix-2oyvu1h9vjbt9 | success | logs | 1 test cases passed
matrix-2k0a4e3vuybq2 | success | logs | 1 test cases passed
matrix-1txbrpfsw8h2t | success | logs | 1 test cases passed
matrix-abnm2il5p9wva | success | logs | 1 test cases passed
matrix-1n0fks2qwnquo | success | logs | 1 test cases passed
matrix-2hxlexa3y8elw | success | logs | 1 test cases passed
matrix-dk4ov9isv3gaa | success | logs | 1 test cases passed
matrix-1bj6qi41k8mhv | success | logs | 1 test cases passed
matrix-z7l6dg3qzfhla | success | logs | 1 test cases passed
matrix-38y6g6chrmh9a | success | logs | 1 test cases passed
matrix-1ikfg4hu03pe1 | success | logs | 1 test cases passed
matrix-254vofr71oavd | success | logs | 1 test cases passed
matrix-3rlrmi30f93jw | success | logs | 1 test cases passed
matrix-2u6hhzp6at5i4 | success | logs | 1 test cases passed
matrix-2wx3e7ahyqfe1 | success | logs | 1 test cases passed
matrix-3gmnk7yul1ilq | success | logs | 1 test cases passed
matrix-1dwlnijsh2qqq | success | logs | 1 test cases passed
matrix-2ym65x9mmi8y3 | success | logs | 1 test cases passed
matrix-2l3e2swg9vqp3 | success | logs | 1 test cases passed
matrix-1k0syrf563cb7 | success | logs | 1 test cases passed
matrix-3haxyly1j9g5j | success | logs | 1 test cases passed
matrix-2lczhftkdegiq | success | logs | 1 test cases passed
matrix-13sv8c3g9z1u3 | success | logs | 1 test cases passed
matrix-2xawp0xl137ld | success | logs | 1 test cases passed
matrix-2ukrfo40e3fn8 | success | logs | 1 test cases passed
matrix-2c8asp63im1ky | success | logs | 1 test cases passed
matrix-1s71trmraydup | success | logs | 1 test cases passed
matrix-2caikxol7vutw | success | logs | 1 test cases passed
matrix-2sfs8faeu8mws | success | logs | 1 test cases passed
matrix-jk32ujr33mu4a | success | logs | 1 test cases passed
matrix-2iwtnept96zgh | success | logs | 1 test cases passed
matrix-1ef5mw05dzg6r | success | logs | 1 test cases passed
matrix-1ryqwpl166ne5 | success | logs | 1 test cases passed
matrix-2d868c1412a3n | success | logs | 1 test cases passed
matrix-3d8yls7lzbist | success | logs | 1 test cases passed
matrix-2gw6k7y9i8ykb | success | logs | 1 test cases passed
matrix-36ad0v5fphjcj | success | logs | 1 test cases passed
matrix-oq0s56zqa5k6a | success | logs | 1 test cases passed
matrix-1pfu5qz627k30 | success | logs | 1 test cases passed
matrix-wyfcwvkpx15qa | success | logs | 1 test cases passed
matrix-1dt24k6ii270o | success | logs | 1 test cases passed
matrix-btefxm4ewxw1a | success | logs | 1 test cases passed
matrix-1re2907eckt9o | success | logs | 1 test cases passed
matrix-19shllx4be8n6 | success | logs | 1 test cases passed
matrix-3uviyvjkqndo0 | success | logs | 1 test cases passed
matrix-6qliocuqampla | success | logs | 1 test cases passed
matrix-3ruip6yehfpob | success | logs | 1 test cases passed
matrix-2epkz5xbppml2 | success | logs | 1 test cases passed
matrix-3paz9vzpastgp | success | logs | 1 test cases passed
matrix-28nr9o2zsnhby | success | logs | 1 test cases passed
matrix-htvx6cfdnrkwa | success | logs | 1 test cases passed
matrix-ckm4rdj7wmdya | success | logs | 1 test cases passed
matrix-2842dzjljclmt | success | logs | 1 test cases passed
matrix-39qzctikvi94h | success | logs | 1 test cases passed
matrix-346yyw0vi3w2u | success | logs | 1 test cases passed
matrix-2bf4lr1a3d2vu | success | logs | 1 test cases passed
matrix-1ddp956nso4zx | success | logs | 1 test cases passed
matrix-1lgu76b55p31w | success | logs | 1 test cases passed
matrix-218gawzntyu1n | success | logs | 1 test cases passed
matrix-2u95pphtk2rls | success | logs | 1 test cases passed
matrix-3ch1wpxfpwesx | success | logs | 1 test cases passed
matrix-1a8jpvgju0ign | success | logs | 1 test cases passed

</details>

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by sv-ohorvath — COMMENTED** [review]
The flakiness was caused by an issue that can affect any test that loads a webpage, so it was random. I think this was disabled because it failed on Nightly. If the failures due to that issue haven't decreased yet, let's be cautious about re-enabling this.

**Comment by AndiAJ** [comment]
Thanks @sv-ohorvath .
Indeed it failed on Nightly back in Nov. 

There's a low rate of occurrence for the exception
12 days ago for `openMainMenuHistoryItemTest` Flaky 1x 
19 days ago for `visitURLTest` 1x Failure on Nightly

I could add the `NoMatchingViewException` to the `RetryTestRule` and afterwards add the it to the HistoryTest class.
Perhaps it will prevent the problem from `enterURLAndEnterToBrowser`

On the other hand, by updating the `RetryTestRule` we might end up overlooking a real bug. #22316

@isabelrios and @AaronMT could you please share your thoughts? ☺️

**Comment by AaronMT** [comment]
@AndiAJ I'd say for now update the branch and let's see how it does

**Review by AaronMT — APPROVED** [review]

**Comment by AndiAJ** [comment]
Updated the branch and successfully re-ran 50x the test on Firebase.

**Pull request merged**
