### PR TITLE
No issue: Improve rendering of jump back in

### PR DESCRIPTION
**Pull request by rocketsroger**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by MozillaNoah — APPROVED** [review]

**Review by jonalmeida — APPROVED** [review]
🧟

**Comment by jonalmeida** [comment]
If you look at the video of the failing tests, it's because we've landed a new onboarding screen and the UI tests are not aware of it.

**Comment by rocketsroger** [comment]
> If you look at the video of the failing tests, it's because we've landed a new onboarding screen and the UI tests are not aware of it.

I see, I didn't expect that since this pr didn't really change how UI behaves.  I'll look into fixing these tests.

**Comment by csadilek** [comment]
@rocketsroger It looks like @Amejia481 deactivated the onboarding dialog for quite a few tests already: https://github.com/mozilla-mobile/fenix/pull/21494/files (see calls to `settings.hasShownHomeOnboardingDialog = true`). Can we do the same?

**Comment by csadilek** [comment]
Although I don't understand why this only happens in this PR....

**Comment by rocketsroger** [comment]
> @rocketsroger It looks like @Amejia481 deactivated the onboarding dialog for quite a few tests already: https://github.com/mozilla-mobile/fenix/pull/21494/files (see calls to `settings.hasShownHomeOnboardingDialog = true`). Can we do the same?

Thanks, I'll apply this to the failing tests.

**Comment by Amejia481** [comment]
> Although I don't understand why this only happens in this PR....

I think the new changes are triggering the dialog as it's checking for [any sections in the home screen to be visible ](https://github.com/mozilla-mobile/fenix/pull/21494/files#diff-f6968644d19314ed1385ed1bef14d8a3aaa163999143e11b0449b94292e6be56R173-R175),  as we are providing an initial state on this PR.

**Comment by Amejia481** [comment]
> > Although I don't understand why this only happens in this PR....
> 
> I think the new changes are triggering the dialog as it's checking for [any sections in the home screen to be visible ](https://github.com/mozilla-mobile/fenix/pull/21494/files#diff-f6968644d19314ed1385ed1bef14d8a3aaa163999143e11b0449b94292e6be56R173-R175), as we are providing an initial state on this PR.

I will take a look to see if the dialog is still behaving as it should with the new changes

**Review by Amejia481 — APPROVED** [review]
The dialog is still working as expected :)

**Pull request merged**
