### PR TITLE
For #1487 Add "my library" menu category and items to home 3-dot menu 

### PR DESCRIPTION
**Pull request by mcarare**
---

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features
  

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by cadeyrn** [comment]
Looks good! But for me the purple color for the caption is really hard to read in the dark theme. In the light theme the color is not exact the same as for the menu items but it's very similar. Is there a reason why the color of the caption can't be similar to the color of the menu items in the dark theme?

**Comment by mcarare** [comment]
I have set the color as `accent` as per UX specs. I agree that it could be improved.

**Comment by apbitner** [comment]
@mcarare Apologies, in https://github.com/mozilla-mobile/fenix/issues/1487 when you said:

> text color attribute for all themes (is it accent?)

I thought you were just asking about the light theme, I missed that you said _all_ themes. For the dark theme, we should use the same header color as we do in settings: `color: rgb(251, 251, 254);`

**Comment by mcarare** [comment]
@apbitner And for private theme? TY!

**Comment by apbitner** [comment]
@mcarare Same as dark.

**Comment by mcarare** [comment]
These are the new colors:

**Pull request merged**
