### PR TITLE
Settings privacy tests

### PR DESCRIPTION
**Pull request by isnirp**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by liuche** [comment]
@rpappalax is this something that we want to add in? If so, we'll need to get this rebased and conflicts fixed, but then I can repush to run CI.

**Comment by liuche** [comment]
@AaronMT do all these conflicts mean this was already done? If so, can you close this.

**Comment by AaronMT** [comment]
Let's re-run it and see what happens but yes these conflicts would need to be resolved (@isnirp would you be willing to re-base on latest master and see if these still run?)

**Comment by isnirp** [comment]
> Let's re-run it and see what happens but yes these conflicts would need to be resolved (@isnirp would you be willing to re-base on latest master and see if these still run?)

Sorry for late response... yes I'm willing to fix it. Thanks

**Comment by isnirp** [comment]
hello @AaronMT I'm having some issues getting the app to launch. It causes the android studio and my whole system to freeze. I don't know why this issue. I've decided to fork the app again. If it won't be an issue this pull request can be closed and I will open a new pull request once I get the tests done.

**Pull request closed without merging**
