### PR TITLE
For #12571: Rename 'Shortcuts' to 'Search engines'

### PR DESCRIPTION
**Pull request by KhushrajRathod**
Renamed the "Shortcuts" button to "Search engines", based on UX recommendations

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not - The issue contains an image, and I will add an image soon
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by KhushrajRathod** [comment]
> No Taskcluster jobs started for this pull request

Hi, I need help regarding this, thanks

**Comment by hakkikaancaliskan** [comment]
> > No Taskcluster jobs started for this pull request
> 
> Hi, I need help regarding this, thanks

Taskcluster runs just for members. Don't care with it.

**Comment by KhushrajRathod** [comment]
> > > No Taskcluster jobs started for this pull request
> > 
> > 
> > Hi, I need help regarding this, thanks
> 
> Taskcluster runs just for members. Don't care with it.

Oh ok thanks. So there's nothing else I have to change in this PR right? I thought CI would build a apk for me to test, so I could take a screenshot

**Comment by hakkikaancaliskan** [comment]
> > > > No Taskcluster jobs started for this pull request
> > > 
> > > 
> > > Hi, I need help regarding this, thanks
> > 
> > Taskcluster runs just for members. Don't care with it.
> 
> Oh ok thanks. So there's nothing else I have to change in this PR right? I thought CI would build a apk for me to test, so I could take a screenshot

No way, you should build yourself.
We're not going to refactor code from "shortcuts" to "search engines", right? Just string changes?

**Comment by KhushrajRathod** [comment]
> We're not going to refactor code from "shortcuts" to "search engines", right?
@hakkikaancaliskan No I don't think so, only the string needs to changed according to @NotWoods 

> Since this should just involve string changes I'm making it as good first issue

**Comment by hakkikaancaliskan** [comment]
Ok got it.

You should share screenshot for ux verify.

**Comment by cadeyrn** [comment]
It's needed to change the translation key, otherwise the change won't be exposed to the localizers.

**Comment by hakkikaancaliskan** [comment]
Yep, agreed. search_engines_shortcut_button would be a good name :)

**Comment by NotWoods** [comment]
preferences_show_search_shortcuts should also get updated to "Show search engines".

Unfortunately we need to update the string resource ID when updating the strings for our localization process (docs are [pending](https://github.com/mozilla-mobile/shared-docs/issues/61)). Usually we just increment a number (ie `search_shortcuts_button_2`) but in this case you might want to change the ID name from shortcuts to engines.

**Comment by hakkikaancaliskan** [comment]
@KhushrajRathod if you don't have pc for this, i can take the issue.

**Comment by KhushrajRathod** [comment]
> @KhushrajRathod if you don't have pc for this, i can take the issue.

I do have a PC, however I'm not too familiar with Android development. I'm usually doing web development. It's great if you could take over 👍

**Comment by hakkikaancaliskan** [comment]
> 
> 
> > @KhushrajRathod if you don't have pc for this, i can take the issue.
> 
> I do have a PC, however I'm not too familiar with Android development. I'm usually doing web development. It's great if you could take over 👍

Got it, you can close pr.

**Comment by KhushrajRathod** [comment]
Taken over by @hakkikaancaliskan

**Pull request closed without merging**
