### PR TITLE
fixes #4237 - Cannot edit the default name of a collection only replace it

### LINKED ISSUE #4237: [Bug] Cannot edit the default name of a collection, only replace it
## Steps to reproduce
1. Create collection. Tap Rename collection.
2. Tap the default name to edit it, not replace it.
### Expected behavior
The selection is dismissed, the cursor appears at the end of the text. Can add or remove some characters. 
### Actual behavior
Can't add or remove a few chars, only to replace the entire text as the name stays selected when you tap the text box.
### Device information

* Android device: S10+(Android 9) , Nexus 5 (Android 6.0.1), Huawei P9 Lite (Android 6.0), Samsung Galaxy Tab A 6 (Android 5.1.1)
*Not reproducing on a HTC 10 (Android 8.0)
* Fenix version: 1.1.0 rc2

### PR DESCRIPTION
**Pull request by mcarare**
made name_collection_edittext field clickable when SaveCollectionStep.RenameCollection

### Pull Request checklist

- [ x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [ x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by mihai-adrian** [comment]
IMHO I don't think we should put property setting in onResume(), it could be unnecessary called each time. Could you please explain the reason you requested the change? TY

**Comment by NotWoods** [comment]
I want the code to stay mostly consistent between the `SaveCollectionStep.NameCollection` and `SaveCollectionStep.RenameCollection` steps, so I don't want to set the edit text to be clickable on only one of those steps. 

I thought changing line 329 to the following might be an alternate solution that unifies code between the steps:
```diff
+ if (step == SaveCollectionStep.NameCollection || step == SaveCollectionStep.RenameCollection) {
      view.name_collection_edittext.showKeyboard()
  }
```

**Comment by mihai-adrian** [comment]
Actually, the title of the opened issue is misleading. The problem is that you cannot **rename** an existing collection the first time the view is shown. Only if you hide the keyboard you can then click on the existing name and change parts of it. Your addition would not fix the issue, but nevertheless, we should add it so the keyboard is automatically shown when onResume is called. 
I will investigate a way we can solve it and keep consistency.

Also, I think the title text should change in case of a renaming, from: "Name collection" to "Rename collection". What do you think?

**Comment by NotWoods** [comment]
Changing the title text sounds great 😄 

Thank you for investigating for a way to solve the issue while maintaining consistency. Perhaps setting `android:clickable="true"` in the layout file would work?

**Comment by mihai-adrian** [comment]
I will make that change regarding the title.
I have also tried setting clickable in layout file. It does not work.
I think the problem is from the rendering of the layout. When it is done, the field cannot receive focus. 
I changed the position of the title text change (order in code), and, in 8 times out of 10 the collection name text is clickable. It also fixes some flickering issues. I will try to find a full-proof fix tomorrow morning.

**Comment by mcarare** [comment]
Thank you also for your input! @NotWoods

**Pull request merged**
