### PR TITLE
Open links in apps UI test

### PR DESCRIPTION
**Pull request by AndiAJ**
1. Add new Play store link to `generic3.html`
2. Create new `openLinkInAppTest` smoke test ✅ Successfully passed 60x on Firebase
2. Add missing request interceptors to androidTest AppRequestInterceptor
3. Fix `mainMenuOpenInAppTest` smoke test (**didn't do anything before**) ✅ Successfully passed 60x on Firebase

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by Mugurell** [comment]
@isabelrios Investigated with Andi an issue with the app not behaving as expected in tests and saw that the "open in app" and "error pages" related functionalities are affected by the change from https://github.com/mozilla-mobile/fenix/pull/8489 which will use another request interceptor in tests, one that does not know about those functionalities.
That interceptor used in tests seems to [send all requests](https://github.com/mozilla-mobile/fenix/blob/main/app/src/androidTest/java/org/mozilla/fenix/AppRequestInterceptor.kt#L38) to the FXA interceptor [to finish authentication](https://github.com/mozilla-mobile/android-components/blob/71e124a5dbafffb800168ea615fdbc54d7398f50/components/feature/accounts/src/main/java/mozilla/components/feature/accounts/FirefoxAccountsAuthFeature.kt#L75-L98). Not sure what was the original intent but maybe this is not needed anymore? Otherwise we'll need to add the functionality from the "used in code" interceptor to this "used in tests" one.

**Comment by AndiAJ** [comment]
`mainMenuInstallPWATest` failed due to the PWA name change, it will pass once #23335 lands

**Comment by isabelrios** [comment]
> @isabelrios Investigated with Andi an issue with the app not behaving as expected in tests and saw that the "open in app" and "error pages" related functionalities are affected by the change from #8489 which will use another request interceptor in tests, one that does not know about those functionalities. That interceptor used in tests seems to [send all requests](https://github.com/mozilla-mobile/fenix/blob/main/app/src/androidTest/java/org/mozilla/fenix/AppRequestInterceptor.kt#L38) to the FXA interceptor [to finish authentication](https://github.com/mozilla-mobile/android-components/blob/71e124a5dbafffb800168ea615fdbc54d7398f50/components/feature/accounts/src/main/java/mozilla/components/feature/accounts/FirefoxAccountsAuthFeature.kt#L75-L98). Not sure what was the original intent but maybe this is not needed anymore? Otherwise we'll need to add the functionality from the "used in code" interceptor to this "used in tests" one.

Hey @Mugurell thanks for investigating this and helping Andi to find a solution. The purpose of those changes were intended so that (IIRC) we could use FxA stage server to run the sync integration tests. These tests were enabled back them and were very useful as we can start a test on fenix, log in, have some bookmark/history and then log in on desktopo using same account to verify the sync process. Unfortunately due to several changes in the UI and flakiness with the emulator we had to disabled them. It is one task we, mobile test eng team, have in mind for this year, to enable back these tests. 
So, thank you for looking an alternative solution that does not require to remove or modify this current behaviour 🙏

**Review by isabelrios — APPROVED** [review]
I just run the sync int tests locally and they work correctly after applying the change in the AppRequestInterceptor, thanks for the changes there to also add the new tests in this PR! 👏

**Pull request merged**
