### PR TITLE
For #7862: Correct "Learn more" arrow icon direction in ETP settings for RTL layouts

### LINKED ISSUE #7862: [Bug][RTL] The Learn More's arrow icon in ETP settings is pointing in the wrong direction
[Originally filed as bug against GeckoView by @itiel](https://bugzilla.mozilla.org/show_bug.cgi?id=1608187). Screenshots attached in Bugzilla for more information.

### PR DESCRIPTION
**Pull request by lyrjie**
For #7862 

### Pull Request checklist

- [x] **Tests**: The change is only within `.xml`
- [x] **Screenshots**: 

- [x] **Accessibility**: 

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by NotWoods** [comment]
@lyrjie Can you try merging the latest master into your branch to fix the unrelated failing test?

**Comment by lyrjie** [comment]
Sure, will do when I get a chance

**Comment by lyrjie** [comment]
Yeah, I messed and have no idea how to fix it. Should we just close PR and do it all over?

**Comment by NotWoods** [comment]
I was able to redo the rebase :)

**Comment by lyrjie** [comment]
Thanks a lot

**Pull request merged**
