### PR TITLE
For #13179 - Ensure we only dismiss share prompt once

### PR DESCRIPTION
**Pull request by ekager**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by ekager** [comment]
@jonalmeida from what I can tell via debugging - we are calling the dialog `dismiss` in `onPause` as well (so we close the share sheet when we leave Fenix) and end up triggering this twice
```
consumePrompt {
            onDismiss()
        }
```

**Comment by ekager** [comment]
Are you saying we should be able to consume the prompt twice without crashing?

**Comment by jonalmeida** [comment]
Yes, it shouldn't crash with the current behaviour. I can see from a quick git-blame lookup that the original behaviour that was added worked as expected when it landed: https://github.com/mozilla-mobile/fenix/commit/fe034226a335a2e48b4fa94e94aa80d7fe278f57#diff-950ceadcf9bd0ff8d1b61fae91f56240R45

I imagine something has either changed in AC or the share fragment lifecycle has changed where we are holding on to a reference of the hold prompt request (my bet is on the former).

**Comment by ekager** [comment]
Later we added the `onPause` callback that calls `dismiss` as well -> https://github.com/mozilla-mobile/fenix/pull/9671/files

**Comment by jonalmeida** [comment]
Ah, great find! I missed that.

In order to support that behaviour and not make the duplicate calls to consume the same prompt request twice, we could move the `consumePrompt` call to the `onPause` and remove the overridden `dismiss`. This would avoid adding extra state to the fragment.

I tested on that change for a bit and it seems to support the early dismissal that we're looking for without crashing on the consume.

**Pull request merged**
