### PR TITLE
For #5684 & #6054: Allows users to change toolbar position

### PR DESCRIPTION
**Pull request by sblatz**
---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by sblatz** [comment]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) **What questions will you answer with this data?**
- How often users choose a top nav bar. 

2) **Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements?**

- If more than 20% of users choose top nav bar (without surfacing this option during onboarding) then we will investigate (through user research or otherwise) whether we need to consider changing the default.

3) **What alternative methods did you consider to answer these questions? Why were they not sufficient?**

* N/A (These are baseline metrics)

4) **Can current instrumentation answer these questions?**
* No, this is a new feature and there is no telemetry surrounding which selection users make for their toolbar position.

5) **List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox [data c](https://wiki.mozilla.org/Firefox/Data_Collection)[ollection ](https://wiki.mozilla.org/Firefox/Data_Collection)[categories](https://wiki.mozilla.org/Firefox/Data_Collection) on the found on the Mozilla wiki.**

* All data is Category 2.

6) **How long will this data be collected?**

Until 03/01/2020

7) **What populations will you measure?**

* All release, beta, and nightly users with telemetry enabled.

8) **Please provide a general description of how you will analyze this data.**

* Glean / Amplitude

9) **Where do you intend to share the results of your analysis?**

* Only on Glean, Amplitude and with mobile teams.

**Comment by sblatz** [comment]
toolbar position change 2019-11-12 10_10_42

**Comment by sblatz** [comment]
@apbitner mentioned that I will need to reverse the menu items. I'll work on that tomorrow!

**Comment by boek** [comment]
@sblatz We have an existing event that we're using for settings here: https://github.com/mozilla-mobile/fenix/blob/master/app/metrics.yaml#L108
@vesta0 for telemetry do we also want to add a metric for the core ping storing the current state of this setting?

**Comment by sblatz** [comment]
@boek Yeah, I tried to use preferenceToggled, but it actually doesn't work well for this case. That's because *each* RadioButton would send a toggle event any time one of them is selected (If I select TOP, bottom toggles OFF, top toggles ON) which led to confusing telemetry. Because of this I felt it made more sense to make a new metric.

**Comment by hiikezoe** [comment]
I wonder whether the top toolbar covers the content or not in the case where the content scroll position is (0,0).

**Comment by vesta0** [comment]
> @vesta0 for telemetry do we also want to add a metric for the core ping storing the current state of this setting?

Yes that would be ideal

**Comment by boek** [comment]
@sblatz could we add a metric as well? :)

**Comment by sblatz** [comment]
> I wonder whether the top toolbar covers the content or not in the case where the content scroll position is (0,0).

@hiikezoe thank you for catching this! I have created a new PR to handle this :) https://github.com/mozilla-mobile/fenix/pull/6608

**Pull request closed without merging**
