### PR TITLE
Upgrade to Android Component 62.0.20201006190820 with breaking changes

### PR DESCRIPTION
**Pull request by jonalmeida**
AC upgrade that fixes the breaking changes with `ImageLoader` and `ImageLoadRequest`.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by pocmo — APPROVED** [review]

**Comment by jonalmeida** [comment]
This is now failing on the same media tests as https://github.com/mozilla-mobile/fenix/pull/15727.

**Comment by jonalmeida** [comment]
I'm beginning to suspect the tests.

When debugging `audioPlaybackSystemNotificationTest` (which fails consistently), adding a breakpoint at `waitForPlaybackToStart` returns false the few times when it looks for the text "Media file is playing". However, I can see that text on the screen.

Evaluating that line a few times, and then the value returns true all the time. I don't see any direct changes to the tests so far or the helper classes.

I'm going to re-test this with an older GV version to see if they start to pass.

**Comment by liuche** [comment]
@jonalmeida there's also an intermittent for that media test: https://github.com/mozilla-mobile/fenix/issues/14593

If it's too flaky, then you can disable the test too.

**Comment by st3fan** [comment]
@jonalmeida +1 to disabling the tests and filing an issue to get them going - this will unblock people sooner.

**Comment by jonalmeida** [comment]
There are a few tests that are failing, so I ended up testing with `tabMediaControlButtonTest` from the following list:
- `audioPlaybackSystemNotificationTest` - apparent intermittent; consistent failing now
- `mediaSystemNotificationInPrivateModeTest` - hard to reproduce; need older API level device that I do not have.
- `tabMediaControlButtonTest` - should be consistent.

I tried a bunch of GV builds to see what the media failure is but I've come across some confusing results. Using the latest AC (`3e68528074`) with these GV Nightly versions tested:
- `83.0.20201005093214` - ❌ (monday's GV after media regression was fixed)
- `83.0.20201001094020` - ❌ (GV media breakage)
- `83.0.20200930092918` - ❌ (before GV media breakage; expected to fail)
- `83.0.20200929094055` - ❌ (second before media breakage; expected to fail)

GV media regression was fixed (feature was disabled) in 20201001094020 so the `83.0.20201005093214` _should_ have worked.
  - https://hg.mozilla.org/mozilla-central/rev/e4e35e1aae77

---

I've disabled UI test failures for now so we can investigate without blocking anyone and I've filed the follow issue: https://github.com/mozilla-mobile/fenix/issues/15754

**Comment by liuche** [comment]
Thanks for following through with these - @jonalmeida i also gave the testing team a heads up in https://chat.mozilla.org/#/room/#mobile-test-eng:mozilla.org which is where @rpappalax and team look into intermittents.

Do you have any insight into whether these tests are failing as intended (e.g. catching an actual problem) or that we need to go through and redo how we're using the testing framework?

**Comment by jonalmeida** [comment]
> Thanks for following through with these - @jonalmeida i also gave the testing team a heads up in https://chat.mozilla.org/#/room/#mobile-test-eng:mozilla.org which is where @rpappalax and team look into intermittents.
> 
> Do you have any insight into whether these tests are failing as intended (e.g. catching an actual problem) or that we need to go through and redo how we're using the testing framework?

The tests were originally catching legitimate regressions in GeckoView, but it seems those same tests are still failing with newer GeckoView versions. For example, I've verified that the media tests are able to press play on the media elements and the verification text on the screen _should_ have been correctly asserted, but those tests are still failing.

**Pull request merged**
