### PR TITLE
Issue #19956: Add telemetry for tab view setting changes

### PR DESCRIPTION
**Pull request by jonalmeida**
This differs from `tab_view_setting` which tells us what the user's tab
setting is at startup. It does not tell us if the user explicitly
changed it instead of just using the default (which was recently
changed in #19809).

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by jonalmeida** [comment]
Request for data collection review
---
1. What questions will you answer with this data?
    - This data will tell us if a user changes the tab tray view when the (new) default is grid view.
 
2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
   - Yes, this gives us an understanding of user experience if our new default is the right one and we increase in usage.
 
3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
   -  No alternative is available to answer this question.
 
4. Can current instrumentation answer these questions?
   -  No, we have `tab_view_setting` that exists, but this can incorrectly skew our data for users that have not changed the default settings and will see the new default.
 
5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories found on the Mozilla wiki.

Measurement   Description | Data Collection   Category | Tracking Bug #
-- | -- | --
Tab view setting is list or grid | category 2 - Interaction data | https://github.com/mozilla-mobile/fenix/issues/19956

6. How long will this data be collected? Choose one of the following:
   -  I want this data to be collected for 1 year initially (ending on May 10, 2022), with the option to renew at that point. 
 
7. What populations will you measure?
   -  No filters - all locales, channels, etc.
 
8. If this data collection is default on, what is the opt-out mechanism for users?
   -  Default Glean SDK opt-out mechanism.
 
9. Please provide a general description of how you will analyze this data.
   -  When we see that our new default increases in usage, and users are not switching away from the new default.
 
10. Where do you intend to share the results of your analysis?
    -  Internally in the Fenix teams.
 
11. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?
    -  No third-party tool will use this data.

**Comment by gabrielluong** [comment]
We have a similar telemetry for this in "tab_view_setting". I am not quite sure if it's worthwhile to collect the "change" since we already collect a metrics ping about what the tab view is set to everyday.

**Comment by travis79** [comment]
> ## Request for data collection review
> 
>     1. What questions will you answer with this data?
>        
>        * This data will tell us if a user changes the tab tray view when the (new) default is grid view.
> 
>     2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
>        
>        * Yes, this gives us an understanding of user experience if our new default is the right one and we increase in usage.
> 
>     3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
>        
>        * No alternative is available to answer this question.
> 
>     4. Can current instrumentation answer these questions?
>        
>        * No, we have `tab_view_setting` that exists, but this can incorrectly skew our data for users that have not changed the default settings and will see the new default.
> 
>     5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories found on the Mozilla wiki.
> 
> 
> Measurement Description 	Data Collection Category 	Tracking Bug #
> Tab view setting is list or grid 	category 2 - Interaction data 	#19956
> 
>     1. How long will this data be collected? Choose one of the following:
>        
>        * I want this data to be collected for 1 year initially (ending on May 10, 2022), with the option to renew at that point.
> 
>     2. What populations will you measure?
>        
>        * No filters - all locales, channels, etc.
> 
>     3. If this data collection is default on, what is the opt-out mechanism for users?
>        
>        * Default Glean SDK opt-out mechanism.
> 
>     4. Please provide a general description of how you will analyze this data.
>        
>        * When we see that our new default increases in usage, and users are not switching away from the new default.
> 
>     5. Where do you intend to share the results of your analysis?
>        
>        * Internally in the Fenix teams.
> 
>     6. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?
>        
>        * No third-party tool will use this data.

# Data Review

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way?

Yes, through the metrics.yaml file and the Glean Dictionary

2) Is there a control mechanism that allows the user to turn the data collection on and off? 

Yes, through the "Send Usage Data" toggle in the app preferences

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

N/A, collection set to end May, 2022

4) Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Category 2, User Interaction Data

5) Is the data collection request for default-on or default-off?

Default-on

6) Does the instrumentation include the addition of **any *new* identifiers**?

No

7) Is the data collection covered by the existing Firefox privacy notice?

Yes

8) Does the data collection use a third-party collection tool?

No

## Result

data-review+

**Review by rocketsroger — APPROVED** [review]

**Comment by jonalmeida** [comment]
Intermittent test failing from mockk. I'll fix this in a separate PR and restart the build here until then:
```
AddonsManagementViewTest. onAddonItemClicked shows details if addon is not installed
io.mockk.MockKException: Can't instantiate proxy for class kotlin.Function1
	at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:64)
	at io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:29)
	at io.mockk.impl.instantiation.AbstractMockFactory.mockk(AbstractMockFactory.kt:59)
	at io.mockk.impl.annotations.JvmMockInitializer.assignRelaxedMockK(JvmMockInitializer.kt:142)
	at io.mockk.impl.annotations.JvmMockInitializer.initMock(JvmMockInitializer.kt:47)
```

**Pull request merged**
