### PR TITLE
For #8847: Add preference for dynamic toolbar to Customization menu

### PR DESCRIPTION
**Pull request by fredboy**
Added new preference key and string value for dynamic toolbar. The new preference is now used instead of feature flag for dynamic bottom toolbar. This preference can be changed in settings, customization menu with CheckBox, which I've also added. 

When toolbar was on top, it checked if user has screen reader enabled to determine if it should not be dynamic. I left it as it was, because I'm not sure, how it should be. So if user has a dynamic top toolbar enabled, it still won't be dynamic if the screen reader is also enabled. If dynamic toolbar is enabled at the bottom, it will be dynamic regardless of screen reader.

Here's the GIF of how toolbar is behaving with different settings:
Screen-Recording-20200615-231412

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not

- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by Mugurell** [comment]
Thank you @fredboy !
This looks great!

But I see in https://github.com/mozilla-mobile/fenix/issues/10240#issuecomment-647241235 some proposed specs different that what is used in this patch.

Sorry for the work invested already but thank you for pushing through with this!

Maybe after we get the final specs you would like to update the patch accordingly?

**Comment by fredboy** [comment]
@Mugurell yes, sure. I'll be glad to

**Comment by AmyYLee** [comment]
My feedback is that if we want to add a new "dynamic" setting that we should have strings to describe what this does. I'll let @brampitoyo make the final call.

**Comment by brampitoyo** [comment]
@fredboy The dynamic toolbar idea makes a lot of sense, but as the only difference between dynamic and non-dynamic concerns the use of gesture (ie. does it minimise when you scroll up/down the page, or not?), we should put it under a “Gestures” section.

Otherwise, I agree that “Customise” is the right sub-page to put this setting menu item, so thanks for proposing it!

**Comment by brampitoyo** [comment]
Closing this issue in favour of implementing gesture options on https://github.com/mozilla-mobile/fenix/issues/10240#issuecomment-647241235.

**Pull request closed without merging**
