### PR TITLE
Bug 1624875 - Remove raptor tests and increase vismet tier to 2.

### PR DESCRIPTION
**Pull request by gmierz**
This patch removes the Raptor Fenix tests (except for the youtube-playback one) and increases the visual metrics task's tier to 2.

The patch also removes the aframe pageload test which we found to not be useful.

### CODE REVIEW

**Comment by gmierz** [comment]
Thanks for the quick review @JohanLorenzo! We will have to wait until tomorrow to land this.

**Comment by gmierz** [comment]
Ok, we're ready! @JohanLorenzo would you be able to merge this please?

**Comment by JohanLorenzo** [comment]
Here we go!

**Comment by gmierz** [comment]
Woohoo! Thanks @JohanLorenzo :D

**Pull request merged**
