### PR TITLE
Fixes #3602:navigate to top of home screen after tapping "start browsing"

### LINKED ISSUE #3602: FNX3-17150 ⁃ [Bug] Scroll required to reveal entirety of home-screen after tapping 'Start Browsing'
Build: afb59251c19ea4959e3cd84245cafea7f11f30b0
Device: Nexus 6P

On first run, after selecting 'Start Browsing' one is required to scroll up to reveal the entirety of the home-screen. This is sub-optimal. The browser just scroll to the top after selecting 'Start Browsing'. This is a bad first impression.

### PR DESCRIPTION
**Pull request by mcarare**
After onboarding.finish(), added navigation to homeFragment

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by mcarare** [comment]
Yes it will add to back stack, and if you hit back after it will navigate to the bottom of fragment. When I implemented it, I thought it should be the expected result, if you want to navigate back, but as you mentioned it now, I also think it is not the best behaviour. 

I could scroll to top by using  `transitionToStart`(), but I find I find the transition to not be too pretty, cause it happens in the same time with the replacement of the cards.

Another approach would be navigation using directions and setting `launchSingleTop` as `true`, but it does not show the card replacement animation.

What do you think it's the preferred approach?

**Comment by mcarare** [comment]
Tried it. I think it does almost the same think with the difference that `transitionToStart()` does animateTo(0F) (although the animation is not very noticeable). You're right, it doesn't that terrible. I can go either way, just let me know. Thanks for your input!

**Comment by ekager** [comment]
Let's try the scroll up (either one, whichever you prefer)!

**Comment by ekager** [comment]
Thank you!

**Comment by mcarare** [comment]
Thank you, also!

**Pull request merged**
