### PR TITLE
For #18076: Renew telemetry expiring in April.

### PR DESCRIPTION
**Pull request by mcarare**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by mcarare** [comment]
### Telemetry renewal requests


**activation**

`activation` and `activation_id`
1) Provide a link to the initial Data Collection Review Request for this collection.
https://github.com/mozilla-mobile/fenix/pull/1707#issuecomment-486972209
2) When will this collection now expire? 04/01/2021
3) Why was the initial period of collection insufficient?
Ongoing need for bizdev accounting needs to measure Fenix installation activations

**events**

`about_page`
1) Provide a link to the initial Data Collection Review Request for this collection.
https://github.com/mozilla-mobile/fenix/pull/8047
2) When will this collection now expire? 04/01/2021
3) Why was the initial period of collection insufficient?
Need to know whether users are visiting privacy notice, crashes, support in the About page compared to other locations, especially after migration

`addons`
open_addons events
1) Provide a link to the initial Data Collection Review Request for this collection.
https://github.com/mozilla-mobile/fenix/pull/8318
2) When will this collection now expire? 04/01/2021
3) Why was the initial period of collection insufficient?
addons telemetry will inform how we invest in addons in the future, and gauge interest because currently, not all addons are enabled

`app_theme.dark_theme_selected`
1) Provide a link to the initial Data Collection Review Request for this collection.
https://github.com/mozilla-mobile/fenix/pull/7968
2) When will this collection now expire? 04/01/2021
3) Why was the initial period of collection insufficient?
Dark mode needed to understand user preference to understand whether to invest

`autoplay` changed and visited
1) Provide a link to the initial Data Collection Review Request for this collection.
https://github.com/mozilla-mobile/fenix/pull/13041#issuecomment-665777411
2) When will this collection now expire? 04/01/2021
3) Why was the initial period of collection insufficient?
Autoplay changed and visited necessary to decide whether to continue to invest

`bookmarks_management`
1) Provide a link to the initial Data Collection Review Request for this collection.
https://github.com/mozilla-mobile/fenix/pull/1708
2) When will this collection now expire? 04/01/2021
3) Why was the initial period of collection insufficient?
Need to understand how people use bookmarks management after migration, and whether that’s a priority.

`collections`
1) Provide a link to the initial Data Collection Review Request for this collection.
https://github.com/mozilla-mobile/fenix/pull/4358
2) When will this collection now expire? 04/01/2021
3) Why was the initial period of collection insufficient?
Doing ongoing work in Collections and is important to understand user flow on a Release population

`context_menu.item_tapped`
1) Provide a link to the initial Data Collection Review Request for this collection.
https://github.com/mozilla-mobile/fenix/pull/1344#issuecomment-479285010
2) When will this collection now expire? 04/01/2021
3) Why was the initial period of collection insufficient?
needed for identifying useful context menu items post-migration

`contextual_hint` TP interactions
1) Provide a link to the initial Data Collection Review Request for this collection.
https://github.com/mozilla-mobile/fenix/pull/11923
2) When will this collection now expire? 04/01/2021
3) Why was the initial period of collection insufficient?
Contextual hint telemetry is new, and we need to understand how well the CFRs are working for education and engagement of users. Tracking protection in particular is important.

`crash_reporter` closed/opened
1) Provide a link to the initial Data Collection Review Request for this collection.
https://github.com/mozilla-mobile/fenix/pull/1214#issue-264756708
2) When will this collection now expire? 04/01/2021
3) Why was the initial period of collection insufficient?
Need to know about crash reporter interactions ongoing

`custom_tab` usage
1) Provide a link to the initial Data Collection Review Request for this collection.
https://github.com/mozilla-mobile/fenix/pull/1697
2) When will this collection now expire? 04/01/2021
3) Why was the initial period of collection insufficient?
We need to understand how users use custom tab because it may suggest other features for opening links

`download_notification`
1) Provide a link to the initial Data Collection Review Request for this collection.
https://github.com/mozilla-mobile/fenix/pull/6554
2) When will this collection now expire? 04/01/2021
3) Why was the initial period of collection insufficient?
Downloads is a new feature and we need to monitor downloads successes and failures and usage of the Downloads

`error_page.visited_error`
1) Provide a link to the initial Data Collection Review Request for this collection.
https://github.com/mozilla-mobile/fenix/pull/2491#issuecomment-492414486
2) When will this collection now expire? 04/01/2021
3) Why was the initial period of collection insufficient?
Tracking errors that are encountered on Mobile ongoing

`app_opened`
1) Provide a link to the initial Data Collection Review Request for this collection.
https://github.com/mozilla-mobile/fenix/pull/1067#issuecomment-474598673
2) When will this collection now expire? 04/01/2021
3) Why was the initial period of collection insufficient?
Need to continue knowing how people are opening fenix and a basis for usage

`app_opened_all_startup` and `app_received_intent`
1) Provide a link to the initial Data Collection Review Request for this collection.
https://github.com/mozilla-mobile/fenix/pull/12114#pullrequestreview-445245341
https://github.com/mozilla-mobile/fenix/pull/11940/
2) When will this collection now expire? 06/01/2021
3) Why was the initial period of collection insufficient?
Performance-related telemetry for how the app is opened

`browser_menu_action`
1) Provide a link to the initial Data Collection Review Request for this collection.
https://github.com/mozilla-mobile/fenix/pull/1214#issue-264756708
2) When will this collection now expire? 04/01/2021
3) Why was the initial period of collection insufficient?
Menu item usage are useful to create a good intuitive user interface and remove unused items over time

`entered_url`, `opened_link`, `performed_search`, `search_bar_tapped`
1) Provide a link to the initial Data Collection Review Request for this collection.
https://github.com/mozilla-mobile/fenix/pull/1067#issuecomment-474598673
https://github.com/mozilla-mobile/fenix/pull/5975
2) When will this collection now expire? 04/01/2021
3) Why was the initial period of collection insufficient?
browser usage through the url and search are core browser features for measuring usage, and we need it to enhance search

`preference_toggled`
1) Provide a link to the initial Data Collection Review Request for this collection.
https://github.com/mozilla-mobile/fenix/pull/1896
2) When will this collection now expire? 06/01/2021
3) Why was the initial period of collection insufficient?
Measuring preference usage to create a good intuitive user interface and remove unused items oven time

`tab_counter_menu_action`, `whats_new_tapped`
1) Provide a link to the initial Data Collection Review Request for this collection.
https://github.com/mozilla-mobile/fenix/pull/11533
https://github.com/mozilla-mobile/fenix/pull/5090
2) When will this collection now expire? 04/01/2021
3) Why was the initial period of collection insufficient?
Need to validate product decisions with release population, and also compare usage across other parts in the app

**metrics**
`addons`
enabled & installed
1) Provide a link to the initial Data Collection Review Request for this collection.
https://github.com/mozilla-mobile/fenix/pull/11080
2) When will this collection now expire? 04/01/2021
3) Why was the initial period of collection insufficient?
addons telemetry will inform how we invest in addons in the future, and gauge interest because currently, not all addons are enabled

**Review by eliserichards — APPROVED** [review]
Awesome! Thank you for being so thorough 😍

**Comment by mcarare** [comment]
cc @boek for data review! TY!

**Review by boek — APPROVED** [review]
Data Collection Renewal Review (to be filled by Data Stewards)

Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?
Yes

Is the data collection covered by the existing Firefox Privacy Notice?
Yes

**Pull request merged**
