### PR TITLE
For #25808: Build with compileSdkVersion for Android 13 / API 33.

### LINKED ISSUE #25808: Build with SDK for Android 13 / API 33
See A-C: https://github.com/mozilla-mobile/android-components/issues/12378

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-20845)

### PR DESCRIPTION
**Pull request by mcarare**
Needs https://github.com/mozilla-mobile/android-components/pull/12396 to be merged first.

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

Fixes #25808

### CODE REVIEW

**Comment by mcarare** [comment]
For the moment this is blocked by https://issuetracker.google.com/issues/237725966.

**Comment by mcarare** [comment]
> For the moment this is blocked by https://issuetracker.google.com/issues/237725966.

This will be fixed in a Navigation 2.5.1 bug fix release. It might involve needing to upgrade some other libraries.

**Comment by mcarare** [comment]
As it involves multiple dependency updates and presumably a lot of breaking changes, I am going to break out updating to navigation 2.5.1 (only 2.5.0 currently available) into a separate issue. Also, that keeps this PR clean, in the unlikely case of changes in 2.5.1. to suppress deprecations in generated safe args code will be backported.

**Review by jonalmeida — APPROVED** [review]
Added a couple more commits to suppress a few more deprecations that we can address in the future.

**Comment by mcarare** [comment]
DIsabled 3 UI tests that pass on other devices and work as expected in real app usage.
Opened https://github.com/mozilla-mobile/fenix/issues/27865 for investigating and possibly re-enabling the tests.

**Pull request merged**
