### PR TITLE
For #17855 - Stops SecureWindowFeature from removing FLAG_SECURE

### PR DESCRIPTION
**Pull request by codrut-topliceanu**
⚠️ **Needs:** https://github.com/mozilla-mobile/android-components/pull/10552

For https://github.com/mozilla-mobile/fenix/issues/17855
### Pull Request checklist

- [x] **Tests**: This PR includes no tests as it is only a minor change.
- [x] **Screenshots**: This PR doesn't include footage because that's the whole point of this PR. 
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md).

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by jonalmeida — APPROVED** [review]
If we plan to land this before the 90 release cut off at the beginning of next week, let's get this landed and tested by QA soon to see if we cause any regressions.

Otherwise, we can always land it later.

**Comment by jonalmeida** [comment]
After a rebase, this should be good to land.

**Comment by codrut-topliceanu** [comment]
> After a rebase, this should be good to land.

Just waiting for that AC version bump.

**Comment by jonalmeida** [comment]
We bumped it yesterday. I wonder why it didn't pick up your changes. 🤔

**Pull request merged**
