### PR TITLE
Pin AC TO 57.0.0 and remove feature flag for view downloads

### PR DESCRIPTION
**Pull request by Amejia481**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by liuche** [comment]
Some failing tests, some that seem unrelated:
verifySearchEngineCanBeChangedTemporarilyUsingShortcuts
[testDownloadNotification](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6983616570060627538/executions/bs.f09143f2a994f68b/testcases/1/test-cases) 
saveLoginFromPromptTest
settingsMenuBasicsItemsTests

**Comment by rpappalax** [comment]
> Some failing tests, some that seem unrelated:
> verifySearchEngineCanBeChangedTemporarilyUsingShortcuts
> [testDownloadNotification](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/6983616570060627538/executions/bs.f09143f2a994f68b/testcases/1/test-cases)
> saveLoginFromPromptTest
> settingsMenuBasicsItemsTests

@liuche we see this occasionally with A-C upgrades where some UI tests become unstable.  If the test failures are intermittent and seem unrelated to the PR and are blocking, pls give us a heads-up (@AaronMT @sv-ohorvath  @rpappalax).  It looks like at least settingsMenuBasicsItemsTests may be a genuine failure but we can take a look if this is blocking

**Comment by liuche** [comment]
testStrictVisitProtectionSheet
testStrictVisitContentNotification
verifySearchEngineCanBeChangedTemporarilyUsingShortcuts *
testDownloadNotification
neverSaveLoginFromPromptTest
settingsMenuBasicsItemsTests *
verifyAddonsCanBeUninstalled
videoPlaybackSystemNotificationTest

Pushing a PR real quick for search engine tests broken by #13452

**Comment by liuche** [comment]
lmao maven errors

**Comment by liuche** [comment]
verifyContextOpenLinkNewTab
audioPlaybackSystemNotificationTest (intermittent)

since these seem unrelated, I'm going to cherry-pick these commits onto a release branch while we wait for CI to go green here.

**Comment by liuche** [comment]
RPC failure fetching docker: https://firefox-ci-tc.services.mozilla.com/tasks/AEvLdPx5QSa8fXvDxKmhGg/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FAEvLdPx5QSa8fXvDxKmhGg%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

**Comment by liuche** [comment]
maven failure: https://firefox-ci-tc.services.mozilla.com/tasks/eGT-8LKbTIuwSeLU5EnzUg/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FeGT-8LKbTIuwSeLU5EnzUg%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

**Comment by liuche** [comment]
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉

**Comment by Amejia481** [comment]
Finally 🎉

**Pull request merged**
