### PR TITLE
For #9391: Consider network connectivity on updating account UI

### PR DESCRIPTION
**Pull request by mcarare**
### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. 
pass

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by mcarare** [comment]
@topotropic I think we should show the user the info in the attached screenshot when there is no network connectivity. 
The icon and text remains to be approved. Can you help with this, or redirect to someone else? TY!

**Comment by topotropic** [comment]
@betsymi can you check the copy here?

I think for an icon we should align with what we use here https://share.goabstract.com/66058508-b4ec-4b44-a82e-cec3de7e5446?mode=design&sha=c56b553b26dfeefc55e704ece2ff2d6f0673d592 

Thanks for reaching out!

**Comment by mcarare** [comment]
@topotropic I have used the same icon we use in the share sheet when we are offline and cannot show list of devices. But I will change it to the other one, if you think it's more suggestive! Thank you for your input!

**Comment by grigoryk** [comment]
I don't think we should do this.

Issue that causing the crash (see https://github.com/mozilla-mobile/fenix/issues/9391, https://github.com/mozilla-mobile/fenix/issues/9530) was resolved is resolved (by https://github.com/mozilla-mobile/fenix/issues/9530). So, this change doesn't resolve an immediate problem anymore.

In my experience, Android's network availability notifications could be quite flaky, and their behaviour differs quite a bit based on the device, API version, etc. I have a feeling we could be chasing bugs around this conditional for years if we land this :) Maybe it got better now, but we support API21+, so...

Besides, devices could go offline for short periods of time, forcing an unlucky user to go in-and-out of the Settings UI if they're trying to simply open account settings while on a flaky connection.

**Comment by ekager** [comment]
cc @topotropic knowing that the crash has been fixed do you still think we should do this?

> 
> Issue that was causing the crash (see #9391, #9530) was resolved (by #9532). So, this change doesn't help with an immediate problem anymore. Just from this alone, I'd vote for less code/complexity.
> 
> In my experience, Android's network status/availability notifications could be quite flaky, and their behaviour differs quite a bit based on the device, API version, etc. I have a feeling we could be chasing bugs around this conditional for years if we land this :) Maybe it got better now, but we support API21+, so I wouldn't bet on it.
> 
> Besides, devices could go offline for short periods of time, forcing an unlucky user to go in-and-out of the Settings UI if they're trying to simply open account settings while on a flaky connection.

**Comment by mcarare** [comment]
Alternative solution was implemented.

**Pull request closed without merging**
