### PR TITLE
Fixes #9696: Adds Add-ons menu item to the home menu

### LINKED ISSUE #9696: [Bug] Add-ons option not present on the home screen main menu
It seems odd that reaching the add-ons screen requires a tab to be open or go through the settings. @topotropic was this intentional? If so then just close this issue.  

## Steps to reproduce
* Open Fenix and make sure the homescreen is displayed
* Tap on the 3 dot menu

### Expected behavior
* Add-ons listed

### Actual behavior
* Add-ons not listed

### Device information

* Android device: Any
* Fenix version: 4.2.1 and Nightly

### PR DESCRIPTION
**Pull request by ValentinTimisica**
### Pull Request checklist

- [x] **Tests**: This PR does not include thorough tests.
- [x] **Screenshots**: This PR includes screenshots of the changes made.
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md).

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by Mugurell** [comment]
The patch looks nice but it's not clear what the new menu item position should be.
Asking for UX review here based on the above screenshot.

**Comment by ekager** [comment]
cc @brampitoyo @topotropic could one of you give feedback to the position of this menu item so we can land it? Thanks!

**Comment by topotropic** [comment]
Looking good, would it be possible to restructure the menu like in the attached image (w/o synced tabs) as part of the PR or does that extend the scope of the issue? Thank! Home menu

**Comment by ValentinTimisica** [comment]
@topotropic I would prefer to create another issue for this.

**Comment by topotropic** [comment]
https://github.com/mozilla-mobile/fenix/issues/11132

**Pull request merged**
