### PR TITLE
Bug 1693532 - Pass auto-generated build info (version code and name) to Glean

### PR DESCRIPTION
**Pull request by badboy**
This also re-generated the Glean docs due to an update of the bundled glean-parser.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by mdboom — APPROVED** [review]
LGTM!

**Comment by badboy** [comment]
woops, no idea why this was in draft mode.
I also saw that I forgot to update the baseling ping test, did that now

**Comment by Mugurell** [comment]
> curl: (16) Error in the HTTP2 framing layer when downloading sdk
Restarting CI tasks.

**Comment by mdboom** [comment]
Some additional context:  This change means we no longer have to call the Android package manager at runtime to get basic known-at-build-time version information into Glean telemetry.  We have a *theory* that the package manager may fail in a significant number of cases resulting in missing pings and/or incomplete metadata.  (But even without that, not calling out to an external process during startup should be a performance win).  We'd like to get this merged ASAP so we can test the theory as part of a larger Android telemetry confidence workshop planned this month.

**Review by eliserichards — APPROVED** [review]
👍 looks good!

**Pull request merged**
