### PR TITLE
For #21313: Renew fission metrics expiring in December

### PR DESCRIPTION
**Pull request by eliserichards**
For #21313

- [x] Approval from @agi - see [doc](https://docs.google.com/document/d/1NGlnTa9TPyTnd3ciUPbwujbITjkX8p8vJybXcZrrM2w/edit#)
- [x] data review
- [x] update data review TBDs in PR

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by travis79** [comment]
> # Request for Data Collection Renewal
> 
> `engine_tab`:
> 
>     * `kills`
> 
>     * `kill_foreground_age`
> 
>     * `kill_background_age`
> 
>     * `foreground_metrics`
> 
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Issue #12731: Collect telemetry about the content process of tabs getting killed. #17864](https://github.com/mozilla-mobile/fenix/pull/17864)
> 
>     2. When will this collection now expire?
>        
>        * All probes that were set to expire in December 2021 will now expire in July 2022 (2022-07-01).
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * These metrics are being actively used to monitor the Fission project, which is still ongoing.

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

**Comment by eliserichards** [comment]
@mergifyio rebase

**Comment by eliserichards** [comment]
@Mergifyio rebase

**Comment by eliserichards** [comment]
@Mergifyio backport releases_v94.0.0

**Pull request merged**
