### PR TITLE
No issue: Renew/remove metrics set to expire in April 2022

### PR DESCRIPTION
**Pull request by rocketsroger**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by rocketsroger** [comment]
# Request for Data Collection Renewal
### Renew for 1 year
Total: 4
———
`experiments_default_browser.toolbar_menu_clicked`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/18982#pullrequestreview-635098629

2) When will this collection now expire?
    - 2023-03-31

3) Why was the initial period of collection insufficient?
    - default browser is a key metric

———
`home_menu.settings_item_clicked`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/18987

2) When will this collection now expire?
    - 2023-03-31

3) Why was the initial period of collection insufficient?
    - primary user interaction

———
`home_screen.home_screen_displayed`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/19025

2) When will this collection now expire?
    - 2023-03-31

3) Why was the initial period of collection insufficient?
    - primary user interaction

———
`recent_searches.group_deleted`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/22176#issuecomment-956421788

2) When will this collection now expire?
    - 2023-03-31

3) Why was the initial period of collection insufficient?
    - working on iterating on the feature

———

**Review by MozillaNoah — APPROVED** [review]
engineering r+

**Comment by eliserichards** [comment]
> # Request for Data Collection Renewal
> ### Renew for 1 year
> 
> Total: 4 ——— `experiments_default_browser.toolbar_menu_clicked`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Telemetry for #18855, #18851 and #18857  #18982 (review)](https://github.com/mozilla-mobile/fenix/pull/18982#pullrequestreview-635098629)
> 
>     2. When will this collection now expire?
>        
>        * 2023-03-31
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * default browser is a key metric
> 
> 


# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes


> ——— `home_menu.settings_item_clicked`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #18856: Add metrics for opening settings screen from home menu. #18987](https://github.com/mozilla-mobile/fenix/pull/18987)
> 
>     2. When will this collection now expire?
>        
>        * 2023-03-31
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * primary user interaction
> 
> 

# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

> ——— `home_screen.home_screen_displayed`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #18854: Add metrics for home screen being displayed. #19025](https://github.com/mozilla-mobile/fenix/pull/19025)
> 
>     2. When will this collection now expire?
>        
>        * 2023-03-31
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * primary user interaction
> 
> 

# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

> ——— `recent_searches.group_deleted`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #22175: Telemetry for deleting a search term group from recent searches on home #22176 (comment)](https://github.com/mozilla-mobile/fenix/pull/22176#issuecomment-956421788)
> 
>     2. When will this collection now expire?
>        
>        * 2023-03-31
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * working on iterating on the feature
> 
> 
# Data Collection Renewal Review 

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

# Result

data-review+

**Review by eliserichards — APPROVED** [review]
data-review+

**Comment by rocketsroger** [comment]
@Mergifyio backport releases_v98.0.0

**Pull request merged**
