### PR TITLE
For #18426: add telemetry for app.onCreate subsections.

### PR DESCRIPTION
**Pull request by mcomella**
@MarcLeclair For code review
@mmccorks For data review

Hopefully this will help us understand behavior of the
`application_on_create` probe, specifically that it seems to take longer
in telemetry than in does locally compared to `home_activity_on_create`
(comparing the medians to local runs)..

# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) What questions will you answer with this data?

- Are there any performance cliffs or other performance problems in `FenixApplication.onCreate`?
- Do all parts of app.onCreate exhibit the same performance behavior? i.e. is one of them problematic?

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:

* Understand performance in the wild in order to make improvements we can't see locally

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

We're seeing performance discrepancies in the telemetry but not locally so we have to measure in telemetry

4) Can current instrumentation answer these questions?

No

5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Firefox/Data_Collection) found on the Mozilla wiki.   

**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**

<table>
  <tr>
    <td>app_on_create_to_glean_init</td>
    <td>Technical</td>
    <td>#18426</td>
  </tr>
  <tr>
    <td>app_on_create_to_megazord_init</td>
    <td>Technical</td>
    <td>#18426</td>
  </tr>
  <tr>
    <td>app_on_create_to_setup_in_main</td>
    <td>Technical</td>
    <td>#18426</td>
  </tr>
</table>

6) Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.

https://github.com/mozilla-mobile/fenix/blob/master/docs/metrics.md

7) How long will this data be collected?  Choose one of the following:

* I want this data to be collected for 6 months initially (potentially renewable).

8) What populations will you measure?

* Which release channels?

All

* Which countries?

All

* Which locales?

All

* Any other filters?  Please describe in detail below.

9) If this data collection is default on, what is the opt-out mechanism for users?

Telemetry toggle in app

10) Please provide a general description of how you will analyze this data.

Compare metrics to one another, `application_on_create` metric, and other start up metrics to determine what behavior is expected and what is not so we can pinpoint what might be creating any performance problems.

11) Where do you intend to share the results of your analysis?

Internal, SQL.tmo, GLAM

12) Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection? If so:

No

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by mcomella** [comment]
Pushed an update to use a helper method I'm writing for a follow-up PR: the functionality should be the same.

Looks like I also need to rebase.

**Review by MarcLeclair — APPROVED** [review]
Looks good to me!

**Comment by MarcLeclair** [comment]
@mcomella  I did have a question, I see we're adding a marker in there. Have we confirmed that it has no negative performance effect, I don't remember if we had done that.

**Comment by mcomella** [comment]
> @mcomella I did have a question, I see we're adding a marker in there. Have we confirmed that it has no negative performance effect, I don't remember if we had done that.

@MarcLeclair  We didn't add a marker – I just indented some code. What are you referring to?

iirc, on start up the marker performance was slightly worse than a log statement duration - maybe two log statement durations.

**Review by mmccorks — APPROVED** [review]
1.    Is there or will there be documentation that describes the schema for the ultimate data set in a public, complete, and accurate way? 
Yes, this will be documented in metrics.md. 

2.    Is there a control mechanism that allows the user to turn the data collection on and off?
Yes, users can opt out of telemetry collection. 

3.    If the request is for permanent data collection, is there someone who will monitor the data over time?
Not permanent data collection. 

4.    Using the category system of data types on the Mozilla wiki, what collection type of data do the requested measurements fall under?
Category 1, Technical data. 

5.    Is the data collection request for default-on or default-off?
Default on.

6.    Does the instrumentation include the addition of any new identifiers?
No new identifiers. 

7.    Is the data collection covered by the existing Firefox privacy notice? 
Yes. 

8.    Does there need to be a check-in in the future to determine whether to renew the data? 
Check in in 6 months (September 2021).

9.    Does the data collection use a third-party collection tool? 
No. 

---- 
data-review +

**Pull request merged**
