### PR TITLE
For #17816: add profiler markers for WARM VIEW, start up

### PR DESCRIPTION
**Pull request by mcomella**
See commit summaries for what they're useful for. There will be more PRs to make these more useful.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by mcomella** [comment]
Test failure seems unrelated:

> androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with id: org.mozilla.fenix.debug:id/overflow_menu and has parent matching: has child: with text: is "Ecosia")

**Comment by sv-ohorvath** [comment]
Please rebase, the blocking test was disabled: https://github.com/mozilla-mobile/fenix/commit/f0b7b3b987202339a5affbe76c5b857405f004a6

**Review by MarcLeclair — APPROVED** [review]
I think it looks good. I'm a bit confused as to why the `IntentReceiverActivity` is the marker that determines WARM start up since warm can also be through MAIN, no? I thought `IntentReceiverActivity` was only used for VIEW. Thoughts, @mcomella ?

**Comment by mcomella** [comment]
> I think it looks good. I'm a bit confused as to why the `IntentReceiverActivity` is the marker that determines WARM start up since warm can also be through MAIN, no? I thought `IntentReceiverActivity` was only used for VIEW. Thoughts, @mcomella ?

You are right that `IntentReceiverActivity` is only for VIEW. However, I'm only adding markers for WARM VIEW so MAIN is out-of-scope.

**Pull request merged**
