### PR TITLE
Let relbot update A-C on trunk

### PR DESCRIPTION
**Pull request by jcristau**
We already use relbot for this on fenix release branches and on all
branches for focus-android, so might as well avoid the duplication.

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [ ] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation

Used by GitHub Actions.

### CODE REVIEW

**Comment by rvandermeulen** [comment]
😍

**Review by JohanLorenzo — APPROVED** [review]
I'm glad to see we're converging towards a single way of bumping A-C. Before merging this PR, there are a few things we need to change in `.mergify.yml`. If we don't, we will break the autoapproval added in https://github.com/mozilla-mobile/fenix/pull/26148. 

If I'm not mistaken, it should be a matter of removing these lines:

https://github.com/mozilla-mobile/fenix/blob/1750240bc60771c0e23a7d749e8d4a07d8c7274f/.mergify.yml#L52-L58 

and then updating these 2 regexes to take `main` into account: 

https://github.com/mozilla-mobile/fenix/blob/1750240bc60771c0e23a7d749e8d4a07d8c7274f/.mergify.yml#L8

https://github.com/mozilla-mobile/fenix/blob/1750240bc60771c0e23a7d749e8d4a07d8c7274f/.mergify.yml#L60

**Comment by jcristau** [comment]
> I'm glad to see we're converging towards a single way of bumping A-C. Before merging this PR, there are a few things we need to change in `.mergify.yml`. If we don't, we will break the autoapproval added in #26148.

Good catch, thank you!

**Comment by jcristau** [comment]
merged manually due to the mergify config change.

**Pull request merged**
