### PR TITLE
(Do Not Merge til 24th) Docker update for #3411

### PR DESCRIPTION
**Pull request by npark-mozilla**
### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Changelog**: This PR includes [a changelog entry](https://github.com/mozilla-mobile/fenix/blob/master/CHANGELOG.md) or does not need one
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by npark-mozilla** [comment]
Before this PR can be merged, a new docker image with tag 1.4 need to be uploaded

**Comment by npark-mozilla** [comment]
@pocmo I'm getting "Artifact "public/actions.json" not found at "/opt/fenix/actions.json" error msg, do you think it's because I'm cleaning something wrong?

**Comment by sarentz** [comment]
lets land this after we've shipped - i would ike the build system to be the same for each RC and final build we do between now and then

**Comment by npark-mozilla** [comment]
@sarentz sounds good, after code freeze it is unlikely that we really need this to be set up to detect the startup crash via UI tests.  Monday after all hands should be good.

**Pull request merged**
