### PR TITLE
Disabled all flaky History UI Tests.

### PR DESCRIPTION
**Pull request by sv-ohorvath**
Ignoring all the flaky history tests again.
---

### Pull Request checklist

- [ ] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by boek** [comment]
Looks like the historytest is still failing on a device. Also ktlint is failing?

**Comment by sv-ohorvath** [comment]
> Looks like the historytest is still failing on a device. Also ktlint is failing?

@boek Could you point me to a failed test report so I could see what's wrong?
ktlint is failing on this PR with "unused import" on the "org.junit.Rule" import which is obviously in use. I'll have a look.

**Comment by AaronMT** [comment]
We should keep this disabled while investigating.

**Comment by sv-ohorvath** [comment]
Due to https://github.com/mozilla-mobile/fenix/issues/6859 and the tests failing on this PR check, I've disabled again all the possible flaky tests while I'm doing some more investigation.

**Pull request merged**
