### PR TITLE
For #11245: Integrate Synced Tabs AwesomeBar suggestions

### PR DESCRIPTION
**Pull request by hakkikaancaliskan**
### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [x] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by ekager** [comment]
cc @topotropic want to take a quick pass of the synced tab suggestion UX?

**Comment by hakkikaancaliskan** [comment]
@ekager hey emily, i just wanna ask you just a little question. Is this bug just for me or is it known or there is a known workaround? If it's just for me, I'm gonna close the issue. Thanks in advance.
#11259

**Comment by hakkikaancaliskan** [comment]
>     * synced tabs view: device icons should align with the back arrow in the header (16dp left margin).
> 
>     * please add a full-width separator below the device name (color: light_grey_30 in light mode and dark_grey_10 in dark mode)
> 
> 
> https://share.goabstract.com/d1d0bb78-03c9-4822-aea1-a553d2fd4944?mode=build&sha=72ed314cb3b094e510d264a18e99870147787fa0

This issue is about to synced tabs suggestion integration, not for synced tabs view. Maybe we should create a seperate issue? What do you think?

**Comment by topotropic** [comment]
> > ```
> > * synced tabs view: device icons should align with the back arrow in the header (16dp left margin).
> > 
> > * please add a full-width separator below the device name (color: light_grey_30 in light mode and dark_grey_10 in dark mode)
> > ```
> > 
> > 
> > https://share.goabstract.com/d1d0bb78-03c9-4822-aea1-a553d2fd4944?mode=build&sha=72ed314cb3b094e510d264a18e99870147787fa0
> 
> This issue is about to synced tabs suggestion integration, not for synced tabs view. Maybe we should create a seperate issue? What do you think?

oh! sorry, I thought it was about the synced tabs screen as well because of the screenshot that was posted. I can create a separate issue. 

For the search suggestions option I'd like to get feedback from @betsymi on whether we want to go with "Open tabs" that include synced tabs or whether we want to separate "Open tabs" and "Synced tabs". 

Thanks!

**Comment by hakkikaancaliskan** [comment]
> For the search suggestions option I'd like to get feedback from @betsymi on whether we want to go with "Open tabs" that include synced tabs or whether we want to separate "Open tabs" and "Synced tabs".

If I understand correctly, search in currently open tabs feature will be added in the future, right? And you mean current "search synced tabs" option should cover currently open tabs or seperated?

**Comment by vesta0** [comment]
I don't think we should show synced tabs in the awesome bar at all (at least for the initial implementation) because the volume can really over crowd other more relevant suggestions.

**Comment by jonalmeida** [comment]
Adding the `do not land` label so we can discuss how we want this feature to work before landing it. :)

**Comment by liuche** [comment]
@vesta0 I'm going through the old PRs, and wondering what the next thing to do here is.

I see @brampitoyo's comment about including synced tabs in the [awesomebar suggestions](https://github.com/mozilla-mobile/fenix/issues/11245#issuecomment-645787078) but you also mentioned above that it's making the suggestions too cluttered.

What are some options here?
- cap number of synced tabs suggested
- don't add this feature?

**Comment by brampitoyo** [comment]
@liuche I think that visually labelling the icon of different suggestion types (keywords vs. history vs. bookmarks vs. open tabs vs. synced tabs) will go quite a long way towards distinguishing them from each other. I know that we already put device name, but it may not be enough of a signal.

I propose creating a new issue to solve this icon labelling problem separately.

Either way, I think it’s still worth it to “borrow” the same recipe that desktop uses to sort/rank and eliminate different types of suggestions. I know, for example, that if you have a bookmark open in a tab, that bookmark will never be suggested (instead, the open tab will be suggested) until the tab is closed.

The only exception being, on Fenix, search suggestions are always shown ahead of “the rest” (browsing history, bookmarks, open tabs, etc.)

**Comment by hakkikaancaliskan** [comment]
@vesta0 what's the decision here?

**Comment by vesta0** [comment]
Let's go ahead with @brampitoyo 's recommendation for now and I will create a separate issue to look at the sorting/ranking suggestions + icon labeling problem.

**Comment by hakkikaancaliskan** [comment]
I've rebased and currently works great. What do we need now? Done?
image

**Comment by hakkikaancaliskan** [comment]
Also I've created PR's for adding indicator to synced tabs suggestions.
https://github.com/mozilla-mobile/android-components/pull/8157
https://github.com/mozilla-mobile/fenix/pull/13923

This PR ready for review.

**Comment by hakkikaancaliskan** [comment]
@ekager could you please label as ready for review?

**Comment by hakkikaancaliskan** [comment]
@NotWoods this is also ready for review :)

**Comment by hakkikaancaliskan** [comment]
Ready for review

**Comment by jonalmeida** [comment]
I've rebased your changes here and push https://github.com/mozilla-mobile/fenix/pull/15098 to let the CI server run with your changes (it doesn't work on contributor PRs unfortunately). We can review your changes as well. :)

**Comment by hakkikaancaliskan** [comment]
@jonalmeida i can't see test results because tc says file is missing.
resim

**Comment by jonalmeida** [comment]
This looks good to me. I'm going to merge it on the other PR and we can look at getting the indicator change landed next!

**Review by jonalmeida — APPROVED** [review]

**Comment by jonalmeida** [comment]
Landed in https://github.com/mozilla-mobile/fenix/pull/15098!

**Pull request closed without merging**
