### PR TITLE
Add preference for enabling/disabling Android Autofill from within the app.

### PR DESCRIPTION
**Pull request by pocmo**
This adds a preference to Fenix for enabling/disabling Android Autofill support from within the app. To distinguish the setting from the one for autofilling logins in web content, I changed the string:

autofill_preference

### CODE REVIEW

**Comment by pocmo** [comment]
@topotropic Are the new strings okay? Is there someone else I should involve?

**Comment by topotropic** [comment]
Thanks for the ping! @lime124 can help you out here!

**Comment by pocmo** [comment]
Updated strings:

background

**Review by jonalmeida — APPROVED** [review]
Looks good code-wise.

**Comment by jonalmeida** [comment]
Not merging in case there is some other review we're waiting for.

**Pull request merged**
