### PR TITLE
For #21087: Updates Recently Saved design

### PR DESCRIPTION
**Pull request by codrut-topliceanu**
For https://github.com/mozilla-mobile/fenix/issues/21087
### Pull Request checklist

- [x] **Tests**: This PR includes no tests as it's only a minor change.
- [x] **Screenshots**: This PR includes screenshots on the jira issue.
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md).

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by codrut-topliceanu** [comment]
I'm having trouble with Android Studio which is preventing me from easily identifying errors.
image

**Review by eliserichards — APPROVED** [review]
This looks great! :shipit:

**Comment by eliserichards** [comment]
Oops, looks like that merge didn't do the right thing 🤔 it added two things into `styles` that it shouldn't have 🤔 I'm gonna take the "needs landing" label off for now

**Comment by codrut-topliceanu** [comment]
Thank you for taking a look at this ❤️

**Review by eliserichards — APPROVED** [review]
:shipit: :ship:

**Pull request merged**
