### PR TITLE
For #26582 - Renew telemetry expiring in 107

### LINKED ISSUE #26582: Renew telemetry expiring in 107
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-21356)

### PR DESCRIPTION
**Pull request by MatthewTighe**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation
Fixes #26582

### CODE REVIEW

**Comment by MatthewTighe** [comment]
# Request for Data Collection Renewal
### Renew for 1 year
Total: 37
———
`customize_home.opening_screen`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/22333

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Interested in interactions for future iterations

———
`preferences.studies_enabled`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/22193

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Needed to understand the population of users for studies

———
`preferences.studies_preference_enabled`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/22193

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Needed to understand the population of users for studies

———
`preferences.inactive_tabs_enabled`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/21908

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Interested in interactions for future iterations

———
`history.recent_searches_tapped`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/22173

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Interested in interactions for future iterations

———
`history.search_term_group_tapped`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/22300

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Interested in interactions for future iterations

———
`history.search_term_group_open_tab`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/22368#issuecomment-964223263

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Interested in interactions for future iterations

———
`history.search_term_group_remove_tab`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/22368#issuecomment-964223263

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Interested in interactions for future iterations

———
`history.search_term_group_remove_all`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/22368#issuecomment-964223263

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Interested in interactions for future iterations

———
`tabs_tray.has_inactive_tabs`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/21908

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Interested in interactions for future iterations

———
`tabs_tray.close_all_inactive_tabs`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/21908

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Interested in interactions for future iterations

———
`tabs_tray.auto_close_seen`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/22171

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Interested in interactions for future iterations

———
`tabs_tray.auto_close_turn_on_clicked`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/22171

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Interested in interactions for future iterations

———
`tabs_tray.auto_close_dimissed`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/22171

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Interested in interactions for future iterations

———
`tabs_tray.close_inactive_tab`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/21908

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Interested in interactions for future iterations

———
`tabs_tray.open_inactive_tab`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/21908

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Interested in interactions for future iterations

———
`tabs_tray.inactive_tabs_cfr_settings`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/22301

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Interested in interactions for future iterations

———
`tabs_tray.inactive_tabs_cfr_dismissed`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/22301

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Interested in interactions for future iterations

———
`tabs_tray.inactive_tabs_cfr_visible`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/22301

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Interested in interactions for future iterations

———
`tabs_tray.enter_multiselect_mode`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/23964#issuecomment-1051128057

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Interested in interactions for future iterations

———
`tabs_tray.share_selected_tabs`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/23964#issuecomment-1051128057

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Interested in interactions for future iterations

———
`tabs_tray.bookmark_selected_tabs`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/23964#issuecomment-1051128057

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Interested in interactions for future iterations

———
`tabs_tray.close_selected_tabs`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/23964#issuecomment-1051128057

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Interested in interactions for future iterations

———
`tabs_tray.selected_tabs_to_collection`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/23964#issuecomment-1051128057

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Interested in interactions for future iterations

———
`perf.awesomebar.history_suggestions`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/10276#pullrequestreview-411101979

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - key performance metric

———
`perf.awesomebar.bookmark_suggestions`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/10276#pullrequestreview-411101979

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - key performance metric

———
`perf.awesomebar.search_engine_suggestions`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/10276#pullrequestreview-411101979

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - key performance metric

———
`perf.awesomebar.session_suggestions`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/10276#pullrequestreview-411101979

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - key performance metric

———
`perf.awesomebar.synced_tabs_suggestions`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/10276#pullrequestreview-411101979

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - key performance metric

———
`perf.awesomebar.clipboard_suggestions`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/10276#pullrequestreview-411101979

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - key performance metric

———
`perf.awesomebar.shortcuts_suggestions`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/10276#pullrequestreview-411101979

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - key performance metric

———
`recent_tabs.section_visible`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/22166

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Interested in interactions for future iterations

———
`recent_bookmarks.shown`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/22104

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Interested in interactions for future iterations

———
`recent_bookmarks.recent_bookmarks_count`:
1) Provide a link to the initial Data Collection Review Request for this collection.
    - https://github.com/mozilla-mobile/fenix/pull/22293

2) When will this collection now expire?
    - 120

3) Why was the initial period of collection insufficient?
    - Interested in interactions for future iterations

———

**Comment by rocketsroger** [comment]
> ### Pull Request checklist
> 
>     * [ ]  **Tests**: This PR includes thorough tests or an explanation of why it does not
> 
>     * [ ]  **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
> 
>     * [ ]  **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.
> 
> 
> ### QA
> 
>     * [x]  **QA Needed**
> 
> 
> ### To download an APK when reviewing a PR (after all CI tasks finished running):
> 
>     1. Click on `Checks` at the top of the PR page.
> 
>     2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
> 
>     3. Click on the `build-debug` task.
> 
>     4. Click on `View task in Taskcluster` in the new `DETAILS` section.
> 
>     5. The APK links should be on the right side of the screen, named for each CPU architecture.
> 
> 
> ### GitHub Automation
> 
> Fixes #26582

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

**Review by MozillaNoah — APPROVED** [review]
engineering r+

**Comment by rocketsroger** [comment]
> # Request for Data Collection Renewal
> ### Renew for 1 year
> 
> Total: 35 ——— `customize_home.opening_screen`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [MR2 Telemetry: Opening screen preference #22333](https://github.com/mozilla-mobile/fenix/pull/22333)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Interested in interactions for future iterations
> 
> 
> ——— `preferences.studies_enabled`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #22192 add telemetry for studies #22193](https://github.com/mozilla-mobile/fenix/pull/22193)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Needed to understand the population of users for studies
> 
> 
> ——— `preferences.studies_preference_enabled`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #22192 add telemetry for studies #22193](https://github.com/mozilla-mobile/fenix/pull/22193)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Needed to understand the population of users for studies
> 
> 
> ——— `preferences.inactive_tabs_enabled`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [MR2 Inactive tabs telemetry #21908](https://github.com/mozilla-mobile/fenix/pull/21908)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Interested in interactions for future iterations
> 
> 
> ——— `history.recent_searches_tapped`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Close #22172: Add Recent searches telemetry #22173](https://github.com/mozilla-mobile/fenix/pull/22173)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Interested in interactions for future iterations
> 
> 
> ——— `history.search_term_group_tapped`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Close #22299: Add history search term group telemetry #22300](https://github.com/mozilla-mobile/fenix/pull/22300)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Interested in interactions for future iterations
> 
> 
> ——— `history.search_term_group_open_tab`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #22147 - New search term groups telemetry #22368 (comment)](https://github.com/mozilla-mobile/fenix/pull/22368#issuecomment-964223263)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Interested in interactions for future iterations
> 
> 
> ——— `history.search_term_group_remove_tab`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #22147 - New search term groups telemetry #22368 (comment)](https://github.com/mozilla-mobile/fenix/pull/22368#issuecomment-964223263)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Interested in interactions for future iterations
> 
> 
> ——— `history.search_term_group_remove_all`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #22147 - New search term groups telemetry #22368 (comment)](https://github.com/mozilla-mobile/fenix/pull/22368#issuecomment-964223263)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Interested in interactions for future iterations
> 
> 
> ——— `tabs_tray.has_inactive_tabs`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [MR2 Inactive tabs telemetry #21908](https://github.com/mozilla-mobile/fenix/pull/21908)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Interested in interactions for future iterations
> 
> 
> ——— `tabs_tray.close_all_inactive_tabs`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [MR2 Inactive tabs telemetry #21908](https://github.com/mozilla-mobile/fenix/pull/21908)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Interested in interactions for future iterations
> 
> 
> ——— `tabs_tray.auto_close_seen`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #22170: Add telemetry for the auto-close prompt #22171](https://github.com/mozilla-mobile/fenix/pull/22171)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Interested in interactions for future iterations
> 
> 
> ——— `tabs_tray.auto_close_turn_on_clicked`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #22170: Add telemetry for the auto-close prompt #22171](https://github.com/mozilla-mobile/fenix/pull/22171)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Interested in interactions for future iterations
> 
> 
> ——— `tabs_tray.auto_close_dimissed`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #22170: Add telemetry for the auto-close prompt #22171](https://github.com/mozilla-mobile/fenix/pull/22171)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Interested in interactions for future iterations
> 
> 
> ——— `tabs_tray.close_inactive_tab`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [MR2 Inactive tabs telemetry #21908](https://github.com/mozilla-mobile/fenix/pull/21908)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Interested in interactions for future iterations
> 
> 
> ——— `tabs_tray.open_inactive_tab`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [MR2 Inactive tabs telemetry #21908](https://github.com/mozilla-mobile/fenix/pull/21908)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Interested in interactions for future iterations
> 
> 
> ——— `tabs_tray.inactive_tabs_cfr_settings`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [MR2 telemetry - Inactive tabs CFR #22301](https://github.com/mozilla-mobile/fenix/pull/22301)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Interested in interactions for future iterations
> 
> 
> ——— `tabs_tray.inactive_tabs_cfr_dismissed`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [MR2 telemetry - Inactive tabs CFR #22301](https://github.com/mozilla-mobile/fenix/pull/22301)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Interested in interactions for future iterations
> 
> 
> ——— `tabs_tray.inactive_tabs_cfr_visible`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [MR2 telemetry - Inactive tabs CFR #22301](https://github.com/mozilla-mobile/fenix/pull/22301)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Interested in interactions for future iterations
> 
> 
> ——— `tabs_tray.enter_multiselect_mode`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #23399: Add tabs tray multi-select telemetry. #23964 (comment)](https://github.com/mozilla-mobile/fenix/pull/23964#issuecomment-1051128057)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Interested in interactions for future iterations
> 
> 
> ——— `tabs_tray.share_selected_tabs`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #23399: Add tabs tray multi-select telemetry. #23964 (comment)](https://github.com/mozilla-mobile/fenix/pull/23964#issuecomment-1051128057)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Interested in interactions for future iterations
> 
> 
> ——— `tabs_tray.bookmark_selected_tabs`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #23399: Add tabs tray multi-select telemetry. #23964 (comment)](https://github.com/mozilla-mobile/fenix/pull/23964#issuecomment-1051128057)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Interested in interactions for future iterations
> 
> 
> ——— `tabs_tray.close_selected_tabs`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #23399: Add tabs tray multi-select telemetry. #23964 (comment)](https://github.com/mozilla-mobile/fenix/pull/23964#issuecomment-1051128057)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Interested in interactions for future iterations
> 
> 
> ——— `tabs_tray.selected_tabs_to_collection`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [For #23399: Add tabs tray multi-select telemetry. #23964 (comment)](https://github.com/mozilla-mobile/fenix/pull/23964#issuecomment-1051128057)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Interested in interactions for future iterations
> 
> 
> ——— `perf.awesomebar.history_suggestions`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Performance telemetry for awesomebar suggestion provider durations #10276 (review)](https://github.com/mozilla-mobile/fenix/pull/10276#pullrequestreview-411101979)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * key performance metric
> 
> 
> ——— `perf.awesomebar.bookmark_suggestions`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Performance telemetry for awesomebar suggestion provider durations #10276 (review)](https://github.com/mozilla-mobile/fenix/pull/10276#pullrequestreview-411101979)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * key performance metric
> 
> 
> ——— `perf.awesomebar.search_engine_suggestions`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Performance telemetry for awesomebar suggestion provider durations #10276 (review)](https://github.com/mozilla-mobile/fenix/pull/10276#pullrequestreview-411101979)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * key performance metric
> 
> 
> ——— `perf.awesomebar.session_suggestions`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Performance telemetry for awesomebar suggestion provider durations #10276 (review)](https://github.com/mozilla-mobile/fenix/pull/10276#pullrequestreview-411101979)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * key performance metric
> 
> 
> ——— `perf.awesomebar.synced_tabs_suggestions`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Performance telemetry for awesomebar suggestion provider durations #10276 (review)](https://github.com/mozilla-mobile/fenix/pull/10276#pullrequestreview-411101979)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * key performance metric
> 
> 
> ——— `perf.awesomebar.clipboard_suggestions`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Performance telemetry for awesomebar suggestion provider durations #10276 (review)](https://github.com/mozilla-mobile/fenix/pull/10276#pullrequestreview-411101979)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * key performance metric
> 
> 
> ——— `perf.awesomebar.shortcuts_suggestions`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Performance telemetry for awesomebar suggestion provider durations #10276 (review)](https://github.com/mozilla-mobile/fenix/pull/10276#pullrequestreview-411101979)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * key performance metric
> 
> 
> ——— `home_screen.home_screen_view_count`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [MR2 Telemetry: Recent tabs section probe #22166](https://github.com/mozilla-mobile/fenix/pull/22166)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        -key metric to understand performance of home screen features
>        ———
>        `recent_tabs.section_visible`:
> 
>     4. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [MR2 Telemetry: Recent tabs section probe #22166](https://github.com/mozilla-mobile/fenix/pull/22166)
> 
>     5. When will this collection now expire?
>        
>        * 120
> 
>     6. Why was the initial period of collection insufficient?
>        
>        * Interested in interactions for future iterations
> 
> 
> ——— `recent_bookmarks.shown`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Close #22103: Add recent bookmarks telemetry #22104](https://github.com/mozilla-mobile/fenix/pull/22104)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Interested in interactions for future iterations
> 
> 
> ——— `recent_bookmarks.recent_bookmarks_count`:
> 
>     1. Provide a link to the initial Data Collection Review Request for this collection.
>        
>        * [Recent bookmark count telemetry  #22293](https://github.com/mozilla-mobile/fenix/pull/22293)
> 
>     2. When will this collection now expire?
>        
>        * 120
> 
>     3. Why was the initial period of collection insufficient?
>        
>        * Interested in interactions for future iterations
> 
> 
> ———

# Data Collection Renewal Review

1) Is the provided Data Collection Review complete, correct, and data-review+ by a Data Steward?

Yes

2) Is the data collection covered by the existing Firefox Privacy Notice?

Yes

## Result

data-review+

**Pull request merged**
