### PR TITLE
DO NOT LAND: Draft for removing black screen flicker on start

### PR DESCRIPTION
**Pull request by MarcLeclair**
@pocmo  not sure if I'm missing much but doing this avoid a heavy black flickr on start up and seems to not change too much of our migration code. Would this change be okay with you?

cc @mcomella 

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by MarcLeclair** [comment]
@pocmo That makes sense. Yeah, the black flicker happens mostly on lower end devices (not *just* low ends  as in the G5 but I also notice it on a nexus 6p huawei p10 and a few other "recent" phones that are pre 2017). I got a link here: https://streamable.com/c45y3x. FYI the black screen is worse on the `geckonightlyfennecnightly` build for some odd reason.

I tried multiple different ways to remove that by playing around with `MigrationDecisionActivity` and it seems to be the fact that we're killing the activity and starting a new one since it doesn't happen with the patch here. The issue is that this black screen happens everytime I open the app. Not just once when the user is migrating but every time (plus going through the `startactivity` seems to take 100-150ms on medium/lower end device, go wonder why its so slow there)

**Comment by mcomella** [comment]
> However I would like to learn more about this black screen flicker. Is there an issue about this?

https://github.com/mozilla-mobile/fenix/issues/11616

**Comment by MarcLeclair** [comment]
I'll close this since it seems I've found a possible alternative solution that seems a lot safer than jeopardizing the whole migration workflow. For reference, here's the draft PR : #11796

**Comment by pocmo** [comment]
Awesome! That's great. :)

**Pull request closed without merging**
