### PR TITLE
Remove TabsUseCases methods that take a Session object.

### PR DESCRIPTION
**Pull request by pocmo**
This is the Fenix change for this breaking AC change (not landed yet): https://github.com/mozilla-mobile/android-components/pull/9592

### CODE REVIEW

**Review by csadilek — APPROVED** [review]
👍

**Comment by pocmo** [comment]
Added latest AC version to the PR.

**Comment by gabrielluong** [comment]
Fixes #17795

**Comment by pocmo** [comment]
Looks like there has been another, unrelated change in AC:

```
[task 2021-02-03T17:20:25.699Z] e: /builds/worker/checkouts/src/app/src/geckoRelease/java/org/mozilla/fenix/engine/GeckoProvider.kt: (83, 17): Unresolved reference: ContentBlocking
[task 2021-02-03T17:20:25.699Z] e: /builds/worker/checkouts/src/app/src/geckoRelease/java/org/mozilla/fenix/engine/GeckoProvider.kt: (84, 17): Unresolved reference: ContentBlocking
```

**Comment by pocmo** [comment]
Alright, patch is up, now it should pass.

**Pull request merged**
