### PR TITLE
Switch to GeckoView 69 Beta.

### PR DESCRIPTION
**Pull request by pocmo**
~~This is currently being discussed. Please only merge if there's a decision to ship with GV 69 Beta.~~ ✅ 

Engineering-wise with GeckoView 69/Beta we no longer need to maintain a copy of the GeckoView version in Fenix and so I deleted `Gecko.kt`. Just including `browser-engine-gecko-beta` is enough and the matching GeckoView version will come automatically as transitive dependency.

### CODE REVIEW

**Comment by mitchhentges** [comment]
Heads up that this will break raptor tasks, since this affects our `gradle` function for returning the current geckoview release.

See [`reference-browser`'s `printGeckoviewVersion` function](https://github.com/mozilla-mobile/reference-browser/blob/master/app/build.gradle#L297-L304). If you update `fenix`'s `build.gradle` to have the same function body, raptor should still work. This can be tested locally with `./gradlew printGeckoviewVersions`.
Let me know if you'd like assistance, or if you'd like me to update it and provide you a patch/update your branch

**Comment by pocmo** [comment]
@mitchhentges Thanks! I'll fix that and flag you for review.

@mozilla-mobile/fenix This PR is ready to get in - all stakeholders seem to agree that we want to go with GV 69 as soon as possible.

**Comment by pocmo** [comment]
@mitchhentges I updated `printGeckoviewVersion` (also without `s` now). I had to add a check for the `selected` property since it didn't seem to exist for unresolved dependencies. I couldn't find any code in Fenix yet that actually calles `printGeckoviewVersion/s` - is that right?

**Comment by mitchhentges** [comment]
@pocmo thanks!

> I had to add a check for the selected property since it didn't seem to exist for unresolved dependencies

IIRC by fetching `resolutionResult`, you trigger the resolution of the entire resolution graph. Is it possible for there to be unresolved dependencies at that point?

> I couldn't find any code in Fenix yet that actually calles printGeckoviewVersion/s - is that right?

... wait a second :man_facepalming: [we always use the latest raptor these days](https://github.com/mozilla-mobile/fenix/pull/4181)! You can safely remove `printGeckoviewVersion`, my bad

**Comment by pocmo** [comment]
> IIRC by fetching `resolutionResult`, you trigger the resolution of the entire resolution graph. Is it possible for there to be unresolved dependencies at that point?

I'm not sure. 🤷‍♂ It ended up calling `selected` on some `Unresolved....` class that didn't have this property. 🤔 

> ... wait a second 🤦‍♂ we always use the latest raptor these days! You can safely remove printGeckoviewVersion, my bad

Ah, great. Will do that!

**Pull request merged**
