### PR TITLE
For #7122 Fix icons for saved logins screen 

### PR DESCRIPTION
**Pull request by mcarare**
### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices]

Edited: new screenshots here: https://github.com/mozilla-mobile/fenix/pull/7268#issuecomment-567097930

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by mcarare** [comment]
@AmyYLee These are the new icons based on the provided assets. Can you please give a feedback, considering the screenshots? Thank you!

**Comment by AmyYLee** [comment]
@

> @AmyYLee These are the new icons based on the provided assets. Can you please give a feedback, considering the screenshots? Thank you!

@mcarare Hi, I found out what the issue was. There was an extra colour fill box in the SVG and I think that is causing the jagged edges. The "password-show" icon is good. Please update the other 2 with these icons. Thank you!

Copy icon: https://drive.google.com/open?id=1u0H3gvA5Dou43ZMzpzWpoH3fvieKCnlk
password-hide: https://drive.google.com/open?id=1tz6vDm06Xv4VSJQ6wgq6aOgjADnquiUf

**Comment by mcarare** [comment]
@AmyYLee Thanks for the update. I had to correct some circular reference in them and do a little tweaking to get rid of `filltype`, but I think the result is good. What do you think?

passy
passn

**Comment by AmyYLee** [comment]
> @AmyYLee Thanks for the update. I had to correct some circular reference in them and do a little tweaking to get rid of `filltype`, but I think the result is good. What do you think?
> 
> passy
> passn

@mcarare This looks great! Thanks

**Pull request merged**
