### PR TITLE
Run CI for 21652

### PR DESCRIPTION
**Pull request by Mugurell**
Run CI for https://github.com/mozilla-mobile/fenix/pull/26152

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [ ] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation

Used by GitHub Actions.

### CODE REVIEW

**Comment by Mugurell** [comment]
Building failed the first time because of TC issues - https://firefox-ci-tc.services.mozilla.com/tasks/JEkNh3GTQsGO4c1uhH3Lcw/runs/0/logs/public/logs/live.log 
Trying one more time.

**Comment by Mugurell** [comment]
The missing scopes were added upstream.
Restarting CI.

**Comment by hneiva** [comment]
RelEng was tagged automatically, removed from reviewers.

**Comment by Mugurell** [comment]
Original PR was merged. Closing this.

**Pull request closed without merging**
