### PR TITLE
Update Android Components version

### PR DESCRIPTION
**Pull request by MickeyMoz**

### CODE REVIEW

**Comment by AaronMT** [comment]
x86 UI -> https://github.com/mozilla-mobile/fenix/commit/4dc3a00ed0f129cc14f9f07bf4e382ae931e4b14

**Comment by pocmo** [comment]
I landed some breaking API changes in AC that are causing this to fail here. I'll push a patch to this PR.

**Comment by ekager** [comment]
2 test instances :/ 
```
e: /builds/worker/checkouts/src/app/src/androidTest/java/org/mozilla/fenix/AppRequestInterceptor.kt: (20, 5): 'onLoadRequest' overrides nothing
e: /builds/worker/checkouts/src/app/src/androidTest/java/org/mozilla/fenix/AppRequestInterceptor.kt: (29, 9): No value passed for parameter 'isDirectNavigation'
```

**Comment by ekager** [comment]
Updated to include the tests

**Comment by pocmo** [comment]
Thank you!

**Pull request merged**
