### PR TITLE
For #5077 #5078: Strings cleanup

### PR DESCRIPTION
**Pull request by mcarare**
Removed whitespaces from es string, added exclamation marks(!) to it strings

### Pull Request checklist

- [x] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features

### CODE REVIEW

**Comment by mcarare** [comment]
@Delphine, could you please take a look ?

**Comment by ekager** [comment]
AFAIK we can't make any string changes directly in these files, they will need to be fixed in the l10n source files or they will be overwritten the next time strings are imported

**Comment by Delphine** [comment]
Correct, we'd need to fix this on Pontoon side.
Side-note: while I understand the white space fixes, I'm not sure it was intentional or not in Italian to remove the exclamation point. Flagging @flod in case he knows.

**Comment by mcarare** [comment]
Closing this, following above comments.

**Pull request closed without merging**
