### PR TITLE
Target Android 11

### PR DESCRIPTION
**Pull request by Amejia481**
Let's see if there is any tests failing or any issue with upgrading.
 
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Review by mcarare — APPROVED** [review]
LGTM! 👍

**Comment by mcarare** [comment]
Other than this and the deprecation issues, I think we should also look into behavior changes and file issues to investigate them (i.e. permissions)

**Comment by abodea** [comment]
Note that I verified this issue on the [debug build](https://github.com/Amejia481/fenix/tree/target_android_11) with Google Pixel 4 XL (11).
I covered a lot of scenarios but maninly:
- sync
- YT videos / play / pause / interrupts
- Search / Browse
- Upload Files
- Download different file types
Note that I didn't encountered any issues on this build.

**Comment by Amejia481** [comment]
🚢 !

**Pull request merged**
