### PR TITLE
Closes #22688: Remove inactive_tabs_recently_closed probe

### LINKED ISSUE #22688: Remove unused inactive_tabs_recently_closed probe
Issue to represent FNXV2-18421:

Remove the following probes that are no longer being used for MR2: `inactive_tabs_recently_closed`

### PR DESCRIPTION
**Pull request by MatthewTighe**
Fixes #22688

### Pull Request checklist

- [x] **Tests**: Removes applicable test
- [x] **Screenshots**: N/A
- [x] **Accessibility**: N/A

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by gabrielluong** [comment]
Sorry for the drive by, could you add a reference the issue number in the PR title and commit? If a GitHub issue doesn't exist, I would usually create one and reference the jira ticket in the description if that also exists.

**Comment by MatthewTighe** [comment]
> Sorry for the drive by, could you add a reference the issue number in the PR title and commit? If a GitHub issue doesn't exist, I would usually create one and reference the jira ticket in the description if that also exists.

Driveby feedback very welcome 😄 Added an issue that references the Jira ticket

**Comment by gabrielluong** [comment]
> > Sorry for the drive by, could you add a reference the issue number in the PR title and commit? If a GitHub issue doesn't exist, I would usually create one and reference the jira ticket in the description if that also exists.
> 
> Driveby feedback very welcome 😄 Added an issue that references the Jira ticket

Might also need to amend your commit message as well. Mergify only uses your PR title if you do a squash landing since the commit messages will all get squashed into the description. If you used pr:needs-landing, it will land your existing commit which won't have the commit message that references the issue. The nice thing about having the issue reference is when someone needs to go back and get more context of the work easily.

**Comment by MatthewTighe** [comment]
Gotcha, thanks for the info. Updated further based on your suggestions

**Review by rocketsroger — APPROVED** [review]
🚢

**Review by eliserichards — APPROVED** [review]
Looks great! 🚀

**Pull request merged**
