### PR TITLE
For #12105: Follow ux mock on Settings --> Accessibility screen

### PR DESCRIPTION
**Pull request by hakkikaancaliskan**
cc @brampitoyo

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [x] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by cadeyrn** [comment]
The alignment does not match the mockup you posted in #12105 (see the orange line). Since such a gap was added on several other screens it has to be added here as well.

**Comment by hakkikaancaliskan** [comment]
> 
> 
> The alignment does not match the mockup you posted in #12105 (see the orange line). Since such a gap was added on several other screens it has to be added here as well.

After @ghost's comment @brampitoyo changed his mind. https://github.com/mozilla-mobile/fenix/issues/12105#issuecomment-652143674

**Comment by cadeyrn** [comment]
I am not sure about the "changed mind" because it was not explicitly mentioned. But to give a bit context: First there were no gaps on the settings screens at all. Then there were gaps on a few screens. I opened issues where I suggested to remove the few gaps to be conistent across the product. Then it was said the gaps are correct because of the Google Material Design guidelines and other screens has to be changed, too.  Either there is a gap or there is no gap on the settings screens, that's the designer's decision. But the decision should apply to all screens, not only to some. 😉

**Comment by hakkikaancaliskan** [comment]
@cadeyrn that's not a hard work to put a gap. I'll wait for ux feedback.
Thanks :)

**Comment by brampitoyo** [comment]
Sorry @cadeyrn. You are absolutely correct.

- You did suggest to remove a few gaps to be consistent across product
- I then suggested to add gaps to be consistent with Material Design keylines
- But when I reviewed @hakkikaancaliskan’s work on Accessibility Settings, I totally forgot about this gap

I have re-added the gap now, and you can read it on https://github.com/mozilla-mobile/fenix/issues/12105#issuecomment-657337542.

Thanks so much for pointing out this error, and sorry @hakkikaancaliskan for making more work for you!

**Comment by hakkikaancaliskan** [comment]
@brampitoyo re-review please

Also ready for eng review.

**Comment by brampitoyo** [comment]
@hakkikaancaliskan Yes. Now everything looks good to me. I wasn’t aware of the RTL layout issue, so let’s fix that.

**Comment by brampitoyo** [comment]
@hakkikaancaliskan @person808 Looks good to me. Thank you!

**Comment by person808** [comment]
Closing in favor of #12597

**Pull request closed without merging**
