### PR TITLE
For #20668 - New awesomebar suggestion providers probes

### PR DESCRIPTION
**Pull request by Mugurell**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by Mugurell** [comment]
# Request for data collection review form

**All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**

1) What questions will you answer with this data?

This data will allow us to monitor real-life performance of all of the awesomebar suggestion providers. How fast/slow they are, what does distribution of duration looks like, etc.

2) Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:

Awesomebar is one of the main points of interaction with the browser for our users. It needs to be fast and responsive. Measuring real-life performance will allow us to understand better how users are experiencing this part of the product.

- Establish baselines and measure changes (across releases) in awesomebar performance.
- Track what effect product changes have on the performance of the awesomebar.

3) What alternative methods did you consider to answer these questions? Why were they not sufficient?

There are qualitative alternatives to understanding raw performance of suggestion providers (and of the awesomebar as a whole) - they mainly take form of monitoring user feedback from various channels. The quality of the data is hard to rely on, and data collection/processing effort is high.

Automatic collection of raw performance metrics is both much more accurate, and doesn't involve a lot of effort to monitor over time once dashboards are established.

4) Can current instrumentation answer these questions?

No.

5) List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Firefox/Data_Collection) found on the Mozilla wiki.   

**Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**

<table>
<tr>
<td>Measurement Description</td>
<td>Data Collection Category</td>
<td>Tracking Bug #</td>
</tr>
<tr>
<td>Duration distribution of history metadata suggestion queries</td>
<td>Category 1</td>
<td>https://github.com/mozilla-mobile/fenix/issues/20668</td>
</tr>
<tr>
<td>Duration distribution of combined history suggestion queries</td>
<td>Category 1</td>
<td>https://github.com/mozilla-mobile/fenix/issues/20668</td>
</tr>
<tr>
<td>Duration distribution of search engine names suggestion queries</td>
<td>Category 1</td>
<td>https://github.com/mozilla-mobile/fenix/issues/20668</td>
</tr>
<tr>
<td>Duration distribution of search action suggestion queries</td>
<td>Category 1</td>
<td>https://github.com/mozilla-mobile/fenix/issues/20668</td>
</tr>
</table>

6) How long will this data be collected?  Choose one of the following:

Data currently expires on 2020-09-15.

7) What populations will you measure?

All channels, all user population.

8) If this data collection is default on, what is the opt-out mechanism for users?

Standard Glean SDK opt-out.

9) Please provide a general description of how you will analyze this data.

Through redash dashboards.

10) Where do you intend to share the results of your analysis?

Fenix, a-c and a-s teams.

11) Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection? If so:

N/A

**Comment by Mugurell** [comment]
@travis79 maybe you can help with a data-review for this?

**Comment by travis79** [comment]
> # Request for data collection review form
> 
> **All questions are mandatory. You must receive review from a data steward peer on your responses to these questions before shipping new data collection.**
> 
>     1. What questions will you answer with this data?
> 
> 
> This data will allow us to monitor real-life performance of all of the awesomebar suggestion providers. How fast/slow they are, what does distribution of duration looks like, etc.
> 
>     1. Why does Mozilla need to answer these questions?  Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:
> 
> 
> Awesomebar is one of the main points of interaction with the browser for our users. It needs to be fast and responsive. Measuring real-life performance will allow us to understand better how users are experiencing this part of the product.
> 
>     * Establish baselines and measure changes (across releases) in awesomebar performance.
> 
>     * Track what effect product changes have on the performance of the awesomebar.
> 
> 
>     1. What alternative methods did you consider to answer these questions? Why were they not sufficient?
> 
> 
> There are qualitative alternatives to understanding raw performance of suggestion providers (and of the awesomebar as a whole) - they mainly take form of monitoring user feedback from various channels. The quality of the data is hard to rely on, and data collection/processing effort is high.
> 
> Automatic collection of raw performance metrics is both much more accurate, and doesn't involve a lot of effort to monitor over time once dashboards are established.
> 
>     1. Can current instrumentation answer these questions?
> 
> 
> No.
> 
>     1. List all proposed measurements and indicate the category of data collection for each measurement, using the [Firefox data collection categories](https://wiki.mozilla.org/Firefox/Data_Collection) found on the Mozilla wiki.
> 
> 
> **Note that the data steward reviewing your request will characterize your data collection based on the highest (and most sensitive) category.**
> Measurement Description 	Data Collection Category 	Tracking Bug #
> Duration distribution of history metadata suggestion queries 	Category 1 	https://github.com/[/issues/20668](https://github.com/mozilla-mobile/fenix/issues/20668)
> Duration distribution of combined history suggestion queries 	Category 1 	https://github.com/[/issues/20668](https://github.com/mozilla-mobile/fenix/issues/20668)
> Duration distribution of search engine names suggestion queries 	Category 1 	https://github.com/[/issues/20668](https://github.com/mozilla-mobile/fenix/issues/20668)
> Duration distribution of search action suggestion queries 	Category 1 	https://github.com/[/issues/20668](https://github.com/mozilla-mobile/fenix/issues/20668)
> 
>     1. How long will this data be collected?  Choose one of the following:
> 
> 
> Data currently expires on 2021-11-15.
> 
>     1. What populations will you measure?
> 
> 
> All channels, all user population.
> 
>     1. If this data collection is default on, what is the opt-out mechanism for users?
> 
> 
> Standard Glean SDK opt-out.
> 
>     1. Please provide a general description of how you will analyze this data.
> 
> 
> Through redash dashboards.
> 
>     1. Where do you intend to share the results of your analysis?
> 
> 
> Fenix, a-c and a-s teams.
> 
>     1. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection? If so:
> 
> 
> N/A

# Data Review

1. Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way?

Yes, through the metrics.yaml file and the Glean Dictionary.

1. Is there a control mechanism that allows the user to turn the data collection on and off?

Yes, through the "Send Usage Data" toggle in the app settings.

1. If the request is for permanent data collection, is there someone who will monitor the data over time?

N/A, collection to end 2021-11-15

1. Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Category 1, Technical data

1. Is the data collection request for default-on or default-off?

default-on

1. Does the instrumentation include the addition of **any *new* identifiers**?

No

1. Is the data collection covered by the existing Firefox privacy notice?

Yes

1. Does the data collection use a third-party collection tool?

No

## Result

data-review+

**Comment by Mugurell** [comment]
@grigoryk Do these changes look okay to you too?

**Comment by gabrielluong** [comment]
@Mugurell Do we still need this or can we close it?

**Comment by Mugurell** [comment]
> @Mugurell Do we still need this or can we close it?

Guess this would be a question rather for @grigoryk .

**Comment by Mugurell** [comment]
Guess this isn't needed.

**Pull request closed without merging**
