### PR TITLE
For #21841 - New telemetry for Google and Baidu top sites removal

### PR DESCRIPTION
**Pull request by Mugurell**
### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by travis79** [comment]
I should be able to data-review this today.

**Comment by travis79** [comment]
> ### **Request for data collection review**
> 
>     1. What questions will you answer with this data?
> 
> 
>     * When users remove the default top sites.
> 
> 
>     1. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
> 
> 
>     * This data will help understand the usefulness of the feature.
> 
> 
>     1. What alternative methods did you consider to answer these questions? Why were they not sufficient?
> 
> 
>     * N/A
> 
> 
>     1. Can current instrumentation answer these questions?
> 
> 
>     * No
> 
> 
>     1. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories found on the Mozilla wiki.
> 
> 
> Measurement Description 	Data Collection Category 	Tracking Bug #
> Event: User removed the default Google top site 	Category 2 “Interaction data” 	#21841
> Event: User removed the default Baidu top site 	Category 2 “Interaction data” 	#21841
> 
>     1. Please provide a link to the documentation for this data collection which describes the ultimate data set in a public, complete, and accurate way.
> 
> 
>     * [dictionary.telemetry.mozilla.org/apps/fenix](https://dictionary.telemetry.mozilla.org/apps/fenix)
> 
> 
>     1. How long will this data be collected? Choose one of the following:
> 
> 
>     * For now the probes are set to expire in 2022-02-01 - the same as other top sites probes.
> 
> 
>     1. What populations will you measure?
> 
> 
>     * All users on all release channels
> 
> 
>     1. If this data collection is default on, what is the opt-out mechanism for users?
> 
> 
>     * Default Glean SDK opt-out mechanism.
> 
> 
>     1. Please provide a general description of how you will analyze this data.
> 
> 
>     * Redash / GLAM
> 
> 
>     1. Where do you intend to share the results of your analysis?
> 
> 
>     * Internal with mobile team(s)
> 
> 
>     1. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?
> 
> 
>     * No

# Data Review

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way? 

Yes, through the metrics.yaml and the [Glean Dictionary](https://dictionary.telemetry.mozilla.org/)

2) Is there a control mechanism that allows the user to turn the data collection on and off?

Yes, through the "Send Usage Data" preference in the application settings

3) If the request is for permanent data collection, is there someone who will monitor the data over time?

N/A, collection set to end or be renewed by 2022-02-01

4) Using the **[category system of data types](https://wiki.mozilla.org/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?

Category 2, Interaction data

5) Is the data collection request for default-on or default-off?

default-on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?

No

7) Is the data collection covered by the existing Firefox privacy notice? 

Yes

8) Does the data collection use a third-party collection tool? 

No

## Result

data-review+

**Comment by Mugurell** [comment]
Waiting for a data science confirmation that these events look good.

**Comment by Mugurell** [comment]
Rebased and added the data-review link in `metrics.yaml`.

**Comment by rocketsroger** [comment]
@Mergifyio backport releases_v94.0.0

**Pull request merged**
