### PR TITLE
For #12692 - Remove "www." prefix from tab URL in tab tray

### LINKED ISSUE #12692: FNX2-15412 ⁃ [Bug] "www." not trimmed from url in tab tray
## Steps to reproduce
Open https://www.wikipedia.org/ or https://www.nytimes.com/.

### Expected behavior
URLs in tab tray have the "www." stripped like they do in the address bar:

This also happened in the old version of the tab tray (I borrowed this screenshot from https://github.com/mozilla-mobile/fenix/issues/10683#issue-618970283):

### Actual behavior
The "www." is present:

There are actully two arguments in favor of this:

1. The hostname shown should reflect the one shown in the address bar.
1. Hiding this reduces clutter in the tab tray.

### PR DESCRIPTION
**Pull request by amkcpu**
Closes #12692. 
Basically uses the same approach as https://github.com/mozilla-mobile/android-components/pull/6232, stripping "www." if the hostname starts with that.

**Screenshot:**

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by ekager** [comment]
This needs UX approval in the issue before review

**Comment by ekager** [comment]
https://github.com/mozilla-mobile/android-components/pull/6232 actually added a util class to do this for us, so you can just use `URLStringUtils.toDisplayUrl(url)` to be consistent.

**Comment by amkcpu** [comment]
> [mozilla-mobile/android-components#6232](https://github.com/mozilla-mobile/android-components/pull/6232) actually added a util class to do this for us, so you can just use `URLStringUtils.toDisplayUrl(url)` to be consistent.

The issue I see with that is that `toDisplayUrl()` includes the URL's path. Showing the path would make the tab tray extremely cluttered.

**Comment by Mugurell** [comment]
Hello,
In the meantime a new PR was put up that uses https://github.com/mozilla-mobile/fenix/blob/eab9660146704f557472e2cde33fafd8a99d9887/app/src/main/java/org/mozilla/fenix/ext/String.kt#L42
which would strip even more prefixes.
Not sure which approach is the best.. @ekager ?

**Comment by ekager** [comment]
Hey @amkcpu thanks for your contribution and sorry I lost track of this. We're going to go with this way of doing it because it's more consistent with how we do it elsewhere in the app. Let us know if you want help finding something else to work on in Fenix! Thanks!
https://github.com/mozilla-mobile/fenix/pull/12984

**Pull request closed without merging**
