### PR TITLE
For #11132: Rearranges home menu items

### PR DESCRIPTION
**Pull request by ValentinTimisica**
### Pull Request checklist

- [x] **Tests**: This PR does not include thorough tests.
- [x] **Screenshots**: This PR includes screenshots of the changes made.
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md).

| Bottom toolbar   |      Top toolbar      |
|:---------------:|:-------------------:|
|  |   |

### After merge
- [ ] **Milestone**: Make sure issues finished by this pull request are added to the [milestone](https://github.com/mozilla-mobile/fenix/milestones) of the version currently in development.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by Scripterr** [comment]
The add-ons menu icon looks bigger than other icons, it should be consistent with other icons.

**Comment by ValentinTimisica** [comment]
@Scripterr thanks for pointing that out, but in this PR the add-ons icons was not changed or modified. I looked over the code and, for example, [add-ons icon](https://github.com/mozilla-mobile/android-components/blob/a8e7f3c4ccee0162e7a0ddab07747591e5377fa0/components/ui/icons/src/main/res/drawable/mozac_ic_extensions.xml#L6) has the same dimensions as the [history icon](https://github.com/mozilla-mobile/fenix/blob/b332deedd49be77a956ca327c018c75b6e78951c/app/src/main/res/drawable/ic_history.xml#L6). If you think this is a bug feel free to open a new issue with it.

**Comment by Scripterr** [comment]
I have filled the bug previously in https://github.com/mozilla-mobile/fenix/issues/9205 , but it doesn't have any progress on it, so I saw this PR was changing some icons and menu positions that may be it can be acknowledged or fixed here.

**Comment by ekager** [comment]
I just bumped #9205 so hopefully we'll get new assets there.

**Comment by brampitoyo** [comment]
@ekager I’ve posted the new extensions icon asset over at https://github.com/mozilla-mobile/fenix/issues/9205#issuecomment-640285511

**Comment by ekager** [comment]
We can follow up with the new assets later.

**Pull request merged**
