### PR TITLE
For #9935 - Fallback region selection on first load

### PR DESCRIPTION
**Pull request by boek**

### CODE REVIEW

**Comment by sblatz** [comment]
@mcomella are you able to test this directly from this PR branch?

**Comment by mcomella** [comment]
I can still reproduce the delay on my android emulator with simulated latency by:
- clearing data
- starting the app
- click the toolbar

I think we fixed one invocation but not others:
```
2020-06-25 14:50:58.591 22161-22161/? E/lol installedIdentifier: average 0
2020-06-25 14:50:58.601 22161-22418/? E/lol installedIdentifier: average 0
2020-06-25 14:51:15.239 22466-22466/? E/lol installedIdentifier: average 6195
2020-06-25 14:51:15.239 22466-22513/? E/lol installedIdentifier: average 7611
2020-06-25 14:51:15.240 22466-22495/? E/lol installedIdentifier: average 7923
2020-06-25 14:51:15.265 22466-22466/? E/lol installedIdentifier: average 0
2020-06-25 14:51:15.452 22466-22685/? E/lol installedIdentifier: average 0
```

This is a log statement I added inside `installedSearchEngines` measuring the time it takes to call this line: https://searchfox.org/mozilla-mobile/rev/8fb090f2849be16319f5ab85f063d5de8cb44473/fenix/app/src/main/java/org/mozilla/fenix/components/searchengine/FenixSearchEngineProvider.kt#106

The first two times it's called, the problem is solved. The next three are not solved. The last two are. I'll dig in to figure out what's up.

**Comment by mcomella** [comment]
I think the problem is this line: https://searchfox.org/mozilla-mobile/rev/8fb090f2849be16319f5ab85f063d5de8cb44473/fenix/app/src/main/java/org/mozilla/fenix/components/searchengine/FenixSearchEngineProvider.kt#198

`baseSearchEngines.await()` -> the baseSearchEngines is initialized with the `localizationProvider` and its method calls localizationProvider.determineRegion().

**Comment by mcomella** [comment]
I can no longer reproduce using the STR above. I'll skim through the profile and my logs to make sure we're not missing anything.

**Comment by liuche** [comment]
Seems like it might be hitting this #12042

**Pull request merged**
