### PR TITLE
For #13368 - Ignores strict mode for LeanplumMetricsService

### PR DESCRIPTION
**Pull request by boek**

### CODE REVIEW

**Comment by liuche** [comment]
cc @mcomella bc you've been doing strictmode issues. Shouldn't block just 👀

**Comment by jonalmeida** [comment]
Duplicate of https://github.com/mozilla-mobile/fenix/pull/13971?

**Comment by mcomella** [comment]
@boek Why did we decide to ignore the warning? It's okay to ignore it but I just want to make sure that we're being deliberate about prioritizing other work over busting a possible regression.

**Comment by jonalmeida** [comment]
UI tests are failing for PRs because of the strict mode violation dialog so we're going to merge this for now, and we can follow-up the correct fix with #13971.

**Pull request merged**
