### PR TITLE
For #23841: Credit cards: Hide keyboard when selecting month or year

### LINKED ISSUE #23841: Credit cards: hide keyboard when selecting month or year
### Steps to reproduce

https://user-images.githubusercontent.com/36289013/154830205-64873b24-9f4e-4b92-981a-694b839f99a8.mp4

### Expected behaviour

Keyboard should be hidden when selecting Expiry month or year.

### Actual behaviour

It's visible.

### Device name

_No response_

### Android version

Android 10

### Firefox release type

Firefox Nightly

### Firefox version

99.0a1

### Device logs

_No response_

### Additional information

_No response_

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/FNXV2-19569)

### PR DESCRIPTION
**Pull request by sunilk9211**
https://user-images.githubusercontent.com/36289013/155844318-21f32ecc-ee20-47d0-87d2-ee8375980f81.mp4

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

Fixes #23841
Fixes #23841
Fixes #23841

### CODE REVIEW

**Comment by t-p-white** [comment]
@sunilk9211 thank you for the contribution, I would like to help get this landed, could you please resolve the conflicting file?

**Comment by boek** [comment]
@t-p-white I went ahead and rebased this PR.

Do we also want to clear the focus of any selected input, or is just hiding the keyboard appropriate on Android?

**Comment by mavduevskiy** [comment]
@boek 
After triggering the drop down menu, focus shifts to the menu and selector goes away. When the menu is hidden, focus goes back to it's previous position. It does look like expected behavior for android.

**Comment by t-p-white** [comment]
@boek 👍 that's a good question!
Agree with @mavduevskiy's point above, from what I can see this is also consistent with other application behaviour e.g. adding an address.

**Review by t-p-white — APPROVED** [review]
lgtm 👌

**Comment by t-p-white** [comment]
Hey @boek the klint task is failing could you fix this please?

**Pull request merged**
