### PR TITLE
For #17816: add ProfilerFactProcessor and register it, tests.

### PR DESCRIPTION
**Pull request by mcomella**
This will need to be rebased on ac after https://github.com/mozilla-mobile/android-components/commit/e5b0d15bd4a8860ea5cecec4eb41b019e73f46ea merges into fenix (so tomorrow).

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

### CODE REVIEW

**Comment by sv-ohorvath** [comment]
Please rebase, a blocking UI test was disabled: https://github.com/mozilla-mobile/fenix/commit/f0b7b3b987202339a5affbe76c5b857405f004a6

**Comment by mcomella** [comment]
My test is failing now so I'll need to see what's causing that...

**Comment by mcomella** [comment]
Accidentally committed a test version of my test that I had because the ac PR hadn't landed yet – should be fixed.

**Review by MarcLeclair — APPROVED** [review]
Looks good to me. I like the abstraction of the code

**Pull request merged**
