### PR TITLE
For #18898 - implement quit button in page menu

### PR DESCRIPTION
**Pull request by cadeyrn**
For #18898.

Screenshot_20210411-143537

### CODE REVIEW

**Comment by gabrielluong** [comment]
I don't know if this was in the design spec. We should check if we want to have this feature.

**Comment by amedyne** [comment]
@topotropic , @violasong ?

**Comment by eliserichards** [comment]
I'll check with Victoria on this

**Review by eliserichards — APPROVED** [review]
Awesome job!

**Comment by violasong** [comment]
Thanks for catching this @cadeyrn! 

It was in the purple fine print of the figma. Next time I'll make things like this more clear.

**Pull request merged**
